### ISSUE TITLE
BlockTheSpot Partially Working

### ISSUE THREAD

**Issue by Davoleo** [mrpond/BlockTheSpot#10]
**Describe the bug**
Banners are blocked and also most of the audio ads, however after a while you listen to the same playlist it plays some audio ads
I don't think the issue is my lib being replaced since I've tried replacing it with the patched one multiple times on the same version, and the bug was happening anyways

**Desktop:**
 - OS: Windows 10 build 1903
 - Spotify Version: 1.1.17.543.geb9254e9

**Additional context**
ListDLLs log: https://pastebin.com/faXpXBB7

**Comment by Peuuuur-Noel** [comment]
Same thing for me after few hours.
From my current location, audio ads are requested from `tubemogul.com`.
It works after adding it to the block list in `hosts.h`.

**Comment by mrpond** [comment]
Hello, thanks for the report.
@Davoleo may I know your region?
@Peuuuur-Noel also your too?

**Comment by Peuuuur-Noel** [comment]
@mrpond EU, France.

**Comment by mrpond** [comment]
updated v0.27, I'm now thinking about integrate adguard https://adguard.com/en/adguard-dns/overview.html  into dll, but some ppl didn't control network env.

**Comment by Davoleo** [comment]
I'm from EU, Italy

**Comment by Davoleo** [comment]
ok, I've tried updating both spotify and blockthespot to the latest version but I'm getting the same issue once again
After some time listening to music there's an audio ad that plays
![image](https://user-images.githubusercontent.com/24458276/68313601-22bb4400-00b5-11ea-80f2-e279ed9043d8.png)

**Desktop:**
OS: Windows 10 build 1903
Spotify Version: 1.1.18.611.g9cc9bdc9

**Additional context**
NEW ListDLLs log: https://pastebin.com/AZTFZMHZ

**Comment by mrpond** [comment]
I will make logging dll tonight, will post here. maybe there are other things I miss out.

**Comment by mrpond** [comment]
[chrome_elf_log.zip](https://github.com/mrpond/BlockTheSpot/files/3815887/chrome_elf_log.zip)
@Davoleo use this dll
log file httplog.txt will create in spotify folder,
after ads play, zip the log file and upload here.

**Comment by Davoleo** [comment]
no problems so far
