### ISSUE TITLE
Windows Defender detecting and quarantining possible Trojan threats out of chrome_elf.dll

### ISSUE THREAD

**Issue by WillTjipta** [mrpond/BlockTheSpot#101]
**Important**
 - Make sure you use [latest spotify](https://www.spotify.com) before reporting a bug.
     I am using version 1.1.48.625.g1c87c7f7-a
 - Make sure you use the [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before reporting a bug.
     The last-modified date in my BlockTheSpot is 10/13/2020. However, I assumed BlockTheSpot.bat makes a call out to GitHub to download the latest files?
 - Make sure if blockthespot DLL got replaced after Spotify update (important).
    I don't know any blockthespot.dll. However, the chrome_elf.dll is replaced after running BlockTheSpot.bat.

**Describe the bug**
- A clear and concise description of what the bug is.
    Windows Defender is scanning chrome_elf.dll and finding possible Trojan threats after it has been updated by BlockTheSpot.
[https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fYmacco.AA6E&threatid=2147757251](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fYmacco.AA6E&threatid=2147757251)
[https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fCryptInject!ml&threatid=2147760506](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fCryptInject!ml&threatid=2147760506)

Please let me know if these are safe and good to remove from quarantine. If not, please remove these from the code.

Thank you for all your work!

**Desktop:**

 - OS: Windows 10
 - Spotify Version: 1.1.48.625.g1c87c7f7-a
 - BlockTheSpot Product Version: 0.51.0.0

**Additional context**
![image](https://user-images.githubusercontent.com/22486015/102699588-b210b180-41fa-11eb-9970-d28e85e67e3d.png)
![image](https://user-images.githubusercontent.com/22486015/102699593-b89f2900-41fa-11eb-8b9c-190ba4d86bf8.png)
![image](https://user-images.githubusercontent.com/22486015/102699600-c3f25480-41fa-11eb-88cb-bfc6f2fc4760.png)
![image](https://user-images.githubusercontent.com/22486015/102699604-c94f9f00-41fa-11eb-93d3-ac751799ae74.png)

**Comment by rednek46** [comment]
False positive.
Check #96 .

**Comment by WillTjipta** [comment]
Thanks for clarifying!
