### ISSUE TITLE
windows defender just now blocked and classified your patch as a trojan

### ISSUE THREAD

**Issue by freespotify** [mrpond/BlockTheSpot#102]
windows defender just now blocked and classified your patch (nov 18) as a trojan: 

https://imgur.com/a/nguLRGk

Edition	        Windows 10 Home
Version	        20H2
Installed on	‎04-‎Sep-‎20
OS build	       19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by chrispinkney** [comment]
Same

**Comment by mimecry** [comment]
dupe: https://github.com/mrpond/BlockTheSpot/issues/96

**Comment by freespotify** [comment]
I should've checked closed issues. my mistake.
