### ISSUE TITLE
Why does Windows find a virus?

### ISSUE THREAD

**Issue by presence35** [mrpond/BlockTheSpot#105]
Thanks for this DLL, it works fine. I'm nervous about the disabling of my virus protection, though.

Where in the code is the problem coming from? I would like to inspect that file myself to make sure it's really safe.

Thx

**Comment by rednek46** [comment]
Please try to check the existence of any duplicate issue first before posting it.For  Windows threat check #96.
The issue is not with the code, but the Appveyor auto build integration.
