### ISSUE TITLE
Enable discussions tab

### ISSUE THREAD

**Issue by Daksh777** [mrpond/BlockTheSpot#106]
It would be great if the discussion tab were enabled so that some topics like #83 can be discussed in those and not clutter the issue itself. Furthermore, users can also open discussions to get quick support directly from the repo itself. I believe that it would be a great addition.

**Comment by mrpond** [comment]
Hello, it really overkill for this small project.
my goal to make these enchantment in #83 stay in single dll.

reverse how spotify parse and calling zlink.spa -> zlink.bundle.js is on going.

**Comment by rednek46** [comment]
> It would be great if the discussion tab were enabled so that some topics like #83 can be discussed in those and not clutter the issue itself. Furthermore, users can also open discussions to get quick support directly from the repo itself. I believe that it would be a great addition.

If its OK, I have a discussion tab open at my fork for the bat file. but you are open for any discussion on this repo [there](https://github.com/rednek46/BlockTheSpot).

**Comment by Daksh777** [comment]
> > It would be great if the discussion tab were enabled so that some topics like #83 can be discussed in those and not clutter the issue itself. Furthermore, users can also open discussions to get quick support directly from the repo itself. I believe that it would be a great addition.
> 
> If its OK, I have a discussion tab open at my fork for the bat file. but you are open for any discussion on this repo [there](https://github.com/rednek46/BlockTheSpot).

Got it, thank you!

**Comment by rednek46** [comment]
@mrpond I have a Discord Support server for BTS.
Let me know if I could add an invite link in the readme.

**Comment by rednek46** [comment]
@Daksh777 A discord server is now open for support and discussion.
invite link in the readme.md

**Comment by Daksh777** [comment]
> @Daksh777 A discord server is now open for support and discussion.
> invite link in the readme.md

I don't use Discord but thanks a lot for the invite.
