### ISSUE TITLE
Some ads are played

### ISSUE THREAD

**Issue by Peuuuur-Noel** [mrpond/BlockTheSpot#11]
**Describe the bug**
Following this comment https://github.com/mrpond/BlockTheSpot/issues/10#issuecomment-549573856

Here is the datalog.txt containing json dump: [datalog.zip](https://github.com/mrpond/BlockTheSpot/files/3829440/datalog.zip)
Looks like another domain is used to retrieve files: `creativeservice-production.scdn.co` (bypassed by `scdn.co` which is whitlisted)
You can also see calls for ads from `tubemogul.com` (previously added in blacklist).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spotify Version: 1.1.18.611.g9cc9bdc9

**Comment by mrpond** [comment]
Hi, thank you for json-log.
I had been update v0.30 https://github.com/mrpond/BlockTheSpot/blob/master/chrome_elf.zip
Tell me how it goes.

**Comment by Peuuuur-Noel** [comment]
Hi, this is the version I use.

**Comment by mrpond** [comment]
v0.30 debug build are json logging only, no ad blocking.
release build will empty all json response.

**Comment by Peuuuur-Noel** [comment]
Indeed.
I didn't see this debugging condition when I compile it.

**Comment by mrpond** [comment]
in next week, I will integrate adguard dns lookup into dll, maybe you can help me test it.
