### ISSUE TITLE
Latest Chrome_Elf blocked by Microsoft Defender

### ISSUE THREAD

**Issue by dennyamarojr** [mrpond/BlockTheSpot#112]
Hi mrpond,

Download the 2021 version of chrome_elf and Microsoft Defender has blocked the .dll, here's a screenshot

![image](https://user-images.githubusercontent.com/36896116/104195460-833fc280-53d7-11eb-927d-5e137e15d1e1.png)

Information about the update of Microsoft Defender: 

![image](https://user-images.githubusercontent.com/36896116/104195541-9a7eb000-53d7-11eb-8998-1367ff3e883b.png)

I'm using Windows 10 20H2

**Comment by mrpond** [comment]
appveyor again, please try 2021.1.09.30. this one compile from my computer

**Comment by dennyamarojr** [comment]
Will try here

**Comment by dennyamarojr** [comment]
Re-download and Microsoft Defender don't detect anything, Thanks to reply in short time.

**Comment by rednek46** [comment]
Reopened to avoid duplicates.

**Comment by LiuAndre** [comment]
Windows Defender still block it in latest version.
VirusTotal check: https://www.virustotal.com/gui/file/b577fcda4a756c4c3c6a54835fcc029a547839dc0d077de92be136d66a4c3a3c/detection

**Comment by rednek46** [comment]
@LiuAndre  are you sure you downloaded 2021.1.09.30 ?
or you can alternatively use the BlockTheSpot.bat

**Comment by Davoleo** [comment]
can confirm this happens when downloading the latest manual compiled version

**Comment by Jinnai** [comment]
Same issue: https://i.imgur.com/ynddxw0.png

**Comment by rednek46** [comment]
@Davoleo @Jinnai for the confirmation.

**Comment by Dr4w** [comment]
Same issue with 2021.1.09.30.

**Comment by LiuAndre** [comment]
@rednek46 
Yes, I'm sure. I just download the latest version because I saw this issue and want to confirm it.
Im still using november 2020 [release](https://github.com/mrpond/BlockTheSpot/releases/tag/26), and still worked like a charm in lates spotify version 👍

**Comment by mrpond** [comment]
okay, I revert the release.
2021.1.09.30 are intent to fix this 109 issue.
https://github.com/mrpond/BlockTheSpot/issues/109

btw I can't fix 109 issue yet.

**Comment by MichalisSak** [comment]
I have the same problem and I can't use 2021.1.09.30 either.
