### ISSUE TITLE
After restart computer, Microsoft Defender detect chrome_elf.dll as a trojan [Sorry for duplicate issue]

### ISSUE THREAD

**Issue by dennyamarojr** [mrpond/BlockTheSpot#114]
Here's the screenshot
![image](https://user-images.githubusercontent.com/36896116/104251675-19e6a080-5425-11eb-9d0b-24423521450e.png)

**Comment by rednek46** [comment]
The latest release should work without the false positive. Right now its an issue with appveyor compiler which does the automatic release.
