### ISSUE TITLE
Spotify randomly stops playing

### ISSUE THREAD

**Issue by elhertz** [mrpond/BlockTheSpot#115]
Running latest Spotify and BlockTheSpot

**Describe the bug**
Some songs will stop playing for a couple seconds and sometimes they'll  throw an error [like this one](https://i.imgur.com/cKxNZ2E.png)
Video: https://user-images.githubusercontent.com/13700335/104823691-cc09d800-582a-11eb-8b44-2aad7cf8fd93.mp4

**Desktop:**
 - OS: Windows 10
 - Spotify Version: 1.1.48.625.g1c87c7f7
 - BlockTheSpot Product Version: 0.51.0.0

**Additional context**
I did the log thingy but I couldn't find the txt files.

**Comment by Daksh777** [comment]
I've always faced such issue with a poor network connection. The song is unable to buffer because of slow internet and then it throws the error "Can't play this song".
I'm using the same version of Spotify on a high-speed connection and I do not face any such issues. I presume it to be a connection issue itself.

To check if it's your connection or BlockTheSpot, uninstall Spotify and install it again (without BTS) and check if you face the same error, if you do, then it's probably your connection.

**Comment by elhertz** [comment]
> I've always faced such issue with a poor network connection. The song is unable to buffer because of slow internet and then it throws the error "Can't play this song".
> I'm using the same version of Spotify on a high-speed connection and I do not face any such issues. I presume it to be a connection issue itself.
> 
> To check if it's your connection or BlockTheSpot, uninstall Spotify and install it again (without BTS) and check if you face the same error, if you do, then it's probably your connection.

It works just fine without BTS. Also it is working on my cracked spotify android app.
Definitely not my connection :/
How do I make the log work? it's not generating any files. Should I reinstall spotify altogether?

**Comment by rednek46** [comment]
@elhertz To enable the logs, goto Spotify directory and in the config.ini set log = 1.
Then use Spotify until you encounter the error.
Then upload the log here.

I haven't had any issues you say btw.
But like @Daksh777 said, poor internet connection can cause this issue.

**Comment by Daksh777** [comment]
> It works just fine without BTS. Also it is working on my cracked spotify android app.
> Definitely not my connection :/

How about you try on a different connection? Maybe use your phone's data's hotspot and try with that?

**Comment by rednek46** [comment]
Considering this as solved. Reopen if you still have issues.

**Comment by elhertz** [comment]
Sorry for the late reply. Covid would not let me function normally.
Noticed that I need to set the quality to "normal" when using BlockTheSpot for some reason. Otherwise it works fine on "High" without BTS. 
Weird but the problem is clearly my connection. Thanks.
