### ISSUE TITLE
Spotify doesn't launch

### ISSUE THREAD

**Issue by streetbeds** [mrpond/BlockTheSpot#117]
After I install BlockTheSpot, spotify doesn't open or launch anymore

**Comment by rednek46** [comment]
@streetbeds you maybe using the removed BTS which is detected as false positive by defender. Try using the current patch.

**Comment by streetbeds** [comment]
I've tried the 26FIX release and the latest release of BTS but spotify still doesn't open

**Comment by rednek46** [comment]
can you check if there is a file called chrome_elf.dll in the spotify dir?

**Comment by streetbeds** [comment]
There is a file called that but when I install BTS it's gone

**Comment by rednek46** [comment]
can you manually download the release package and install without using the BlockTheSpot bat?

**Comment by streetbeds** [comment]
How do you do that?

**Comment by rednek46** [comment]
Browse to your Spotify installation folder %APPDATA%\Spotify
Download chrome_elf.zip from releases
Unzip and replace chrome_elf.dll and config.ini

**Comment by streetbeds** [comment]
there is no file called chrome_elf.dll in the chrome_elf.zip

**Comment by rednek46** [comment]
> there is no file called chrome_elf.dll in the chrome_elf.zip

So its your antivirus that is causing this issue.
Do you have any extreme antivirus other than windows defender?

**Comment by streetbeds** [comment]
mcafee but I turned it off so now I see the file now. I replaced the files and now it's working

**Comment by rednek46** [comment]
> mcafee but I turned it off so now I see the file now. I replaced the files and now it's working

its a false positive by mcafee. so you can whitelist the chrome_elf.dll and it should work fine.
