### ISSUE TITLE
Epic collection: liked song limit

### ISSUE THREAD

**Issue by presence35** [mrpond/BlockTheSpot#119]
Suddenly I'm getting the error "epic collection, friend. Your library is all filled up. To save more, you'll need to remove some songs."

Google says this limitation was removed from Spotify a few months ago. It used to be 10,000 but I only have 3,000 songs in my library anyway.

Windows. Latest everything.

Could this be an issue with the DLL?

**Comment by rednek46** [comment]
This is not related to BlockTheSpot or caused by it either. Use the official Spotify Support.
