### ISSUE TITLE
Resource slowdown on startup

### ISSUE THREAD

**Issue by jayloofah** [mrpond/BlockTheSpot#12]
Resources load very slowly after DNS filter was integrated. This includes cover art and status of the internet (marked as offline for a few seconds on startup).

Desktop
 - OS: [e.g. Windows 10]
 - Spotify Version: 1.1.19.480.g7d17e3ce

**Comment by mrpond** [comment]
fetch test from here https://github.com/mrpond/DNSQuery_AdGuard/
https://github.com/mrpond/DNSQuery_AdGuard/releases/download/v1.0/Q831226_1.zip
use command prompt to test this
.\Q831226_1.exe google.com
and paste the result here

**Comment by mrpond** [comment]
v0.34 is out added option to turn AdGuardDNS off by set it to 0 in config.ini

```
[Config]
AdGuardDNS = 0
Log = 0
Skip_wpad = 0
```

**Comment by jacksonmgoode** [comment]
Just to follow up, this does work. But it's a good idea to add the DNS as a means of having a constantly updated source, if there was a way to perhaps delay the DNS filter until a connection is established?

**Comment by mrpond** [comment]
@jacksonmgoode 

https://github.com/mrpond/BlockTheSpot/blob/e2a25e08bdfe6758d789b8670cd24c5b7bd0fa9b/src/hosts.cpp#L73
I had improve it lately.
if your (default) DNS return success then it will lookup AdguardDNS.
if it fail, AduardDNS lookup will be skipped.
let's me know if you still had this problem.

**Comment by jayloofah** [comment]
Fantastic! Could you also remove the quote (@) to that person. It's my other account, thanks!
