### ISSUE TITLE
spotify not opening

### ISSUE THREAD

**Issue by Honetar19** [mrpond/BlockTheSpot#122]
after replacing the file whenever i open spotify windows defender automatically deletes the replaced files and spotify won't open, solution please

**Comment by rednek46** [comment]
> after replacing the file whenever i open spotify windows defender automatically deletes the replaced files and spotify won't open, solution please

Use BlockTheSpot.bat or use the patch release #26FIX .
If its still removed, then update Windows Defender virus definitions and if it happens again, exclude chrome_elf.dll from scanning. It is a False positive.

**Comment by Honetar19** [comment]
Thanks 26fix worked
