### ISSUE TITLE
Why is the latest chrome_elf zip full of malware and viruses? VirusTotal Scan

### ISSUE THREAD

**Issue by DanKay1** [mrpond/BlockTheSpot#123]
The latest updated zip is full of malware and even has ransomware.

What's up with that?

Scaned with VirusTotal, MalwareBytes and WD.

**Comment by rednek46** [comment]
@DanKay1 Its a false positive. Try using release #26FIX .
Also please consider reading pinned issues or closed issues before posting duplicates #96 😃 .
