### ISSUE TITLE
Windows Defender threat problem

### ISSUE THREAD

**Issue by AdriGeeK03** [mrpond/BlockTheSpot#128]
hey i just got an issue after doing the spotify updtae, it tell me that block the spot.bat is a trojan. I knw=ow u fised this by the past so i just wanted to know if its possible to patch it again .

BTW ,i love ur job ty developpers

**Comment by rednek46** [comment]
@AdriGeeK03 Its a false positive.
you can allow chrome_elf.dll on the antivirus.

**Comment by mrpond** [comment]
already report them for false positive. let's keep this issue open, for now

**Comment by akasaka2013** [comment]
its not working

**Comment by karaeren** [comment]
The issue seems to be fixed, as it's not getting marked by WD as a virus at the moment...

**Comment by mrpond** [comment]
fixed by microsoft windows defender team. I close this issue.

**Comment by nosmall** [comment]
Reopen ?
https://www.virustotal.com/gui/file/cee8edca39529e00f0118168c5eb9d50caa569e5894a1303880f589f81b07f69/detection/f-cee8edca39529e00f0118168c5eb9d50caa569e5894a1303880f589f81b07f69-1617138550

![Snímek obrazovky 2021-03-31 214619](https://user-images.githubusercontent.com/48532/113202056-95106380-926a-11eb-8d2a-6743eeb282e7.png)

**Comment by bluelhf** [comment]
@nosmall issue's been reported via feedback hub, but no feedback yet

**Comment by isaktexas** [comment]
So this isn't a virus right it's just false that virustotal says?

**Comment by muadhferoz** [comment]
so how do I fix this

**Comment by Rishabh672003** [comment]
<img width="960" alt="brave_nBEAgLlFI4" src="https://user-images.githubusercontent.com/53911515/126865909-aa708b9e-de35-407e-9057-3a5948d4db3f.png">
2 others also say that it is malicious

**Comment by Nuzair46** [comment]
@Rishabh672003 its a false positive.
you can ignore it. and allow the patch or add exclusion.

**Comment by GlaZedBelmont** [comment]
virustotal will tell you a normal ass C program contains shit. If a big one detects it as a virus, then yeah I'd be worried

**Comment by kartax4** [comment]
Why is this application contacting this 
![image](https://user-images.githubusercontent.com/72432845/149397188-c411285c-95b0-48e4-9fd3-8f8826c994a9.png)
