### ISSUE TITLE
Still ads

### ISSUE THREAD

**Issue by Tcheburachka** [mrpond/BlockTheSpot#13]
Hello,
Since weeks, I have ads after 2-3 songs. I tried to uninstall fully Spotify (using Revo Uninstaller to be sure to kill everything from previous version) and reinstall but nothing to do, there are always ads playing. 
I have only this problem on my desktop computer (on Win 7), everything seems to work fine with my laptop computer (on Win 10) even though they are both connected on same network.
I don't use proxy nor customised DNS.
I read that previously some people from France (where I live) and Italy had same problem, don't know if it still the case for them and if there's a link...

You'll find enclosed listed DLLs for spotify.exe

Thanks for your work and your support

[dllspotify.txt](https://github.com/mrpond/BlockTheSpot/files/3853242/dllspotify.txt)

**Comment by mrpond** [comment]
use new version v0.34 open config.ini turn on the log
```
[Config]
AdGuardDNS = 1
Log = 1
Skip_wpad = 0
```

**Comment by Tcheburachka** [comment]
Here it is
[log.zip](https://github.com/mrpond/BlockTheSpot/files/3854006/log.zip)

**Comment by mrpond** [comment]
after enable log, did you still get the ads song?

**Comment by Tcheburachka** [comment]
Sadly yes, I just tried again and had one video ad after 10mn. I also noticed that sometimes ads are blocked indeed, but it also blocks the application and prevents it to continue to play songs (screen 1). There's a message displaying " (screen 2), and it forces to restart Spotify. It happened 10mn after first video ad.

![Screen1](https://user-images.githubusercontent.com/57594429/68992775-6a3d8f00-0870-11ea-9a81-2e3074f1fb6a.JPG)
![Screen2](https://user-images.githubusercontent.com/57594429/68992776-6d387f80-0870-11ea-8c09-5c40a22c834d.JPG)

**Comment by mrpond** [comment]
oops, I can't reproduce the bug. but I think it is windows 7 relate.
ok, help me test one by one. and tell me how it goes.

[chrome_elf_zeromem.zip](https://github.com/mrpond/BlockTheSpot/files/3854190/chrome_elf_zeromem.zip)
[chrome_elf_forcefalse.zip](https://github.com/mrpond/BlockTheSpot/files/3854191/chrome_elf_forcefalse.zip)

**Comment by Peuuuur-Noel** [comment]
> use new version v0.34 open config.ini turn on the log
> 
> ```
> [Config]
> AdGuardDNS = 1
> Log = 1
> Skip_wpad = 0
> ```
> 
> zip all log_* and upload here.

Can you commit the config.ini file on git to create it (is in the .gitignore) or add a notice in the readme?

**Comment by Tcheburachka** [comment]
> 
> 
> oops, I can't reproduce the bug. but I think it is windows 7 relate.
> ok, help me test one by one. and tell me how it goes.
> 
> [chrome_elf_zeromem.zip](https://github.com/mrpond/BlockTheSpot/files/3854190/chrome_elf_zeromem.zip)
> [chrome_elf_forcefalse.zip](https://github.com/mrpond/BlockTheSpot/files/3854191/chrome_elf_forcefalse.zip)

For now, Kaspersky detects VHO:Trojan-Dropper.Win32.Roxer.gen in both :/

**Comment by mrpond** [comment]
@Peuuuur-Noel it in the zip file, aha I see. seem I forget to mention it on readme..

@Tcheburachka zeromem modify only this line
https://github.com/mrpond/BlockTheSpot/blob/5ff5050c4c612889c23aba2fe79fa6c19cf44595/src/hosts.cpp#L125
from SecureZeroMemory (lpBuffer, dwNumberOfBytesToRead); 
to ZeroMemory (lpBuffer, dwNumberOfBytesToRead);


forcefalse from true to false
https://github.com/mrpond/BlockTheSpot/blob/5ff5050c4c612889c23aba2fe79fa6c19cf44595/src/hosts.cpp#L126

you can recompile it from source

**Comment by Tcheburachka** [comment]
> 
> 
> oops, I can't reproduce the bug. but I think it is windows 7 relate.
> ok, help me test one by one. and tell me how it goes.
> 
> [chrome_elf_zeromem.zip](https://github.com/mrpond/BlockTheSpot/files/3854190/chrome_elf_zeromem.zip)
> [chrome_elf_forcefalse.zip](https://github.com/mrpond/BlockTheSpot/files/3854191/chrome_elf_forcefalse.zip)

Hello, I tried both. I still had ads with zeromem. But everything seems OK right now with forcefalse, no more ads appeared since a while ! So I guess you managed to fix the problem for good ;) Many thanks for your support and amazing work.

**Comment by mrpond** [comment]
@Tcheburachka ok, tonight I will update forcefalse into v0.37.
