### ISSUE TITLE
Blank Banner in Liked Songs

### ISSUE THREAD

**Issue by tatsumara** [mrpond/BlockTheSpot#130]
**Important**
 - Make sure you use [latest spotify](https://www.spotify.com) before reporting a bug.
 - Make sure you use the [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before reporting a bug.
 - Make sure if blockthespot DLL got replaced after Spotify update (important).

**Describe the bug**
Blank banner above player controls in Liked Songs and playlists, everything else works

**Desktop:**
 - OS: Windows 10
 - Spotify Version: 1.1.52.687.gf5565fe5-a
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by rednek46** [comment]
Provided Spotify version is incomplete. 
anyway you may have the alpha test version. This can cause issues. Check for -a at the end of spotify version.

**Comment by tatsumara** [comment]
Apologies, edited the version and yes I am using the -a version. Any way to easily downgrade?

**Comment by rednek46** [comment]
You could try uninstalling spotify and downloading a clean installer from the site.

**Comment by tatsumara** [comment]
It unfortunately just installs the alpha version again, and I can't seem to find a non-alpha version anywhere to download!

**Comment by rednek46** [comment]
In that case, contact spotify support. I will keep this issue open in case anyone knows how to bypass this.

**Comment by Daksh777** [comment]
> It unfortunately just installs the alpha version again, and I can't seem to find a non-alpha version anywhere to download!

I'm not entirely sure but these ways may work:
1. Ask Spotify support to remove your account from beta/alpha testing
2. Try to download Spotify from an incognito window, and check if that helps.
3. Use a different, non-beta account.

**Comment by centralsport** [comment]
> It unfortunately just installs the alpha version again, and I can't seem to find a non-alpha version anywhere to download!

First Unninstall Spotify 
Download this version (Im also using it)
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.51.382.g8e3b11ed-55.exe
Once u install it after few minutes you should be getting blue dot that new version is available 
When u get blue dot that new spotify update is available go to APPDATA -Local Files-Spotify and right click on Update folder , click on properties-security and deny all permissions for everything

**Comment by SaberAkiyama** [comment]
Mine was the v1.1.53.608.g7ed9c03a-a (latest) is same blank banner

**Comment by rednek46** [comment]
@SaberAkiyama you have an unsopprted alpha version. use @centralsport 's solution to use normal Spotify.

**Comment by SaberAkiyama** [comment]
@rednek46 actually, it's the latest stable version, by the way.

**Comment by rednek46** [comment]
@SaberAkiyama if you have -a at the end of your Spotify version, then its an Alpha release.
