### ISSUE TITLE
Patch to remove upgrade button also removes Spotify profile photo

### ISSUE THREAD

**Issue by Daksh777** [mrpond/BlockTheSpot#131]
When applying the patch to remove the "Upgrade" button, it also removes the profile photo of Spotify.

**Before applying patch:**
![image](https://user-images.githubusercontent.com/43648146/107538887-6ec73380-6bea-11eb-8c51-ee6a5ad8acc3.png)

**After applying patch:**
![image](https://user-images.githubusercontent.com/43648146/107538955-81da0380-6bea-11eb-91db-79219ebdcf68.png)

**Comment by rednek46** [comment]
@Daksh777 can you share your spotify version?

**Comment by Daksh777** [comment]
> @Daksh777 can you share your spotify version?

1.1.52.687.gf5565fe5

**Comment by rednek46** [comment]
@Daksh777 I will try to fix it by editing the zlink.spa of the latest spotify.

**Comment by rednek46** [comment]
Can you try this.
[zlink.zip](https://github.com/mrpond/BlockTheSpot/files/5967596/zlink.zip)

extract and copy zlink.spa to spotify/apps/

**Comment by Daksh777** [comment]
> Can you try this.
> [zlink.zip](https://github.com/mrpond/BlockTheSpot/files/5967596/zlink.zip)
> 
> extract and copy zlink.spa to spotify/apps/

That fixed the issue.

**Comment by rednek46** [comment]
Ok im closing this issue. for future issues and updates on this, use #83 .

**Comment by Neurotoxin001** [comment]
What is zlink?

**Comment by rednek46** [comment]
> What is zlink?

#83

**Comment by Daksh777** [comment]
@rednek46 Same problem again in 1.1.53.605.g2788eafc
