### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by GitWizz** [mrpond/BlockTheSpot#133]
**Important**
 - Make sure you use [latest spotify](https://www.spotify.com) before reporting a bug.
 - Make sure you use the [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before reporting a bug.
 - Make sure if blockthespot DLL got replaced after Spotify update (important).

**Describe the bug**
songs wont play at all anymore. no ads alright but no songs either.

**Desktop:**
 - OS: Windows 10
 - Spotify Version:1.1.53.608.g7ed9c03a
 - BlockTheSpot Product Version: 0.51.0.0 
 - 
**Additional context**
If ad blocking is not working, please include a debug log by
 1. edit config.ini and set Log = 1 
 2. after ads song play close Spotify(songs wont even play)
 3. zip the main_log.txt, utility_log.txt

**Comment by rednek46** [comment]
@GitWizz update your logs.

**Comment by GitWizz** [comment]
[Spotify.zip](https://github.com/mrpond/BlockTheSpot/files/6024223/Spotify.zip)

**Comment by GitWizz** [comment]
hello again. sorry to disrupt you but I have fixed the problem. turns out it was a router issue so i simply did some tuning and it worked! thanks for being amazing and publishing this software!
