### ISSUE TITLE
top banner add appearing with latest spotify update

### ISSUE THREAD

**Issue by zleng1129** [mrpond/BlockTheSpot#134]
![image](https://user-images.githubusercontent.com/74921194/109553800-753a2400-7aa1-11eb-8bc7-7721efea1ef8.png)
Spotify version 1.1.53.608.g7ed9c03a, I only noticed this banner ad when I updated Spotify.

Additionally, I noticed that the download icon shows up when I check the download on my playlist. However, unless these files are stored somewhere else, my spotify folder is still only ~500KB. Could be a bug in blockthespot allowing this download icon to show up, but could also be an error on spotify's end of things.

**Comment by rednek46** [comment]
You have to apply the patch again after the update.
also make sure to enable the `banner_only` option in the config since you are using premium.
The download icon maybe related to Spotify itself.

**Comment by zleng1129** [comment]
Thanks! the banner ad is gone now after the update. But for clarification, I _dont_ have premium, which is why I find it odd that spotify is letting me toggle the download. And as of right now, the folder seems to have actually downloaded all of my songs.
![image](https://user-images.githubusercontent.com/74921194/109562399-568d5a80-7aac-11eb-860f-878b5f3d4b90.png)
Not really an issue, more of an unintentional feature that I just wanted to report in case you wanted to look into it.

**Comment by SaberAkiyama** [comment]
Same, it's only from Home page. Others are removed

**Comment by zleng1129** [comment]
Yeah, even after my reinstall of blockthespot now the banner ad is still showing up for me.

**Comment by mrpond** [comment]
wait for few days, my region still 1.1.53.608.g7ed9c03a.

**Comment by Daksh777** [comment]
I'm on the same version of Spotify but do not see any banner ads
![image](https://user-images.githubusercontent.com/43648146/109933393-5d58df00-7cf1-11eb-8780-a0164be5486f.png)
![image](https://user-images.githubusercontent.com/43648146/109933424-68ac0a80-7cf1-11eb-820e-e5bae2d72569.png)

**Comment by mrpond** [comment]
I can't reproduce these bug on my side.
For who had banner in home page,
turn on Log = 1 in config.ini and upload the log files here. I'll look into it

**Comment by karaeren** [comment]
@mrpond where's the log file supposed to be? Also having ads after the latest update.

**Comment by rednek46** [comment]
@karaeren logs can be found at %appdata%/spotify/

**Comment by Honyant** [comment]
My solution to this issue was to temporarily disable _Real-Time Protection_ under _Virus & Threat Protection Settings_ while running the script.

**Comment by rednek46** [comment]
@Honyant thats not actually a solution to this. Update your windows defender definitions.

**Comment by ronny941** [comment]
the spotify update v1.1.54.592 is out 
I have never had problems with blockspot and there'is no banner ads in the home of my spotify.

**Comment by akasaka2013** [comment]
waiting for a new update patch :)

**Comment by rednek46** [comment]
@akasaka2013 if you have banners,  please attach the log file here.

**Comment by LXGaming** [comment]
Spotify v1.1.54.592.gc0b20638

When opening Spotify the banner ad isn't loaded however I found that by reloading the page (Ctrl + Shift + R) forced it to appear, I've included a screenshot of the request chain from the Chrome devtools (Not sure if that helps)

[blockthespot_log.txt](https://github.com/mrpond/BlockTheSpot/files/6145410/blockthespot_log.txt)

![Banner](https://user-images.githubusercontent.com/10443061/111242080-4d32ef00-8663-11eb-92f1-bc6341fdbd7a.PNG)
![Chain](https://user-images.githubusercontent.com/10443061/111241773-abab9d80-8662-11eb-97f7-eba6597dc12f.PNG)

**Comment by mrpond** [comment]
@LXGaming I think it relate to using custom DNS configuration, 
chrome.cloudflare-dns.com 

if you wish to hide browsing history by this mean, I suggest you to try
adguard dns instead https://adguard.com/en/adguard-dns/overview.html

**Comment by Neurotoxin001** [comment]
> I think it relate to using custom DNS configuration, chrome.cloudflare-dns.com

Why do you think that?

**Comment by mrpond** [comment]
> > I think it relate to using custom DNS configuration, chrome.cloudflare-dns.com
> 
> Why do you think that? Cloudflare does not include any ads in their DNS.
> 
> I too got this banner after first launch with 1.1.54.592.gc0b20638 but after restart banner disappears.
> 
> **UPD**: Nope, banner is still here but it's appears not instantly after launch.
Well, BTS already block *doubleclick*, *googletagservices* domain for any request.
https://github.com/mrpond/BlockTheSpot/blob/611cb84aada3de2229ea8ea30e0f4938e575cc08/src/hosts.cpp#L10

From picture @LXGaming , his/her pc still able to fetch ads module from googletagservices/doubleclick.net 
with log file that never show it connected to doubleclick.net, instead it display cf dns..

here from my PC
allowed - apresolve.spotify.com
allowed - s3.amazonaws.com
allowed - login5.spotify.com
allowed - spclient.wg.spotify.com
allowed - spclient.wg.spotify.com
allowed - gae-spclient.spotify.com
allowed - dailymix-images.scdn.co
allowed - i.scdn.co
allowed - newjams-images.scdn.co
allowed - seeded-session-images.scdn.co

allowed - thisis-images.scdn.co
**blocked - www.googletagservices.com**
blocked - dntcl.qualaroo.com

**Comment by Neurotoxin001** [comment]
Ok, seems like problem is really in Cloudflare DNS (1.1.1.1 and 1.0.0.1) so you must block them too.

Google DNS log - https://pastebin.com/QSMBd9G4
Cloudflare DNS log - https://pastebin.com/GkZ4cmKw

Banner appears not instantly after Spotify start, but after ~20 minutes of using. And it's only one banner (on top of main page) and there is no more ads in other places.

**Comment by mrpond** [comment]
> Ok, seems like problem is really in Cloudflare DNS (1.1.1.1 and 1.0.0.1) so you must block them too.
> 
> Google DNS log - https://pastebin.com/QSMBd9G4
> Cloudflare DNS log - https://pastebin.com/GkZ4cmKw
> 
> Banner appears not instantly after Spotify start, but after ~20 minutes of using. And it's only one banner (on top of main page) and there is no more ads in other places.


1. Block that will make other functionality not working.
e.g. album picture

2. I think these dns try to speed things up. 
By caching these high traffic ads domain+data and serve from their server directly.

3. In this case, I suggest to not use these dns services, but if you really want to hide surf-history from isp(only)
go switch to adguard dns instead.

**Comment by Neurotoxin001** [comment]
Why then you blocking google dns? And adguard is much slower in ping tests.

**Comment by mrpond** [comment]
> Why then you blocking google dns? And adguard is much slower in ping tests.

DNS functional/duty are made to resolve domain name, not acting like ads cache in this case
I wildcard *google* because a lot spotify ads rely on google services.
It a bug in my logic and beyond my test case, xD.

Seriously, for me. adguard high ping are not much issue
Windows also cache these dns hostname locally too, so request somethings second time
would look up from local windows cache first.

**Comment by mrpond** [comment]
btw, I will mark this as bug, next BTS version will log something about dns problem too.
I need todo something much more creative, in order to catch these problem.

**Comment by mrpond** [comment]
Hi , dns bug can be solve by set Skip_wpad = 1 in config.ini

**Comment by hyoretsu** [comment]
My Spotify UI changed after today, guessing it's an update. (used hosts file to block them though) Banner area started showing up again, though ads between songs didn't.
Here's my log:
```
GetModuleInformation OK!
main process - patch success!
Mhook_SetHook - getaddrinfo success!
allowed - login5.spotify.com
allowed - apresolve.spotify.com
allowed - spclient.wg.spotify.com
allowed - spclient.wg.spotify.com
allowed - guc-spclient.spotify.com
allowed - guc-dealer.spotify.com
allowed - api.spotify.com
allowed - api-partner.spotify.com
allowed - i.scdn.co
allowed - spclient.wg.spotify.com
allowed - guc-spclient.spotify.com
allowed - api-partner.spotify.com
allowed - i.scdn.co
allowed - audio-fa.scdn.co
allowed - i.scdn.co
allowed - i.scdn.co
```

**Comment by rednek46** [comment]
@hyoretsu would be good if you could also provide your Spotify version,

**Comment by hyoretsu** [comment]
@rednek46 Couldn't find it inside Spotify but Control Panel says 1.1.54.592.gc0b20638. I had to re-install it to solve another issue, so it should be the latest one.

**Comment by rednek46** [comment]
@hyoretsu it is not the latest.

**Comment by hyoretsu** [comment]
@rednek46 Now it's 1.1.55.498.gf9a83c60 and it's still there. Just got back from formatting my PC.

**Comment by rednek46** [comment]
> @rednek46 Now it's `v1.1.55.498.gf9a83c60` and it's still there. Just got back from formatting my PC.

Can you try [this](https://github.com/mrpond/BlockTheSpot/issues/134#issuecomment-805594122)

**Comment by hyoretsu** [comment]
> Can you try [this](https://github.com/mrpond/BlockTheSpot/issues/134#issuecomment-805594122)
Already tried the first time, but still tried again. Didn't do anything.
