### ISSUE TITLE
New User, Spotify completely broken

### ISSUE THREAD

**Issue by KarmicEmpire** [mrpond/BlockTheSpot#136]
When I copy the files from chrome_elf to %APPDATA%/Spotify, an error appears on Windows saying that it cannot find libcef.dll even though the file is there.
![Error Spotify](https://user-images.githubusercontent.com/80420976/110682097-3ca5f300-81e3-11eb-9c8f-1ddf7f3c3ec5.PNG)

As well as when I use the BlockTheSpot.bat file, I can open spotify but, nothing will play and no songs will load.

**Desktop:**

 - OS: Windows 10
 - Spotify Version: 1.1.54.592.gc0b20638
 - BlockTheSpot Product Version: [e.g. 0.50.0.0]

**Comment by rednek46** [comment]
Can you install with blockthespot.bat

**Comment by KarmicEmpire** [comment]
> Can you install with blockthespot.bat

I've tried that and Spotify completely shuts down

**Comment by rednek46** [comment]
Your antivirus is blocking chrome_elf.dll . Try allowing it.

**Comment by KarmicEmpire** [comment]
> 
> 
> Your antivirus is blocking chrome_elf.dll . Try allowing it.

I tried that and I turned off my antivirus, it still has the same problem

**Comment by mrpond** [comment]
> When I copy the files from chrome_elf to %APPDATA%/Spotify, an error appears on Windows saying that it cannot find libcef.dll even though the file is there.
> ![Error Spotify](https://user-images.githubusercontent.com/80420976/110682097-3ca5f300-81e3-11eb-9c8f-1ddf7f3c3ec5.PNG)
> 
> As well as when I use the BlockTheSpot.bat file, I can open spotify but, nothing will play and no songs will load.
> 
> **Desktop:**
> 
> * OS: Windows 10
> * Spotify Version: 1.1.54.592.gc0b20638
> * BlockTheSpot Product Version: [e.g. 0.50.0.0]

download 26FIX version from release. and it will working

**Comment by KarmicEmpire** [comment]
> > When I copy the files from chrome_elf to %APPDATA%/Spotify, an error appears on Windows saying that it cannot find libcef.dll even though the file is there.
> > ![Error Spotify](https://user-images.githubusercontent.com/80420976/110682097-3ca5f300-81e3-11eb-9c8f-1ddf7f3c3ec5.PNG)
> > As well as when I use the BlockTheSpot.bat file, I can open spotify but, nothing will play and no songs will load.
> > **Desktop:**
> > 
> > * OS: Windows 10
> > * Spotify Version: 1.1.54.592.gc0b20638
> > * BlockTheSpot Product Version: [e.g. 0.50.0.0]
> 
> download 26FIX version from release. and it will working

It works. Thank you so much

**Comment by rednek46** [comment]
closing as it is solved
