### ISSUE TITLE
Random songs start playing

### ISSUE THREAD

**Issue by Nichesco** [mrpond/BlockTheSpot#138]
**Describe the bug**
After 15-30 seconds random songs start automatically playing! Its real problem!

**Desktop:**

 - OS: [e.g. Windows 10]
 - Spotify Version: latest
 - BlockTheSpot Product Version: latest

**Comment by mrpond** [comment]
![image](https://user-images.githubusercontent.com/18654771/111034785-cbb44480-8449-11eb-9d81-5ab15b12c83f.png)
If there are connected device your account had been compromise.
change password and it will be fine. 
Long ago I use temp mail to register Spotify and got account take over too.
here full read,
![image](https://user-images.githubusercontent.com/18654771/111034830-f4d4d500-8449-11eb-9d48-4881f224db41.png)

**Comment by Nichesco** [comment]
> ![image](https://user-images.githubusercontent.com/18654771/111034785-cbb44480-8449-11eb-9d81-5ab15b12c83f.png)
> If there are connected device your account had been compromise.
> change password and it will be fine.
> Long ago I use temp mail to register Spotify and got account take over too.
> here full read,
> ![image](https://user-images.githubusercontent.com/18654771/111034830-f4d4d500-8449-11eb-9d48-4881f224db41.png)

Well theres nothing in connected devices i will try to change pass.

**Comment by Nichesco** [comment]
Didnt help i have no idea whats the problem here

**Comment by Nichesco** [comment]
It seems to be something with my account because when i use other accounts it fine. Sorry for bothering
