### ISSUE TITLE
Ads back at version 1.1.20 Nov. 24, 2019

### ISSUE THREAD

**Issue by Kingzyyy** [mrpond/BlockTheSpot#14]
Ads definitely back at v1.1.20.

**Comment by Kingzyyy** [comment]
Ads definitely back at version 1.1.20.

**Comment by markypizz** [comment]
I had to reinstall spotify from the web and then re-apply the patch, and it seems good from my end now.

I had noticed when I went to "About Spotify" it said I suddenly was using the Windows Store version, which I never installed. Noticed %APPDATA%/Spotify didn't exist anymore either. Not sure what happened there. Not sure if that's happening to anyone else either, or if that's what the cause of this is

**Comment by mrpond** [comment]
@Kingzyyy please report using report form, blockthespot work fine.
you need to reapply the patch after spotify got updated.

@markypizz remove the store version use the web instead.
since windows block modify store app folder.
