### ISSUE TITLE
Rollback to the old interface

### ISSUE THREAD

**Issue by amd64fox** [mrpond/BlockTheSpot#141]
Hello everyone, someone has an idea how to rollback to the old client interface, I have version `1.1.55.498.gf9a83c60` and a new interface, ads are blocked, but empty blocks are displayed under the playlists. Your way to rollback through this [version](http://download.spotify.com/SpotifyFullSetup.exe) does not help.

Or maybe there is a way to block ads in the new interface?

**Comment by Daksh777** [comment]
I'm on the same version as you are but I don't see any ads or any empty blocks either.
How about you try using BlockTheSpot.bat?

**Comment by amd64fox** [comment]
You and I have the same versions, but I have a new interface, and you have an old one. 
Using BlockTheSpot.bat didn't help.
![12343](https://user-images.githubusercontent.com/62529699/112749907-08497980-8fce-11eb-9744-a222775152db.jpg)

**Comment by Daksh777** [comment]
Are you sure you don't have "-a" in your Spotify version?

**Comment by amd64fox** [comment]
I do not have at the end of the version -a.
Thanks, I was helped by the instruction below from the respected @khanhas

________________________________________________________________________________________________________________________________________
1.Create a file named index.html, paste this content in:

 <html><script>window.location.assign("spotify:app:zlink")</script></html> 
2. Create a file named manifest.json, paste this content in:

{
"BundleIdentifier": "xpui",
"BundleType": "Application"
}
3. Now using any zip utility to zip those 2 files and names the zip file xpui.spa

4. Copy and replace it with the original one in Spotify's Apps folders, depends on your platform, it could locate in: MacOS: /Applications/Spotify.app/Contents/Resources/Apps
Windows: %appdata%\Spotify\Apps
Linux: Please find where your package manager installed Spotify

5. Restart Spotify.
Note: After every new Spotify update, just do step 4 and 5 again then you should be fine.

**Comment by rednek46** [comment]
[xpui.zip](https://github.com/mrpond/BlockTheSpot/files/6234124/xpui.zip)
Above patch

**Comment by rednek46** [comment]
@amd64fox thanks for this.
I have added it to BlockTheSpot.bat
So you can just run it and it will do it automatically.

**Comment by amd64fox** [comment]
@mrpond @rednek46 My regards 👏

**Comment by amd64fox** [comment]
On reddit.com , [here](https://www.reddit.com/r/spotify/comments/mpxwz3/reverting_to_the_classic_desktop_ui/) I saw a new way to rollback to the old interface, you need to add a new line to the prefs file `ui.experience_override="classic"`

**Comment by rednek46** [comment]
Old interface rollback feature is already added to BlockTheSpot.bat

**Comment by Davoleo** [comment]
The new way sounds like a less intrusive solution than the other one though

**Comment by rednek46** [comment]
@Davoleo I understand that. And its easy when doing it manually.

The reason I don't want the script to do that is because `pref` file contains all the Spotify user details including the User Access Token. It's just that editing a file that contains credentials and Sensitive contents may raise many questions.
