### ISSUE TITLE
Spotify Connect Not working?

### ISSUE THREAD

**Issue by Techie5879** [mrpond/BlockTheSpot#142]
Spotify Connect isn't working with this desktop version, it shows greyed out and for premium users only, but I think it used to work previously.

 - OS: Windows 10 (20H2)
 
  1. Latest Spotify 1.1.55.498.gf9a83c60
  2. Yes latest BlockTheSpot
  3. Blockthespot are not working with Spotify from Microsoft Store or alpha version of Spotify.

I'm not sure if it is supposed to work or not, I'm using the desktop blockthespot and mod android app, can select the desktop from the android app but cannot select the android phone from the desktop (as I said, it shows greyed out.)

**Comment by fosam** [comment]
Hi, how is it going..?

I think i have this situation too, i can choose on the phone but not on the desktop, so you are right, it is not working to be exact.

But i'm not worried as i don't use this function, i think it is absurd that Spotify calls this feature "premium" as it almost does nothing than just switch speakers/players whereas one can just use bluetooth to do the same thing, what do you think?

![Capture 29_03_2021_00_03_57](https://user-images.githubusercontent.com/52612348/112769820-7a987900-9023-11eb-8584-72497632c82f.png)

**Comment by rednek46** [comment]
It looks like a feature for premium users only now.
So it may not be fixed here. I'll wait for what mrpond has to say.

**Comment by Techie5879** [comment]
Yeah I'm not really sure but I kinda vaguely remember it working before but maybe I'm wrong. Its not really a big deal but just was  a convenience kinda thing, dont use it that often but its nice to have. I'll wait for what mrpond has to say, and if this is not doable that's completely fine with me.

**Comment by rednek46** [comment]
It was free before. And it maybe do able. But this repo is for ad blocking. Unlocking a premium feature like that can result in a DMCA takedown.

**Comment by ronny941** [comment]
I wanted to tell you that spotify has changed interface and that now it seems that the bug of the recently listened songs that were not shown in the home is fixed now everything is working correctly, I wanted to say it in the other discussion but I could not do it.
