### ISSUE TITLE
There's no ad but where the ad is placed is still there

### ISSUE THREAD

**Issue by UnnieChaeng** [mrpond/BlockTheSpot#146]
There's no ad but where the ad is placed is still there
![image](https://user-images.githubusercontent.com/73013338/114256381-142c3700-99e3-11eb-92ff-8560e57bf259.png)

**Comment by Syzygianinfern0** [comment]
Same issue for me too

**Comment by Daksh777** [comment]
You are using the new Spotify UI, switch back to the old one: https://github.com/mrpond/BlockTheSpot/issues/141#issuecomment-808897804

**Comment by rednek46** [comment]
@Syzygianinfern0 @UnnieChaeng use BlockTheSpot.bat and enter Y when prompt appears to swap to OLD UI.
