### ISSUE TITLE
Spotify ads are back!

### ISSUE THREAD

**Issue by drewcu** [mrpond/BlockTheSpot#148]
**Describe the bug**
Ads play even with the 2 files in the Spotify folder after the recent Desktop application update. Didn't used to have this issue.

**Important:**
 - OS: Windows 7 Ultimate (April 2021 security patches)
 - Confirm that you currently using latest version of
  1. Spotify version 1.1.57.443.ga029a6c4
  2. Blockthespot version 2021.3.25.33

**Additional context:**
[blockthespot_log.zip](https://github.com/mrpond/BlockTheSpot/files/6328233/blockthespot_log.zip)

**Temporary workaround:** 

1. Install next most recent Spotify version 1.1.56.595 from a site like [https://spotify.en.uptodown.com/windows/download/3433214](https://spotify.en.uptodown.com/windows/download/3433214).

2. Block automatic updates by removing Spotify's admin permissions using [https://community.spotify.com/t5/Desktop-Windows/Stopping-Auto-update/td-p/4785101](https://community.spotify.com/t5/Desktop-Windows/Stopping-Auto-update/td-p/4785101) as a guide.

```
Open Admin Command Prompt and type these commands one by one:
rm %localappdata%\Spotify\Update (Use "rem" instead of "rm" if on Windows 7 - thanks @Invictaz)
mkdir %localappdata%\Spotify\Update
icacls %localappdata%\Spotify\Update /deny "%username%":D
icacls %localappdata%\Spotify\Update /deny "%username%":R
```

3. Reinstall Blockthespot and profit. Now Spotify cannot autoupdate without proper permissions... think this needs to be done for all Admin users of the PC who use Spotify.

Hopefully a Blockthespot fix will avoid the need for all this and you can restore permissions by doing the following from another Admin Command Prompt: `icacls %localappdata%\Spotify\Update /reset /T`

Thanks!

**Comment by rednek46** [comment]
Wait for it. The update may not be available on @mrpond's country yet.

**Comment by Sang21y** [comment]
I added my way and it worked 
- follow this guide:
+ Copy everything below: 
--------------------------------------------------
127.0.0.1 adclick.g.doublecklick.net 
127.0.0.1 adeventtracker.spotify.com 
127.0.0.1 ads-fa.spotify.com 
127.0.0.1 analytics.spotify.com 
127.0.0.1 audio2.spotify.com 
127.0.0.1 b.scorecardresearch.com 
127.0.0.1 bounceexchange.com 
127.0.0.1 bs.serving-sys.com 
127.0.0.1 content.bitsontherun.com 
127.0.0.1 core.insightexpressai.com 
127.0.0.1 crashdump.spotify.com 
127.0.0.1 d2gi7ultltnc2u.cloudfront.net 
127.0.0.1 d3rt1990lpmkn.cloudfront.net 
127.0.0.1 desktop.spotify.com 
127.0.0.1 doubleclick.net 
127.0.0.1 ds.serving-sys.com 
127.0.0.1 googleadservices.com 
127.0.0.1 googleads.g.doubleclick.net 
127.0.0.1 gtssl2-ocsp.geotrust.com 
127.0.0.1 js.moatads.com 
127.0.0.1 log.spotify.com 
127.0.0.1 omaze.com 
127.0.0.1 open.spotify.com 
127.0.0.1 pagead46.l.doubleclick.net 
127.0.0.1 pagead2.googlesyndication.com 
127.0.0.1 partner.googleadservices.com 
127.0.0.1 pubads.g.doubleclick.net 
127.0.0.1 redirector.gvt1.com 
127.0.0.1 s0.2mdn.net 
127.0.0.1 securepubads.g.doubleclick.net 
127.0.0.1 tpc.googlesyndication.com 
127.0.0.1 v.jwpcdn.com 
127.0.0.1 video-ad-stats.googlesyndication.com 
127.0.0.1 https://www.techattend.com 
127.0.0.1 weblb-wg.gslb.spotify.com 
127.0.0.1 http://www.googleadservices.com 
127.0.0.1 http://www.googletagservices.com 
127.0.0.0 gads.pubmatic.com
--------------------------------------------------------------------
+ After that, open "File Explorer" and change directory to "C:\Windows\System32\drivers\etc" 
+ Double click to "host" file then paste all content to that file. 
+ Finally you save that and enjoy !!! :D
### It's may only work for windows operating system ###
Edit: I hope someone can turn this into a .bat file that you just press it to run without having to manually do this anymore. I am not good at programming and I'm just getting used to it :D

**Comment by ronny941** [comment]
but those of spotify had not bypassed this block of the hosts file with the previous versions?
I say this because I had seen some videos saying that after you put the strings in the windows hosts file
it's true about the ads of spotify iwas blocked 
but however there was the problem that some songs no longer started and they were not reproduced and crashed all the time.

**Comment by rednek46** [comment]
> but those of spotify had not bypassed this block of the hosts file with the previous versions?
> I say this because I had seen some videos saying that after if you put the strings in the windows hosts file
> it's true about the ads of spotify was blocked
> but however there was the problem that some songs no longer started and they were not reproduced and crashed all the time.

BTS doesn't make any changes to the host file. Since change in host file can block things like songs too.

**Comment by ronny941** [comment]
> 
> 
> > but those of spotify had not bypassed this block of the hosts file with the previous versions?
> > I say this because I had seen some videos saying that after if you put the strings in the windows hosts file
> > it's true about the ads of spotify was blocked
> > but however there was the problem that some songs no longer started and they were not reproduced and crashed all the time.
> 
> BTS doesn't make any changes to the host file. Since change in host file can block things like songs too.

yes i know that blockthespot works differently and it works 100% for me
but i had read the Sang21y's comment on her problem and I remembered that spotify has patched this procedure of the hosts file because the songs no longer did work

**Comment by Invictaz** [comment]
@drewcu for Windows 7 you need "rem" instead of "rm" for the first command, otherwise it won't work. RM is not understood by my version of Windows 7, maybe because of language although I doubt that. With "rem" it works.

**Comment by bzzrak** [comment]
Can confirm that BTS doesn't work with the latest version of Spotify.

**Comment by drewcu** [comment]
> @drewcu for Windows 7 you need "rem" instead of "rm" for the first command, otherwise it won't work. RM is not understood by my version of Windows 7, maybe because of language although I doubt that. With "rem" it works.

Yeah I wasn't sure what the Win 7 command was as "rm" like you said doesn't work, but in my case I didn't have an Update folder at the time. I'm updating my OP with the Win 7 command, thanks!

**Comment by bzzrak** [comment]
@Invictaz yep, don't update.

**Comment by saltyshxtt** [comment]
from what i've tested reverting to the old UI fixes things (the option that pops up in the cmd prompt)

**Comment by zakblacki** [comment]
waiting for update.

**Comment by Bec-de-Xorbin** [comment]
> Wait for it. The update may not be available on @mrpond's country yet.

URL to update: https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.57.443.ga029a6c4-43.exe

Latest working version at the moment: https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.56.595.g2d2da0de-20.exe

**Comment by Bec-de-Xorbin** [comment]
> @drewcu for Windows 7 you need "rem" instead of "rm" for the first command, otherwise it won't work. RM is not understood by my version of Windows 7, maybe because of language although I doubt that. With "rem" it works.

rem doesn't do anything. It is used for comments in a batch file.

`rd /s /q "%localappdata%\Spotify\Update"` should do the trick, if the directory is present. Usually it isn't.

**Comment by richtschej** [comment]
For me the last version of the chrome files also work for 1.1.57. no ads and prem functions

**Comment by McStecca** [comment]
I don't know why but i'm still using [this version](https://github.com/mrpond/BlockTheSpot/releases/tag/2020.9.30.22) and the only thing is that now the ad bar appered but it's blank i have no ads

**Comment by McStecca** [comment]
So i went in %appdata%\Spotify\Apps\zlink\css\zlink.css and added `height:0` to `#leaderboard-ad-wrapper` to hide the banner

**Comment by SammCheese** [comment]
Alright, here a temporary solution. Download the Latest Working Version from [here](https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.56.595.g2d2da0de-20.exe) and add these lines to your `C:\Windows\System32\drivers\etc\hosts` file
#

- 0.0.0.0 upgrade.spotify.com
- 0.0.0.0 www.spotify-desktop.com
- 0.0.0.0 sto3-accesspoint-a88.sto3.spotify.net
- 0.0.0.0 upgrade.scdn.co
- 0.0.0.0 beta.spotify.map.fastly.net
- 0.0.0.0 prod.spotify.map.fastlylb.net
#

This should prevent your Client from Autoupdating.

Once BlockTheSpot has been updated, simply remove the lines from your Hosts file

**Comment by TheArgentinian** [comment]
this is why I should read the issue page before updating. i forced updated this morning, smh.

**Comment by mrpond** [comment]
I just got update 5 minute ago, and it is alpha version LOL, let's me roll out a test on discord

**Comment by ronny941** [comment]
ok we have to wait for a new update of blockthespot 
the update in question is proposed to me but if you say that the ads of spotify  reappears I wait the update of blockthespot before applyng this update

**Comment by mrpond** [comment]
fixed !

**Comment by drewcu** [comment]
```
GetModuleInformation OK!
**main process#1 - patch failed!**
main process#2 - patch success!
Mhook_SetHook - getaddrinfo success!
```

Installed the updated BTS and latest Spotify - is the 2nd line above from the log expected behavior?

Thanks!
