### ISSUE TITLE
Profile pictures in friends activity are not visible

### ISSUE THREAD

**Issue by punpun0** [mrpond/BlockTheSpot#149]
Profile pictures in friends activity are not visible.
Used to be visible in older versions (previously used version 28 which worked fine).

 - OS: Windows 10
 - Using the latest Spotify version and BlockTheSpot release.
 - Using Spicetify, however the profile pictures don't appear without it either.
 
![Spotify_ScKD2aKLIh](https://user-images.githubusercontent.com/28404695/115254929-7f3de200-a136-11eb-8213-8545c2979bc1.png)

**Comment by rednek46** [comment]
I think its an issue with Spotify itself. Because I have the same issue without using BTS. Please uninstall BTS and see if they exist.

**Comment by punpun0** [comment]
> 
> 
> I think its an issue with Spotify itself. Because I have the same issue without using BTS. Please uninstall BTS and see if they exist.

I have uninstalled BTS and the profile pictures now appear.

**Comment by rednek46** [comment]
Okay thanks for the info.

**Comment by mrpond** [comment]
ok, I fix it in next version.

**Comment by mrpond** [comment]
ok please test it. I remove fbsbx  domain block.

**Comment by punpun0** [comment]
> 
> 
> ok please test it. I remove fbsbx domain block.

Working perfectly now. Thank you.
