### ISSUE TITLE
Add the "exit" to bat file

### ISSUE THREAD

**Issue by vsuh** [mrpond/BlockTheSpot#151]
Add 6 line after `;;;===,,,pause`:
```cmd
;;;===,,,Exit
```

**Comment by rednek46** [comment]
> Add 6 line after `;;;===,,,pause`:
> 
> ```batchfile
> ;;;===,,,Exit
> ```

Exit will automatically close the shell after the bat has finished execution or if it errored out. Pause is used so that it wont happen, and in case of an error, it should be easy for the user to take note of it. Its just the matter of pressing enter. so...
