### ISSUE TITLE
Recently Played Songs Bug 

### ISSUE THREAD

**Issue by ronny941** [mrpond/BlockTheSpot#153]
when you close and reopen the program the songs and the playlist or the artist are displayed in the home of spotify
but now in the spotify home  "recently listened songs" there is a bug because once you close the program and reopen it, it doesn't remember the songs you have listened to and it's not remain saved
when spotify it is open the songs are counts them normally but when you close and reopen spotify 
the songs was vanished
as you can see the songs I have listening now are the ones that I have circled on the screen  
once reopened the program this is should remain saved
I have the latest version of spotify and the latest version of block the spot
![canzoni ascoltate di recente](https://user-images.githubusercontent.com/32131958/115798658-0e692500-a3d7-11eb-9ec5-ea2e910ca99a.JPG)

but when I close spotify and I riopened them this not happens and the songs that I had listened to before are disappeared
![Canzoni che avevo ascoltato Sparite](https://user-images.githubusercontent.com/32131958/115798766-4d977600-a3d7-11eb-8d23-0377495fae9c.JPG)

I hope you fix this bug

**Comment by rednek46** [comment]
Are you sure this bug is not present in Spotify without using BTS?

**Comment by ronny941** [comment]
> 
> 
> Are you sure this bug is not present in Spotify without using BTS?

it's a bug by spotify again because before blockthespot and after applyng blockthespot the bug persist

**Comment by rednek46** [comment]
So. if its a bug by Spotify how do you imagine this repository maintain that? Please contact Spotify support for issues related to Spotify. This repo is for blocking ads.
