### ISSUE TITLE
Unlock the "Very high" Streaming quality

### ISSUE THREAD

**Issue by SwagsRGB** [mrpond/BlockTheSpot#154]
Block the spot is the best thing Ive ever used. However i was wondering if the Very High streaming quality can be unlocked. Because it seems its a client sided feature.
Sorry to bother if its server sided and impossible to add.

**Comment by Daksh777** [comment]
"Very High" streaming quality can only be selected by Premium users, it's not something BTS can achieve.

**Comment by rednek46** [comment]
^^
