### ISSUE TITLE
Hide playlist sponsor

### ISSUE THREAD

**Issue by McStecca** [mrpond/BlockTheSpot#156]
Not a really big issue, but on certain spotify playlist there is this space with a sponsor
![image](https://user-images.githubusercontent.com/21223192/117587133-b7748700-b11c-11eb-9052-5e11a61e5a3a.png)

I'm using Windows 10 and this version
![image](https://user-images.githubusercontent.com/21223192/117587144-d8d57300-b11c-11eb-8551-1d416a12e08f.png)

**Comment by amd64fox** [comment]
I have the same version, but there is no such block with a sponsor.
Can be blocked via `xpui-routes-playlist.css`, you just need to find the correct css block using developer mode.

**Comment by TheseusPrince** [comment]
> I have the same version, but there is no such block with a sponsor.
> Can be blocked via `xpui-routes-playlist.css`, you just need to find the correct css block using developer mode.

How do I activate developer mode?
I've searched my google but i can't find it

Thanks!

**Comment by amd64fox** [comment]
@TheseusPrince 

You need to add a new line to the prefs file.

- Win+R
- `%appdata%\Spotify\prefs`
- Open prefs file with notepad
- add a new line `app.enable-developer-mode=true`
- close and save

**Comment by Daksh777** [comment]
Seems like `.HomeHeader #hpto-container .ad-container .hpto-image-creative` is that CSS property.
![image](https://user-images.githubusercontent.com/43648146/118254973-4b51a480-b4c9-11eb-8f24-04d223d7154a.png)

**Comment by TheseusPrince** [comment]
> @TheseusPrince
> 
> You need to add a new line to the prefs file.
> 
> * Win+R
> * `%appdata%\Spotify\prefs`
> * Open prefs file with notepad
> * add a new line `app.enable-developer-mode=true`
> * close and save

@amd64fox Alright, thank you!

**Comment by Daksh777** [comment]
I can't seem to find it any playlist, can anyone confirm?

**Comment by amd64fox** [comment]
>can anyone confirm?

also could not find such playlists

**Comment by Nuzair46** [comment]
Closing for being a stale issue.
