### ISSUE TITLE
BlockTheSpot script cannot revert to the old UI and shows a black screen

### ISSUE THREAD

**Issue by Daksh777** [mrpond/BlockTheSpot#157]
![image](https://user-images.githubusercontent.com/43648146/117822927-929e2200-b28a-11eb-912b-3c8a4baacdff.png) <br>
Spotify version: `1.1.59.710.g134abcca-a`

Using `ui.experience_override="classic"` in prefs no longer works either.

**Comment by Daksh777** [comment]
Also, with the new changes that keep happening on Spotify, to remove the upgrade button, use https://github.com/daksh777/spotifynopremium
It still works with the new UI.

**Comment by Daksh777** [comment]
It is advisable to not update to this version.

- Go to C:\Users\username\AppData\Local\Spotify
- Create a folder called "Update", if you already have it then ignore this point
- Go to the properties of the folder and the into the security tab and deny "Full Control" for the Users group

**Comment by Rednek46** [comment]
@Daksh777 the BTS blocks the ad for the new version right?

**Comment by mrpond** [comment]
I still not get this version update... wait few days .

**Comment by Daksh777** [comment]
> @Daksh777 the BTS blocks the ad for the new version right?

Yes

**Comment by Rednek46** [comment]
@Daksh777 I removed (commented out) the old UI patch from the script. I think Spotify completely removed the support or something.

**Comment by Rednek46** [comment]
Im closing this. About the remove upgrade patch, i have mentioned it in issue 83.
