### ISSUE TITLE
How to Block Audio and video ads only 

### ISSUE THREAD

**Issue by tonydavidx** [mrpond/BlockTheSpot#159]
is is possible to block audio and video ads only ?

**Comment by Rednek46** [comment]
Yes. use BlockTheSpot.bat or read the instructions in the readme.

**Comment by tonydavidx** [comment]
config.ini file has option to block banner only

**Comment by Daksh777** [comment]
> config.ini file has option to block banner only

Re-read the sentence, "For ***Spotify Premium*** users, setting Block_BannerOnly = 1 will only block the banner at home"

By default, BlockTheSpot will block all ads.
