### ISSUE TITLE
Sidebar Facebook 

### ISSUE THREAD

**Issue by zakblacki** [mrpond/BlockTheSpot#16]
Any chance we can bring back the facebook friends sidebar on the right ?

**Comment by mrpond** [comment]
I'm personally don't use that feature.
I can suggest 2 option
A: I do it
turn on the winhttp logging goto friend sidebar then close program, 
zip the log and post it here. I try add it.
B: you help me do it
turn on the winhttp logging , figure out which respond are fb-friend.
and add it into the exception in host.cpp like this
https://github.com/mrpond/BlockTheSpot/blob/e2a25e08bdfe6758d789b8670cd24c5b7bd0fa9b/src/hosts.cpp#L111
and this
https://github.com/mrpond/BlockTheSpot/blob/e2a25e08bdfe6758d789b8670cd24c5b7bd0fa9b/src/hosts.cpp#L116
these 2 exception are for fb-login.
:)

**Comment by mrpond** [comment]
`	char* pdest = strstr ((LPSTR)lpBuffer, "{\"login_url");
	if (pdest != NULL) {
		return true;
	}

	pdest = strstr ((LPSTR)lpBuffer, "{\"credentials");
	if (pdest != NULL) {
		return true;
	}
`
here are how the skip work so if you (think you) found it 
you can try append it 

`	char* pdest = strstr ((LPSTR)lpBuffer, "{\"login_url");
	if (pdest != NULL) {
		return true;
	}
	pdest = strstr ((LPSTR)lpBuffer, "{\"credentials");
	if (pdest != NULL) {
		return true;
	}
	pdest = strstr ((LPSTR)lpBuffer, "{\"**I think this is friend sidebar!**");
	if (pdest != NULL) {
		return true;
	}
`

hope it help
