### ISSUE TITLE
Not able to use Spicetify alongside with BTS!!

### ISSUE THREAD

**Issue by navaneethkm004** [mrpond/BlockTheSpot#162]
Well, after I install Spotify, I installed a Spicetify theme, then I ran BTS with upgrade button not removed and also used Alpha UI. So after that, when I try to open Spotify, it isn't opening. So I tried the reverse, I ran BTS with the same settings as above and then I installed Spicetify theme, then ADs aren't blocked. So what should I do to use Spicetify theme as well as use BTS. I know BTS doesn't work well with Alpha UI but it does block the audio ADs and that's all I want. Please help!!

 - OS: Windows 10
 - Using latest Spotify and latest BTS.

**Comment by Rednek46** [comment]
Hey. use the latest BlockTheSpot.bat or install the patch manually AFTER applying Spicetify Theme.
BTS blocks ads in the new UI, except have a few bugs but it should work fine with spicetify since I'm using it currently with no issue.

**Comment by navaneethkm004** [comment]
![image](https://user-images.githubusercontent.com/34748927/118442684-868de680-b708-11eb-8f71-c1e7c54ee59e.png)

**Comment by navaneethkm004** [comment]
This is the result after doing BTS.bat after applying theme

**Comment by navaneethkm004** [comment]
I'll try manually next time.

**Comment by navaneethkm004** [comment]
Yess. It worked when I did it manually!! Please try to rectify the error coming when I do it using the bat file.

**Comment by Rednek46** [comment]
The script just does the same copy paste. I think you may be using the old commit of the script.
I fixed some issues in the latest one. Please give it a try if possible.

Also, this is the first issue related to this. No one else reported anything yet.

**Comment by navaneethkm004** [comment]
Ok 👍. I'll download the script again and try. Thanks for replying ✌

**Comment by introvertism** [comment]
I'm having the same issue and have been for almost a week now, I just figured it was a me thing since no one else reported it. My script is up to date and I've tried running it many times with the same issue. Never used Spicetify though I'm on default Spotify.

**Comment by Rednek46** [comment]
@navaneethkm004 I checked right now and it seems i too have this issue.
did you face any "user.css" not found error while applying Spicetify? Also, I think a latest version of Spicetify is relased 2 days ago. give it a try.

**Comment by navaneethkm004** [comment]
@Rednek46 No, I didnt face that issue

**Comment by Rednek46** [comment]
@navaneethkm004 spicetify Themes wont work anymore until updated for new UI. Maybe thats the issue. Check Spicetify changelog for more info.

**Comment by navaneethkm004** [comment]
Sure I'll check
