### ISSUE TITLE
advertising frame is back :(((

### ISSUE THREAD

**Issue by Sang21y** [mrpond/BlockTheSpot#164]
The ad frame reappear even though I changed "Block_BannerOnly = 0" :(((

You can see that in below picture:
--------------------------------
![image](https://user-images.githubusercontent.com/82255151/118804977-9146a800-b8cf-11eb-85f7-7bbb7dfefc7e.png)
--------------------------------
Spotify version 1.1.59.712.g54f36e5d
I hope you can fix it soon :(((
Thank you so very much <3

**Comment by Rednek46** [comment]
dupe #150
