### ISSUE TITLE
still doesn't work, maybe after 30 min coming ads

### ISSUE THREAD

**Issue by zendiesel** [mrpond/BlockTheSpot#165]

**Comment by zendiesel** [comment]
Installed .bat file, for first 30 min seems ok, then again coming ads.

**Comment by Rednek46** [comment]
submit the log

**Comment by zendiesel** [comment]
Sorry, i'm little bit noob, where i could see that directory/log files  [screenshot](https://imgur.com/a/Rl2D04e)

**Comment by Rednek46** [comment]
Edit the config.ini like I said inside Spotify Folder.
Run spotify till you get ads,
Then in the Spotify folder, you will see blockthespot_log.txt.
Send that here.

**Comment by zendiesel** [comment]
Yeah, tried again, can't see needed files inside [screensh](https://imgur.com/a/NaJ2GFS)

**Comment by Rednek46** [comment]
run spotify till you get ads.

**Comment by Rednek46** [comment]
@zendiesel also, send the debug file. Thats not a Spotify file and I dont remember BTS changing log file name.
If its not something else, share it.

**Comment by mrpond** [comment]
run blockthespot.bat again, I think you use old version of blockthespot

**Comment by Rishab2** [comment]
no problem for me 1 hour no ads

**Comment by Nuzair46** [comment]
Closing as this is highly likely a false positive.

**Comment by zendiesel** [comment]
well after 3 day still no ads. I'm  manually installed chrome.elf and seems it work fine. thx man!
