### ISSUE TITLE
ad is back

### ISSUE THREAD

**Issue by bakinazik** [mrpond/BlockTheSpot#169]
While the music was playing, the ad started popping up. the developer team is not dead, right?

**Comment by Nuzair46** [comment]
@bakinazik The bug report template explains how you should submit an issue. Kindly follow the template.

**Comment by Rishab2** [comment]
no ads, but songs keeps stopping and then saying "says can't play a current song" and then it plays again. Exit the app or change song it plays for like 5 sec then stops and says "can't play current song"

**Comment by Enevevet** [comment]
> > no ads, but songs keeps stopping and then saying "says can't play a current song" and then it plays again. Exit the app or change song it plays for like 5 sec then stops and says "can't play current song"
> 
> check #115 .

Same here.
If I set music quality on "Automatic", it stops after 5 seconds. If I set music quality on "Low" it stops after 10 seconds.
Anyway after 30 seconds of silent, the song resumes playing; although the problem occurs for every song so it's really annoying.

I really don't think it is a connection problem (mine is quite fast, widely enough to load a song almost instantly).
On [spotify community forums](https://community.spotify.com/t5/Desktop-Windows/Music-stop-playing-after-5-seconds/m-p/4746962), people say that it can happen if the host file is blocking some spotify addresses. Doesn't BTS work in the same way?

**Comment by Nuzair46** [comment]
> > > no ads, but songs keeps stopping and then saying "says can't play a current song" and then it plays again. Exit the app or change song it plays for like 5 sec then stops and says "can't play current song"
> > 
> > 
> > check #115 .
> 
> Same here.
> If I set music quality on "Automatic", it stops after 5 seconds. If I set music quality on "Low" it stops after 10 seconds.
> Anyway after 30 seconds of silent, the song resumes playing; although the problem occurs for every song so it's really annoying.
> 
> I really don't think it is a connection problem (mine is quite fast, widely enough to load a song almost instantly).
> On [spotify community forums](https://community.spotify.com/t5/Desktop-Windows/Music-stop-playing-after-5-seconds/m-p/4746962), people say that it can happen if the host file is blocking some spotify addresses. Doesn't BTS work in the same way?

No. BTS doesn't edit host files. But this issue is not seen by any other users So, make sure your host file has not been edited by you previously. Also test if the songs are playing without using BTS.

**Comment by tortlay** [comment]
Yes, audio ads is still coming.

**Comment by Kibakus** [comment]
Such an advertisement began to appear.
![image](https://user-images.githubusercontent.com/25794861/121228927-cb8bdf80-c8a6-11eb-8132-d52179b267ce.png)

**Comment by mrpond** [comment]
Yes, I found this issue myself. 
I'll look into it.

**Comment by Daksh777** [comment]
I do not see any ads here, version 1.1.61.583.gad060c66-a

**Comment by tortlay** [comment]
I reapplied the .bat and now so far not see any ads.

**Comment by zakblacki** [comment]
Banner ads appearing on version 1.1.61.583.gad060c66-a

**Comment by maks244** [comment]
I'm also getting video ads on 1.1.61.583.gad060c66-a

**Comment by Enevevet** [comment]
> > > no ads, but songs keeps stopping and then saying "says can't play a current song" and then it plays again. Exit the app or change song it plays for like 5 sec then stops and says "can't play current song"
> > 
> > 
> > check #115 .
> 
> Same here.
> If I set music quality on "Automatic", it stops after 5 seconds. If I set music quality on "Low" it stops after 10 seconds.
> Anyway after 30 seconds of silent, the song resumes playing; although the problem occurs for every song so it's really annoying.
> 
> I really don't think it is a connection problem (mine is quite fast, widely enough to load a song almost instantly).
> On [spotify community forums](https://community.spotify.com/t5/Desktop-Windows/Music-stop-playing-after-5-seconds/m-p/4746962), people say that it can happen if the host file is blocking some spotify addresses. Doesn't BTS work in the same way?

For those who have the same problem, I fixed my issue by reinstalling Spotify.

**Comment by zachjmurphy** [comment]
Not getting any Ads on Spotify Version: 1.1.60.672.g6ad9c215-a

**Comment by RichardLeblanc** [comment]
> 
> 
> Not getting any Ads on Spotify Version: 1.1.61.583.gad060c66-a

Idem, everything works perfectly like previous versions

**Comment by Nuzair46** [comment]
Closing as this issue is stale for more than 2 weeks. Reopen if the issue still persists.
