### ISSUE TITLE
chrome_elf version 35 isn't working for me with the latest Spotify version.

### ISSUE THREAD

**Issue by idgas01** [mrpond/BlockTheSpot#172]
I have two laptops.  A newer Acer Nitro 5 gaming laptop.  And an older, non-gaming Acer Aspire 5 laptop.

Neither of them is using BlockTheSpot or bat files.

I've just been replacing the chrome_elf.dll and config files at C:\Users\Brian\AppData\Roaming\Spotify.

On my newer Acer Nitro 5 gaming laptop, I have the hosts file edited:

##    SPOTIFY - NO UPDATE - 

0.0.0.0 upgrade.spotify.com
0.0.0.0 www.spotify-desktop.com
0.0.0.0 sto3-accesspoint-a88.sto3.spotify.net
0.0.0.0 upgrade.scdn.co
0.0.0.0 beta.spotify.map.fastly.net
0.0.0.0 prod.spotify.map.fastlylb.net

##    SPOTIFY - NO UPDATE - END

But I read somewhere that it isn't necessary to do this.  I'm thinking that whoever said that it isn't necessary to update hosts file is wrong and spreading false information.

So anyway, on this newer Acer Nitro 5 gaming laptop, I am using chrome_elf version 26 (FIX) with Spotify version 1.1.51.382.g8e3b11ed-a and it seems to be working well.  No ads.

On my older Acer Aspire 5 laptop, I didn't edit the hosts file.  Because as I said, I read numerous posts by know-it-all experts on Reddit that it was no longer necessary.

And I guess because of that, my Spotify was updated to a more recent version, but not the very latest.  And my chrome_elf version 26 (FIX) no longer worked.  I used chrome_elf version 35 instead, and it still didn't work.  So I updated Spotify to the newest and latest veresion - 1.1.60.672.g6ad9c215-a.  crhome_elf version 35 didn't work with it.

So yeah, not sure what to do.  I will probably leave my newer Acer Nitro 5 alone.  But ideally, I would like to use chrome_elf 35 with it's corresponding Spotify version so I have a Spotify that is more up to date than the old 1.1.51.382.g8e3b11ed-a that works with chrome_elf version 26 (FIX).  Or maybe get a chrome_elf 36 that works with the version I have now - 1.1.60.672.g6ad9c215-a.

**Comment by idgas01** [comment]
I found a Spotify page that lets me download older version of Spotify.  I'm going to try that.

**Comment by idgas01** [comment]
I wish that the "releases" for chrome_elf would tell me which Spotify version they are compatible with.  The only thing that I have to go on is "dates", but dates aren't that helpful.  There was a Spotify version released on April 20, and there was a chrome_elf "release" released the same day.  But the chrome_elf release was probably for an older version of Spotify and it took a month or so for it be released.  In other words, it is a guessing game that takes a lot of trial and error.

**Comment by Nuzair46** [comment]
1. This repository does not recommend editing host files to block updates as BlockTheSpot is aimed to support the latest version of Spotify.
        This repo is will work even if there is no host file edit (to block ads).
2. Editing host files will stop updates but also will block song playback. It's been noted many times.
3. BlockTheSpot is tested working with the latest Spotify version. Check the Readme title.
4. This is likely to be an issue in your end, possibly because the patch you have is old, So I recommend you to try the BlockTheSpot.bat .

**Comment by idgas01** [comment]
Nuzair, you post a lot and you are one of the administrators of this GitHub, but I don't think that you know what you are talking about.  It even says on the main page of this GitHub that you DON'T NEED TO USE BLOCKTHESPOT.BAT.  That we can just replace the chrome_elf and config manually.  That's what I've been doing for a super long time and it's always worked.  Yeah, the easy to go reply is "it's on your end" but yet you have no advice on what exactly on my end is wrong.

**Comment by idgas01** [comment]
Anyway, I'm stuck.  I tried downloading an older version of Spotify and it still shows 1.1.60 as the version instead of the 1.1.57 (or older) version that I wanted.

**Comment by Nuzair46** [comment]
I know why that you dont have to use the bat file. You can do it manually. But to make it clear that the issue is not related to you doing a wrong step, using the bat file is recommended. 
If you are sure you applied the patch correctly, please turn on the logs and upload the log here.

**Comment by idgas01** [comment]
So as mentioned several posts ago, I attempted to install an older version of Spotify to use with chrome_elf (35).  The Spotify version I tried to download was 1.1.57.  But it kept showing 1.1.60.  Turns out that the uploader uploaded the wrong installer for that version, and that's why it kept showing 1.1.60.  So like if I installed a different version like 1.1.56 or 1.1.55, it would install the desired older version.  I attempted some older versions of chrome_elf and Spotify, and I ran into the same problem in all of them.  Just like I said in my original post AT THE BOTTOM OF THE PLAYLIST THERE IS AN AD BANNER SECTION that I wanted to get rid of.  So I finally gave up and installed 1.1.51 (like on my other laptop) and the corresponding chrome_elf 26 (FIX) and it worked perfectly.  No more banner ad section on the bottom of my playlist.  It's funny, because there is a whole issue dedicated to this problem that I complained (BANNER AD SECTION AT THE BOTTOM OF THE PLAYLIST), an issue which Nuzair46 made numerous posts on (but yet he couldn't clue me in on that it is a KNOWN PROBLEM, with some tedious WORKAROUNDS)   https://github.com/mrpond/BlockTheSpot/issues/150#issuecomment-826379721  Thanks for wasting my time.  FYI, Just because you post a lot doesn't mean you know a lot.  And just because you post INFORMATION about OTHER LOOSELY RELATED OR UNRELATED THINGS does not make you an EXPERT on the SPECIFIC THING THAT THE POSTER NEEDED HELP ON.  I see this kind of behavior all of the time by wanna be moderators and people wanting huge post karma on Reddit.  You ask a specific question about a game, and the person replying will post all sorts of information about this and that, all very impressive, all very recognition worthy, but none of it actually answers the specific question and the person is just talking out of their arse.

**Comment by Nuzair46** [comment]
The ad block in the latest version of spotify is a known issue. If your read the README, There is a section called Known Issues that says this. I'm sorry that you're not able to read the README.

**Comment by SwagsRGB** [comment]
> 
> 
> So as mentioned several posts ago, I attempted to install an older version of Spotify to use with chrome_elf (35). The Spotify version I tried to download was 1.1.57. But it kept showing 1.1.60. Turns out that the uploader uploaded the wrong installer for that version, and that's why it kept showing 1.1.60. So like if I installed a different version like 1.1.56 or 1.1.55, it would install the desired older version. I attempted some older versions of chrome_elf and Spotify, and I ran into the same problem in all of them. Just like I said in my original post AT THE BOTTOM OF THE PLAYLIST THERE IS AN AD BANNER SECTION that I wanted to get rid of. So I finally gave up and installed 1.1.51 (like on my other laptop) and the corresponding chrome_elf 26 (FIX) and it worked perfectly. No more banner ad section on the bottom of my playlist. It's funny, because there is a whole issue dedicated to this problem that I complained about (BANNER AD SECTION AT THE BOTTOM OF THE PLAYLIST), an issue which Nuzair46 made numerous posts on (but yet he couldn't clue me in on that it is a KNOWN PROBLEM, with some tedious WORKAROUNDS) [#150 (comment)](https://github.com/mrpond/BlockTheSpot/issues/150#issuecomment-826379721) Thanks for wasting my time. FYI, Just because you post a lot doesn't mean you know a lot. And just because you post INFORMATION about OTHER LOOSELY RELATED OR UNRELATED THINGS does not make you an EXPERT on the SPECIFIC THING THAT THE POSTER NEEDS HELP ON. I see this kind of behavior all of the time by wanna be moderators and people wanting huge post karma on Reddit. You ask a specific question about a game, and the person replying will post all sorts of information about this and that, all very impressive, all very recognition worthy, but none of it actually answers the specific question and the person is just talking out of their arse.

Well atleast Nuzair's contributions look more than you so ofc he knows more than you. Just go back to the basement u ive in without shit talking and read the readme next time

**Comment by idgas01** [comment]
What contribution?  Acting like a know it all authority figure while providing no help whatsoever isn't a contribution.  At least me attempting to get help caused me to figure out stuff on my own, which is that the last six or so chrome_elf's do not work (might work if you use BlocktheSpot or Spicetify) because it leaves a huge ad banner space at the bottom of the playlist that takes up a ton of space.  Anyway, I'm tired of (I cant use that language here) trolling closed, dead posts that no one has posted in for two months.  So I am just going to add this low IQ swag troll to my ignore list and be done with it without telling him what I really want to tell him.

**Comment by Daksh777** [comment]
If you're really bothered by the ad placeholder, you can just run the .bat file in https://github.com/daksh777/spotifynopremium which is also mentioned in the same issue (https://github.com/mrpond/BlockTheSpot/issues/150#issuecomment-842831580).
It is much much easier to install and it's not difficult at all.
Yes, it is a known bug and there are currently only workarounds for it and people like me and @Nuzair46 are trying to help the best we can. You cannot expect professional, corporate level help from an open-source project. Everyone contributes when they have time and when they want to.
