### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by BradenWentworth** [mrpond/BlockTheSpot#174]
**Describe the bug**
I just did a clean reformat of my OS drive and then run BlockTheSpot.bat which was successful
Spotify opens and asks me to login like normal then after I login the app goes mostly black and is completely unusable except for the buttons the the top of the window.
I also cannot move the window by clicking and dragging at all.

Here is a screenshot - https://i.imgur.com/BxgJEr7.png

**Important:**
 - OS: Windows 10 Pro (fresh install)
 - Confirm that you currently using latest version of
  1. [latest spotify](https://www.spotify.com) 
  2. [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
  3. Blockthespot are not working with Spotify from Microsoft Store or alpha version of Spotify.

Option 2.
I did not have Spotify previously installed, I only ran the bat file from this repo.

**Additional context**
If ad blocking is not working, please include a debug log by
 1. edit config.ini and set Log = 1 
 2. after ads song play close Spotify
 3. zip the blockthespot_log.txt

I edited the config and ran the exe for a while and then exited, but it doesn't seem to have generated a log file.

**Comment by Davoleo** [comment]
Try running `uninstall.bat` and then updating the install batch script (BlockTheSpot.bat) and running it again
This problem was most probably caused if you previously tried to restore the old UI through the old install script

**Comment by BradenWentworth** [comment]
> Try running `uninstall.bat` and then updating the install batch script (BlockTheSpot.bat) and running it again
> This problem was most probably caused if you previously tried to restore the old UI through the old install script

That did not help.
As I said, this is a fresh install, there is no updating to do.

**Comment by Nuzair46** [comment]
> > Try running `uninstall.bat` and then updating the install batch script (BlockTheSpot.bat) and running it again
> > This problem was most probably caused if you previously tried to restore the old UI through the old install script
> 
> That did not help.
> As I said, this is a fresh install, there is no updating to do.

hey. can you do the patch manually if you used the BlocktheSpot.bat?
1. Browse to your Spotify installation folder `%APPDATA%\Spotify`
2. Download chrome_elf.zip from [releases](https://github.com/mrpond/BlockTheSpot/releases)
3. Unzip and replace `chrome_elf.dll` and `config.ini`

**Comment by BradenWentworth** [comment]
It had no effect. Though I do see the log file has now shown itself.

```
GetModuleInformation OK!
main process#1 - patch failed!
main process#2 - patch success!
Mhook_SetHook - getaddrinfo success!
```

**Comment by Nuzair46** [comment]
> It had no effect. Though I do see the log file has now shown itself.
> 
> ```
> GetModuleInformation OK!
> main process#1 - patch failed!
> main process#2 - patch success!
> Mhook_SetHook - getaddrinfo success!
> ```

You are not using any other patch that removes "upgrade" button or "revert to old UI" right?

**Comment by BradenWentworth** [comment]
No, this is a fresh OS with only the newest version of the bat file, I haven't done anything else.

**Comment by Nuzair46** [comment]
> No, this is a fresh OS with only the newest version of the bat file, I haven't done anything else.

can you uninstall spotify completely, download the latest from Spotfy website, then apply the patch manually. Also, before applying the patch, make sure it doesnt give any issue without any patches.

**Comment by BradenWentworth** [comment]
It works now, thank you.
Is installing the official client first supposed to be part of the normal install steps, if so those instructions should be updated.

**Comment by Nuzair46** [comment]
> It works now, thank you.
> Is installing the official client first supposed to be part of the normal install steps, if so those instructions should be updated.

Installing the official client first is step 0 for any patch like this. 
by the way, running the bat file will normally ask you to install Spotify if you haven't installed it before.
