### ISSUE TITLE
Missing chrome_elf.dll

### ISSUE THREAD

**Issue by lolurbadkid** [mrpond/BlockTheSpot#176]
I'm using Windows 8.1 and it says chrome_elf.dll is missing when I downloaded it.. I need help with this.

**Comment by Nuzair46** [comment]
Try manually installing the patch.

**Comment by lolurbadkid** [comment]
Can you tell me how?

**Comment by not-lucky** [comment]
1. Browse to your Spotify installation folder %APPDATA%\Spotify
2. Download chrome_elf.zip from releases
3. Unzip and replace chrome_elf.dll and config.ini

**Comment by mrpond** [comment]
Antivirus delete it. update antivirus signature database.
