### ISSUE TITLE
Does not remove the ad from the main screen

### ISSUE THREAD

**Issue by JaderMejia** [mrpond/BlockTheSpot#177]
It does not remove the ad from the main screen, any solution? I mean, it allows me to skip the songs but it does not remove the banner
![image](https://user-images.githubusercontent.com/86989549/124524021-fcd0d000-ddbe-11eb-96b0-ecc34a9e8a0b.png)

**Comment by JaderMejia** [comment]
I withdraw what I said, they do not remove the ads, what solution can they give me?

**Comment by Nuzair46** [comment]
Make sure you are using the latest Spotify and download the [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and run it.

**Comment by Nuzair46** [comment]
Reopen if issue persists. Closing for being stale.
