### ISSUE TITLE
bash file not working

### ISSUE THREAD

**Issue by weckd** [mrpond/BlockTheSpot#180]
**Describe the bug**
Running the bash file gives error 
```
'findstr' is not recognized as an internal or external command,
operable program or batch file.
'PowerShell.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
```
Running with admin: 
```
'PowerShell.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
```

**Important:**

 - OS: Win 10
 - Confirm that you currently using latest version of
  1. [latest spotify](https://www.spotify.com) : Yes
  2. [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) from github. : bash file not working
  3. Blockthespot are not working with Spotify from Microsoft Store or alpha version of Spotify. : Not windows store version

**Comment by xcooI** [comment]
Right click on the bash file while you pressing hte left shift button at the same time and run it as admin. Why is it giving powershell error? You dont have cmd?

**Comment by weckd** [comment]
I have both powershell  and cmd, running as admin gives the same error

**Comment by weckd** [comment]
Something messed the environment variables, fixed it.
For anyone else facing this problem do the following:
https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

**Comment by Nuzair46** [comment]
@weckd Sorry couldn't reach you in time. good to see that you figured it out.

**Comment by weckd** [comment]
np 😊

**Comment by abdhan** [comment]
@weckd I had the same error. Thanks for the fix.
