### ISSUE TITLE
Ads not being blocked.

### ISSUE THREAD

**Issue by poeticua** [mrpond/BlockTheSpot#181]
Since yesterday or so, ads are no longer being blocked for me - both banner ads and ads after playing songs. I haven't updated anything, and just guessing by this Reddit post, I'm not the only one? 

https://www.reddit.com/r/Piracy/comments/ojmzqj/blockthespot_not_working_anymore/

I've been using BTS for years without a single issue until now, and I haven't deviated from the installation instructions in any manner whatsoever.

**Comment by Nuzair46** [comment]
Can you provide your Spotify version?
Just to be on the same page, make sure the repo you are using is [this](https://github.com/mrpond/BlockTheSpot).

**Comment by mournblank** [comment]
Happened to me today. Ads are not blocked anymore. I noticed it because suddenly my pc prompted Windows Defender Firewall to include network setting for inbound Public and Private. 

I am using master131's blockthespot.
Spotify version: 1.1.4.197.g92d52c4f-13

**Comment by Nuzair46** [comment]
@mournblank Master131's repo is deprecated and no more supported.
Update Spotify to your latest version and then use the BlockTheSpot.bat from this repo. 

Closing since this issue is related to a deprecated version not related to this fork. Reopen if it persists.
