### ISSUE TITLE
Trojan virus

### ISSUE THREAD

**Issue by jgsource** [mrpond/BlockTheSpot#182]
When I ran the bat file, it created this powershell file called ps.ps1. Kapersky immediately caught it and began disinfection. I thought it was a false positive till it started making my browser extensions crash, and even my whole desktop crash to a black screen. I do not think any false positive is capable of such

**Comment by chadmongodong** [comment]
yo is this fr? i checked issues right before you posted it and there was nothing ab a virus but as soon as i downloaded and refreshed you posted lmfao. my antivirus hasn't seen anything yet but i'm running a full scan rn

**Comment by jgsource** [comment]
Yea, I am surprised there was no issue related to this trojan at all. Has it been updated recently. The trojan was literally causing all sorts of memory issues to pop up. Kapersky saved my ass

**Comment by chadmongodong** [comment]
do you remember where your ps.ps1 file saved to? just looked it up on reddit and there were some posts ab it being a false positive for a trojan. i just ran it through virustotal and it said it was perfectly fine

**Comment by jgsource** [comment]
When I ran the bat file, it created a powershell file called ps.ps1 in my downloads folder, same location in which I downloaded the bat file

**Comment by jgsource** [comment]
My question is, doesn't a false positive trojan do basically nothing? This trojan was breaking my pc right before my eyes. Applications would not work, etc.

**Comment by chadmongodong** [comment]
huh that's weird, that didn't happen to me although i stopped it from running midway. the bat file is opensourced and it doesn't look like that should have happened, so maybe scan some of your other recently downloaded files? thanks for the heads-up tho you saved me fr

**Comment by jgsource** [comment]
Yea I did not expect that to happen, let alone a file from github that has already been downloaded numerous times. It cannot come from my older files because the only recent files I had was blockthespot.bat and after running the file, ps.ps1. When I looked at the report, it showed Trojan.win32.bazon which others are saying is a false positive. I am just so confused why my pc started acting up..

**Comment by mournblank** [comment]
Looks clean so far on my Norton360 🤔

**Comment by Nuzair46** [comment]
There is no trojan or any virus coded into the scripts in this repo. You are on your own if you download the scripts from somewhere else, but if it was downloaded from here, then its completely safe and the Antivirus was giving a false positive.
