### ISSUE TITLE
No longer working after recent Windows security patch

### ISSUE THREAD

**Issue by Undercover-Dev** [mrpond/BlockTheSpot#183]
**Describe the bug**
After having updated to the latest edition of Windows to get the latest Windows security patch, BlockTheSpot stopped functioning.

**Information regarding the specific update**
https://support.microsoft.com/en-us/topic/july-13-2021-kb5004237-os-builds-19041-1110-19042-1110-and-19043-1110-ae798d3c-3de3-4c1f-b9d9-7391b71da889

![image](https://user-images.githubusercontent.com/87505745/125875193-7f2f6c7d-bb95-4403-b333-7d65d63f78db.png)

**Important:**

 - OS:  Windows 10
 - Confirm that you currently using the latest version of
  1. Using the downgraded Spotify
  2. Using mrpond's latest BlockTheSpot

**Additional context**
You can temporarily uninstall the update and then all is well however this is not a possible long term solution.

**Comment by 1Phase1** [comment]
Can confirm, the latest security update broke this. Uninstalling the update makes it work again

**Comment by mrpond** [comment]
I can't reproduce it here.
![image](https://user-images.githubusercontent.com/18654771/125972804-41844e2f-271f-4659-9cf1-e32a38cd98cc.png)
Edition	Windows 10 Pro
Version	21H1
Installed on	‎*
OS build	19043.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by judebox11** [comment]
Yep. no longer working after the update

**Comment by AggelosM** [comment]
I got the update and it's working for me but the ad banners are being displayed.

**Comment by Joreon** [comment]
Also no longer working for the new Windows 11 update.

**Comment by Ezty** [comment]
Sadly it no longer working

**Comment by Mento-s** [comment]
No longer working :c

**Comment by Hansukie** [comment]
This happened to me too. I just had to uninstall Spotify and reinstall an older version. I used the August 2020 Version of Spotify. Unsure if there's a better version to use that doesn't have the horrid new UI. 

Run BlockTheSpot again and no more ads should show up. 

Also, I don't know if there's a way to prevent the blue dot on the profile name to indicate a Spotify update can be blocked? It shows up after a while even though the update folders permissions are blocked in appdata.

**Comment by dromzeh** [comment]
can reproduce this:

- Running 21H1, 19043.1110
- Spotify 1.1.4.197.g92d52c4f

**Comment by Undercover-Dev** [comment]
**Misconceptions:**
- I think a lot of us come from the 'old' BlockTheSpot in which you use a downgraded version of Spotify (master131's edition)
- However, that version is now obsolete due to the recent Windows update and is discontinued.

**How to fix the issue permanently:**
- Uninstall whatever version of Spotify you have currently
- Install the latest Spotify version from the Spotify website
- Run BlockTheSpot.Bat

**Future improvements that should be made**:
- Specify within the README.md file to utilise the latest version of Spotify before applying BlockTheSpot.bat. 
- Acknowledge the existence of master131's edition and the issues/extra steps when moving from that edition to mrpond's edition.

**Comment by kbirger** [comment]
Thanks for clearing that up. I'm actually curious what about this update is causing a problem. It seems to mostly be concerned with removing Flash (RIP)
