### ISSUE TITLE
Keyboard commands not working

### ISSUE THREAD

**Issue by AndreasKaratzas** [mrpond/BlockTheSpot#184]
**Describe the bug**
None of my keyboard shortcuts for music work while spotify is minimized. For example, I cannot press the pause/unpause shortcut to pause/unpause the music. However, as soon as I open it as a main window, all shortcuts work. It's obviously not a keyboard fault. I tried to find any related settings of the app. I restarted several times my PC. Nothing worked.

**Important:**

 - OS: Windows 10
 - Confirm that you currently using latest version of
  1. My Spotify version: 1.1.63.568.gda8cb5ac-a
  2. Blockthespot version: 2021.7.03.36 
  3. Spotify Desktop version

**Additional context**
I am not a premium user.

**Comment by Nuzair46** [comment]
This is not related to BlockTheSpot. Try Spotify Support.
