### ISSUE TITLE
Unable to load recent played songs list

### ISSUE THREAD

**Issue by RichardLeblanc** [mrpond/BlockTheSpot#19]
It is normal that the application is unable to load recent played songs list? Can't remember the chrome_elf.dll version. Spotify is 1.1.19.480
everything else works perfectly

![Immagine](https://user-images.githubusercontent.com/47771443/72709307-f87e0c00-3b64-11ea-89ad-65bcfda74f09.jpg)

**Comment by mrpond** [comment]
Hi,
please update spotify to latest version **1.1.24.91**
and **BTS(chrome_elf) to 0.43** https://github.com/mrpond/BlockTheSpot/blob/master/chrome_elf.zip

if the problem still exist, turn on the log in config.ini

**Comment by RichardLeblanc** [comment]
Updated to **1.1.24.91** and **chrome_elf** to **0.43**.
Problem solved, works flawlessly, thank you
