### ISSUE TITLE
Improvement: Block Spotify auto-updates

### ISSUE THREAD

**Issue by red9350** [mrpond/BlockTheSpot#195]
Here's the code used in the old repo (master131/BlockTheSpot) that disables Spotify auto-updates.
Launch every command in succession in a CMD window:
```
icacls "%localappdata%\Spotify\Update" /reset /T > NUL 2>&1
del /s /q "%localappdata%\Spotify\Update" > NUL 2>&1
mkdir "%localappdata%\Spotify\Update" > NUL 2>&1
icacls "%localappdata%\Spotify\Update" /deny "%username%":W > NUL 2>&1 
```

@mrpond please add it to your installation script

**Comment by amd64fox** [comment]
Outdated version, it works, but still allows you to download the client to the `Temp` folder.
Here is the powershell version, based on example Spicetify.

```powershell
$ch = Read-Host -Prompt "Want to block updates ? (Y/N)"
if ($ch -eq 'y'){
If(Test-Path $env:LOCALAPPDATA\Spotify) {} 
Else {
New-Item -Path $env:LOCALAPPDATA -Name "Spotify" -ItemType "directory"
}
If(Test-Path $env:LOCALAPPDATA\Spotify\Update) {
Remove-item $env:LOCALAPPDATA\Spotify\Update -Recurse -Force
} 
Else {}
New-Item -Path $env:LOCALAPPDATA\Spotify\ -Name "Update" -ItemType "file" -Value "STOPIT"
$file = Get-ItemProperty -Path $env:LOCALAPPDATA\Spotify\Update
$file.Attributes = "ReadOnly", "System"
If(Test-Path $env:APPDATA\Spotify\SpotifyMigrator.bak) {
Remove-item $env:APPDATA\Spotify\SpotifyMigrator.bak -Recurse -Force
} 
Else {}
Rename-Item -path $env:APPDATA\Spotify\SpotifyMigrator.exe -NewName $env:APPDATA\Spotify\SpotifyMigrator.bak
} else{}
```

**Comment by Nuzair46** [comment]
This repo doesn't promote blocking updates as it works with latest Spotify version.

Support for older Spotify is also removed by this repo from time to time. So If you keep non updated in an older version, then you are just gonna run into issues.

**Comment by amd64fox** [comment]
@red9350 
If interested, then I implemented it [here](https://github.com/amd64fox/SpotX).
