### ISSUE TITLE
Request: Auto run when updated

### ISSUE THREAD

**Issue by jimmysofat6864** [mrpond/BlockTheSpot#199]
## Feature Request 
I would appreciate if it came with a feature so blockthespot automatically runs when there is an update or it runs on startup because I would like to use it without repatching every single time.

**Comment by SonGorLick** [comment]
That sounds like a good idea, though idk if the person who dose this can do that or not

**Comment by Daksh777** [comment]
That won't be a good idea, we will have to run a script constantly to check for any updates, which itself would be complicated.
You can instead watch this repository for releases and run the script.

**Comment by Nuzair46** [comment]
This would mean that a process will have to verify if Spotify is updated and this is out of scope for this repository. 
Doing a background process will be a bad idea and I think you can achieve the same by using task scheduler. Google on how to schedule stuff with task scheduler in windows. It is a built in tool.
