### ISSUE TITLE
ads are back

### ISSUE THREAD

**Issue by Maxcension** [mrpond/BlockTheSpot#2]
**Describe the bug**

All the ads are back. :(

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Spotify Version: [1.1.15.448.g00fba0e3 (but they are back since 1.1.14)]

**Additional context**
ListDLLs: https://pastebin.com/EY1cP1ej

anyway, thank you for maintaining BlockTheSpot!

**Comment by mrpond** [comment]
Hi, I'm download and reinstall the spotify again.
the latest version I got are "1.1.14.475.g566c8beb".
Seem you region had got the newer version first(I'm in Asia). 
by the ways, this is my current-development, try it and report me it working or not.

[chrome_elf.zip](https://github.com/mrpond/BlockTheSpot/files/3610084/chrome_elf.zip)
