### ISSUE TITLE
Fullscreen mode (icon on the bottom right corner)

### ISSUE THREAD

**Issue by Sterben113** [mrpond/BlockTheSpot#200]
When using spicetify there was icon once in bottom for fullscreen playback, can it be added without using spicetify? Submitting first time, want to tag this as enhancement. Read every known issue but found nothing.

**Comment by Nuzair46** [comment]
It is a premium feature now, So it can't be unlocked.

**Comment by Sterben113** [comment]
actually they removed the feature as a whole I guess, it was brought back to free version for some time, will work if we rollback to old version probably.

**Comment by Nuzair46** [comment]
No its still available in the premium client.
