### ISSUE TITLE
error while running bts

### ISSUE THREAD

**Issue by 5447** [mrpond/BlockTheSpot#201]
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

[
![image](https://user-images.githubusercontent.com/49858492/129036500-3be323fa-cde6-46ed-9018-20e8026f7adf.png)
](url)

**Comment by Nuzair46** [comment]
Check [this](https://github.com/mrpond/BlockTheSpot/issues/42#issuecomment-615973812)
