### ISSUE TITLE
Ads no longer blocked on version 1.66

### ISSUE THREAD

**Issue by jakey1995abc** [mrpond/BlockTheSpot#203]
BlockTheSpot is no longer blocking ads as of Spotify version 1.1.66.578.gc54d0f69-a

**Comment by Nuzair46** [comment]
@jakey1995abc can you upload the logs.

**Comment by alixti** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/67288109/129659309-93ebafe5-b49d-41a9-ab90-89a55f4b8067.png)

**Comment by Daksh777** [comment]
I'm getting ads on that version too, I'll upload the logs when I encounter an ad again.

**Comment by mrpond** [comment]
wait few days, my region didn't receive this version update yet.

**Comment by amd64fox** [comment]
> wait few days, my region didn't receive this version update yet.

https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.66.578.gc54d0f69-15.exe

I have everything clean after one day of use. And what type of advertising appears ?

**Comment by mrpond** [comment]
> > wait few days, my region didn't receive this version update yet.
> 
> https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.66.578.gc54d0f69-15.exe
> 
> I have everything clean after one day of use. And what type of advertising appears ?

Thx, fixed. check latest release.
