### ISSUE TITLE
VIRUS TROJAN DETECTED BY WINDOWS DEFENDER! 👀

### ISSUE THREAD

**Issue by KTM888** [mrpond/BlockTheSpot#204]
![image](https://user-images.githubusercontent.com/66633291/129795662-a5c33637-d5c5-453f-aa09-068d29545185.png)

**Comment by amd64fox** [comment]
False positive, try updating your Windows Defender
https://www.virustotal.com/gui/file/f22e894695e21c223a63b6212af5e86b6160eba3b21416cb5b1eebdd47097257/detection

**Comment by mrpond** [comment]
Hi you can recompile and audit the source code. it didn't contain anything malicious there.
