### ISSUE TITLE
Spotify screen size error on Window 11

### ISSUE THREAD

**Issue by NguyenASang** [mrpond/BlockTheSpot#206]
![Screenshot (108)](https://user-images.githubusercontent.com/87893636/130196107-e548ae25-b9f5-4f0c-a4d3-fa93202dc3b3.png)
When I use Spotify on windows 10 there is no any error with the screen but when I upgrade to Window 11, Spotify can't go full screen on my computer screen. Can anyone help me fix that error ? That is too annoying 😢😥😭

**Comment by Davoleo** [comment]
I'm almost 100% sure that is not related to / caused by BlockTheSpot

**Comment by NguyenASang** [comment]
> I'm almost 100% sure that is not related to / caused by BlockTheSpot
> (try contacting spotify support)
Okay but I searched on google no one has the same error as me :(

**Comment by NguyenASang** [comment]
Okay but I searched on google no one has the same error as me. I tried contacting Spotify support :(

**Comment by Nuzair46** [comment]
This issue is caused by Windows 11.

**Comment by RealDrPuc** [comment]
> 
> 
> Okay but I searched on google no one has the same error as me. I tried contacting Spotify support :(

https://www.reddit.com/r/Windows11/comments/pb9mch/small_line_of_pixels_at_the_bottom_of_spotify/

**Comment by NguyenASang** [comment]
> > Okay but I searched on google no one has the same error as me. I tried contacting Spotify support :(
> 
> https://www.reddit.com/r/Windows11/comments/pb9mch/small_line_of_pixels_at_the_bottom_of_spotify/

Thanks bro :D Have a nice day
