### ISSUE TITLE
Playing greyed out songs

### ISSUE THREAD

**Issue by Hexiro** [mrpond/BlockTheSpot#216]
This isn't exactly relevant to the project as whole, but do you know if it's possible to play greyed out songs? The fact that they're marked as unavailable, and not just completely removed from the servers makes me think that maybe the song files still exist too.

If so, this would be a pretty cool feature.

example: (bottom is greyed out)
![image](https://user-images.githubusercontent.com/42787085/132076993-1f71bd94-fa86-4f12-960d-df0b5acd13bb.png)

**Comment by Nuzair46** [comment]
No its not possible as this is related to you account location.
