### ISSUE TITLE
Unable to use Spicetify extensions with BlockTheSpot

### ISSUE THREAD

**Issue by ZeroDiscord** [mrpond/BlockTheSpot#217]
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [] You enabled logging by editing config.ini `set log = 1`.

### Unable to access the webnowplaying script with spicetify 
Upon installing BlockTheSpot it works well as intended although my spotify is edited via [spicetify](https://github.com/khanhas/spicetify-cli)  which has a webnowplaying.js extension which allows Rainmeter to recieve audio from spotify for its skins, this in particular stopped working for some reason.

OS: Windows 10

**Comment by Nuzair46** [comment]
This doesn't seem to be an issue with BlockTheSpot. Are you sure BlockTheSpot causes this issue?

**Comment by ZeroDiscord** [comment]
I'm sure since it was working fine before that. Could you try to reproduce?

**Comment by Nuzair46** [comment]
No I can't since I don't use Spicetify.
Also, this seems to be an issue on Spicetify or an issue related to the particular theme. Please try for support in their respective repo. Until a concrete detail on this that BlockTheSpot is causing this issue, this issue will be closed.
