### ISSUE TITLE
cannot launch spotify after installing the .bat file—Win11 Preview Build 22000.184

### ISSUE THREAD

**Issue by sppon** [mrpond/BlockTheSpot#218]
after noticing that spotify started playing ads again (i presume after an automatic update), i launched the .bat while spotify was open. it closed spotify, and i turned on ad placeholder and upgrade button remover. 

spotify did not relaunch after completing the installation, and after deleting all spotify program files and reinstalling it still doesn't open. it had worked before. 

https://user-images.githubusercontent.com/69046095/132992610-fd070a45-8daf-4436-8654-d5ac0c639ad4.mp4

during this recording, i can assure you i checked task manager for any existing spotify reminants—there wasnt any.

**Comment by Nuzair46** [comment]
Please follow the bug report template. One of the checkbox will fix your issue.
