### ISSUE TITLE
Windows defender and other AV going crazy

### ISSUE THREAD

**Issue by shybruh** [mrpond/BlockTheSpot#221]
first of all, here is the vt link : https://www.virustotal.com/gui/file/bdb2521a47cadad9f45844fa9f494ed81cd111b68a3aa5f319c69b1c3bc7a7bc/detection
https://www.hybrid-analysis.com/sample/bdb2521a47cadad9f45844fa9f494ed81cd111b68a3aa5f319c69b1c3bc7a7bc

now I know its normal for false positives to be there, like 1 or 2, but its 53/68. I don't know if to be worried, or not.

**Comment by Nuzair46** [comment]
False positive.

**Comment by Nuzair46** [comment]
This is the current virus total result https://www.virustotal.com/gui/file/10d83cda0ee91661a5038de1a8515fcc8c89c6bbd629b761e7f9d88397ef4ace/details

And it is safe. You may have an older version or maybe downloaded the file from an unsafe repo.
