### ISSUE TITLE
HomePage Not Working

### ISSUE THREAD

**Issue by sawnn** [mrpond/BlockTheSpot#222]
Hellio, i just installed BlockTheSpot, it is working nice, but the homepage is not working, do you know why ? I am on Windows 10

![image](https://user-images.githubusercontent.com/40355675/133669028-224e85c7-6381-4e90-8def-c5a6a769c764.png)

thanks !

**Comment by serhangursoy** [comment]
It doesn't seem to be related to BlockTheSpot  - [It's down for some users](https://www.androidauthority.com/spotify-not-working-1149414/)
I also uninstalled and tested a fresh installation without BlockTheSpot, it's also not connecting and giving the same error

**Comment by Gabsletobar** [comment]
It's not blockthespot.
it's spotify problem. If you go via web browser it's doing the same thing.

**Comment by sawnn** [comment]
oh okay, thank you
