### ISSUE TITLE
playlist sponsor placement

### ISSUE THREAD

**Issue by chris-kwl** [mrpond/BlockTheSpot#226]
As already mentioned in https://github.com/mrpond/BlockTheSpot/issues/156 and https://github.com/mrpond/BlockTheSpot/issues/223#issuecomment-922267087 there are in some playlists sponsor placements at least for some users/regions.

The ad/placment is part of the class `.sponsor-container` and can be hidden through css with `display: none` and e.g. Spicetify.
Not sure how it can be done with the batch-file, but I think similar to the upgrade-button removal.

E.g.:
![grafik](https://user-images.githubusercontent.com/59339711/133888139-18069c24-c048-44f4-9a71-0eef9f4f40dd.png)

**Comment by amd64fox** [comment]
@chris-kwl 

I tried to do this through js, but I can't check, I didn't have such banners initially.

Test these two versions of [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/7227450/xpui.zip) or [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/7227452/xpui.zip)

You need to check on the latest version of the client `1.1.68.632`




- First, make a backup of your `xpui.spa`
- Download `xpui.zip` and rename it to `xpui.spa`
- then try these 2 options, one at a time, replacing the original `xpiu.spa`

**Comment by chris-kwl** [comment]
Thanks for the fast support.

The first version is working :) the second is not.

**Comment by amd64fox** [comment]
@chris-kwl 
I understood, if it's not difficult for you, test this working version more, there may be bugs, if everything goes well, I will add this method to my repository https://github.com/amd64fox/SpotX

**Comment by chris-kwl** [comment]
Sure because the version seems to block all ads let it active and keep Spicetify disabled for now.
Does the version include something regarding https://github.com/mrpond/BlockTheSpot/issues/223 ? 
Because I also tried to get the ad again to provide information here: https://github.com/Daksh777/SpotifyNoPremium/issues/23

**Comment by amd64fox** [comment]
> Does the version include something regarding #223 ?

No

I found another option in the file `xpui.js`, need to check... [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/7227680/xpui.zip)

If this option also works, it will be preferred.

**Comment by chris-kwl** [comment]
yeah works :)

**Comment by amd64fox** [comment]
@chris-kwl  
Great, test the next few days, if there are no problems, I will add to my repo.

**Comment by bamper45** [comment]
Doesn't work on windows 11

**Comment by amd64fox** [comment]
@bamper45  
What specifically doesn't work? Tell us more...

**Comment by bamper45** [comment]
> 
> 
> @bamper45
> What specifically doesn't work? Tell us more...
 
I do not know how to remove the log, but it writes like this when opening "BlockTheSpot.bat":
 FINDSTR: ═x єfrhЄё yЄъЁ√Є№ E: \ Files \ BlockTheSpot-34 \ BlockTheSpot-34 \ BlockTheSpot.bat
Press any key to continue. ... ...

**Comment by amd64fox** [comment]
@chris-kwl 

Hi, did you notice any bugs in my xpui.spa after a few days?

**Comment by chris-kwl** [comment]
No, I haven't noticed any problems. Is there anything I should pay special attention to?

**Comment by amd64fox** [comment]
I added to the automatic installation who had ads from sponsors in playlists, then please test here
https://github.com/amd64fox/SpotX

**Comment by chris-kwl** [comment]
works 👍 
But only using the Install.bat from the latest release, the install.bat from main brings an 404 error because **i**nstall.ps1 is not capitalized in the download url.

**Comment by amd64fox** [comment]
I fixed it, but this file didn't run anything, but thanks anyway.

**Comment by chris-kwl** [comment]
Since it is already fixed with [amd64fox/SpotX](https://github.com/amd64fox/SpotX) I will close here.
