### ISSUE TITLE
Doesn't work on the latest version of Spotify (1.1.69.612)

### ISSUE THREAD

**Issue by MathewJake365** [mrpond/BlockTheSpot#227]
Spotify Version: 1.1.69.612.gb7409abc

All sorts of ads are back. Only the "UPGRADE" button stays removed.

**Comment by Damnmind** [comment]
can confirm release 2021.8.17.39 not working properly on version
Spotify for Windows
1.1.69.612.gb7409abc
banner and audio ads show up

**Comment by mrpond** [comment]
I didn't got this update yet. :P wait few day before spotify push it into my area

**Comment by carolsinus** [comment]
Yep I can confirm,  I got this new upgrade on 9/30/21. Thanks Mrpond for your work!

Spotify for Windows
1.1.69.612.gb7409abc

**Comment by Lewdcifer** [comment]
is it impossible to block the update?

**Comment by AnonymousHacker1279** [comment]
Can also confirm. The upgrade button is still gone though. But everything else is back.

**Comment by bzzrak** [comment]
> is it impossible to block the update?

You can put the servers where the updates come from into your hosts file.

**Comment by alixti** [comment]
> is it impossible to block the update?

https://community.spotify.com/t5/Desktop-Windows/Stopping-Auto-update/td-p/4785101

**Comment by FrappuccinoCaramel** [comment]
I can also confirm for this issue, after the last update it's broken and all sorts of advertisements are back.

**Comment by gahtv** [comment]
Hey, I'm on 1.1.68.632.g2b11de83, and I found if you disable the option to hide the upgrade button when applying it, ads continue to be blocked, however YMMV.

**Comment by GhostSlayer** [comment]
This might work. It's the latest release: https://github.com/mrpond/BlockTheSpot/releases/tag/2021.8.17.39

**Comment by Pixel3000nerd** [comment]
> 
> 
> This might work. It's the latest release: https://github.com/mrpond/BlockTheSpot/releases/tag/2021.8.17.39

If using the batch file, it always grabs the latest release. Unfortunately, I can confirm the latest release of BlockTheSpot does not work on latest version of Spotify for Windows (1.1.69.612.gb7409abc)

**Comment by amd64fox** [comment]
@mrpond 
https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.69.612.gb7409abc-16.exe

**Comment by TrueMLGPro** [comment]
Can confirm, BlockTheSpot can't patch the new Spotify version
```log
LOG | 01-Oct-2021 10:23:53 - GetModuleInformation OK!
LOG | 01-Oct-2021 10:23:53 - main process - patch failed!
LOG | 01-Oct-2021 10:23:53 - main process 1.1.66.578.gc54d0f69-a - patch failed!
```

**Comment by Parth-Mawai** [comment]
i can also confirm that latest version broke the BlockTheSpot and all ads back

> @mrpond https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.69.612.gb7409abc-16.exe
Not working

**Comment by MathewJake365** [comment]
> @mrpond https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.69.612.gb7409abc-16.exe

How did you get that URL?

**Comment by TrueMLGPro** [comment]
> > Can confirm, BlockTheSpot can't patch the new Spotify version
> > ```
> > LOG | 01-Oct-2021 10:23:53 - GetModuleInformation OK!
> > LOG | 01-Oct-2021 10:23:53 - main process - patch failed!
> > LOG | 01-Oct-2021 10:23:53 - main process 1.1.66.578.gc54d0f69-a - patch failed!
> > ```
> 
> Where can I see the LOG?

Locate `config.ini` in `%APPDATA%\Spotify\` and change `Log = 0;` to `Log = 1;` and save
Each time you open Spotify, log file (blockthespot_log.txt) will appear in this folder

**Comment by amd64fox** [comment]
> How did you get that URL?

https://github.com/amd64fox/LoaderSpot

**Comment by Parth-Mawai** [comment]
> > @mrpond https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.1.69.612.gb7409abc-16.exe
> 
> How did you get that URL?

someone wrote that above my comment

**Comment by grimmyxx** [comment]
i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated

if anyone wants to do that too, i'll send a link to the rar files i made (i don't know if it's allowed so i won't risk it)

**Comment by lukjod** [comment]
> 
> 
> i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated
> 
> if anyone wants to do that too, i'll send a link to the rar file i made (i don't know if it's allowed so i won't risk it)

Please do it, does anyone know the link to host file to block globally on router in eg openwrt? i ve found https://github.com/AlfonsoVergara-github/Host-to-block-ads-for-spotify but it is outdated

**Comment by xerta555** [comment]
> 
> 
> release 2021.8.17.39 not working properly on version Spotify for Windows 1.1.69.612.gb7409abc banner and audio ads show up

I confirm too.

**Comment by MathewJake365** [comment]
> > > Can confirm, BlockTheSpot can't patch the new Spotify version
> > > ```
> > > LOG | 01-Oct-2021 10:23:53 - GetModuleInformation OK!
> > > LOG | 01-Oct-2021 10:23:53 - main process - patch failed!
> > > LOG | 01-Oct-2021 10:23:53 - main process 1.1.66.578.gc54d0f69-a - patch failed!
> > > ```
> > 
> > 
> > Where can I see the LOG?
> 
> Locate `config.ini` in `%APPDATA%\Spotify\` and change `Log = 0` to `Log = 1`, then save it Each time you open Spotify, log file (blockthespot_log.txt) will appear in this folder

That doesn't work either.

**Comment by FrappuccinoCaramel** [comment]
> This might work. It's the latest release: https://github.com/mrpond/BlockTheSpot/releases/tag/2021.8.17.39

That's just stupid to say or recommend, you clearly don't have any insight in what's going on and why we're all here talking.

**Comment by FrappuccinoCaramel** [comment]
> This might work. It's the latest release: https://github.com/mrpond/BlockTheSpot/releases/tag/2021.8.17.39

That's just stupid to say or recommend, @GhostSlayer. You clearly don't have any insight in what's going on and why we're all here talking.

**Comment by dswapnil104** [comment]
> i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated
> 
> if anyone wants to do that too, i'll send a link to the rar file i made (i don't know if it's allowed so i won't risk it)

How are we supposed to blocking the auto updates??

**Comment by Nuzair46** [comment]
The latest version 1.1.69.612.gb7409abc is identified as not supported. Please wait until a new patch is released. You can watch this repo by clicking on the top right button if you want to be notified on the latest release. Please do not submit any more issues as its already tracked.

**Comment by GhostSlayer** [comment]
> > This might work. It's the latest release: https://github.com/mrpond/BlockTheSpot/releases/tag/2021.8.17.39
> 
> That's just stupid to say or recommend, @GhostSlayer. You clearly don't have any insight in what's going on and why we're all here talking.

Yeah my bad :D it was morning and just quicky sent something without realizing anything. And yeah i use BlockTheSpot so i clearly know "why we're all here talking." dont act special

**Comment by dswapnil104** [comment]
> > i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated
> > if anyone wants to do that too, i'll send a link to the rar file i made (i don't know if it's allowed so i won't risk it)
> 
> How are we supposed to blocking the auto updates and downgrade to an older version??

**Heads Up!!**
If anyone wants to roll back :

**Use these resources:**
https://github.com/amd64fox/LoaderSpot `(To get the latest supported Spotify Client installer)`

**Then block the automatic updates** :

[Follow this](url) [guide](https://youtu.be/iCr9TckFu-M)

Ciao ✌️

**Comment by ronny941** [comment]
> 
> 
> I didn't got this update yet. :P wait few day before spotify push it into my area

I hope you fix this problem your tool is the best

**Comment by Flysix16** [comment]
block the spot don't work on the lastest version all ads back just the upgrade buttom missing ):

**Comment by hvrgl** [comment]
> > > i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated
> > > if anyone wants to do that too, i'll send a link to the rar file i made (i don't know if it's allowed so i won't risk it)
> > 
> > 
> > How are we supposed to blocking the auto updates and downgrade to an older version??
> 
> **Heads Up!!** If anyone wants to roll back :
> 
> **Use these resources:** https://github.com/amd64fox/LoaderSpot `(To get the latest supported Spotify Client installer)`
> 
> _Currently;_
> 
> ```
> 
> - Last updated: 17 August 2021
> - Last tested version: 1.1.68.628.geb44bd66
> ```
> 
> **Then block the automatic updates** :
> 
> Follow this
> 
> * [Guide](https://youtu.be/iCr9TckFu-M)
> 
> Ciao ✌️

I also made a batch file that automates the update blocking stuff, this might help!
~ [DisableSpotifyUpdate.bat](https://github.com/hvrgl/BlockTheSpot/blob/master/DisableSpotifyUpdate.bat)
- Automatically create spotify_new.exe file and set the permission to read only.
- Automatically create Update folder under %LocalAppData%\Spotify and set to deny all permission.

**Comment by mrpond** [comment]
@amd64fox ty! fixed!

**Comment by dswapnil104** [comment]
> > > > i downgraded my spotify back to the 1.1.68.628 version (aka the one blockthespot was last tested with) and disabled the updates as a temporary fix until it gets updated
> > > > if anyone wants to do that too, i'll send a link to the rar file i made (i don't know if it's allowed so i won't risk it)
> > > 
> > > 
> > > How are we supposed to blocking the auto updates and downgrade to an older version??
> > 
> > 
> > **Heads Up!!** If anyone wants to roll back :
> > **Use these resources:** https://github.com/amd64fox/LoaderSpot `(To get the latest supported Spotify Client installer)`
> > _Currently;_
> > ```
> > 
> > - Last updated: 17 August 2021
> > - Last tested version: 1.1.68.628.geb44bd66
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Then block the automatic updates** :
> > Follow this
> > 
> > * [Guide](https://youtu.be/iCr9TckFu-M)
> > 
> > Ciao ✌️
> 
> I also made a batch file that automates the update blocking stuff, this might help! _make sure to run as admin_ ~ [DisableSpotifyUpdate.bat](https://github.com/hvrgl/BlockTheSpot/blob/master/DisableSpotifyUpdate.bat)
> 
> * Automatically create spotify_new.exe file and set the permission to read only.
> * Automatically create Update folder under %LocalAppData%\Spotify and set to deny all permission.

I guess the batch file needs to be updated to patch the required attributes for ver. `1.1.72.439.gc253025e` or in general for the latest version supported by the team blockthespot .

**Comment by xerta555** [comment]
> I guess the batch file needs to be updated to patch the required attributes for ver. `1.1.72.439.gc253025e` or in general for the latest version supported by the team blockthespot .

You have to download again the bat file and run it on your Windows to fix that.

**Comment by dswapnil104** [comment]
> > I guess the batch file needs to be updated to patch the required attributes for ver. `1.1.72.439.gc253025e` or in general for the latest version supported by the team blockthespot .
> 
> You have to download again the bat file and run it on your Windows to fix that.

Well, yeah that is a quick and dirty fix, but hey it works nonetheless.

**Comment by xerta555** [comment]
> > > I guess the batch file needs to be updated to patch the required attributes for ver. `1.1.72.439.gc253025e` or in general for the latest version supported by the team blockthespot .
> > 
> > 
> > You have to download again the bat file and run it on your Windows to fix that.
> 
> Well, yeah that is a quick and dirty fix, but hey it works nonetheless.

Not wrong, but since the script file is updated manually on a URL that doesn't change, I made a script to download it and run it automatically, easier.
