### ISSUE TITLE
banner ads + audio ads after a few songs

### ISSUE THREAD

**Issue by kamxsato** [mrpond/BlockTheSpot#231]
I used blockthespot exactly a week ago and it was going fine without any issues until today when I noticed a sponsor ad and audio ad after listening to like 5-ish songs. My sister also uses it and her one works just fine so I'm not sure what's the issue.

I have:
- disabled my anti-virus before running it (i thought maybe it was my antivirus interfering cuz norton antivirus smh so i disabled it whilst using spotify but it was the same)
- uninstalled and re-installed it
- restarted my laptop
- used solutions from previous issues

pls help thanks[](url)

**Comment by rustokomuska** [comment]
same issue

**Comment by Mistedxo** [comment]
Same problem for me too!

**Comment by dolpce** [comment]
Nothing to worry about, there was an update today. Exactly the same problem I have, but it seems like manual installation helped. Otherwise, just wait for the BlockTheSpot update.

**Comment by mreduar** [comment]
Same problem today

**Comment by mrpond** [comment]
fixed !
