### ISSUE TITLE
Upgrade button still here

### ISSUE THREAD

**Issue by HazemDa1st** [mrpond/BlockTheSpot#233]
I install Blockthespot.bat as admin 
I get this when I hit Y - Iam using spotify 1.1.69 and spicetify 2.7

![Screenshot 2021-10-03 220315](https://user-images.githubusercontent.com/47460655/135770491-a06668f4-3ebf-499d-8b9c-9c136df9343c.png)

**Comment by teodosioo** [comment]
i had this too and ran the program as administrator and it got fixed

**Comment by Nuzair46** [comment]
This fix will not work if Spicetify is being used. 
In that case, manually remove upgrade button through Spicetify
