### ISSUE TITLE
Ads have returned

### ISSUE THREAD

**Issue by ktjnn** [mrpond/BlockTheSpot#234]
I followed the checklist including Davoleo's in-depth guide and was glad that the Upgrade Button and the ugly banner w/ the broken code filling it or just that big black rectangle for the banner were gone. But an ad managed to get through after a day or so of me downloading the new code and patch. 

If you cycle through songs manually by pressing next, you don't get that weird song block that has an ad. But if you let a 3rd or 4th song in a cycle just play and finish on its own, you'll get a sudden ad. This has been happening for the past few minutes

![Screenshot (247)](https://user-images.githubusercontent.com/37252515/136014423-af0f6d97-0e2d-4613-8ddf-263dd8620a07.png)
.

**Comment by Nuzair46** [comment]
Please upload Spotify version and BlockTheSpot Logs.

**Comment by lukszi** [comment]
I had the same issue,
Spotify version was: 1.1.65.643.g2d707698-a and logs showed no problems.

I tried to update to the newest version of spotify through the about spotify dialogue, but that failed.
What solved it, was a clean reinstall of spotify and then BlockTheSpot.

**Comment by Nuzair46** [comment]
You said you followed the bug report checklist and it looks like you haven't.
you are not using the latest version of Spotify. Read the readme for the latest supported version
