### ISSUE TITLE
remove ad placeholder not working

### ISSUE THREAD

**Issue by WelkinBunbury** [mrpond/BlockTheSpot#235]
![image](https://user-images.githubusercontent.com/33565456/136149526-e4c1613b-9826-4dc5-a323-cdbac3cbc276.png)
I had installed dribblish v2, and got this error when installing BLOCK THE SPOT
I am not getting any adds it working fine but I was not able to remove add placeholder.

please help

**Comment by Nuzair46** [comment]
It says you have to press "N" if you use Spicetify. This is because this fix doesnt work when Spicetify is used.
