### ISSUE TITLE
Another Windows Defender false positive

### ISSUE THREAD

**Issue by MasicoreLord** [mrpond/BlockTheSpot#24]
Falsely detected threat: Trojan:Win32/Wacatac.B!ml
[Screenshot](https://i.imgur.com/fSJfX7o.png)

**Comment by mrpond** [comment]
Hi, 
please follow below instruction, 
Official from windows defender team.

> Analyst comments:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> Run "MpCmdRun.exe -removedefinitions -dynamicsignatures"
> Run "MpCmdRun.exe -SignatureUpdate"
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

**Comment by MasicoreLord** [comment]
@mrpond didn't realize that an AV could hold onto false positives in it's cache for a while.

**Comment by MichalisSak** [comment]
Latest fix isn't working anymore.
