### ISSUE TITLE
Spotify not launching

### ISSUE THREAD

**Issue by dreamco3d** [mrpond/BlockTheSpot#243]
It seems that spotify does not launch at all after the latest patch.

**Comment by Nuzair46** [comment]
@dreamco3d @Brazem3 @yuliy1wnl can you guys run the latest patch again?

**Comment by dreamco3d** [comment]
> @dreamco3d @Brazem3 @yuliy1wnl can you guys run the latest patch again?

Still not working..why should it be? Nothing has changed..

**Comment by Saint-Mod19** [comment]
> 
> 
> @dreamco3d @Brazem3 @yuliy1wnl can you guys run the latest patch again?

The application does not start. Older patches do crash after a few seconds.

**Comment by Tuniax** [comment]
It works for 1 minute or something, then spotify crashes.

**Comment by iamSaand** [comment]
Same here

**Comment by bzzrak** [comment]
I get just a black screen. Should be noted that I use Spicetify though.

**Comment by skullyyyyyyy** [comment]
is there a fix coming nuzair sir?

**Comment by Tuniax** [comment]
i guess he is working on it, but you can try to install an older version for spotify and disabling auto update by deny the access to the update folder. would be nice if you can tell me if this gonna work.

**Comment by Saint-Mod19** [comment]
> i guess he is working on it, but you can try to install an older version for spotify and disabling auto update by deny the access to the update folder. would be nice if you can tell me if this gonna work.

On the previous version of the application, the last patch worked fine. I don't know where to download the older version.

**Comment by hozansahin** [comment]
I have the same problem

**Comment by Nuzair46** [comment]
Hey, Please uninstall Spotify, then install the latest from https://spotify.com and apply the patch.

There was a faulty BlockTheSpot release earlier today which maybe causing the issue, The updated patch should work fine. To make it work, reinstall Spotify and then apply the patch.

**Comment by hazieness** [comment]
> 
> 
> Hey, Please uninstall Spotify, then install the latest from https://spotify.com and apply the patch.
> 
> There was a faulty BlockTheSpot release earlier today which maybe causing the issue, The updated patch should work fine. To make it work, reinstall Spotify and then apply the patch.

Already tried that earlier, but will do this again. Thanks!

**Comment by Nuzair46** [comment]
Please make sure to download the latest patch release or use BlockTheSpot.bat

**Comment by dreamco3d** [comment]
> Please make sure to download the latest patch release or use BlockTheSpot.bat

Nothing happens. Spotify does not launch

**Comment by hazieness** [comment]
> 
> # Uninstall Spotify, then just run the BlockTheSpot.bat
> It will download both the latest Spotify and Patch. Sorry for the inconvinience.

This does work. Thank you!

**Comment by levinhank** [comment]
Hi @Nuzair46 , I have experienced the same error like the people above me did. I followed your instructions and I uninstalled the Spotify app, deleted every related folder and ran the .bat file, but after it installed Spotify and I tried to sign in, but now it shows me the "Something went wrong, try reloading the page" error and I don't know what to do about it.
Do you have any idea about what might have caused this problem and how could I solve it?

**Comment by ronny941** [comment]
the app it doesnt' launching i have uninstalled and reinstalled spotify and applied blockthespot but the app it doesn't launch

**Comment by skullyyyyyyy** [comment]
still not working :(

**Comment by ronny941** [comment]
it works only with the 2 original files of this version, when you copy the 2 files of blockthespot spotify it doesn't launch

**Comment by ivxnboi** [comment]
When u install chrome elf, spoty just doesn't launch. Just install Blockthespot, it works perfectly

**Comment by skullyyyyyyy** [comment]
the blockthespot.bat file wasnt working so i downloaded the latest chrome elf zip and pasted it, it works for now.

**Comment by ronny941** [comment]
the program it doesn't opened the process spotify appears on the task manager but the program never opens

**Comment by ronny941** [comment]
> 
> 
> When u install chrome elf, spoty just doesn't launch. Just install Blockthespot, it works perfectly

I confirm it works when you launch blockthespot.bat thank you for this solution.

**Comment by La-wea-cosmica** [comment]
now nothing works

**Comment by JacobHornbeck** [comment]
> # Uninstall Spotify, then just run the BlockTheSpot.bat
> It will download both the latest Spotify and Patch. Sorry for the inconvinience.

This worked for me as well! Thank you! It may be an inconvenience, but software development isn't easy... fixing it as fast as you guys did is awesome. I can't complain 😉

**Comment by yuliy1wnl** [comment]
why it's still not working for me

**Comment by iluluchuu** [comment]
> 
> 
> Hey, Please uninstall Spotify, then install the latest from https://spotify.com and apply the patch.
> 
> There was a faulty BlockTheSpot release earlier today which maybe causing the issue, The updated patch should work fine. To make it work, reinstall Spotify and then apply the patch.

worked for me after many tries thank you so much ! 

I just had to rename the original chrome_elf.dll to chrome_elf_bak.dll and leave it there along side the patch as the instructions say. it was working fine without doing that step with older patches though.

**Comment by MeatyChunks** [comment]
The people saying uninstalling and repatching works must be lucky, because that method does not work here.

**Comment by mrpond** [comment]
Hi, when in doubt try do the manual install. https://github.com/mrpond/BlockTheSpot/blob/master/README.md

**Comment by mrpond** [comment]
![imageBTS](https://user-images.githubusercontent.com/18654771/139521263-b366df17-658d-4222-a313-94162006491b.png)
open new issue if problem still there
