### ISSUE TITLE
still doesnt work after trying diffrent tings of trying to fix 

### ISSUE THREAD

**Issue by StepZ0** [mrpond/BlockTheSpot#248]
Make sure you have completed everything in the following checklist.

 - [ ] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [ ] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ ] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

i have tried uninstalling and a lot of different stuff but it just still isn't going my way is it just me being a dumbass or?
I'm sorry if I missed sum 
ty <3

**Comment by Nuzair46** [comment]
1. Uninstall Spotify.
2. Download **Latest (important)** BlockTheSpot.bat and run it.
