### ISSUE TITLE
Doesent work.

### ISSUE THREAD

**Issue by SatanicScripter** [mrpond/BlockTheSpot#249]
When i lauch spotify it doesent open.
I re installed all chrome_elf and it doesent work.
:(

**Comment by telumletiferum** [comment]
Either use the ps script or read step n.2 of manual install.

**Comment by Keelar** [comment]
Not working for me either. I've tried all of the manual install steps, the ps script and the batch file, nothing works anymore. I haven't had this issue in the past.

**Comment by telumletiferum** [comment]
> Not working for me either. I've tried all of the manual install steps, the ps script, the batch file, even uninstalled and reinstalled Spotify manually. Nothing works anymore. I haven't had this issue in the past.

What is the version of Spotify? For me the new install method in the readme worked like a charm. My Spotify version is 1.1.71.560.

**Comment by Keelar** [comment]
Same version for me 1.1.71.560. Whenever I try to start it nothing happens for like 30-60 seconds and then a little dialog pops up saying "The Spotify application is not responding."

**Comment by Nuzair46** [comment]
1. Uninstall Spotify.
2. Download **Latest (important)** BlockTheSpot.bat and run it.

**Comment by Keelar** [comment]
I have uninstalled several times and downloaded the most recent BlockTheSpot. It still doesn't work.

**Comment by telumletiferum** [comment]
> I have uninstalled several times and downloaded the most recent BlockTheSpot. It still doesn't work.

Please lay out exactly the steps that you took to try and install block the spot

**Comment by Keelar** [comment]
Opened task manager and made sure there were no Spotify processes running, then went to control panel and uninstalled Spotify. Then went to the official Spotify site and downloaded the latest version and installed it. Then went to the README of this repo and followed the install instructions. The first one I tried was the BlockTheSpot.bat batch file and ran it, no errors while running it, but Spotify would fail to open. Then uninstalled and reinstalled Spotify again. Then copied the PowerShell script in the instructions and executed it in PowerShell, no errors while running it, but again Spotify would fail to open. Then followed the manual instructions exactly as explained in the instructions and again Spotify would fail to open.

I've had to update BlockTheSpot literally dozens of times in the past whenever Spotify updates and have never had a problem until yesterday. I'm not new to using it.

**Comment by telumletiferum** [comment]
> Opened task manager and made sure there were no Spotify processes running, then went to control panel and uninstalled Spotify. Then went to the official Spotify site and downloaded the latest version and installed it. Then went to the README of this repo and followed the install instructions. The first one I tried was the BlockTheSpot.bat batch file and ran it, no errors while running it, but Spotify would fail to open. Then uninstalled and reinstalled Spotify again. Then copied the PowerShell script in the instructions and executed it in PowerShell, no errors while running it, but again Spotify would fail to open. Then followed the manual instructions exactly as explained in the instructions and again Spotify would fail to open.
> 
> I've had to update BlockTheSpot literally dozens of times in the past whenever Spotify updates and have never had a problem until yesterday. I'm not new to using it.

Can you screenshot, the root folder of Spotify?

**Comment by Keelar** [comment]
Apparently all I had to do was restart my computer, because I just tried it today after turning my PC on and it worked without issue. Sorry about that, I should've tried that yesterday.
