### ISSUE TITLE
Request - The BAT should always download the last chrome_elf.zip

### ISSUE THREAD

**Issue by HostFat** [mrpond/BlockTheSpot#25]
As title

Currently the user has to always download the last version of chrome_elf.zip, and then run the bat.

I think that it will be more userfriendly if the bat also download the last chrome_elf.zip from github.

**Comment by mrpond** [comment]
ok @rednek46

**Comment by rednek46** [comment]
> ok @rednek46

I have made a pull request on this including another minor bug fix.

**Comment by mrpond** [comment]
@HostFat  okay, I had merge from @rednek46 thanks guy

**Comment by omrisim210** [comment]
Since powershell does most of the heavy lifting, wouldn't it be faster to have the bat file invoke powershell once and write the entire thing in powershell instead of invoking it a few times?  
At least on my system powershell has a pretty long startup compared to cmd so it makes sense to only start it once.

**Comment by mrpond** [comment]
@omrisim210 thank you very much !
but I never use CI before...  will try look into it.
I let's installation work to @rednek46

**Comment by mrpond** [comment]
@omrisim210 I tested appveyor, it work.
thank for suggestion!
now i need some automation 
zipped output file and run the version for me.

**Comment by rednek46** [comment]
> Since powershell does most of the heavy lifting, wouldn't it be faster to have the bat file invoke powershell once and write the entire thing in powershell instead of invoking it a few times?
> At least on my system powershell has a pretty long startup compared to cmd so it makes sense to only start it once.
> 
> Or (possibly) even better, embed the binary directly into the bat file like the original BTS did.
> [You might be interested in these answers](https://stackoverflow.com/questions/19575665/store-a-file-inside-of-a-batch-file).
> 
> I think you could even have an online CI system like appveyor build it automatically and upload it to the releases, since I noticed you usually only update the zip file in the repo instead of using the releases for their intended purpose.

Embedding the chrome_elf.dll directly to the bat file would mean that i should keep on updating the bat file every once a new release of the patch is made. I haven't used any CI, will definitely try. And about the powershell, its only used to check existing spotify installation , download and extract chrome_elf.zip . Though i could use curl to download the patch, it sometimes doesn't work as expected. I would definitely try using appveyor to create a new bat file with embedded patch whenever a new release is made. I think having the patch embedded with the bat is better than using powershell.

**Comment by kapitaniglo11** [comment]
Updated to the newest version and now chrome_elf is not working - tried automatic and manual method. Any links to the Full Setup with it confirmed to work?

**Comment by rednek46** [comment]
> Updated to the newest version and now chrome_elf is not working - tried automatic and manual method. Any links to the Full Setup with it confirmed to work?

can you also send the spotify version? and did you notice any error while using the automatic method?

**Comment by rednek46** [comment]
> Updated to the newest version and now chrome_elf is not working - tried automatic and manual method. Any links to the Full Setup with it confirmed to work?



> > Since powershell does most of the heavy lifting, wouldn't it be faster to have the bat file invoke powershell once and write the entire thing in powershell instead of invoking it a few times?
> > At least on my system powershell has a pretty long startup compared to cmd so it makes sense to only start it once.
> > Or (possibly) even better, embed the binary directly into the bat file like the original BTS did.
> > [You might be interested in these answers](https://stackoverflow.com/questions/19575665/store-a-file-inside-of-a-batch-file).
> > I think you could even have an online CI system like appveyor build it automatically and upload it to the releases, since I noticed you usually only update the zip file in the repo instead of using the releases for their intended purpose.
> 
> Embedding the chrome_elf.dll directly to the bat file would mean that i should keep on updating the bat file every once a new release of the patch is made. I haven't used any CI, will definitely try. And about the powershell, its only used to check existing spotify installation , download and extract chrome_elf.zip . Though i could use curl to download the patch, it sometimes doesn't work as expected. I would definitely try using appveyor to create a new bat file with embedded patch whenever a new release is made. I think having the patch embedded with the bat is better than using powershell.



> Updated to the newest version and now chrome_elf is not working - tried automatic and manual method. Any links to the Full Setup with it confirmed to work?

Make sure you have the latest blockthespot from this [repo](https://github.com/mrpond/BlockTheSpot) .
and try changing  Skip_wpad in config.ini to 1 . 
if that fails too uninstall spotify and run the automatic installer. it will install the latest spotify and patch.

**Comment by kapitaniglo11** [comment]
Spotify version is the current one: 1.1.29.592. Tried using the automatic installer and the same thing happen. Cannot start the app after applying elf.

**Comment by Rootzpower** [comment]
> 
> 
> Spotify version is the current one: 1.1.29.592. Tried using the automatic installer and the same thing happen. Cannot start the app after applying elf.

+1

**Comment by rednek46** [comment]
> Spotify version is the current one: 1.1.29.592. Tried using the automatic installer and the same thing happen. Cannot start the app after applying elf.



> > Spotify version is the current one: 1.1.29.592. Tried using the automatic installer and the same thing happen. Cannot start the app after applying elf.
> 
> +1

can you guys try using [this](https://github.com/mrpond/BlockTheSpot/releases/download/v0.50/chrome_elf.zip) version. install it manually.

**Comment by kapitaniglo11** [comment]
> can you guys try using [this](https://github.com/mrpond/BlockTheSpot/releases/download/v0.50/chrome_elf.zip) version. install it manually.

Well! This one is working! Thanks!

**Comment by rednek46** [comment]
> > can you guys try using [this](https://github.com/mrpond/BlockTheSpot/releases/download/v0.50/chrome_elf.zip) version. install it manually.
> 
> Well! This one is working! Thanks!

@Rootzpower  use this  v0.50 patch. the latest release has some kind of error.

**Comment by rednek46** [comment]
@mrpond  i have created a new issue based on this. looks like the appveyor release has a problem.

**Comment by Davoleo** [comment]
It'd be nice if the script updated Spotify automatically if it detects Spotify is outdated, sorta like how it installs it automatically when you don't have spotify entirely

**Comment by omrisim210** [comment]
> Embedding the chrome_elf.dll directly to the bat file would mean that i should keep on updating the bat file every once a new release of the patch is made.

True, but you could wrap it in a powershell one-liner and get the effect you're looking for (perhaps the script can download the batch file to `$env:TEMP` and delete it after it finishes installing).  
You could also add it to the repo and even have it show a WinForms message box ([as shown here](https://michlstechblog.info/blog/powershell-show-a-messagebox/)) for some extra usability for non-computer-savvy people.

> And about the powershell, its only used to check existing spotify installation , download and extract chrome_elf.zip . Though i could use curl to download the patch, it sometimes doesn't work as expected.

Curl is unnecessary here as powershell can do everything this script needs and is present on every Windows machine, I just suggested that the script could run powershell once and do everything from inside it as opposed to having the logic written in batch and invoking powershell for some commands (it also has the advantage of being easier to understand, batch is ugly).

**Comment by omrisim210** [comment]
> 
> 
> It'd be nice if the script updated Spotify automatically if it detects Spotify is outdated, sorta like how it installs it automatically when you don't have spotify entirely
> Don't know if that's possible in a batch script though

Batch can invoke powershell or have any type of data embedded in it, which in theory means you can use .NET or native programs/dlls, so I'd say it's possible to do anything from a batch file.

But doesn't Spotify already update itself? On my machine I've noticed it auto-updates on Windows startup (but maybe that's because I have it open all the time and it actually auto-updates when Spotify is launched).

I guess it could be desirable to implement Spotify updating if you disable auto-updating somehow (like how the original BlockTheSpot had a batch file that downgraded Spotify and forced it to stay on an old version) but preventing Spotify from updating itself might prevent other means of updating, it depends on how you do it.

**Comment by rednek46** [comment]
> It'd be nice if the script updated Spotify automatically if it detects Spotify is outdated, sorta like how it installs it automatically when you don't have spotify entirely
Spotify updates itself automatically. And there is an update option in "about spotify" in the settings. 
I don't think anyone would use this batch file to update when spotify provides an option for it. If you don't see any updates, you might have accidentally paused spotify update by running master131's patch which disables updates.Try Reinstalling spotify. If you want to force update/reinstall, just uninstall your current version and run the batch file.

> Don't know if that's possible in a batch script though
It is possible to update Spotify automatically if it detects an older Spotify using batch script. just need to cross check the local version and the version given in the readme or other online source.

**Comment by rednek46** [comment]
> > Embedding the chrome_elf.dll directly to the bat file would mean that i should keep on updating the bat file every once a new release of the patch is made.
> 
> True, but you could wrap it in a powershell one-liner and get the effect you're looking for (perhaps the script can download the batch file to `$env:TEMP` and delete it after it finishes installing).
>
I will definitely work on this next. 
> You could also add it to the repo and even have it show a WinForms message box ([as shown here](https://michlstechblog.info/blog/powershell-show-a-messagebox/)) for some extra usability for non-computer-savvy people.
> 
> > And about the powershell, its only used to check existing spotify installation , download and extract chrome_elf.zip . Though i could use curl to download the patch, it sometimes doesn't work as expected.
> 
> Curl is unnecessary here as powershell can do everything this script needs and is present on every Windows machine, I just suggested that the script could run powershell once and do everything from inside it as opposed to having the logic written in batch and invoking powershell for some commands (it also has the advantage of being easier to understand, batch is ugly).
> 
I have actually used curl in this script to download the spotify installer. for some reason, the powershell throwing errors when downlaoding with it. in rare cases, powershell shows error while downloading the patch.

**Comment by rednek46** [comment]
@omrisim210  check [this](https://github.com/rednek46/BlockTheSpot) out. Now the batch file runs a powershell script.

**Comment by mrpond** [comment]
@kapitaniglo11 @Rootzpower download v0.51_fix it should work now.
I reopen enchantment issue in another topic

**Comment by Davoleo** [comment]
> Spotify updates itself automatically. And there is an update option in "about spotify" in the settings.
I don't think anyone would use this batch file to update when spotify provides an option for it. If you don't see any updates, you might have accidentally paused spotify update by running master131's patch which disables updates.Try Reinstalling spotify. If you want to force update/reinstall, just uninstall your current version and run the batch file.

@rednek46 
it does download the updates, although when I click to restart and install, Spotify just restarts on the same version, and doesn't update
