### ISSUE TITLE
BlockTheSpot causes Spotify to be unable to be opened after running the bat file.

### ISSUE THREAD

**Issue by eM-Krow** [mrpond/BlockTheSpot#250]
title

**Comment by PostBaloney** [comment]
Same here.

**Comment by HeIp** [comment]
Newest version causes a crash, should review

**Comment by ADDJ1230** [comment]
That's right, please resolve this issue as quickly as possible. :3

**Comment by telumletiferum** [comment]
Use the powershell script: `Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1' | Invoke-Expression`
or alternatively install it properly manually by the new updated readme steps.

**Comment by eM-Krow** [comment]
Sorry I forgot to mention, I fixed the issue.
Steps to get BTS Working:
1. Uninstall and reinstall Spotify. (Don't install over it or Spotify won't work)
2. Download the newest BTS batch file from the readme. (Using the old one will cause the issue again)
3. Run BTS and type N at the prompt.

Should work after that.
