### ISSUE TITLE
after putting the files, when I open spotify it closes a few seconds later

### ISSUE THREAD

**Issue by ADDJ1230** [mrpond/BlockTheSpot#251]
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

**Comment by telumletiferum** [comment]
Read step nr.2 from readme

**Comment by Nuzair46** [comment]
1. Uninstall Spotify.
2. Download **Latest (important)** BlockTheSpot.bat and run it.
