### ISSUE TITLE
Spotify client still not working

### ISSUE THREAD

**Issue by HeIp** [mrpond/BlockTheSpot#252]
Make sure you have completed everything in the following checklist.

1) Did an uninstall
2) DId a free re-install of spotify
3) Ran the .bat file(said no to placeholder question)
4) Ran spotify
![image](https://user-images.githubusercontent.com/31706214/139586071-67db4014-bc96-402d-a620-93c8b116b489.png)
Extra: Not using spicetify

**Comment by Nuzair46** [comment]
Did you use the latest bat file? 
the patching process has been changed so, use of latest batch file is required. Or do manual installation with the new instructions given in the readme.

**Comment by Constant-ine** [comment]
Same here. Spotify broke applying the latest patch, just doesn't open anymore.

> Did you use the latest bat file? the patching process has been changed so, use of latest batch file is required. Or do manual installation with the new instructions given in the readme.

**Comment by HeIp** [comment]
So this worked for me 

1. Uninstall & Install spotify again
2. Run the bat file, select N for placeholder
3. Spotify should auto run after bat file has finished running

Note: this took me 5 attempts with the same process to get it working.
Manually dragging and dropping the zip files did not work

**Comment by SiriusBYT** [comment]
Deleting the entire Spotify Folder and then using the .bat worked (Even with selecting Y for placeholder).
You do what you want with that information.
