### ISSUE TITLE
spotify client fails to open after applying oct29 patch

### ISSUE THREAD

**Issue by Donny-Simmonds** [mrpond/BlockTheSpot#253]
The new spotify client was installed this morning and after manually applying the patches to the respective folder the spotify client fails to run.

There are no error messages. I have uninstalled and reinstalled and it will load without patches; after applying the oct 29th patch again spotify fails to load.  Powershell has been disabled currently but I would imagine that process would yield the same result as they are all have the same end result.

Thanks.

*edit below*

Also, just tried playing with renaming the chrome_elf.dll to chrome_elf_bak.dll and the unzipping both chrome_elf.dll and config.ini from the latest release and still will not open.

**Comment by cronyakatsuki** [comment]
Same problem here, after aplying the new patch can't open spotify.

**Comment by Nuzair46** [comment]
check #244
