### ISSUE TITLE
Please, don't download chrome_elf.zip 

### ISSUE THREAD

**Issue by AyrtonFidel9** [mrpond/BlockTheSpot#256]
This file have virus, a trojan virus, please, don't download this file because i did it and my computer had very problems of security

I scan this .zip in VIRUS TOTAL and get that chrome_elf.zip have a trojan virus

![image](https://user-images.githubusercontent.com/70295855/140448234-7d685341-a138-4dab-91b6-4492ee14c85d.png)

**Comment by xbec65** [comment]
I think its false alert though.

**Comment by mrpond** [comment]
the project is open source, you can audit the code. and give me paypal, I'll pay you if you found it.
