### ISSUE TITLE
Latest Spotify version doesn't start with the latest BlockTheSpot version

### ISSUE THREAD

**Issue by sylvanic** [mrpond/BlockTheSpot#259]
I updated my Spotify yesterday (1.1.72.439.gc253025e), and I had a BlockTheSpot install from the 2021.10.02.40 release. There were no ads, however a song would play for about 30 seconds, then the sound would cut off, spotify crashes and restarts itself. 

I went ahead and tried uninstalling Spotify altogether, same issue persists. Decided to update BlockTheSpot (I install it manually), and with the last 3 versions, after the files have been put in the Spotify directory, Spotify doesn't start at all, no process, nothing. 

Any help would be appreciated.

**Comment by Nuzair46** [comment]
Make sure you followed the new instruction in the readme.

**Comment by sylvanic** [comment]
The extra step seems to be the fix, thank you.

**Comment by fassina2** [comment]
What fixed it for you? Updating windows? Or removing allowed threats ? Both suck, I'd rather not do either..

**Comment by sylvanic** [comment]
@fassina2, I only install it manually, so I follow these steps:
```
Browse to your Spotify installation folder %APPDATA%\Spotify
Rename chrome_elf.dll to chrome_elf_bak.dll
Download chrome_elf.zip from releases
Unzip chrome_elf.dll and config.ini
```
