### ISSUE TITLE
Ads are back on version for Windows 1.1.72.439.gc253025e (most current)

### ISSUE THREAD

**Issue by goddamn-is-this-available** [mrpond/BlockTheSpot#260]
Current version of Spotify still occasionally inserts ads between songs in the latest release.

Applied latest BlockTheSpot, though with some caveats: running the script as is fails because it cannot initiate a secure connection to download the latest release, so I downloaded it manually and edited PowerShell script to look for dll file in the specific directory I created where I placed the dll. That worked last time.

I have enabled logging in \AppData\Roaming\Spotify\config.ini, but no log appears in the same directory, if it logs somewhere else I haven't managed to find it, would appreciate some help.

**Comment by ronny941** [comment]
have you try running the blockthespot.bat?

**Comment by Daksh777** [comment]
I don't see any ads either, using the same version as you are.

**Comment by nanchaara** [comment]
wait really? my spotify broken after installing BTS

**Comment by gcain1** [comment]
> espera realmente? mi spotify se rompió después de instalar BTS, ni siquiera puedo abrirlo

Same thing happened to me. I even get an error using BTS

**Comment by goddamn-is-this-available** [comment]
> are you try running the blockthespot.bat? for me on the new version is working and I have no ads
I did try, but then I have another error preventing PowerShell script to run at all, I have to execute it in PowerShell directly after I override execution policy which preventing me from executing it.

> I don't see any ads either, using the same version as you are.
Well, to be specific, I don't _see_ any ads either, I _hear_ them, between songs.

**Comment by nanchaara** [comment]
try use this step guys, i tried on different adblock but it might work on BTS too
https://github.com/amd64fox/SpotX/issues/15

**Comment by goddamn-is-this-available** [comment]
For some reason I get "Expand-Archive is not recognized as a commandlet name", so PS is unable to unpack archive and proceed with installation, I have to do unzipping manually and edit the script to use hard links to files instead of variables.

**Comment by amd64fox** [comment]
@goddamn-is-this-available 
what is your version of PowerShell and Windows?

**Comment by goddamn-is-this-available** [comment]
I use Windows 8.1, as for PowerShell version it was probably older than 5 because that's when Expand-Archive was introduced. I have downloaded most recent PowerShell and this seems to have helped, I'll update in a day or two after some testing.

**Comment by amd64fox** [comment]
Windows 8.1 comes with PowerShell 4, but you need at least 5. 

If necessary, I wrote a mini-instruction here, what requires to be done to upgrade to 5 ([Outdated versions of PowerShell](https://github.com/amd64fox/SpotX#possible-problems))

**Comment by Nuzair46** [comment]
Please follow the **NEW** manual installation instructions given in the readme. Also, please do follow the bug report checklist before reopening this issue.
