### ISSUE TITLE
Completely breaks Spotify

### ISSUE THREAD

**Issue by EmperorXenu** [mrpond/BlockTheSpot#262]
Not sure what's causing this, but now when I apply block the spot, Spotify will not launch. Tried reverting to the last available version, same thing. Spotify works fine and applying Block the Spot causes it to not launch.

**Comment by sanjaypopcorn** [comment]
same here

**Comment by sanjaypopcorn** [comment]
for the mean time use the older version of the blocker. Here:
https://github.com/mrpond/BlockTheSpot/releases/tag/2021.10.02.40
manually install the files

**Comment by JamesZas** [comment]
it doesn´t work

**Comment by Nuzair46** [comment]
Please read the Latest Instructions in the Readme.
