### ISSUE TITLE
Ads in new Spotify update

### ISSUE THREAD

**Issue by 0iffy** [mrpond/BlockTheSpot#263]
Spotify Version: Spotify for Windows `1.1.72.439.gc253025e`

**Comment by cristiangerardo** [comment]
With the new Spotify update 1.1.72.439 the patch makes the application not run, it only runs if I delete the downloaded files and replace with the original ones.

**Comment by ronny941** [comment]
you try download and run BlockTheSpot.bat ?
it works for me

**Comment by Nuzair46** [comment]
make sure to follow the new instruction

**Comment by cristiangerardo** [comment]
> you try download and run BlockTheSpot.bat ? it works for me

No, where to download?

**Comment by ronny941** [comment]
> 
> 
> > you try download and run BlockTheSpot.bat ? it works for me
> 
> No, where to download?

yuo can find it here 
https://github.com/mrpond/BlockTheSpot
