### ISSUE TITLE
needs an updater. i made one

### ISSUE THREAD

**Issue by Ae3NerdGod** [mrpond/BlockTheSpot#265]
basically a shameless self-promote, if youre ok with it.

https://github.com/Ae3NerdGod/SpotTheBlock

also, if youre not cool with me linking to your repo in my readme let me know. 

>Features
>- Small Footprint
>- Minimal user interaction needed
>- Advertisement Detection (for reinstalling BlockTheSpot after Spotify updates)
>- Checks for updates every 6 hours

**Comment by 0iffy** [comment]
idk why make another version of BlockTheSpot, if it works perfectly fine just by running the .bat file and automatically installs for you then?

**Comment by Ae3NerdGod** [comment]
> idk why make another version of BlockTheSpot, if it works perfectly fine just by running the .bat file and automatically installs for you then?

it is not another version of blockthespot, it auto updates blockthespot when an advert is detected or a new one is released.

**Comment by Nuzair46** [comment]
This is good. I'll let @mrpond decide whether it needs to be added on to the readme.

**Comment by mrpond** [comment]
Hi, I can't officially endorse anything. since I got no time to validate it. people can freely use it on their own risk.

**Comment by Ae3NerdGod** [comment]
> Hi, I can't officially endorse anything. since I got no time to validate it. people can freely use it on their own risk.

fair enough
