### ISSUE TITLE
both modded and normal spotify is not working 

### ISSUE THREAD

**Issue by nuz-cinel** [mrpond/BlockTheSpot#267]
hello i am new here but i have been using this Spotify ad blocker for close to 1 year and its been no problems but recently it would say not working and then crash, so i uninstalled it and tried to redownload regular Spotify but it wouldn't work and so i was like fine i guess ill use the modded one
but now none of them work and I've tried everything please help i can't live without music and even the chrome web player is networking too idk why :(

**Comment by nuz-cinel** [comment]
![image](https://user-images.githubusercontent.com/76576367/142773101-726d299a-e3a3-4fee-bc08-6b3c58935cc8.png)

**Comment by Nuzair46** [comment]
If you followed the instructions in the readme, then this doesn't seem to be related to the patch. Reach out to Spotify support to dix your issue.
