### ISSUE TITLE
[req] please add blacklisted servers as txt

### ISSUE THREAD

**Issue by lukjod** [mrpond/BlockTheSpot#272]
AS I have addblock list on my openwrt router, is this possible to add blocklisted servers also as txt list as on this unfortunately outdated project https://github.com/AlfonsoVergara-github/Host-to-block-ads-for-spotify to block it permanently on whole network

**Comment by mrpond** [comment]
Spotify's ads, serve from Spotify's server. Host file blocking are obsoleted for Spotify.
