### ISSUE TITLE
Not compatible with latest spotify version

### ISSUE THREAD

**Issue by Avnsx** [mrpond/BlockTheSpot#277]
not working with latest version of spotify. spotify keeps reinstalling itsself over and over - forcing the adds back into the client

**Comment by amitkuliyal** [comment]
yes they have not updated it to support the latest version of spotify. Had to go back to the supported version.

**Comment by Nuzair46** [comment]
Can you guys update the logs?

**Comment by lihanchen** [comment]
How do I get the logs? I just re-patched it. It takes 1-2 weeks for the ads to come back.

**Comment by Avnsx** [comment]
> Can you guys update the logs?

It would be helpfull, if you further described, what you mean by "update the logs"?

**Comment by Nuzair46** [comment]
@Avnsx I meant to upload the logs.
By the way, BlockTheSpot was testing working with latest Spotify version. It seems you may have been following the instructions wrong.
Use the new installer script or follow the new manual installation instruction.

**Comment by Avnsx** [comment]
> @Avnsx I meant to upload the logs. By the way, BlockTheSpot was testing working with latest Spotify version. It seems you may have been following the instructions wrong. Use the new installer script or follow the new manual installation instruction.

Yes, I'm randomly pulling up this issue ticket out of my ass for no reason.
![](https://i.imgur.com/yldun6f.png)
These come up, even when i use spotifyblock.bat to reinstall spotify, over and over

**Comment by Avnsx** [comment]
> @Avnsx I meant to upload the logs. By the way, BlockTheSpot was testing working with latest Spotify version. It seems you may have been following the instructions wrong. Use the new installer script or follow the new manual installation instruction.

![](https://i.imgur.com/q95eUu6.png)

**Comment by amd64fox** [comment]
@Avnsx Try this [repo](https://github.com/amd64fox/SpotX). 

There added a blocking of updates, you need to select it during installation.

And also testing of blocking of banners from your 1st screenshot is underway.

Inform additionally, here or in my repo about whether your problems have been resolved or not.
