### ISSUE TITLE
Automatically install patch when updating Spotify

### ISSUE THREAD

**Issue by NguyenASang** [mrpond/BlockTheSpot#282]
## Feature Request 
Automatically install patch when updating Spotify.

## Explain Idea
![image](https://user-images.githubusercontent.com/87893636/144852284-e262d6d5-31c6-40ba-9d46-afe6d8afdc3f.png)

Note: I believe there is an update file in Spotify somewhere (will find it and update it soon) so if updating just run it then run the patch.

## Addition Text
I know this can be hard to do but nothing is impossible as long as you try 🔥🔥🔥. Thank you for all you do to improve this patch.

**Comment by amd64fox** [comment]
Why are you so confident the patch will work well in the next versions of Spotify?

Just block updates, it will save you all the problems.

**Comment by NguyenASang** [comment]
> Why are you so confident the patch will work well in the next versions of Spotify?

If there is a bug, you can report it here.

> Just block updates, it will save you all the problems.

I don't want to block updates. I want the latest version because in each update it includes performance improvements, new UI, etc.

**Comment by amd64fox** [comment]
> I want the latest version because in each update it includes performance improvements, new UI, etc.

😆

**Comment by Nuzair46** [comment]
Use this https://github.com/Ae3NerdGod/SpotTheBlock .
It automatically installs the patch when Spotify is updated.

**Comment by NguyenASang** [comment]
@Nuzair46 The repo has been removed, I want to uninstall the patch to auto install, how to do that ? Thanks in advance.

**Comment by ArchemedIan** [comment]
> Use this https://github.com/Ae3NerdGod/SpotTheBlock . It automatically installs the patch when Spotify is updated.

https://github.com/ArchemedIan/SpotTheBlock

that account got terminated for some rowdy comments i made. i still use this daily.
