### ISSUE TITLE
Overlay with premim offer is back (#223)

### ISSUE THREAD

**Issue by chris-kwl** [mrpond/BlockTheSpot#284]
The problem from #223 is back for me, since ~ 5 days.
I updated to the latest version of Spotify and BlockTheSspot, so `1.1.73.517.gbef50fdb` is affected and at least the one before.

Overlay appears so far between 0 - 2 times a day.
Ad is quite certainly localized.

Seems to be exactly the same class as before, no idea why the problem is back:
<details>
  <summary>Screenshots</summary>
  
![ad2](https://user-images.githubusercontent.com/59339711/144913810-6ef42395-30be-461c-b556-9a012dd3e949.png)
![code2](https://user-images.githubusercontent.com/59339711/144913808-0246e575-9ed7-48df-ae2d-28673de9bd33.png)
  
</details

**Comment by amd64fox** [comment]
These pop-up suggestions have not been fixed by anyone before. 

They also appear for me occasionally, mostly when I log into my account.

I will try to watch them in the near future.

**Comment by amd64fox** [comment]
I am currently testing fixing this issue on the new version 1.1.74.631 in [my repo](https://github.com/amd64fox/SpotX), I need some feedback

to test just download and run the install.bat

**Comment by chris-kwl** [comment]
Have not managed to get to the 1.1.74.631 so far unfortunately...
but I used it for 1.1.73.517, I will update when possible.

**Comment by amd64fox** [comment]
@chris-kwl 
if necessary, you can update to the latest version [here](https://github.com/amd64fox/LoaderSpot)

**Comment by chris-kwl** [comment]
that worked, as input also the build was needed `1.1.74.631.g0b24d9ad`

**Comment by amd64fox** [comment]
The offer may appear after a while, if this happens, let me know

**Comment by Daksh777** [comment]
I'm also testing this on my repo, if anyone wants to try/has Spicetify: https://github.com/Daksh777/SpotifyNoPremium

**Comment by amd64fox** [comment]
I have this overlay again, I will look for new ways to disable it through js, as soon as I find something, I will unsubscribe here

**Comment by amd64fox** [comment]
@chris-kwl 
What is your approximate interval? I have it big enough, it can reach a week.

**Comment by chris-kwl** [comment]
End of september I had the overlay almost daily.
Currently it appears once or twice a day but in between some days not at all.
Perhaps its also depends on if you click agree, decline or hide the overlay/close Spotify 🤷‍♂️

**Comment by amd64fox** [comment]
I updated [my repository](https://github.com/amd64fox/SpotX), I'm trying to block the ovrley in a new way, for the test I need to download and run `install.bat`

Write about the results here or in my repo.

**Comment by Nuzair46** [comment]
> I updated [my repository](https://github.com/amd64fox/SpotX), I'm trying to block the ovrley in a new way, for the test I need to download and run `install.bat`
> 
> Write about the results here or in my repo.

@mrpond should I add this repo to readme?

**Comment by mrpond** [comment]
> > I updated [my repository](https://github.com/amd64fox/SpotX), I'm trying to block the ovrley in a new way, for the test I need to download and run `install.bat`
> > Write about the results here or in my repo.
> 
> @mrpond should I add this repo to readme?

no need, this is good alternative project. we can mention about this in #repository on our discord channel.

**Comment by chris-kwl** [comment]
To give at least some feedback here....
I reinstalled Spotify yesterday and just applied BlockTheSpot and received the overlay again today.
Its not fully proven but the solution seems to work, if I notice something different I will open an issue in SpotX Repo.

@amd64fox thank you! :)

**Comment by amd64fox** [comment]
@chris-kwl 
Hi, thanks for the feedback.

I can also confirm that my last fix in my repo fixed the problem with this overlay, have been testing for over a week now and everything is clean.
