### ISSUE TITLE
Audio ads

### ISSUE THREAD

**Issue by amd64fox** [mrpond/BlockTheSpot#289]
Client version: 1.1.74.631.g0b24d9ad
BTS: last

audio ads appear if you listen to music for more than 5 hours

<details>
<summary><small>Screenshot</small></summary><p>

![Снимок экрана 2021-12-19 223138](https://user-images.githubusercontent.com/62529699/146688689-cb83f492-6188-4153-9d09-4f59d2f0ce44.png)

</small></summary><p>

</details>

**Comment by Tsagu** [comment]
Just started having these issues as well

**Comment by mrpond** [comment]
Sometimes, I'm also got this kinds of ads. still can't figured it out yet. >_<

**Comment by OrchidWarrior** [comment]
i feel its some kind of regional ads so we need specific regions/languages filter lists. like my country, i am not able to block any ads until using my own country filter lists at ad-blocker apps or extensions.

**Comment by Araxeus** [comment]
Can confirm, I just got an ad (it appeared a few minutes after I started playing music today)

**Comment by zendiesel** [comment]
Hi there!
From november i guess start problem with crashing app. After starting bat file, spotify running about 1-2min and then instantly close without any modal warning or something else. What can be done for fix that? thx

**Comment by Rajbir98** [comment]
the recent update of Spotify breaks block the spot some ads are still there

**Comment by Fluffyice** [comment]
> the recent update of Spotify breaks block the spot some ads are still there

When Spotify updated, the visual ads returned for me. But the audio ads were still nonexistent. I just logged onto Spotify and they seem to have returned, I check the version and Spotify seems to have released ANOTHER updated, but it's still giving me the option to download the new updated. That means, even though they've released a new version again, I don't have it yet. But audio ads returned regardless, I'm not sure what's going on here.

**Comment by Fluffyice** [comment]
Does anybody know of any good BlockTheSpot alternatives I could use while I'm waiting for an update?

**Comment by Nuzair46** [comment]
@Fluffyice BlockTheSpot should work now. This issue only happens in rare case over long sessions of playing.

**Comment by RezhaBlue** [comment]
Seeing this bug on a fresh install right after just 2 songs.

**Comment by Araxeus** [comment]
I've been using spotify daily for months and never experienced this

**Comment by Nuzair46** [comment]
> I've been using spotify daily for months and never experienced this

it occurs very rarely. will be closing this soon because this issue has become stale.

**Comment by zendiesel** [comment]
> I've been using spotify daily for months and never experienced this

Try this fork, for me works fine https://github.com/amd64fox/SpotX

**Comment by itsmeboy0** [comment]
This Spicetify extension works for me: https://github.com/CharlieS1103/spicetify-extensions/tree/main/adblock

Related issue: https://github.com/mrpond/BlockTheSpot/issues/338

**Comment by amd64fox** [comment]
@zendiesel 
My repo is using audio ad blocker from BTS, so the problem is the same there.

**Comment by Nuzair46** [comment]
Is this issue relevant anymore? Anyone still facing this?

**Comment by accelyte** [comment]
Not ads, instead songs keep pausing themselves.

**Comment by amd64fox** [comment]
I didn't get audio ads like this anymore, I think we can close this one as a deprecated issue.
