### ISSUE TITLE
latest 0.51 doesn't work, use v0.50 from the releases and install manually.

### ISSUE THREAD

**Issue by rednek46** [mrpond/BlockTheSpot#29]
@mrpond The latest release by appveyor doesn't work. it seems like the dll is corrupted. the v0.50 is working perfectly.

**Comment by jonaaa20** [comment]
The latest 0.51 is working fine for me. using 1.1.29.592.gf0779179 here.

**Comment by rednek46** [comment]
> The latest 0.51 is working fine for me. using 1.1.29.592.gf0779179 here.
> ![Spotify_rTFlZYUPCD](https://user-images.githubusercontent.com/19306370/78023766-a1976e80-732d-11ea-8fcc-ec1dd8a6e623.png)

you might have the 0.50 released some days ago, it says 0.51 in readme but its 0.50 in the release. a new [patch](https://github.com/mrpond/BlockTheSpot/releases/tag/v0.51) was released today 0.51, which does not work. Try again with this newer one. it wont work.

**Comment by jonaaa20** [comment]
Nope. I'm using the 0.51, downloaded, compiled manually and it worked fine.

**Comment by rednek46** [comment]
> Nope. I'm using the 0.51, downloaded again, also compiled manually and it worked fine.

Strange. Me and 2 other guys had problem with [this](https://github.com/mrpond/BlockTheSpot/releases/tag/v0.51) patch. The spotify app wont launch. but its works fine when previous patch is used. Did you try installing with the help of bat file?

**Comment by Vrekt** [comment]
0.51 wasn't working for me either, the app wouldn't launch. All good now though with 0.50.

**Comment by mkeroppi** [comment]
Me too.

**Comment by jonaaa20** [comment]
I guess I'm lucky, 0.50 and 0.51 works for me, latest Spotify version + Facebook-linked account (if it matters).

**Comment by mrpond** [comment]
@Vrekt @mkeroppi my bad, please download v0.51_fix it should work fine now.

@rednek46  @jonaaa20 if you had visual studio 2019 installed it work.
I forget to tell appveyor to compile it in 'release'
