### ISSUE TITLE
Block the spot installation error

### ISSUE THREAD

**Issue by AyakaW4ngy** [mrpond/BlockTheSpot#291]
![image](https://user-images.githubusercontent.com/96642371/147377450-6ec46b75-849f-42c9-b70a-0a0405b9a681.png)
Is it just me or anyone here having the same issue when clicking the block the spot bat file?

**Comment by amd64fox** [comment]
Apparently your system has an outdated Tls certificate, this is typical of Windows 7 and below, but as I see from the screenshot, you have Windows 10 and this is strange.

In any case, the BTS script does not support installation with outdated certificates. [Try it](https://github.com/amd64fox/SpotX)

**Comment by Nuzair46** [comment]
@KUTlime .
Is it possible to add this https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel permenantly?

**Comment by KUTlime** [comment]
Sure. Give a second, I'll open a PR with fix.

**Comment by amd64fox** [comment]
forgot to readme fix
