### ISSUE TITLE
Error while using the .bat file

### ISSUE THREAD

**Issue by ROCKY-IS-OP** [mrpond/BlockTheSpot#293]
Get-File : The term 'Write-Information' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:139 char:3
+   Get-File -Uri $uri -TargetFile "$elfPath"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Information:String) [Get-
   File], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-File

cmdlet Start-Sleep at command pipeline position 1
Supply values for the following parameters:
Seconds:

**Actually i get this in my cmd whenever i run the .bat file**

**Comment by Nuzair46** [comment]
What is your windows version?

**Comment by ROCKY-IS-OP** [comment]
> What is your windows version?

Windows 8.1

**Comment by C00L3RWASTAKEN** [comment]
> 

same

**Comment by Nuzair46** [comment]
Looks like you have an older version of powershell 4. Try installing version 5 from here https://www.microsoft.com/en-us/download/details.aspx?id=50395
