### ISSUE TITLE
Getting errors when running the application 

### ISSUE THREAD

**Issue by XumoVoidHD** [mrpond/BlockTheSpot#297]
I'm not sure what is causing this error. I have the latest version of spotify and BlockTheSpot. This issue never happened before.
![image](https://user-images.githubusercontent.com/61292952/148725432-58c61e5f-cf9c-4636-9fbb-759618ae8fb6.png)

**Comment by amd64fox** [comment]
It looks like a problem with the network connection, after a while you tried to launch it again?

**Comment by Nuzair46** [comment]
Network issue
