### ISSUE TITLE
Error while running .bat file or executing script on Powershell

### ISSUE THREAD

**Issue by Daksh-T** [mrpond/BlockTheSpot#299]
While running the script on Powershell, I encounter the following error:

```
Downloading latest patch (chrome_elf.zip)...

Start-BitsTransfer : The service cannot be started, either because it is disabled or because it
has no enabled devices associated with it.
The service cannot be started, either because it is disabled or because it has no enabled devices
associated with it.
At line:37 char:9
+         Start-BitsTransfer -Source $Uri -Destination "$($TargetFile.F ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfe
   r.Management.NewBitsTransferCommand

Start-BitsTransfer : Object reference not set to an instance of an object.
At line:37 char:9
+         Start-BitsTransfer -Source $Uri -Destination "$($TargetFile.F ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.BackgroundIntelligentTransfe
   r.Management.NewBitsTransferCommand


cmdlet Start-Sleep at command pipeline position 1
Supply values for the following parameters:
Seconds:
```

I tried using the .bat file but it produced the same result, any idea what could be causing it?

**Comment by Nuzair46** [comment]
@KUTlime Is it possible to disable use of `BitsTransfer` and use normal get if `BitsTransfer` is not available or enabled.
BitsTransfer in the most case provides a better UI and people can avoid the issue when its not enabled.

**Comment by KUTlime** [comment]
@Nuzair46 It is possible if we can find a reliable way how to find that out. I will have look on it.

**Comment by Nuzair46** [comment]
@KUTlime we can catch this error and do the alternative method right instead of explicitly looking for the package?

**Comment by amd64fox** [comment]
Why don't you want to use Spotify's native progress bar?

It looks great and there are no compatibility issues on different versions of Windows
 <details>
<summary><small>Example</small></summary><p>

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/62529699/149981477-dd64dbfc-dcfe-4438-a40f-a27a5883e127.gif)


</details>

**Comment by Nuzair46** [comment]
@amd64fox the issue is concerned about the progress bar for downloading the patch and not Spotify setup.

**Comment by amd64fox** [comment]
This is because in the script script, BitsTransfer is loading a patch at the beginning, if the Spotify installer was being loaded there, then the error would also appear.

I mean in general the use of BitsTransfer in the script and suggested a simpler and more reliable option.

**Comment by KUTlime** [comment]
> This is because in the script, BitsTransfer is loading a patch at the beginning, if the Spotify installer was being loaded there, then the error would also appear.
> 
> I mean in general the use of BitsTransfer in the script and suggested a simpler and more reliable option.

I have no idea what are you trying to say.

**Comment by KUTlime** [comment]
> @KUTlime we can catch this error and do the alternative method right instead of explicitly looking for the package?

This problem happens because there is a misconfiguration in a user system.
@Daksh-T Can you execute this command in PowerShell? `(Get-Service -Name *bit*).StartType`

**Comment by Daksh-T** [comment]
> > @KUTlime we can catch this error and do the alternative method right instead of explicitly looking for the package?
> 
> This problem happens because there is a misconfiguration in a user system. @Daksh-T Can you execute this command in PowerShell? `(Get-Service -Name *bit*).StartType`

It returns
`Disabled`

**Comment by Daksh-T** [comment]
So I just enabled the Background Intelligence Transfer Service (which I suppose is called BIT) and the script worked now. I don't know why it was disabled in the first place though.
