### ISSUE TITLE
Must Report this Issue.

### ISSUE THREAD

**Issue by rednek46** [mrpond/BlockTheSpot#30]
While running the batch file, if anyone encountered this error. Please report [here](https://github.com/rednek46/BlockTheSpot) as a new issue. And also include the No. of times you have run the batch files after the last system startup.
![{98C3571D-5913-4AB2-A9CE-36E14E7DDE53} png](https://user-images.githubusercontent.com/38219313/78042656-f23fb380-738f-11ea-82f1-7e419cbff0e4.jpg)

**Comment by mrpond** [comment]
add some check if download success/zip file exist
