### ISSUE TITLE
Unable to remove the UPGRADE button in the new update.

### ISSUE THREAD

**Issue by certifiedgeek** [mrpond/BlockTheSpot#300]
Today, spotify released a new update (version 1.1.77.643.g3c4c6fc6) and since then, blockthespot cant remove the UPGRADE button in the top right corner of the app. Other functions are working fine.

**Comment by amd64fox** [comment]
There the regular expression is not quite correctly written, wait for it to be corrected or [use this](https://github.com/amd64fox/SpotX)

**Comment by certifiedgeek** [comment]
> There the regular expression is not quite correctly written, wait for it to be corrected or [use this](https://github.com/amd64fox/SpotX)

Thanks, that fixed it.

**Comment by Davoleo** [comment]
> There the regular expression is not quite correctly written, wait for it to be corrected or [use this](https://github.com/amd64fox/SpotX)

@amd64fox if you want to make a pull request contribution to fix this in our repo that would be nice
