### ISSUE TITLE
many errors while lauching the batch file

### ISSUE THREAD

**Issue by NouaaTW** [mrpond/BlockTheSpot#304]
there's some bugs when i try to replace the dll file

**Comment by Davoleo** [comment]
can you attach screenshots or gists of the errors?
we can't fix them otherwise

**Comment by NouaaTW** [comment]
actually not, but it seems not to work anymore after the new spotify's update

i will tonight.

**Comment by Akshay-R01** [comment]
Yes, I can't also seem to run the app after replacing the files. App just doesn't start.

**Comment by NouaaTW** [comment]
![image](https://user-images.githubusercontent.com/75568768/150581065-8c8ceedc-7f37-4767-8b95-724f3097d78e.png)

**Comment by amd64fox** [comment]
> it says "impossible to save the shortcut cause the path doesn't exist"

Shortcut creation script does not work correctly if the default path is changed to another.

Had a similar problem before.

The correct path of the Desktop can be found through the registry.

**Comment by Nuzair46** [comment]
@Davoleo please fix this with a check to see if the shortcut already exists.

**Comment by Nuzair46** [comment]
@NouaaTW you can ignore this error. it will be fixed. The patch should be installed and working correctly.
