### ISSUE TITLE
Bat and powershell error

### ISSUE THREAD

**Issue by Exzify** [mrpond/BlockTheSpot#310]
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

 

This issue suddenly came up after a long time without ads Ive been having this error for a while now and im not sure what is happening.  Everytime i run the downgrade.bat as adminstrator, i get an error. Then it opens spotify, but still the same version(not downgraded) I also tried the powershell method, but i get an error message there as well. I have uninstalled and reinstalled spotify multiple times and neither bat.file or powershell way works. my OS is win 10. 
![image](https://user-images.githubusercontent.com/98287738/150699925-5d43a7df-d935-4dac-b9eb-ad2bf610f00e.png)
![image](https://user-images.githubusercontent.com/98287738/150699929-c4d8ad74-64b0-4dcb-ab14-3857a3f7ed46.png)

**Comment by Nuzair46** [comment]
This script doesn't seem to be the one in this repo. Please use that. Also please don't just tick the checklist. follow the steps and you wont be having these issues.
