### ISSUE TITLE
Spotify crashing after a few seconds

### ISSUE THREAD

**Issue by CatUnderInfluence** [mrpond/BlockTheSpot#311]
Latest Spotify update (with latest BlockTheSpot chrome_elf.dll of course) crashes after a few seconds of playing.

Crash symptoms: Stops playing after a few seconds (10 or so) then plays a bit more (1/10 or 2/10 s.) when CTDing.

blockthespot.log.txt:
LOG | 28-Jan-2022 13:02:31 - GetModuleInformation OK!
LOG | 28-Jan-2022 13:02:31 - main process - patch success!

Thanks by the way for your excellent work so far. :)

**Comment by Chromos-Def** [comment]
Can also confirm the same issue is happening here as well.

**Comment by Nuzair46** [comment]
@Chromos-Def @CatUnderInfluence Please follow the updated Instructions.
