### ISSUE TITLE
blockthespot can't apply the patch

### ISSUE THREAD

**Issue by Gabsletobar** [mrpond/BlockTheSpot#313]
![windows8error](https://user-images.githubusercontent.com/31623861/152054164-14ec5567-0882-4671-b7a4-7984438e255d.png)

**Comment by Nuzair46** [comment]
Auto installer only supports Windows 10 and above

**Comment by Gabsletobar** [comment]
Oh. Ok. **Sorry!** 
**Thanks** for the fast reply!
