### ISSUE TITLE
Propose to make choices from params or make automation possible

### ISSUE THREAD

**Issue by OnkelM** [mrpond/BlockTheSpot#318]
i would like to propose a move of the Read-Host commands simply because currently this avoids / breaks automation.

so instead of these lines
```
  $ch = Read-Host -Prompt 'Uninstall Spotify Windows Store edition (Y/N)'
  if ($ch -eq 'y')
  {
    Write-Host "Uninstalling Spotify.`n"
    Get-AppxPackage -Name SpotifyAB.SpotifyMusic | Remove-AppxPackage
  }
  else
  {
    Read-Host "Exiting...`nPress any key to exit..."
    exit
  }
```
and
```
  $ch = Read-Host -Prompt 'Optional - Update Spotify to the latest version. (Might already be updated). (Y/N)'
  if ($ch -eq 'y')
  {
    $update = $true
  }
  else
  {
    Write-Host 'Won''t try to update Spotify.'
  }
```
and
`$ch = Read-Host -Prompt 'Optional - Remove ad placeholder and upgrade button. (Y/N)'`

it would look like this
```
param (
  $UninstallSpotifyStoreEdition = (Read-Host -Prompt 'Uninstall Spotify Windows Store edition if it exists (Y/N)'),
  $UpdateSpotify = (Read-Host -Prompt 'Optional - Update Spotify to the latest version. (Might already be updated). (Y/N)'),
  $RemoveAdPlaceholder = (Read-Host -Prompt 'Optional - Remove ad placeholder and upgrade button. (Y/N)')
)
  ...
  if ($UninstallSpotifyStoreEdition -eq 'y')
  {
    Write-Host "Uninstalling Spotify.`n"
    Get-AppxPackage -Name SpotifyAB.SpotifyMusic | Remove-AppxPackage
  }
  ...
    if ($UpdateSpotify -eq 'y')
  {
    $update = $true
  }
  else
  {
    Write-Host 'Won''t try to update Spotify.'
  }
  ...
if ($RemoveAdPlaceholder -eq 'y')
{
  ...
}
else
{
  Write-Host "Won't remove ad placeholder and upgrade button.`n"
}
```

Also it would be better to remove the explicit `Read-Host` entrys just for waiting to close the proccess.
So instead of 
```Read-Host "Exiting...`nPress any key to exit..."```
we should use the timeout feature of windows with
```Write-Host "Exiting in...`n"; TIMEOUT /T 30```

no we can call the script from the batch with `Invoke-Expression` and can pass parameters to automate the whole process.
if prefered we can also remove the `Read-Host` questions from `param` and use `[switch]` instead. Now instead of typing the parameters like `-RemoveAdPlaceholder 'y'` we can just type `-RemoveAdPlaceholder` as a parameter and thats it. The `if ($RemoveAdPlaceholder -eq 'y')` changes than to simply `if ($RemoveAdPlaceholder)` which is equivalent to `if ($RemoveAdPlaceholder -eq $true)`

**Comment by Nuzair46** [comment]
@KUTlime what are your thoughts?

**Comment by KUTlime** [comment]
Actually, that is something which I have been thinking for a while. It is a reasonable next step. I will prepare PR.
