### ISSUE TITLE
.bat unfunctional on Windows 7

### ISSUE THREAD

**Issue by ThatTonybo** [mrpond/BlockTheSpot#323]
![image](https://user-images.githubusercontent.com/28176227/153691408-01283ccb-1053-4336-aa93-3f5e83e17669.png)

Windows 7 Ultimate, SP1

**Comment by Davoleo** [comment]
The automatic script only supports Windows 10 and higher (windows 7 support from MS has also recently ended anyways), I suggest to upgrade your operating system or apply the patch manually following the steps in the readme

**Comment by N4rsha** [comment]
> The automatic script only supports Windows 10 and higher (windows 7 support from MS has also recently ended anyways), I suggest to upgrade your operating system or apply the patch manually following the steps in the readme

I'm using windows 10, the script stopped working, it instantly auto-close when I open it

**Comment by ThatTonybo** [comment]
> The automatic script only supports Windows 10 and higher (windows 7 support from MS has also recently ended anyways), I suggest to upgrade your operating system or apply the patch manually following the steps in the readme

No worries. I use Windows 7 on my secondary machine as Windows 10 doesn't perform as well on it, but wasn't aware it was intentional that it didn't work on Windows 7. I already applied the manual patch and it works fine so no worries. 

Thank you :)
