### ISSUE TITLE
New Spotify premium button added

### ISSUE THREAD

**Issue by theliamking** [mrpond/BlockTheSpot#324]
Hello, 
not a big deal but Spotify added a Premium button that I just wanted to be let known. I also use a spicetify theme so it makes it even less visually pleasing to look at.
Could this be resolved with a BlockTheSpot update? 
Thanks everyone :)
![image](https://user-images.githubusercontent.com/99769726/154162803-04c0777f-cadd-4297-bc0e-ff64e28526b7.png)

**Comment by amd64fox** [comment]
Shows this banner if you [use this](https://github.com/amd64fox/SpotX) ?

**Comment by Nuzair46** [comment]
@amd64fox can you open a PR to this repo if its tested working on your side?

**Comment by amd64fox** [comment]
I initially don't have such a button, so for full confidence I need feedback from other users with this problem.

**Comment by christianavi** [comment]
> Shows this button if you [use this](https://github.com/amd64fox/SpotX) ?
Once I saw the Premium button, I uninstaleld Spotify and ran this. There is no Premium button now.

**Comment by svamplike** [comment]
> I initially don't have such a button, so for full confidence I need feedback from other users with this problem.

its also visible for me.
![image](https://user-images.githubusercontent.com/86647391/154811043-d562aaba-d3cc-4e43-a22c-423acd8117e4.png)

**Comment by amd64fox** [comment]
@svamplike 
Can you confirm that you used the bat file from [this repository](https://github.com/amd64fox/SpotX)?

**Comment by christianavi** [comment]
> @svamplike Can you confirm that you used the bat file from [this repository](https://github.com/amd64fox/SpotX)?

I did not use or download the batch file but used this on Powershell instead as described on that repository.
```ps
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1[](https://github.com/amd64fox/SpotX#uninstall)' | Invoke-Expression
```

**Comment by amd64fox** [comment]
@christianavi 
There isn't much difference 🙂

**Comment by christianavi** [comment]
> @christianavi There isn't much difference 🙂

I know. :)

**Comment by amd64fox** [comment]
I continue to test disabling this button, if you have it then try one of the methods below, please unsubscribe which one worked for you.

1. https://github.com/mrpond/BlockTheSpot/issues/324#issuecomment-1041120676

2. Try downloading and replacing the file manually `xpui.spa`

The client version should be `1.1.79.763`


- Navigate to `%APPDATA%/Spotify/Apps`
- First, make a backup of your `xpui.spa`
- Download [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/8103357/xpui.zip) and rename it to `xpui.spa`
- Replace the original `xpui.spa` file

**Comment by svamplike** [comment]
> @svamplike Can you confirm that you used the bat file from [this repository](https://github.com/amd64fox/SpotX)?

yes

**Comment by christianavi** [comment]
> > @svamplike Can you confirm that you used the bat file from [this repository](https://github.com/amd64fox/SpotX)?
> 
> uh the link u wrote is of SpotX, and the one i used is from this(BlockTheSpot) one.

Then you did not read the question and check the links. This does not help the author in troubleshooting at all.

**Comment by svamplike** [comment]
> > > @svamplike Can you confirm that you used the bat file from [this repository](https://github.com/amd64fox/SpotX)?
> > 
> > 
> > uh the link u wrote is of SpotX, and the one i used is from this(BlockTheSpot) one.
> 
> Then you did not read the question and check the links. This does not help the author in troubleshooting at all.

ahh sorry then, my bad.

**Comment by RichardLeblanc** [comment]
> 



> I continue to test disabling this button, if you have it then try one of the methods below, please post which one worked for you.
> 
>     1. [New Spotify premium button added #324 (comment)](https://github.com/mrpond/BlockTheSpot/issues/324#issuecomment-1041120676)
> 
> 
> Or
> 
>     2. Try downloading and replacing the file manually `xpui.spa`
> 
> 
> The client version should be `1.1.79.763`
> 
>     * Navigate to `%APPDATA%/Spotify/Apps`
> 
>     * First, make a backup of your `xpui.spa`
> 
>     * Download [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/8103357/xpui.zip) and rename it to `xpui.spa`
> 
>     * Replace the original `xpui.spa` file

I tested only the second method and it works perfectly.
In order:
1. Installed fresh Spotify 1.1.79.763.gc2965cdf
2. Replaced the files from chrome_elf.zip (from here)
3. Replaced the xpui.spa following the 2 method from above
4. I obviously have a free account

![hamburgherz](https://user-images.githubusercontent.com/47771443/155070067-869b7590-214b-4187-80f7-e93ae6899a95.png)

**Comment by amd64fox** [comment]
@RichardLeblanc 
Do you confirm that you had this button in the original Spotify client 1.1.79.763?
 <details>
<summary><small>Screenshot</small></summary><p>

![154162803-04c0777f-cadd-4297-bc0e-ff64e28526b7](https://user-images.githubusercontent.com/62529699/155073645-a53b1c5c-5c07-4e96-b173-6a304d537277.png)


</details>

**Comment by RichardLeblanc** [comment]
> 

Yes I do!

**Comment by RichardLeblanc** [comment]
> @RichardLeblanc Do you confirm that you had this button in the original Spotify client 1.1.79.763?
> Screenshot

Yes I do!

**Comment by amd64fox** [comment]
@RichardLeblanc 
@christianavi 
Thanks for the feedback
