### ISSUE TITLE
Spotify doesn't launch

### ISSUE THREAD

**Issue by AdrienCarbo** [mrpond/BlockTheSpot#329]
Hello,

### Describe the bug
I am using win10.
After a spotify update i wanted to repatch it with blockTheSpot. Sadly, during patching, i wrote "Y" at the "removing ad placeholder" which caused my spotify to not launch at all (probably because my blockthespot.bat wasn't up to date. Anyway, as i couldn't open spotify after the last patch. I uninstalled it via win10's settings and tried to reinstall it with the installer. It didn't work because at the end i had the same bug : spotify doesn't launch at all (before patching). I tried to run uninstall.bat (BlockTheSpot's one), reinstall spotify etc... Nothing worked
(all the reinstllation and desinstallations were done with lastest versions of .bat)

Any help on that ?
Thanks you

**Comment by Truman-NB** [comment]
I also ran into the problem just now. Then I try the manual installation and its ok.
Maybe the bat doesn't find the right path.

**Comment by Nuzair46** [comment]
are you having this problem if you press "Y" for removing the placeholder?

**Comment by Truman-NB** [comment]
it crashed whether i chose y or n

**Comment by Nuzair46** [comment]
Are you using the latest script from this repo?

**Comment by AdrienCarbo** [comment]
Thanks you for your answers.
I wasn't clear enough : even before the patch spotify doesn't launch at all. When i double click on it, the cursor indicate that something is processing and then nothing happens.
S

**Comment by AdrienCarbo** [comment]
I also tried to run spotify as admin, just to be sure, but nothing happened too

**Comment by AdrienCarbo** [comment]
On my win10, spotify doesn't even run in the background as a process.
I tried to uninstall Spotify with advanced tools (Revo uninstaller) but i got no success : on reinstallation it still fails to run

**Comment by Nuzair46** [comment]
This seems like an issue with Spotify and I can't help you with it here. Please contact Spotify support.
