### ISSUE TITLE
Move to Gitlab? (or elsewhere)

### ISSUE THREAD

**Issue by HostFat** [mrpond/BlockTheSpot#33]
As someone advised here, maybe it can be a good idea

https://www.reddit.com/r/Piracy/comments/fs88qg/new_blockthespot_spotify_ad_blocker_v051_by_mrpond/fm0zj6j/

Maybe even on IPFS can be a good idea :)

Can this be useful? https://fleek.co

**Comment by mrpond** [comment]
First, Thanks for this useful information 
O_o I don't think it will get DMCA.
my project are (chromium) chrome_elf.dll replacement. 
with some injection into windows dll.
It didn't mess with DRM like other project e.g. xspotify,
only ads block.

But I will think about it. :P
