### ISSUE TITLE
Block The Spot Still having inconsistent issues with latest version

### ISSUE THREAD

**Issue by HeIp** [mrpond/BlockTheSpot#330]
Both running the bat file and manual process are failing me on windows 10.
Spotify manage to run the background processes but never opens up.

**Comment by AmandaPeach** [comment]
i got the same issue about it. i ran blockthespot n lastest version and with downgraded version and the spotify doesnt open up.

**Comment by Shrey-Jaiswal** [comment]
same here. spotify doesnt open when i run blockthespot.bat. im on windows 10 with the latest spotify installed and using latest script

**Comment by Nuzair46** [comment]
Are you guys using the latest script?

**Comment by mrpond** [comment]
try manual install if you got problem, each people computer got varies configuration/environment.

**Comment by AmandaPeach** [comment]
i did but no success, im using SpotX and works fine for me. No crash, no ads and no invisible ads

**Comment by Nuzair46** [comment]
@KUTlime , I think that the maximal version in the script is causing this issue. lets remove that feature so if user is using the latest Spotify dont reinstall.
Only if Spotify version is below the unsupported version, install the latest. 
Let me know your thoughts.

**Comment by SammCheese** [comment]
> @KUTlime , I think that the maximal version in the script is causing this issue. lets remove that feature so if user is using the latest Spotify dont reinstall.
> Only if Spotify version is below the unsupported version, install the latest. 
> Let me know your thoughts.

PLEASE. 
My suggestion on this was to remove the Max Version from it, and instead ask the User via the script if the patch was successful after Spotify starts (aka. No "There was an error starting Spotify" on startup)
If it was successful, just close the script, if it wasn't, it restores previously backed up Spotify files.

E.g

```
>Starting Spotify...

>Was the Patch Successful? (Y/N)

Y

>Restoring backed up stock chrome-elf.dll
```

**Comment by KUTlime** [comment]
> > @KUTlime , I think that the maximal version in the script is causing this issue. lets remove that feature so if user is using the latest Spotify dont reinstall.
> > Only if Spotify version is below the unsupported version, install the latest.
> > Let me know your thoughts.
> 
> PLEASE. My suggestion on this was to remove the Max Version from it, and instead ask the User via the script if the patch was successful after Spotify starts (aka. No "There was an error starting Spotify" on startup) If it was successful, just close the script, if it wasn't, it restores previously backed up Spotify files.
> 
> E.g
> 
> ```
> >Starting Spotify...
> 
> >Was the Patch Successful? (Y/N)
> 
> Y
> 
> >Restoring backed up stock chrome-elf.dll
> ```

Not good approach.

The script can detect if the Spotify client is running or not. We don't need to ask user for that.

**Comment by KUTlime** [comment]
> @KUTlime , I think that the maximal version in the script is causing this issue. lets remove that feature so if user is using the latest Spotify dont reinstall. Only if Spotify version is below the unsupported version, install the latest. Let me know your thoughts.

Could you, please, elaborate on what is the real problem here? I see what is the symptom, but I don't see the cause. 🤷🏿‍♀️

**Comment by SammCheese** [comment]
> > > @KUTlime , I think that the maximal version in the script is causing this issue. lets remove that feature so if user is using the latest Spotify dont reinstall.
> > > Only if Spotify version is below the unsupported version, install the latest.
> > > Let me know your thoughts.
> > 
> > 
> > PLEASE. My suggestion on this was to remove the Max Version from it, and instead ask the User via the script if the patch was successful after Spotify starts (aka. No "There was an error starting Spotify" on startup) If it was successful, just close the script, if it wasn't, it restores previously backed up Spotify files.
> > E.g
> > ```
> > >Starting Spotify...
> > 
> > >Was the Patch Successful? (Y/N)
> > 
> > Y
> > 
> > >Restoring backed up stock chrome-elf.dll
> > ```
> 
> Not good approach.
> 
> The script can detect if the Spotify client is running or not. We don't need to ask user for that.


Its not about if spotify starts but if it actually works. 

![image](https://user-images.githubusercontent.com/52699291/156670401-2fd1cdd1-992c-42a9-9f7d-84eeccebe4c6.png)

**Comment by Nuzair46** [comment]
I will track this in a new issue.

**Comment by Nuzair46** [comment]
will be tracked with #334
