### ISSUE TITLE
App crashing after 1 minute of playback on updating to the latest version

### ISSUE THREAD

**Issue by anuj-singh14** [mrpond/BlockTheSpot#336]
Hello team,

I updated the Spotify Desktop app by running **BlockTheSpot.bat** script file today. Since then, the app has been crashing approximately after 1 minute of playing any song. This has started happening right after updating to the current latest version. Please have a look. I am currently running **Windows 10**.

TIA

**Comment by Nuzair46** [comment]
Are you using the latest script? if not, download it from the repo and run again.

**Comment by anuj-singh14** [comment]
Yeah tried it, the issue persists.

**Comment by Nuzair46** [comment]
Uninstall Spotify and run this on powershell
```ps
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1' | Invoke-Expression
```

**Comment by anuj-singh14** [comment]
Working fine now. Thanks a ton!
