### ISSUE TITLE
Causes spotify to simply not work.

### ISSUE THREAD

**Issue by TheOmegaSystem** [mrpond/BlockTheSpot#337]
Not working, causes spotify to "not respond"
![image_2022-03-09_072127](https://user-images.githubusercontent.com/77907310/157440956-c5c0f4a6-2514-486d-90ce-61f15b1fb2f7.png)

**Comment by Davoleo** [comment]
Try killing any spotify process that is active in background via Task Manager and then start spotify again

**Comment by TheOmegaSystem** [comment]
tried that, doesn't work.

**Comment by fun4stuff** [comment]
Same here. Block the spot hasn't been working for about a week now. I think it needs to be updated

**Comment by Nuzair46** [comment]
Uninstall Spotify and use the latest bat script from the repo.
Make sure you download the latest script as the methods have been changed.

**Comment by TheOmegaSystem** [comment]
I did both multiple times

**Comment by Nuzair46** [comment]
@TheOmegaSystem Please provide the Spotify version, Screenshot of Spotify directory.

**Comment by TheOmegaSystem** [comment]
![image](https://user-images.githubusercontent.com/77907310/157447679-ec79f4bd-9771-4f7a-95bb-9a2692be3d02.png)
![image](https://user-images.githubusercontent.com/77907310/157447719-dde82bfd-e92b-4569-8bc7-d7ff7690295b.png)

**Comment by TheOmegaSystem** [comment]
instead of using BlockTheSpot i settled for SpiceTify and an ad blocker extension.

**Comment by fun4stuff** [comment]
So for me, I got it working by using the bat file. I had been doing it manually by adding the chrome_elf.dll and config.ini to %appdata%/Spotify, which used to work but hasn't the last week or so. I had been trying this on work computers where I'm not an administrator. The bat file worked though.

**Comment by TheOmegaSystem** [comment]
excuse you? it's not.

**Comment by TheOmegaSystem** [comment]
> So for me, I got it working by using the bat file. I had been doing it manually by adding the chrome_elf.dll and config.ini to %appdata%/Spotify, which used to work but hasn't the last week or so. I had been trying this on work computers where I'm not an administrator. The bat file worked though.

This is not the case for me, both ways to install DO NOT WORK

**Comment by Nuzair46** [comment]
@TheOmegaSystem , Can you please share the screenshot of the Spotify directory after running the latest BlockTheSpot.bat?

**Comment by TheOmegaSystem** [comment]
> @TheOmegaSystem , Can you please share the screenshot of the Spotify directory after running the latest BlockTheSpot.bat?

uhm, it appears to be working fine now, ig i'll close this issue.
