### ISSUE TITLE
Cross platform adblocker solution

### ISSUE THREAD

**Issue by itsmeboy0** [mrpond/BlockTheSpot#338]
Many people have been asking for a Mac or Linux version in the issues. You should add a note about this [Adblock](https://github.com/CharlieS1103/spicetify-extensions/tree/main/adblock) Spicetify extension in the Readme as it works everywhere as long as Spicetify is installed.

**Comment by Nuzair46** [comment]
We will display it on our discord as we want to keep this repo clean for windows only.
