### ISSUE TITLE
Auto-updating

### ISSUE THREAD

**Issue by ddke1** [mrpond/BlockTheSpot#345]
does it auto update? if so is there a way to turn that off??

**Comment by H3lix-Fire** [comment]
Look at the issue I just submitted, it should help you. (:
Here's the link incase it gets closed, or you can't find it, or something else.
[How to prevent auto update (:](https://github.com/mrpond/BlockTheSpot/issues/346 "How to prevent auto update")

**Comment by Nuzair46** [comment]
we dont recommend disabling it.
