### ISSUE TITLE
Block spotify updates

### ISSUE THREAD

**Issue by anyu7** [mrpond/BlockTheSpot#347]
Question: Is it possible to prevent the update with the command icacls "%localappdata%\Spotify\Update" /deny "%username%":W

**Comment by anyu7** [comment]
Maybe solved, replace the "Update" folder with the "Update" file. Permission settings as shown in the figure。
![截图_20223020023023](https://user-images.githubusercontent.com/36684854/159134076-7c9533cd-8638-4f11-8170-0180e580339c.png)
![截图_20223020023034](https://user-images.githubusercontent.com/36684854/159134079-572b7378-7027-4b84-848c-08e9c0b9590d.png)

**Comment by amd64fox** [comment]
They don't want to use Spotify update blocker here, [try this](https://github.com/amd64fox/SpotX)

**Comment by KUTlime** [comment]
@Nuzair46 I see that three different people asked for auto-update disable #345 #346. We were discussing this in our last PR. How about open a new issue where we can discuss this, link possible duplicates for explanation, and maybe solve this for good?

**Comment by Nuzair46** [comment]
> @Nuzair46 I see that three different people asked for auto-update disable #345 #346. We were discussing this in our last PR. How about open a new issue where we can discuss this, link possible duplicates for explanation, and maybe solve this for good?

Sure. Please open a new issue.
