### ISSUE TITLE
BlockTheSpot.bat dont download spotify proprely

### ISSUE THREAD

**Issue by Rootzpower** [mrpond/BlockTheSpot#35]
![image](https://user-images.githubusercontent.com/15384112/78344290-153ab500-7594-11ea-82f4-cd213790afc7.png)
![image](https://user-images.githubusercontent.com/15384112/78344302-1bc92c80-7594-11ea-92ae-31324df585d0.png)
![image](https://user-images.githubusercontent.com/15384112/78344311-1ec41d00-7594-11ea-81ee-3b86e0752d78.png)

**Comment by rednek46** [comment]
can you tell me exactly how you run the bat file?

**Comment by Rootzpower** [comment]
as usual by cmd

**Comment by Davoleo** [comment]
is it different from running it by simply double clicking the bat file?

**Comment by rednek46** [comment]
> as usual by cmd

you should only need to double click the bat file. it looks like you copied from the script or tried to do something else. the script is actually written in powershell with a batch code that invokes powershell.

**Comment by Rootzpower** [comment]
Yes i know that.
Can you test uninstall your spotify i try run script

**Comment by rednek46** [comment]
i just tested the script. it works fine.

**Comment by rednek46** [comment]
i just tested the script. it works fine.

> Yes i know that.
> Can you test uninstall your spotify i try run script

**Comment by rednek46** [comment]
i just tested the script. it works fine.

> Yes i know that.
> Can you test uninstall your spotify i try run script

i just ran the script and it works fine.

**Comment by rednek46** [comment]
i just tested the script. it works fine.

> Yes i know that.
> Can you test uninstall your spotify i try run script

i just ran the script and it works fine.

**Comment by rednek46** [comment]
clone [this](https://github.com/rednek46/BlockTheSpot/tree/old-batch) old batch script.

**Comment by rednek46** [comment]
> Yes i know that.
> Can you test uninstall your spotify i try run script
@Rootzpower did you run the script inside the zip file without extracting?
that may cause an issue since the batch file creates a powershell file the same directory which will not work if the batch is inside the zip file.

**Comment by Rootzpower** [comment]
Im sorry. It was a problem with windows installer file. Just repair and everything works fine.

**Comment by Rootzpower** [comment]
Can i make a suggestion?
I create an task to run BlockTheSpot.bat every day.
Can you add a function on main script to update herself if exist batch more recent before patch?

**Comment by rednek46** [comment]
> Can i make a suggestion?
> I create an task to run BlockTheSpot.bat every day.
>
I don't get it what you meant by task.
>
> Can you add a function on main script to update herself if exist batch more recent before patch?
>Actually the script hasn't changed its basic functionality from its initial release. only the some minor performance changes. And I don't think its gonna change much either. For the moment this current batch file is OK for many spotify updates unless the name of the assets to patch changes or if spotify decides to go with a different installation location.

**Comment by Rootzpower** [comment]
> I don't get it what you meant by task.

Taskscheduler to run BlockTheSpot.bat

**Comment by rednek46** [comment]
> > I don't get it what you meant by task.
> 
> Taskscheduler to run BlockTheSpot.bat

Why do you need to do that? The batch needs to be run only when if spotify gets updated or reinstalled. Simply Double clicking works right?
