### ISSUE TITLE
Spotify glitching in first few seconds after applying blockthespot

### ISSUE THREAD

**Issue by Maxx058** [mrpond/BlockTheSpot#350]
Hey peeps, ive been facing an issue in spotify desktop version for a week, wherein anytime i play a song it glitches randomly during the first 10 seconds and gets stuck and plays for 3 times then plays normally for the rest of the song. would be so helpful if anybody has a fix for this issue.

also i checked the issues and it was previously mentioned in it but it was locked due to the author saying its related to spotify, but i tried spotify before applying the bat file and it worked fine and it only occurs after using it, so if we can have a fix, that would be appreciated. 

thanks

**Comment by CoolGuyMK** [comment]
Check #348
