### ISSUE TITLE
Lag opening playlists

### ISSUE THREAD

**Issue by SirGryphin** [mrpond/BlockTheSpot#356]
Spotify for Windows
1.1.81.604.gccacfc8c

Not sure if it's just my computer or something else, just thought I would ask here.

If sticking between playlist or open large ones it lags for a long time before opening and sometimes when searching spotify will get stuck and i will have to relaunch. Never had this problem before latest Spotify version. Is anyone else having some thing?

**Comment by Nuzair46** [comment]
This is not a place for Spotify support. Please contact Spotify support for issues related to Spotify app.
