### ISSUE TITLE
Update on issue #348 / After opening Spotify 1st song lag 1/2 frame on first 1-5 sec

### ISSUE THREAD

**Issue by AcelynnBen** [mrpond/BlockTheSpot#358]
It seem that the problem is related to the lyrics, most songs without lyrics don't bug out while the ones with it do.
when the song keeps repeating, its Spotify trying to sync the lyrics with the song, you can notice this problem if u pause the song mid freeze while looking at the Lyrics

If there is a way to disable the lyrics through commands i think it should fix this problem
But officially lyrics cannot be disable

Currently using windows 10

**Comment by Bec-de-Xorbin** [comment]
You can download the latest properly working version here: https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.80.699.gc3dac750-9.exe

One way to block automatic updates is through hosts file. Add this `0.0.0.0 upgrade.scdn.co` in hosts manually or type this in cmd as administrator:
`echo 0.0.0.0 upgrade.scdn.co>>"%windir%\System32\drivers\etc\hosts"`

Remove that line from hosts if you want to upgrade again.

**Comment by Bec-de-Xorbin** [comment]
@Nuzair46 @AcelynnBen
Bug fixed in latest version. Get it here: https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.83.954.gd226dfe8-18.exe

**Comment by AcelynnBen** [comment]
thanks
