### ISSUE TITLE
SOLUTION for Track Stuttering For Few Secs !

### ISSUE THREAD

**Issue by alienfxfiend** [mrpond/BlockTheSpot#361]

**Comment by alienfxfiend** [comment]
Nevermind, it happened again.

**Comment by amd64fox** [comment]
This has been fixed in version `1.1.83.954`-`1.1.83.956`
[Upgrade.](https://cutt.ly/8EH6NuH)

**Comment by alienfxfiend** [comment]
Thank you, is there a separate link to x64 version ?
