### ISSUE TITLE
Random Ads playing

### ISSUE THREAD

**Issue by Fremontcat0607** [mrpond/BlockTheSpot#364]
When I'm listening sometimes ads play with no apparent reason. This happens completely randomly.

**Comment by Nuzair46** [comment]
Please follow the bug report. We are not able to replicate this issue. Meaning that you are not following the instructions correctly or using an old unsupported version. Please reopen this issue with the detailed report with the help of the template.

**Comment by fellypsantos** [comment]
this happened to me now, but I noticed that spotify updated while launching, this probably overited the modified files that prevent ads to load, restoring original ones.

just run the custom installer again (.bat file or PowerShell command) it worked to me, no more ads.
