### ISSUE TITLE
Black bar in the new version

### ISSUE THREAD

**Issue by Francy-2002** [mrpond/BlockTheSpot#370]
![Screenshot (4)](https://user-images.githubusercontent.com/104710411/166135220-11932375-f45a-4ccf-abc5-2cab80fd80a3.png)
Black bar appeared in the new version of Spotify. I'm using Spotify for Windows 1.1.84.716.gc5f8b819

**Comment by Nuzair46** [comment]
Script is not updated for that version yet.

**Comment by KUTlime** [comment]
I have the same version and I do **not** have the black bar there. 🤷🏿‍♀️

**Comment by Nuzair46** [comment]
> I have the same version and I do **not** have the black bar there. 🤷🏿‍♀️

Then they more likely missed to press Y when asked. Please confirm this and close if its solved.

**Comment by Francy-2002** [comment]
I use the manual method and, up to version 1.1.83, I haven't had any problems.

**Comment by Nuzair46** [comment]
Only the script supports the removal of the black bar.
