### ISSUE TITLE
[Request] Method to remove banner popup

### ISSUE THREAD

**Issue by debmaj2** [mrpond/BlockTheSpot#371]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

There's an image popup coming up on starting app. Any effort to track this and patch is appreciated. P.S. Not a Bug

![image](https://user-images.githubusercontent.com/22155707/166231849-cf2cadd9-666d-4e98-ae10-f33ae9bbf68c.png)

**Comment by jonjbm** [comment]
It doesn't just come up when starting the app. After I close it the popup, it pops back up a few minutes later without fail. Very annoying.

**Comment by amd64fox** [comment]
You can test [this](https://github.com/amd64fox/SpotX)

**Comment by AD2011** [comment]
Yeah, I am facing the issue too. It appears either after starting the app or after 30 mins of listening. After closing the pop up, the banner doesn't appear again

**Comment by Nuzair46** [comment]
Is this issue still occuring?

**Comment by amd64fox** [comment]
It is a pity that there was no feedback from users.

[here the same problem](https://github.com/mrpond/BlockTheSpot/issues/284) was closed, there I solved it by changing the experimental functions, in particular, this promotional offer is affected by `quicksilver in-app messaging modal` function.

You can disable this feature yourself, [this instruction](https://github.com/amd64fox/SpotX/discussions/47) will help you or wait for me, I will create a PR when I return from vacation.

**Comment by AD2011** [comment]
No,

**Comment by debmaj2** [comment]
> Is this issue still occuring?

It is not occurring  on my latest Spotify version anymore.
```
 Spotify for Windows
1.1.86.857.g3751ee08
```

However I guess they might use the same method to show a promo later on. Would wait for @amd64fox 's PR when he's back :)

**Comment by Nuzair46** [comment]
closing as this issue is not occuring right now. Please reopen if it does.
