### ISSUE TITLE
upgrade button is not removed after the new update

### ISSUE THREAD

**Issue by adityasajja** [mrpond/BlockTheSpot#373]

**Comment by worldsdream** [comment]
Confirmed

**Comment by Nuzair46** [comment]
Version?

**Comment by worldsdream** [comment]
Spotify for Windows
1.1.85.895.g2a71e1b8

**Comment by worldsdream** [comment]
@Nuzair46 I hope you can download that version and reproduce it. Let me know if you release a new version or want me to test.

**Comment by chuchigod** [comment]
same, after the new update i ran the script as usual without the '-UpdateSpotify' but the upgrade button and the ads stayed.
I tried again with the '-UpdateSpotify' but it just rolled back to previous version, then spotify auto-updated again and again the same issue.

**Comment by worldsdream** [comment]
I can confirm that the Upgrade button is removed after the fix. Thanks.
