### ISSUE TITLE
Banner on old lyric UI

### ISSUE THREAD

**Issue by agentmerlot1412** [mrpond/BlockTheSpot#376]
Spotify hasn't updated the lyric UI to the new one for my account, tested on both app and webapp.
The banner for ads appears but stays blank in this UI. 
Latest version: Spotify for Windows - 1.1.85.895.g2a71e1b8

![image](https://user-images.githubusercontent.com/58659715/168407754-2279ad40-023b-49f8-81e6-1dac436e493a.png)

**Comment by AmbassadorLaZer** [comment]
Same for me

**Comment by amd64fox** [comment]
test

- Navigate to `%APPDATA%/Spotify/Apps`
- First, make a backup of your `xpui.spa`
- Download [xpui.zip](https://github.com/mrpond/BlockTheSpot/files/8692058/xpui.zip) and rename it to `xpui.spa`
- Replace the original `xpui.spa` file

**Comment by AmbassadorLaZer** [comment]
Banner is hidden after replacing the xpui file.

**Comment by amd64fox** [comment]
thanks for the feedback, I'll create a PR with this fix a little later

**Comment by AmbassadorLaZer** [comment]
No problem!

**Comment by agentmerlot1412** [comment]
Yep it works
