### ISSUE TITLE
Sidebar Icons Drift

### ISSUE THREAD

**Issue by 14142000** [mrpond/BlockTheSpot#379]
![image](https://user-images.githubusercontent.com/3375830/168855408-b0967daa-ab1e-4f58-8516-becda7c74500.png)
![image](https://user-images.githubusercontent.com/3375830/168855737-2845d628-e33f-4cca-a209-70c942a449d8.png)

New visual issue where the sidebar icons drift off screen

**Comment by Nuzair46** [comment]
Looks like you are using a Spicetify theme. Please submit the issue in the respective theme repo.

**Comment by 14142000** [comment]
Oh I'm so sorry I got my tabs confused, since I was re-downloading all my spotify stuff
