### ISSUE TITLE
How do I Auto Answer “Yes" to the two questions when using BlockTheSpot.bat?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [mrpond/BlockTheSpot#381]
May you please tell me how I can skip the pop-up prompts when I run the .bat? I just want to "always" type "y" and "y" and I feel like I run this at least once a week.

Hope all is well with you, cheers!

![image](https://user-images.githubusercontent.com/1291364/171286088-e0e18200-c950-463f-b999-807b9e8cbb82.png)

**Comment by Nuzair46** [comment]
https://github.com/mrpond/BlockTheSpot#fully-automated-installation-via-powershell

**Comment by elhertz** [comment]
How do you answer "n" instead?
