### ISSUE TITLE
shuffle perma enabled

### ISSUE THREAD

**Issue by CARLOVVS** [mrpond/BlockTheSpot#385]
![image_2022-07-04_132305067](https://user-images.githubusercontent.com/108696447/177213209-ac54695b-ff58-4679-bed9-7a30d9ac6d08.png)
started up the app today and got welcomed with this popup, have tried a couple of fix attempts including reinstalling current version but to no avail except for going back to an older version

**Comment by Saucy1423423** [comment]
Same thing happened to me fuck spotify

**Comment by amd64fox** [comment]
@Saucy1423423 
You can use this for now https://github.com/amd64fox/SpotX
And please close your duplicate issue
