### ISSUE TITLE
Script not installing the latest version anymore

### ISSUE THREAD

**Issue by lfmnovaes** [mrpond/BlockTheSpot#386]
Using this script from README, it is not installing the latest version of Spotify anymore. So every time you restart your Spotify, it updates automatically but without the fix, and you need to rerun the script.
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify -RemoveAdPlaceholder"
```
![image](https://user-images.githubusercontent.com/13990675/178077138-fdaeec06-ad65-469d-9c91-3aa21840a04a.png)

Edit: blocking the updates with this script helped in my case: https://github.com/amd64fox/Rollback-Spotify

**Comment by Projeet1002** [comment]
So should we install this bat file or not and is it safe?

**Comment by amd64fox** [comment]
And that BTS does not work well with version 1.1.89?
Why are you so afraid to upgrade?

**Comment by lfmnovaes** [comment]
> And that BTS does not work well with version 1.1.89? Why are you so afraid to upgrade?

Afraid? That was not the case. The latest version was just not being installed with the automated version but it probably works when manually installing the latest version and applying the BTS files after.

**Comment by amd64fox** [comment]
The script downloads the latest version from here `https://download.scdn.co/SpotifyFullSetup.exe`
But this link may not be the latest version, since the new version of Spotify is distributed in waves, it all depends on your region.

Therefore, it is necessary that some time pass so that the latest version is available for everyone at this link.

Or use the simplest option, the one you did, just block updates.

**Comment by lfmnovaes** [comment]
I see, makes sense.
Still, this issue can be helpful to some other ppl that are experiencing issues (not exactly the same as this one) with Spotify lately.

**Comment by Nuzair46** [comment]
There is nothing much we can do about this. Spotify makes the update channel more latest before the release channel
