### ISSUE TITLE
error message when opening blockthespot 

### ISSUE THREAD

**Issue by unknxnn** [mrpond/BlockTheSpot#394]
Invoke-WebRequest : 404: Not Found
At line:1 char:85
+ ... pe]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
![image_2022-07-12_224733506](https://user-images.githubusercontent.com/109197466/178652798-8e468157-b9a0-40ec-8c6b-6d0ee809e9b3.png)

**Comment by heivid** [comment]
I´m having the same issue. I had no idea what happen.

**Comment by idenc** [comment]
same issue. bump
