### ISSUE TITLE
404 error in Invoke-WebRequest

### ISSUE THREAD

**Issue by gampboi93** [mrpond/BlockTheSpot#395]
`Invoke-WebRequest : 404: Not Found
At line:1 char:85
+ ... pe]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

Getting this error when attempting to use the bat file

**Comment by TremblayA** [comment]
Yep, got the same: 
Invoke-WebRequest : 404: Not Found
At line:1 char:85
+ ... pe]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by lwrck** [comment]
try the "Manual installation" for me worked
