### ISSUE TITLE
[ANNOUNCEMENT] Change to BlockTheSpot AutoInstaller. Suggestion: Improve communication when there are breaking changes

### ISSUE THREAD

**Issue by juanmalunatic** [mrpond/BlockTheSpot#399]
Thanks for your hard work on consistently patching Spotify's ads and interacting with the community.

With the latest changes on BlockTheSpot's architecture, many users (me included) were left wondering why the program 404'd unexpectedly if there is no new release. The general confusion this caused can be seen in the multiple issues created in this same repo.

My suggestion is: whenever you drop a breaking change, put a disclaimer at the top of the repo's readme, with some short context and maybe a few FAQ-like lines. Something like "Starting at july 2022, BlockTheSpot has been integrated with project X and the installation procedure requires running the following command. If you were using BlockTheSpot.bat, please consider switching to method blabla". This will probably reduce the administrative efforts and the redundant questions.

**Comment by Nuzair46** [comment]
Yeah. Sorry about this and it was a rather quick change and we didn't convey much about it anywhere else other than the Discord server. The readme was updated. I think the worst is now over and most of the users have migrated to the new change. Anyway I'll keep this issue open for some more time.
