### ISSUE TITLE
Songs won't play

### ISSUE THREAD

**Issue by omfgdahoe** [mrpond/BlockTheSpot#4]
**Describe the bug**
The playlists doesn't show the songs that are in it, and I can't play anything if I try to play a song after searching it.
https://i.imgur.com/obx7SVC.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spotify Version: 1.1.15.448.g00fba0e3

**Additional context**
https://pastebin.com/r6ivdACr

**Comment by mrpond** [comment]
![image](https://user-images.githubusercontent.com/18654771/65365550-7d532a80-dc44-11e9-87c2-e36b21f75a95.png)
Hi, I can't reproduce it.

try download latest dll v0.23

**Comment by dhinakg** [comment]
I can reproduce the song not playing after search issue. but not the playlist issue. I'm also having songs randomly stop playing, stuck at 0:00. Usually skipping to the next song and going back works, but sometimes I have to just go to the next song. It was working fine recently with the latest DLL (7d9f3fe6fb57a7bfb460bc610acb9e19bb1f2928) but just started again today.

**Comment by mrpond** [comment]
Hi which song/playlist you had problem, 
I'll make a logging dll for you guys to help me test tonight(GMT+8)

**Comment by omfgdahoe** [comment]
Alright guys, i finally found the stupid fucking mistake...
I had 0.0.0.0 spclient.wg.spotify.com in my host file probally automatically added from another blocker i had used once before.

**Comment by dreamco3d** [comment]
> Alright guys, i finally found the stupid fucking mistake...
> I had 0.0.0.0 spclient.wg.spotify.com in my host file probally automatically added from another blocker i had used once before.

Although this is as workaround, the same error exists even without any host entries. The weird thing is that spotify behaved ok in my office (Win 10) but not at home (Win 8.1). I will try to log back in on Monday and report the results.

**Comment by mrpond** [comment]
@dhinakg I don't know what cause problem on your, here is a test version
if you still had problem with this dll. it is your computer fault.
[chrome_elf_test.zip](https://github.com/mrpond/BlockTheSpot/files/3638682/chrome_elf_test.zip)

**Comment by dreamco3d** [comment]
> @dhinakg I don't know what cause problem on your, here is a test version
> if you still had problem with this dll. it is your computer fault.
> [chrome_elf_test.zip](https://github.com/mrpond/BlockTheSpot/files/3638682/chrome_elf_test.zip)

Actually i deleted my post as soon as i discovered i also had that entry on my hosts file too. Now its working perfectly!! Should i use your fix though?

**Comment by dhinakg** [comment]
Seems to be fixed.

**Comment by mrpond** [comment]
ok download v0.24 fixed, thank you guys.
