### ISSUE TITLE
Now you can't even download the chrome_elf.zip file w/o windows defender blocking it

### ISSUE THREAD

**Issue by MasicoreLord** [mrpond/BlockTheSpot#40]
**Describe the bug**
Chrome claims virus detected, and then Windows Defender comes up saying it detected a "threat"
I used to be able to at least download the adblocker, but now the av seems to catch it at download.

**Comment by rednek46** [comment]
> **Describe the bug**
> Chrome claims virus detected, and then Windows Defender comes up saying it detected a "threat"
> I used to be able to at least download the adblocker, but now the av seems to catch it at download.

This is a false positive and please allow chrome_elf.dll within Microsoft Defender. This will prevent any future blocking. @mrpond has notified MS Defender about this. Hopefully it'll be fixed soon.

**Comment by mrpond** [comment]
Hi, please try again I already fix it in 2020.04.21 release.
