### ISSUE TITLE
block the spot some kind of error pls help

### ISSUE THREAD

**Issue by mrzaydjawad** [mrpond/BlockTheSpot#401]
![image](https://user-images.githubusercontent.com/95502102/180142788-bdcad10f-ddfe-4e80-bea0-ed4245fdde13.png)

**Comment by amd64fox** [comment]
I answered you in the discord, did you decide to duplicate here just in case? 😂

**Comment by mrzaydjawad** [comment]
> I answered you in the discord, did you decide to duplicate here just in case? 

kinda awkward but i can't log in to the discord account linked with this account

**Comment by mrzaydjawad** [comment]
thanks for the help
