### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by TrixySa** [mrpond/BlockTheSpot#402]
I'm trying to use blockthespot, I have been using it for a while, but now I'm getting this error and I tried doing everything but it doesn't seem to wanna work. 

Error in the bat file is 
"Invoke-WebRequest : 404: Not Found
At line:1 char:4
+ & {Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent. ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand"

![unknown](https://user-images.githubusercontent.com/109800970/180435718-623bf715-36df-44b1-aea1-612aca7edc45.png)

**Comment by r3lativo** [comment]
Same here

**Comment by Nuzair46** [comment]
duplicate #396
