### ISSUE TITLE
Experimental features of SpotX are not included

### ISSUE THREAD

**Issue by unofficialdxnny** [mrpond/BlockTheSpot#403]
### The Bug
`Experimental features of SpotX are not included`
idk why `Experimental features of SpotX are not included` for my spotify please help

**Comment by amd64fox** [comment]
Use "Usual installation" from the [SpotX](https://github.com/amd64fox/[SpotX](https://github.com/amd64fox/SpotX)) repository
Also please use the README before opening the issue, there is enough information
