### ISSUE TITLE
spotxbasic not working

### ISSUE THREAD

**Issue by smellywaffles** [mrpond/BlockTheSpot#406]
Found outdated version of Spotify

Automatic update to the recommended version

Downloading and installing Spotify 1.1.91.824
Please wait...

Error downloading SpotifySetup.exe
ScriptHalted

Will re-request in 5 seconds...

Error again
ScriptHalted

Check your network settings and run the installation again

Script is stopped
Press Enter to continue...:
Press any key to continue . . .
![image_2022-08-03_010718545](https://user-images.githubusercontent.com/110492890/182459008-03f05498-40bd-490c-978f-776f01a51485.png)

**Comment by amd64fox** [comment]
Perform a clean install as described [here](https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#i-have-an-error--bug--strange-client-behavior-what-can-i-do-)

**Comment by smellywaffles** [comment]
i did try it but it didnt seem to help

**Comment by smellywaffles** [comment]
![Uploading image.png…]()

**Comment by amd64fox** [comment]
Drop your hosts file here, located here:
`%WinDir%\System32\Drivers\Etc\`
