### ISSUE TITLE
need some help with this dont know if its a bug or if im doing something wrong.

### ISSUE THREAD

**Issue by rackzrackzrackz** [mrpond/BlockTheSpot#407]
i keep getting this issue 

A parameter cannot be found that matches parameter name 'exp_off'.
At line:1716 char:104
+ ... ended_over -podcasts_on -cache_off -block_update_off -exp_off -start_ ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound
![file](https://user-images.githubusercontent.com/110570286/182714446-6a4de8f3-afec-4e49-8e54-8cb4ed44ae12.PNG)

**Comment by Mrfunreal** [comment]
you need to use the new powershell installer script found on the readme.
