### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by edbaldwin122** [mrpond/BlockTheSpot#408]
![image](https://user-images.githubusercontent.com/110117136/182906128-ae9c3a60-e0ec-4cb0-bf3f-54f8cfee52a4.png)

**Comment by juanmalunatic** [comment]
Try running this instead in Powershell with admin rights:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -confirm_uninstall_ms_spoti -confirm_spoti_recomended_over -podcasts_on -cache_off -block_update_off -exp_standart -hide_col_icon_off -start_spoti"
```
(This is taken from the README. In case you don't trust my snippet copy it directly from there :D)

The installation method seems to have changed: the .bat method no longer works.

**Comment by abys72** [comment]
Thanks
