### ISSUE TITLE
404 error in the software

### ISSUE THREAD

**Issue by dhruv1946** [mrpond/BlockTheSpot#409]
### Important
- Issue related to AutoInstaller should be opened at [SpotX](https://github.com/amd64fox/SpotX)

---
### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:
Can't use the software at all. It throws a 404 error [I use windows 11]
Zip and attach the log file.
[BlockTheSpot-2021.10.29.44.zip](https://github.com/mrpond/BlockTheSpot/files/9332666/BlockTheSpot-2021.10.29.44.zip)

---

 - You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - You uninstalled Spotify and just ran [SpotX](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Basic.bat) and is still having issues.
 - You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
  - You enabled logging by editing config.ini `set log = 1`.
 -  Make sure whether an issue related yours is already open or not.
 -  Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.

**Comment by dhruv1946** [comment]
![image](https://user-images.githubusercontent.com/111212544/184521760-79b069d8-d1b7-49ef-bfff-e6228f51a828.png)

This is what it looks like

**Comment by Nuzair46** [comment]
get the latest script
