### ISSUE TITLE
Powershell install stopping

### ISSUE THREAD

**Issue by ORB-Aerospace911** [mrpond/BlockTheSpot#410]
When I execute the PowerShell, Spotify closes and powershell just stays the same.
<img width="722" alt="spotifyadblocker" src="https://user-images.githubusercontent.com/79132854/184675287-3d7209f5-de56-412e-94c6-5339a5726153.PNG">

**Comment by ShatterinSpider** [comment]
Got something similar too

![image](https://user-images.githubusercontent.com/90633816/184689675-291d4b0c-d757-4ed6-bb8e-408f30b7ea19.png)

**Comment by amd64fox** [comment]
download [SpotXBasic.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/SpotXBasic.bat) and run the installation through it

**Comment by ORB-Aerospace911** [comment]
![image](https://user-images.githubusercontent.com/79132854/184709283-db6359e6-bd83-4905-a67a-64bbfa052924.png)

**Comment by amd64fox** [comment]
If you wait? 

How weak is the pc you're running on or maybe it's a virtual machine?

**Comment by ORB-Aerospace911** [comment]
Right I forgot I have a weak computer
