### ISSUE TITLE
Spicetify with the latest BTS

### ISSUE THREAD

**Issue by LweoIsHere** [mrpond/BlockTheSpot#412]
I was wondering if this still works with Spicetify, just leave a message below and tell me if it does! With steps of course since I'm not really the smartest..

**Comment by amd64fox** [comment]
Read [FAQ](https://github.com/amd64fox/SpotX/discussions/111#discussioncomment-3394563)

**Comment by LweoIsHere** [comment]
i did, thanks c:

all good now!
