### ISSUE TITLE
As of today Spotify just crashes whenever I try playing anything

### ISSUE THREAD

**Issue by Keelar** [mrpond/BlockTheSpot#416]
It was fine yesterday, but as of today If I try to play any song Spotify just crashes. If I reinstall Spotify *without* BlockTheSpot it works fine, but as soon as I install BlockTheSpot via SpotX it just crashes when I try to play anything.

Using Windows 10.

**Comment by GravitySandwich** [comment]
same issue

**Comment by Nuzair46** [comment]
@Keelar @GravitySandwich, Can you guys try a manual install?

**Comment by Hybrid3DR** [comment]
@Nuzair46 
I am running the same version that you are and it still crashes. Might attempt a manual install
![image](https://user-images.githubusercontent.com/56696374/188211781-0fafaf2b-f74c-4a0e-a38a-3cebda8d5a18.png)

**Comment by Nuzair46** [comment]
i tried with spotx and mine is not crashing.
We will see if anything comes up.

**Comment by Bozic421** [comment]
Hmm it works fine for me

**Comment by amd64fox** [comment]
For those who have a similar problem:

- open devtools with [this](https://github.com/amd64fox/Enable-devtools-Spotify)

- open console and try to take a screenshot before and after the crash

**Comment by GravitySandwich** [comment]
> @Keelar @GravitySandwich, Can you guys try a manual install?
> 
> Im not able to replicate this on `Spotify for Windows1.1.93.896.g3ae3b4f3`
> 
> make sure you have this version. if its a latest one, please mention here

Same issue with the manual install, but it did work for a bit until I tried changing playlists then it crashed. Then when reopening it crashes every time. Let me try to open dev tools and take a screenshot. My version is:
Spotify for Windows
1.1.93.896.g3ae3b4f3

**Comment by GravitySandwich** [comment]
https://user-images.githubusercontent.com/4969747/188215544-925c0d4c-248e-40ff-b071-b6c82dc1f5ab.mp4

Okay so I opened devtools then hovered to developer tools and opened the console, in the recordings I pressed the play button and as you can see it immediately closes and my recordings stops

**Comment by amd64fox** [comment]
I don't see critical errors in the console

try a clean install and restart your pc

described [here](https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353)

**Comment by Nuzair46** [comment]
@amd64fox please update here incase you found anything related to this. Somebody can pick it up and add it directly to source itself since its a patch issue.

**Comment by GravitySandwich** [comment]
> I don't see critical errors in the console
> 
> try a clean install and restart your pc
> 
> described [here](https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353)

Ran your clean install script, rebooted, then used your install script to install SpotX. Same issue unfortunately. You mentioned something about a hosts file, I double checked mine and disabled my Pi-Hole in case I thought that was it but it did not help.

**Comment by amd64fox** [comment]
- go to `Roaming\Spotify folder`
- delete the `chrome_elf.dll file`
- rename file `chrome_elf_bak.dll` to `chrome_elf.dll`
- сheck your bug again

**Comment by GravitySandwich** [comment]
> 

That fixed it

**Comment by amd64fox** [comment]
so the problem is with `chrome_elf.dll` from bts

@Nuzair46 
need @mrpond

**Comment by Nuzair46** [comment]
I think he is not.
i have no idea.
hopefully he will see this issue
@mrpond

**Comment by Lyxiannnnnn** [comment]
i made an account just to say thanks. i'm not the original commenter, but this solved my issue of spotify recently crashing with blockthespot

**Comment by amd64fox** [comment]
SpotX has been updated, you can update to the latest version 93, we are testing, if something is wrong, then write

**Comment by Keelar** [comment]
Just ran the patch again and this seems to have fixed the issue for me. Thanks!

**Comment by amd64fox** [comment]
@Keelar 
The update is experimental, see if you have audio ads or banner ads

**Comment by Keelar** [comment]
I've used it for a couple hours so far and haven't noticed any banner or audio ads. I'll report back if that changes, but so far so good.

**Comment by Lyxiannnnnn** [comment]
ran the patch as well, no audio ads & banner ads on my end, and spotify doesn't crash anymore. thanks!

**Comment by amd64fox** [comment]
Thanks for your feedback, keep testing

**Comment by mdxaasil** [comment]
spotx doesnt crash. Try it with spotx guys

**Comment by Nuzair46** [comment]
Can you guys try this build and see if the crash still occurs?
 https://cdn.discordapp.com/attachments/993823969394303086/1016293718854205470/chrome_elf.dll

**Comment by Nuzair46** [comment]
Try this new release https://github.com/mrpond/BlockTheSpot/releases/tag/2022.9.05.53

**Comment by Nuzair46** [comment]
will be closing as solved.
reopen if issue exists again.
