### ISSUE TITLE
I can't play certain songs/albums on Spotify

### ISSUE THREAD

**Issue by CorviusAtticus** [mrpond/BlockTheSpot#418]
I was able to play some "david bowie" tracks a week ago but this last couple days I realized that certain songs/albums aren't available on spotify, I don't know exactly if this bug is related to SpotX so I'm asking if it is ?  and if so how can I fix it ? thanks

**Comment by Nuzair46** [comment]
this is Spotify region locking songs.

**Comment by CorviusAtticus** [comment]
> this is Spotify region locking songs.

now it makes sense lol but why it didn't do it before, may I ask ? did they recently started to put those limits ?
also can i just fix it by switching to another region like US, AU or CA ?

thanks for answering
