### ISSUE TITLE
Auto-installer not working

### ISSUE THREAD

**Issue by ZeroLogicGaming** [mrpond/BlockTheSpot#42]
When I run BlockTheSpot.exe from the folder I get this:
![ScreenShot_20200419002136](https://user-images.githubusercontent.com/63679766/79672854-2f080900-81de-11ea-800c-309f851c233b.png)

I tried just pressing enter and then i get this:

![ScreenShot_20200419002853](https://user-images.githubusercontent.com/63679766/79672870-51018b80-81de-11ea-9b37-db43b5710a97.png)

**Comment by rednek46** [comment]
> When I run BlockTheSpot.exe from the folder I get this:
> ![ScreenShot_20200419002136](https://user-images.githubusercontent.com/63679766/79672854-2f080900-81de-11ea-800c-309f851c233b.png)
> 
> I tried just pressing enter and then i get this:
> 
> ![ScreenShot_20200419002853](https://user-images.githubusercontent.com/63679766/79672870-51018b80-81de-11ea-9b37-db43b5710a97.png)

Thats a first timer.
Run the batch file again and if the error persists, open the bat file in notepad and add this line right after the 6th line in the script ie, # Ignore errors from `Stop-Process`
And save, run again. 
`[Net.ServicePointManager]::SecurityProtocol = "tls12" `

**Comment by ZeroLogicGaming** [comment]
Ok now it runs, but it doesn't seem to have done anything. I'm still getting ads and I can't use the Very High quality setting. It did add the files to the Spotify folder, but that didn't actually do anything apparently.

**Comment by rednek46** [comment]
> Ok now it runs, but it doesn't seem to have done anything. I'm still getting ads and I can't use the Very High quality setting. It did add the files to the Spotify folder, but that didn't actually do anything apparently.

Did you run the old-batch or added the line of code to the the batch file you tried first?
And also try removing the Chrome_elf.dll from the spotify dir and run the batch script again. Also make sure windows defender doesn't block the chrome_elf.dll as a threat.

**Comment by ZeroLogicGaming** [comment]
I actually completely reinstalled Spotify and ran the batch script after adding the extra line. I had real time protection disabled in Windows Defender as well. It still didn't work.

**Comment by rednek46** [comment]
> I actually completely reinstalled Spotify and ran the batch script after adding the extra line. I had real time protection disabled in Windows Defender as well. It still didn't work.

That is strange.
Uninstall spotify, then just run the batch file. It will install the latest spotify and patch. If you still get any error, check whether your firewall is blocking the script or something. And i should ask, are you the system Admin?

**Comment by ZeroLogicGaming** [comment]
> > I actually completely reinstalled Spotify and ran the batch script after adding the extra line. I had real time protection disabled in Windows Defender as well. It still didn't work.
> 
> That is strange.
> Uninstall spotify, then just run the batch file. It will install the latest spotify and patch. If you still get any error, check whether your firewall is blocking the script or something. And i should ask, are you the system Admin?

Ok I did this with firewall and real-time protection off, but still nothing. Note that I don't get an error; the script runs fine. It just doesn't do anything. Spotify remains the exact same and nothing changes at all. And yes, my user is an admin user.

**Comment by rednek46** [comment]
> > > I actually completely reinstalled Spotify and ran the batch script after adding the extra line. I had real time protection disabled in Windows Defender as well. It still didn't work.
> > 
> > 
> > That is strange.
> > Uninstall spotify, then just run the batch file. It will install the latest spotify and patch. If you still get any error, check whether your firewall is blocking the script or something. And i should ask, are you the system Admin?
> 
> Ok I did this with firewall and real-time protection off, but still nothing. Note that I don't get an error; the script runs fine. It just doesn't do anything. Spotify remains the exact same and nothing changes at all. And yes, my user is an admin user.
> 
> Edit: as I mentioned before it does add config.ini and chrome_elf.dll to the Spotify folder, however they have no effect. I've even tried adding them manually.

@ZeroLogicGaming ,so the installer is doing fine but the patch file doesn't work. @mrpond might want to check this issue.

**Comment by mrpond** [comment]
> > > I actually completely reinstalled Spotify and ran the batch script after adding the extra line. I had real time protection disabled in Windows Defender as well. It still didn't work.
> > 
> > 
> > That is strange.
> > Uninstall spotify, then just run the batch file. It will install the latest spotify and patch. If you still get any error, check whether your firewall is blocking the script or something. And i should ask, are you the system Admin?
> 
> Ok I did this with firewall and real-time protection off, but still nothing. Note that I don't get an error; the script runs fine. It just doesn't do anything. Spotify remains the exact same and nothing changes at all. And yes, my user is an admin user.
> 
> Edit: as I mentioned before it does add config.ini and chrome_elf.dll to the Spotify folder, however they have no effect. I've even tried adding them manually.

don't turn off antivirus. and this patch doesn't work with windows store version of spotify.

**Comment by ZeroLogicGaming** [comment]
I tried the new version and nothing has changed unfortunately. Did you fix the dll because that's most likely where the problem is right now. The installer runs smoothly with no issues at all, but I get none of the premium features. Also, does it still say 'Upgrade' at the top when it works?

**Comment by mrpond** [comment]
it just adblock, you will not see ad banner and ad song.

**Comment by Dyras** [comment]
@ZeroLogicGaming 
I had the exact same problem as you and I came here to inform mrpond of it.

However, when I turned off the Windows Firewall it worked when I ran the .bat file as an administrator.

Doesn't it work for you, if you run it with the firewall off?

**Comment by rednek46** [comment]
> @ZeroLogicGaming
> I had the exact same problem as you and I came here to inform mrpond of it.
> 
> However, when I turned off the Windows Firewall it worked when I ran the .bat file as an administrator.
> 
> Doesn't it work for you, if you run it with the firewall off?

You don't have to run BlockTheSpot.bat as admin. Your firewall may be preventing the batch file to download the patch. If you are experiencing [this](https://github.com/mrpond/BlockTheSpot/issues/42#issue-602567669) error mentioned above then, 
open the bat file in notepad and add this following line right after the 6th line in the script 
ie, # Ignore errors from Stop-Process
And save, run again.
`[Net.ServicePointManager]::SecurityProtocol = "tls12"`

@ZeroLogicGaming 's issue was fixed with the above line for the installer and also the release 2020.04.21 fixed the issue related to the patch.

**Comment by gitgudscrubb** [comment]
adding the line of code to the batch file solved this for me, replacing the elf file manually resulted in entry point errors
