### ISSUE TITLE
latest version is not recognised as playing on discord / other devices

### ISSUE THREAD

**Issue by jabsyh** [mrpond/BlockTheSpot#420]
hi,

the latest version of blockthespot does not allow discord to use the "listening to spotify" status. sometimes it works, most of the time it does not. i also cannot see my mobile phone on the other devices or vice versa, but both of those work with the default spotify app

i appreciate this patch thoroughly and im not complaining, just trying to pass some info on
hope it helps!

thanks

**Comment by Nuzair46** [comment]
this is issue with Spotify. We cant do anything

**Comment by danigiorgio** [comment]
Unlink my Spotify acc on the Discord Connections Panel, relinking and restarting Spotify solved my issue.
