### ISSUE TITLE
Spotify doesn't show on the discord status 

### ISSUE THREAD

**Issue by Wesleyyy13** [mrpond/BlockTheSpot#422]
After downloading BlockTheSpot, Spotify no longer shows what you're currently listening to on discord. It also doesn't scrobble any songs on the Last FM website. I was wondering if this could be solved because I would really love using those features.

**Comment by Nuzair46** [comment]
This is not BlockTheSpot related issue

**Comment by L3m0n-Cao** [comment]
Relink your Spotify account to your discord.

**Comment by L3m0n-Cao** [comment]
1. Unlink your Spotify on the Discord Connections Panel.
2. Uninstall Spotify.
3. Use Spot X (make sure to do N for cashe)
4. Link Spotify to Discord MAKE SURE "DISPLAY SPOTIFY AS STATUS" IS ON
[image: image.png]
