### ISSUE TITLE
getting this error when putting the command in powershell

### ISSUE THREAD

**Issue by hariiiiiiiii** [mrpond/BlockTheSpot#424]
https://user-images.githubusercontent.com/96715146/191298818-f80b7e0e-b827-4b06-acda-3ded2f1a472d.png

**Comment by amd64fox** [comment]
[FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22The-remote-name-could-not-be-resolved%22-while-running-the-install)
