### ISSUE TITLE
Black rectangle in place of removed ads

### ISSUE THREAD

**Issue by 7evenlxrd** [mrpond/BlockTheSpot#43]
Screenshot of problem

![Adnotacja 2020-04-22 181343](https://user-images.githubusercontent.com/49694911/80006747-9fa47380-84c5-11ea-9508-b9d492b65b00.png)

**Comment by 7evenlxrd** [comment]
This black rectangle is annoying :D

**Comment by rednek46** [comment]
> This black rectangle is annoying :D

And try running the BlockTheSpot.bat again.
Also check if any errors are thrown in the cmd.

**Comment by rednek46** [comment]
> This black rectangle is annoying :D

Is your Spotify version 1.1.31.703.g256add22   ?

**Comment by rednek46** [comment]
@mrpond , the patch doesn't seem to work on the latest 1.1.31.703.g256add22 version.
the Black rectangle as mentioned above by @7evenlxrd can be seen while opening any playlist. And I personally observed that the ads came back after using the app for a long time there is no audio ads, but banners.

**Comment by rednek46** [comment]
I paused Spotify, played some games and when i opened spotify, ads are back. the patch is in place and still the ads pops up after some time. 

these are the only banners that popped up.

![Annotation 2020-04-22 225459](https://user-images.githubusercontent.com/38219313/80013382-69c6b580-84ec-11ea-830a-2b3e4cbf17c4.png)

![Annotation 2020-04-22 225439](https://user-images.githubusercontent.com/38219313/80013392-6f240000-84ec-11ea-8f0e-c8d30702a29a.png)

**Comment by mrpond** [comment]
Ok I look into it today

**Comment by mrpond** [comment]
fixed
