### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by allyaminou** [mrpond/BlockTheSpot#433]
Hi, i would like to know how to permanently uninstall this...i've tried the bat file, it still runs when i turn on my pc. uninstalled spotify , reinstalled, it the same thing...i would appreciate some help on this.

**Comment by 002-sans** [comment]
if you uninstall spotify, your spotify files don't exist anymore ? so there is no longer the tool

**Comment by Nuzair46** [comment]
Reinstalling Spotify will uninstall the patch
