### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vostok1k** [mrpond/BlockTheSpot#436]
![image](https://user-images.githubusercontent.com/111824258/202795451-ee856076-8c78-4288-9393-45a4d387f7f5.png)

**Comment by SinThroughCode** [comment]
Same thing with me. Spotify made and update today so I assume that is why. Project needs to be updated.

**Comment by Nuzair46** [comment]
https://github.com/spotx-cli/spotx-win

**Comment by Vostok1k** [comment]
> https://github.com/spotx-cli/spotx-win

ty :D
