### ISSUE TITLE
Found an issue with the black border at the bottom.

### ISSUE THREAD

**Issue by mamokupisprajt** [mrpond/BlockTheSpot#439]
is there any way to save these settings or do i have to edit dev options to disable the ugly ahh black banner at the bottom?

**Comment by mamokupisprajt** [comment]
and also when i edit the border and a few songs pass the little thumbnail of the song goes gray for the rest of the session till i reset

**Comment by mrpond** [comment]
[xpui.zip](https://github.com/mrpond/BlockTheSpot/files/11075748/xpui.zip)
open 'xpui.spa' with your favorite zip program, replace xpui.css inside it.

**Comment by mrpond** [comment]
it had been fix, download latest blockthespot.
