### ISSUE TITLE
A lot of songs refuse to play with this installed

### ISSUE THREAD

**Issue by MasicoreLord** [mrpond/BlockTheSpot#44]
OS: Window 10
Spotify Version: 1.1.31.703.g256add22
BlockTheSpot Product Version: 0.51.0.0

![image](https://user-images.githubusercontent.com/11468845/80054653-de4e2400-84ed-11ea-920e-fdcee5aa4657.png)

**Comment by mrpond** [comment]
tried change Fix_Black_Banner to 0 in config.ini ,
 this is bug

**Comment by mrpond** [comment]
Thanks for report this, I fix it in 
2020.4.23.11

please try again.
