### ISSUE TITLE
How to enable new theme

### ISSUE THREAD

**Issue by NguyenASang** [mrpond/BlockTheSpot#441]
## Question
- How do I enable the new theme like SpotX ?

## Additional content
Thank you for reopening this project, really love this update!

**Comment by mrpond** [comment]
Develop->Show Debug Window

and look for YLX things

**Comment by superrlol** [comment]
wym develop?

**Comment by NguyenASang** [comment]
@superrlol 

https://user-images.githubusercontent.com/87893636/229028193-2b9ccf67-3864-4edc-9ccd-132a6fa55cdf.mp4

**Comment by superrlol** [comment]
just now seeing this. thank you so much <3
