### ISSUE TITLE
Is it possible to change "Spotify Free" to "Spotify" ?

### ISSUE THREAD

**Issue by NguyenASang** [mrpond/BlockTheSpot#442]
## Image 

![image](https://user-images.githubusercontent.com/87893636/228780042-64d82815-f38f-4f34-9894-4caad1ecc6c4.png)

P/s: I think you should create a "Future request" report template.

**Comment by Nuzair46** [comment]
No. This was discussed before that there is no safe way to remove this without DMCA

**Comment by Pranav6145** [comment]
It has been removed on SpotX
