### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by leotorol** [mrpond/BlockTheSpot#446]
When I try to udate to the latest version it just pulls this:

![image](https://user-images.githubusercontent.com/129588331/229277556-e849b34c-b8f3-43ad-83fc-4787ef394618.png)

I already unistalled the patch and try to update spotify and it gives me the same error

**Comment by Nuzair46** [comment]
can you please follow the bug template?

**Comment by leotorol** [comment]
Sorry, I dont understand what I am supossed to do

**Comment by leotorol** [comment]
> can you please follow the bug template?

Sorry, I dont understand what I am supossed to do
