### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by RedReaperLp** [mrpond/BlockTheSpot#448]
Issue on Windows 11
I´m getting ads, which I think I´m not supposed to be
Bw

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [X] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [X] You uninstalled Spotify and just ran [SpotX](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Basic.bat) and is still having issues.
 - [X] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [X] You read through [SpotX FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22The-remote-name-could-not-be-resolved%22-while-running-the-install)
 - [X] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [X] You enabled logging by editing config.ini `set log = 1`.
 - [X] Make sure whether an issue related yours is already open or not.
 - [X] Make sure you have completed everything in the above checklist.
![Bild_2023-04-21_233957774](https://user-images.githubusercontent.com/64808428/233738773-566185de-8116-4974-8873-6b326ffba6f7.png)

**Comment by Keelar** [comment]
Same issue and I'm on Windows 10. I've redownloaded and ran the latest batch file probably a dozen times over the past few weeks and ads still play and pop up. No errors during installation. I've also manually installed via the zip file and it still doesn't work.

**Comment by ThySiho** [comment]
Same issue here on Windows 11
unlimited skips still work without any problems, but after listening to several songs I will get a unskippable ad

**Comment by mrpond** [comment]
Hi post the data from blockthespot log.txt

**Comment by Keelar** [comment]
> Hi post the data from blockthespot log.txt

Where is that file located?

**Comment by kainigou** [comment]
Hi mrpond, I have the same issue. Where could i find the log.txt ? Thank you !

**Comment by mrpond** [comment]
check the release, fixed https://github.com/mrpond/BlockTheSpot/releases/
