### ISSUE TITLE
Missing chrome_elf.zip file

### ISSUE THREAD

**Issue by k-boss** [mrpond/BlockTheSpot#45]
Apparently every chrome_elf.zip file, even from releases, are missing, making the code not to work.

**Comment by flxshdelirium** [comment]
The installer didn't work either for me last night, nor could I download the chrome_elf archive from the Releases page (I'm guessing it was something to do with Github), but it seems to be downloading fine now. If it's still not working for you, I could attach it.

**Comment by rednek46** [comment]
@k-boss can you check that if the installer is working as of now?
as said by @flxshdelirium , this could be a github issue.

**Comment by kapitaniglo11** [comment]
Also, please make sure that your antivirus is not blocking it - Windows Security does it straight away

**Comment by rednek46** [comment]
> Also, please make sure that your antivirus is not blocking it - Windows Security does it straight away

Yea the latest signature update again removes the file as threat.

**Comment by mrpond** [comment]
@k-boss  @flxshdelirium check release 
https://github.com/mrpond/BlockTheSpot/releases
for latest update,
or use blockthespot.bat for ease of use.
