### ISSUE TITLE
Account hacked

### ISSUE THREAD

**Issue by Necromexe** [mrpond/BlockTheSpot#450]
Sure enough installed this then the following day my account email changed, and got random people on my account.

**Comment by Nuzair46** [comment]
Please don't make false statements without any grounds. The code is completely open and it doesn't include anything that steals your account.

**Comment by mrpond** [comment]
don't show stupidity here.
1. make sure you download dll from this official github, and not somewhere else.
2. if you certain, show proof 
3. if you can't proof use notable third party e.g. tell some anti-virus software company to look into this opensource project.
