### ISSUE TITLE
Spotify Desktop Windows application after fresh install both Manual or Auto installer is not responding

### ISSUE THREAD

**Issue by HairyPloper** [mrpond/BlockTheSpot#454]
Windows 10 version 22H2 (KB5026435)
Spotify version 1.2.12.902.g1924b088
Freshly installed Spotify Desktop Application for Windows. (With auto script and manually from https://www.spotify.com/download/windows/).

Steps to reproduce on my environment:
- Download/Install scripts from README.md
- Authenticate with user credentials

Application after installing and patching does not load any playlists. Can't play/start any song.
Does not load or open Profile settings and most of the features are unresponsive.

What does work. User can authenticate and log in. Search is operational. Home page is being displayed.  Does not crash or produce any errors.

[blockthespot_log.zip](https://github.com/mrpond/BlockTheSpot/files/11655807/blockthespot_log.zip)

**Comment by Nuzair46** [comment]
Is it running fine without the patch?

**Comment by Iheuzio** [comment]
Same thing happened for me today
