### ISSUE TITLE
From version 1.2.13.656.gd13f2059 the upgrade button is back

### ISSUE THREAD

**Issue by xXTimmy89Xx** [mrpond/BlockTheSpot#455]
Describe the bug:

From version 1.2.13.656.gd13f2059 the upgrade button is back

Screenshot:

![image](https://github.com/mrpond/BlockTheSpot/assets/53865707/dd5e035f-27ec-4f77-b42e-ce73d4b8e5f6)

![image](https://github.com/mrpond/BlockTheSpot/assets/53865707/f2d09dea-9741-4a94-8097-b6914ede77ec)

**Comment by Othmane-ElAlami** [comment]
Same here, I tried both the manual and automated method.

**Comment by ronny941** [comment]
same here the upgradw button as returned with the new v1.12.13.661

**Comment by mcluski** [comment]
yeah same here. also, ads started to appear often now

**Comment by mrpond** [comment]
Hi, see https://github.com/mrpond/BlockTheSpot/issues/461
