### ISSUE TITLE
New version of Spotify 

### ISSUE THREAD

**Issue by Azukiov** [mrpond/BlockTheSpot#456]
A new version of Spotify is up
1.2.13.661.ga588f749

i have ads and it's not cool
pls update it ^^

thanks

**Comment by Stealth1226** [comment]
second this ^

**Comment by Nuzair46** [comment]
can you guys upload the logs?

**Comment by Clgbt** [comment]
how to enable it ??

**Comment by khush3718** [comment]
I'm having the same issue here

**Comment by Clgbt** [comment]
I don't have the develop button !!

**Comment by ItsAzukio** [comment]
me too, i dont have this button

**Comment by Clgbt** [comment]
Using SpotX I founded the button, here are logs
[Spotify_BridgeMessages_2023-06-16_193317.txt](https://github.com/mrpond/BlockTheSpot/files/11773332/Spotify_BridgeMessages_2023-06-16_193317.txt)
I think it is not full

**Comment by NocturneOfShadows** [comment]
[Spotify_BridgeMessages_2023-06-17_172947.json](https://pixeldrain.com/u/Y9idM91y)

**Comment by Nuzair46** [comment]
we want this log.
please follow the issue template. as its there for a reason to make this simple and save time https://github.com/mrpond/BlockTheSpot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#describe-the-bug

**Comment by Othmane-ElAlami** [comment]
[Spotify_BridgeMessages_2023-06-19_104709.json.txt](https://github.com/mrpond/BlockTheSpot/files/11786795/Spotify_BridgeMessages_2023-06-19_104709.json.txt)

**Comment by Nuzair46** [comment]
That that is not the logs we want. please go through the mentioned bug report.

**Comment by LokiTacos** [comment]
Having same issue with latest. WIn 11 22h2 build 22621.1848. Upgrade button back as well as ads
[blockthespot_log.txt](https://github.com/mrpond/BlockTheSpot/files/11800981/blockthespot_log.txt)

**Comment by yuda-san** [comment]
i found 

> @Nuzair46 I did enable the logs in config.ini then what? Where am I gonna find those logs?
> 
> I'm sorry but this "tutorial" is useless, you should have at least specified that the **config.ini** is inside **%APPDATA%** or **C:\Users\%USERNAME%\AppData\Roaming\Spotify** and the log file name gonna be generated in the same folder with the name [blockthespot_log.txt](https://github.com/mrpond/BlockTheSpot/files/11788296/blockthespot_log.txt)

i found this file, and seems fine after looking up the config, but that log.txt seems nowhere in this folder

**Comment by Rayyy02** [comment]
> Da KFC lookin good tho
 ![image](https://user-images.githubusercontent.com/135691320/245797781-1f07888b-e625-4cb2-9144-ec89e1355237.png)

**Comment by Rayyy02** [comment]
> 

KFC lookin good tho

**Comment by WarFiN123** [comment]
Yall guys i found a crack for spotify and its looking clean so far

**Comment by GhosttRiderrr** [comment]
Ive got the same problem. Ads on the bottom bat and they never go away.
![Screenshot (59)](https://github.com/mrpond/BlockTheSpot/assets/137924797/1173eb9f-ea89-4991-aa28-9f3e542af36c)

**Comment by 1kingvamp11** [comment]
guys i uninstalled spotify and installed it again and run spotX and I have no ads

**Comment by yewshanooi** [comment]
Version **1.2.14.1149.ga3ae422d** _(Spotify for Windows)_ and BlockTheSpot patch seems to fix the ads issue for me.

**Comment by UnrealFakes** [comment]
Yeah, I also switched to SpotX. You literally just run Install_Auto.bat and it does everything for you lol You don't even have to uninstall Spotify. It automatically installs the correct version over existing one, blocks auto update, patches it, done. Soooo convenient.

**Comment by yuda-san** [comment]
> Version **1.2.14.1149.ga3ae422d** _(Spotify for Windows)_ and BlockTheSpot patch seems to fix the ads issue for me.

had same version, always rerun the .bat file but still showing sponsored banner and ads

**Comment by yuda-san** [comment]
> guys i uninstalled spotify and installed it again and run spotX and I have no ads

i want to do this step while ago, i was so dumb, and today works lol

**Comment by Kynaba** [comment]
Hi i have the new version of spotify and i'd like to recover the old version is it possible ?

**Comment by Othmane-ElAlami** [comment]
@Kynaba yeah just change the $uri in the PowerShell script and run it, I used a link from APKPure but feel free to choose any other website hosting older versions

**Comment by mrpond** [comment]
see https://github.com/mrpond/BlockTheSpot/issues/461
