### ISSUE TITLE
error on installation

### ISSUE THREAD

**Issue by polytropicx** [mrpond/BlockTheSpot#457]
SYSTEM - Windows 11
ERROR -  upon running the "BlockTheSpot.bat" file i get an error:

Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:85
+ ... pe]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
![Screenshot 2023-06-16 163020](https://github.com/mrpond/BlockTheSpot/assets/136807586/9597c50a-9ae5-4df9-9805-c0386a13902d)

**Comment by Othmane-ElAlami** [comment]
Sounds like it's your internet the problem here, try with another network or use a VPN.

**Comment by WarFiN123** [comment]
> Sounds like it's your internet the problem here, try with another network or use a VPN.

Yep that should work for most cases.
