### ISSUE TITLE
Ads are back.

### ISSUE THREAD

**Issue by WarFiN123** [mrpond/BlockTheSpot#458]
Alright so Spotify casually drops a new update which fixes the ads thing. Ads are back on Spotify and its not getting resolved using BlockTheSpot. Well lets see if the devs(gods) can hopefully fix it.

**Comment by WarFiN123** [comment]
Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.

**Comment by imr0by** [comment]
> Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.

What is the name of the crack? Im tired of the ads

**Comment by WarFiN123** [comment]
> > Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.
> 
> What is the name of the crack? Im tired of the ads

Well it's on filecr.com. apparently they have the safest pirated software and the crack is lookin gclean on virustotal too. Basically go to filecr.com and search for Spotify. Then download it for windows.

**Comment by WarFiN123** [comment]
> > > > Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.
> > > 
> > > 
> > > What is the name of the crack? Im tired of the ads
> > 
> > 
> > Well it's on filecr.com. apparently they have the safest pirated software and the crack is lookin gclean on virustotal too. Basically go to filecr.com and search for Spotify. Then download it for windows.
> 
> Thanks

Did it work for you?

**Comment by Nuzair46** [comment]
> > > Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.
> > 
> > 
> > What is the name of the crack? Im tired of the ads
> 
> Well it's on filecr.com. apparently they have the safest pirated software and the crack is lookin gclean on virustotal too. Basically go to filecr.com and search for Spotify. Then download it for windows.

Just be aware that we are not going to take any responsibility from using said crack. and also please refrain from sharing these here.

also closing this issue as its same as #456

**Comment by imr0by** [comment]
> > > > > Alright so i found a crack for the Spotify ad issue and its looking clean so far so im gonna use that for now.
> > > > 
> > > > 
> > > > What is the name of the crack? Im tired of the ads
> > > 
> > > 
> > > Well it's on filecr.com. apparently they have the safest pirated software and the crack is lookin gclean on virustotal too. Basically go to filecr.com and search for Spotify. Then download it for windows.
> > 
> > 
> > Thanks
> 
> Did it work for you?

Nope, doesnt work
