### ISSUE TITLE
Is there a way to disable Spotify auto-updates?

### ISSUE THREAD

**Issue by BitGrub** [mrpond/BlockTheSpot#46]
Title

**Comment by rednek46** [comment]
BlockTheSpot is for the latest Spotify release and it works fine. Why do you want to disable the update?

**Comment by BitGrub** [comment]
> BlockTheSpot is for the latest Spotify release and it works fine. Why do you want to disable the update?

Are you serious?

**Comment by Davoleo** [comment]
Yes, it does work

**Comment by jonaaa20** [comment]
@BitGrub I ask the same, why do you want to disable the auto-update?

**Comment by rednek46** [comment]
> > BlockTheSpot is for the latest Spotify release and it works fine. Why do you want to disable the update?
> 
> Are you serious?

Dude. This Repo is always updated for the latest Spotify.

**Comment by rednek46** [comment]
> > > BlockTheSpot is for the latest Spotify release and it works fine. Why do you want to disable the update?
> > 
> > 
> > Are you serious?
> 
> Dude. This Repo is always updated for the latest Spotify.

@BitGrub uninstall you current spotify and run the BLockTheSpot.bat from this repo. It will install the latest spotify and will patch it.

**Comment by BitGrub** [comment]
Did you know that if Spotify didn't auto-update itself whenever it felt like it, you wouldn't have to manually patch it all the time?

I'm genuinely shocked this needed to be explained to so many of you

**Comment by mrpond** [comment]
@BitGrub a lot of Spotify update aren't only features, 
newer version mean stability and **important security fix**.
If you lazy to manually patch it like me :P , just download BlockTheSpot.bat
put it somewhere easily accessible and run it when new Spotify come.

**Comment by Davoleo** [comment]
> Did you know that if Spotify didn't auto-update itself whenever it felt like it, you wouldn't have to manually patch it all the time?
> 
> I'm genuinely shocked this needed to be explained to so many of you

man, it's just a double-click
and spotify doesn't even get a lot of frequent updates to be fair
furthermore you can also keep always the same bat that also updates the patch to the latest version

**Comment by BitGrub** [comment]
I love this was closed before anyone could answer. A simple "yes"/"no"/"i'm not capable of independent thought" would suffice

**Comment by Davoleo** [comment]
no, there isn't
Are you satisfied now? lol

**Comment by rednek46** [comment]
> I love that this was closed before anyone could answer. A simple "yes"/"no"/"i'm not capable of independent thought" would suffice

I said you can't do that [here](https://github.com/mrpond/BlockTheSpot/issues/46#issuecomment-626182862) . And as I said, this repo is for the latest Spotify only.

**Comment by mrpond** [comment]
@BitGrub check this https://github.com/mrpond/BlockTheSpot/issues/19
I really don't know what todo when issue 19 happen.
Sorry.

**Comment by Neurotoxin001** [comment]
You can do it by putting this in your hosts file:

```
0.0.0.0 upgrade.spotify.com
0.0.0.0 www.spotify-desktop.com
0.0.0.0 upgrade.scdn.co
```
