### ISSUE TITLE
Can't Turn On The Old UI

### ISSUE THREAD

**Issue by HudoraX69** [mrpond/BlockTheSpot#460]
I'm using an windows 10 and i downloaded the 2023.5.20.80 realise date version and now i can't revert to old ui using developer tools (YLX)

**Comment by Rendrox** [comment]
same here

**Comment by xXTimmy89Xx** [comment]
> I'm using an windows 10 and i downloaded the 2023.5.20.80 realise date version and now i can't revert to old ui using developer tools (YLX)

You need spotify version 1.2.13.661.ga588f749 or earlier to enable the old UI, from later version 1.2.13.661.ga588f749 the old UI has been removed.

**Comment by ajarang** [comment]
please edit the readme with this info
