### ISSUE TITLE
Ads are popping up and it doesn't seem to be working for me.

### ISSUE THREAD

**Issue by Aspredo** [mrpond/BlockTheSpot#461]
Ever since like 2 days ago, I noticed I started getting ads even though I had used the program. Not sure if this is an issue on my side or the program needs to be updated.

**Comment by ikki4** [comment]
Same here. Spotify just updated automatically, without my permission, and it doesn't look like it's patched anymore. Banners everywhere. 

> Lives through Spotify updates. No need to patch Spotify after every update anymore.

That no longer seems to be the case.

Current Spotify version: Spotify for desktop-about.platform-win-x86-64 1.2.14.1149.ga3ae422d

**Comment by LercheKa** [comment]
Second this, updating through the .bat doesn't work.

**Comment by wwweixD** [comment]
> Second this, updating through the .bat doesn't work.

i uninstalled spotify, then ran the .bat and it seems fixed

**Comment by zedd-0** [comment]
i replaced the "dpapi.dll" again,
and it seems to work.

**Comment by ikki4** [comment]
@LercheKa @wwweixD @zedd-0 @Aspredo have you tried the Powershell command? It fixed for me.

**Comment by zedd-0** [comment]
i do not like scrips, that i do not understand,
i'm still reading and i will do it by hand.
It would be easier if someone told me what the script does exactly,
or listing the essential commands.
there no comments in it. :(

**Comment by galactic-monkey** [comment]
Also experienced this issue today, but reinstalling spotify and redownloading to make sure I'm using the latest patch seems to have fixed it for now.

**Comment by Chromos-Def** [comment]
Is there any reasoning behind as to why the PowerShell Script would work but manual installation does not?

**Comment by zedd-0** [comment]
The installation by hand works, or at least it should work.
Only when the app updated itself, it didn't work.

Extracting 'dpapi.dll' again did not help.

My suspicion is,
that there is a file/setting somewhere that blocked 'dpapi.dll',
or there might be differences between the update version and the offline installer.

I didn't delete Spotify but installed it over with the offline installer.
I am not sure, if this process deleted or modified cache/settings or other generated files.
I am also unsure, if the update and offline versions are truly different.

I can only describe the experienced behavior.
Here's what I did:


- download the offline installer:
https://download.scdn.co/SpotifyFullSetup.exe

- unpack or reinstall Spotify:
SpotifyFullSetup.exe /extract "Out Dir"
(I recommend the reinstallation)

- download and unpack the patch into the installation directory:
https://github.com/mrpond/BlockTheSpot/releases/download/2023.5.20.80/chrome_elf.zip
C:\Users\YourUserName\AppData\Roaming\Spotify
%APPDATA%\Spotify

- run Spotify


tested with:
Spotify v1.2.14.1149 2023-06-22
chrome_elf.zip v2023.5.20.80 2023-05-20

I hope this helps.
mrpond could update his 'README.md' a litte bit
to include the part with Spotify.

**Comment by classy09az** [comment]
> Ever since like 2 days ago, I noticed I started getting ads even though I had used the program. Not sure if this is an issue on my side or the program needs to be updated.

I had this same problem but found a fix. 
1. Download the latest version of block the spot. 
2. Then on your windows device, in the search bar search for "add or remove programs." Look for spotify in there and uninstall it fully.
3. Run block the spot.

The block the spot will automatically download a version of spotify that it works with so you just need to log in after and you're all set. Hope this helps <3

**Comment by Joashh404** [comment]
Reinstalling Spotify then running the .bat file seems to have sorted it out for me.

**Comment by TooYoungTooSimp** [comment]
The key point is that the newest version of spotify loads system dpapi.dll instead of this patcher. It can be investigated from procexp64's DLL view. I installed an older version of spotify and blocked the update to temporary solve this problem.

**Comment by TooYoungTooSimp** [comment]
> @TooYoungTooSimp how did you stop Spotify from auto updating?

You can use any hex editor to open Spotify.exe and find a string `wg://desktop-update`

change its following to a nonexistent path, for example, change v2 to v5 or anything have the same length

![image](https://github.com/mrpond/BlockTheSpot/assets/6648049/d1778747-692e-4f1c-b33e-22d3b9ede520)

**Comment by verbes4** [comment]
i downloaded SpotifyFullSetup.exe and ran it with /extract. I then hex-edited the exe as TooYoungTooSimp said, and manually installed block the spot. then i ran spotify and now its working perfectly

**Comment by PwccaCode** [comment]
Anyone has a link for older version of spotify installer?

**Comment by ElysRealm** [comment]
> Anyone has a link for older version of spotify installer?

I found an older version of the installer from [UpToDown (Spotify 1.1.98.691)](https://spotify.en.uptodown.com/windows/download/86429191), and then did a clean install of BlackTheSpot and it seems to be working for me for now. Also here is a [report from VirusTotal](https://www.virustotal.com/gui/file/ead80a1767978ed62dfa51443d12f17c0c9444850a8750f7677f82150c0e9598) for that Spotify exe for the paranoid like me lol.

**Comment by zedd-0** [comment]
i have installed "Spotify - 2023-07-07 - v1.2.15.828" (offline installer), and it works.
why? i do not know! it makes no sense.

every over the air update (the last 2 versions cause problems)
will not work with "BlockTheSpot - 2023-05-20 - v2023.5.20.80".

i just overwriting the files with the offline installer,
and it works again...

it is strange why Spotify is act so differently.
i forgot to proof, if there are differences between OTA & offline files.

**Comment by zedd-0** [comment]
update:
found die problem.

if you install spotify with the offline installer,
you get the 32bit version of spotify.

if spotify update itself,
your 32bit installation get replaced with 64bit files.

@mrpond 
can you make a 64 bit version of "dpapi.dll" ?

**Comment by benny999x** [comment]
run this in powershell in admin: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify"

**Comment by zedd-0** [comment]
did you read the full thread?
the script was already offered as a solution.
this does not solve the problem, that spotify changes the program from 32bit to 64bit.
and I assume that the majority of users have a 64-bit operating system.

**Comment by benny999x** [comment]
> did you read the full thread?
> 
> the script was already offered as a solution. this does not solve the problem, that spotify changes the program from 32bit to 64bit. and I assume that the majority of users have a 64-bit operating system.
> 
> I must excuse myself.

Worked for me so idrc tbh

**Comment by mrpond** [comment]
> 

Hi. I had been tinkering with it, since I can't reproduce spotify ads.
Seem 64bit Spotify version is the cause.
thank for pointing this out.

**Comment by mrpond** [comment]
> update: found the problem.
> 
> if you install spotify with the offline installer, you get the 32bit version of spotify.
> 
> if spotify update itself, your 32bit installation get replaced with 64bit files. but "dpapi.dll" is still 32bit.
> 
> @mrpond can you make a 64bit version of "dpapi.dll" ?
> 
> [edit:] i found the offline installer of the 64-bit desktop version: https://download.scdn.co/SpotifyFullSetupX64.exe

Hi. I had been tinkering with it, since I can't reproduce spotify ads.
Seem 64bit Spotify version is the cause.
thank for pointing this out.

**Comment by disruptedtech** [comment]
> 

I tried following these steps, installing that spotify and running blockthespot again and the issue is still there :/

**Comment by zedd-0** [comment]
witch steps? ;)

did you install this: https://download.scdn.co/SpotifyFullSetup.exe ? (32bit)
did you load this: https://github.com/mrpond/BlockTheSpot/releases/download/2023.5.20.80/chrome_elf.zip ? (last version)
did you extract the zip to: "%appdata%\Spotify" or "C:\Users\YourProfileName\AppData\Roaming\Spotify" ?

with [MediaInfo](https://mediaarea.net/en/MediaInfo) you can check if your exe-file (%appdata%\Spotify\Spotify.exe) is 32bit.
https://imgur.com/a/aYNKAUl

**Comment by jack11e** [comment]
i just used the powershell script without uninstalling anything and it worked

**Comment by OIKYO** [comment]
> Ever since like 2 days ago, I noticed I started getting ads even though I had used the program. Not sure if this is an issue on my side or the program needs to be updated.

Yeahh honestly idk whats wrong orwhat should i do bruh, guys please fix this!!!

**Comment by disruptedtech** [comment]
> so u cant update spotify if u want ad blocker working? cause i updated today spotify and ad blocked stopped working

I didn't update mine it just automatically updates :/

**Comment by zedd-0** [comment]
@all
please wait till the update is coming.

in the meantime:
- use the script or
- install the 32-bit offline installer each time after the update:
https://download.scdn.co/SpotifyFullSetup.exe

**Comment by Aryan1Kalra** [comment]
I tried installing with the script but still not working.

**Comment by chandrachristian** [comment]
I tried installing with the script, and other method but still not working.

**Comment by Subroutine7901** [comment]
> so u cant update spotify if u want ad blocker working? cause i updated today spotify and ad blocked stopped working

You can, but you have to reinstall BlockTheSpot and maybe Spotify.

> I didn't update mine it just automatically updates :/

You have to edit the .exe to stop updates, according to @TooYoungTooSimp 

> You can use any hex editor to open Spotify.exe and find a string `wg://desktop-update`
> 
> change its following to a nonexistent path, for example, change v2 to v5 or anything have the same length
> 
> ![image](https://user-images.githubusercontent.com/6648049/251508347-d1778747-692e-4f1c-b33e-22d3b9ede520.png)

**Comment by ejaxh** [comment]
for windows x64: [dpapi.zip](https://github.com/mrpond/BlockTheSpot/files/12137224/dpapi.zip)
[AdBlocker.zip](https://github.com/mrpond/BlockTheSpot/files/12137233/AdBlocker.zip)

**Comment by brewolf** [comment]
just installed new dpapi.dll and all good so far, many thanks.

**Comment by zedd-0** [comment]
works fine.
live-updater works, too.
i keep my eye open for bugs.
 :D

**Comment by ejaxh** [comment]
No problem, it's the updated version of the BlockTheSpot project. I just made some small changes.
![image](https://github.com/mrpond/BlockTheSpot/assets/39572540/0aaccc3b-d797-4e37-b8f1-aa3b171fdc3b)

**Comment by disruptedtech** [comment]
> for windows x64: [dpapi.zip](https://github.com/mrpond/BlockTheSpot/files/12138586/dpapi.zip) [virustotal](https://www.virustotal.com/gui/file/9aa95e7683252e3702ffb1455d15b8c0689fdc34b33a87979741f6cd69537c15?nocache=1)
> 
> source code: [AdBlocker.zip](https://github.com/mrpond/BlockTheSpot/files/12138480/AdBlocker.zip)

I am very new to all of this so I'm sorry for my ignorance, do I just open the dpapi file and then it's fixed? No more ads again?

**Comment by Nuzair46** [comment]
> for windows x64: [dpapi.zip](https://github.com/mrpond/BlockTheSpot/files/12138586/dpapi.zip) [virustotal](https://www.virustotal.com/gui/file/9aa95e7683252e3702ffb1455d15b8c0689fdc34b33a87979741f6cd69537c15?nocache=1)
> 
> source code: [AdBlocker.zip](https://github.com/mrpond/BlockTheSpot/files/12138480/AdBlocker.zip)

Can you explain what these files do?
are they modified to support 64bit? If so, please consider making a PR.

**Comment by ejaxh** [comment]
I have modified the BlockTheSpot project, you can check it out here.

[BlockTheSpot.zip](https://github.com/mrpond/BlockTheSpot/files/12139213/BlockTheSpot.zip)

**Comment by Nuzair46** [comment]
@ejaxh can you comment the issues this solves?
And can you make a PR for this so we can release it.
Thanks

**Comment by Subroutine7901** [comment]
> > for windows x64: [dpapi.zip](https://github.com/mrpond/BlockTheSpot/files/12138586/dpapi.zip) [virustotal](https://www.virustotal.com/gui/file/9aa95e7683252e3702ffb1455d15b8c0689fdc34b33a87979741f6cd69537c15?nocache=1)
> > source code: [AdBlocker.zip](https://github.com/mrpond/BlockTheSpot/files/12138480/AdBlocker.zip)
> 
> I am very new to all of this so I'm sorry for my ignorance, do I just open the dpapi file and then it's fixed? No more ads again?

You follow the manual instructions in the README.md, but using the new dpapi from this thread instead of the old one.

**Comment by disruptedtech** [comment]
I guess I'll just wait for mrpond to update it, going to use spotify on web version for a while since adblock works...

**Comment by PwccaCode** [comment]
> I guess I'll just wait for mrpond to update it, going to use spotify on web version for a while since adblock works...

the x64 version is working fine.

**Comment by Hussi98** [comment]
> > I guess I'll just wait for mrpond to update it, going to use spotify on web version for a while since adblock works...
> 
> the x64 version is working fine.

can you help me find this x64 version?

**Comment by Subroutine7901** [comment]
> can you help me find this x64 version?


> for windows x64: [dpapi.zip](https://github.com/mrpond/BlockTheSpot/files/12138586/dpapi.zip) [virustotal](https://www.virustotal.com/gui/file/9aa95e7683252e3702ffb1455d15b8c0689fdc34b33a87979741f6cd69537c15?nocache=1)
> 
> source code: [AdBlocker.zip](https://github.com/mrpond/BlockTheSpot/files/12138480/AdBlocker.zip)
@Hussi98 Here.
