### ISSUE TITLE
installation bug 

### ISSUE THREAD

**Issue by titoup12** [mrpond/BlockTheSpot#462]
hey!
i have this bug when i install and when i press enter it says i have installed it but the pubs are still in .
![1](https://github.com/mrpond/BlockTheSpot/assets/82751691/50e78825-0e1d-4a79-954b-048eddcacc1f)
![2](https://github.com/mrpond/BlockTheSpot/assets/82751691/35bb6ee8-a79c-4d5f-af8f-4c00cf2c51c9)
thanks 👍 !

**Comment by Geczy** [comment]
english?

**Comment by titoup12** [comment]
it works now . idk why butit works.
