### ISSUE TITLE
feedback.added-to-playlist-specific

### ISSUE THREAD

**Issue by soraimperial** [mrpond/BlockTheSpot#463]
I have recently updated to the May version (after fully removing the program because it kept updating everytime I turned my PC off and bringing back the ads) and since installing this version, I have been getting the generic pop-up "feedback.added-to-playlist-specific" after adding songs to a playlist.

This never happened in previous versions.
I tested a bit around (but I'm not that much of an expert) and it perhaps seems to be a UI issue with UK English? (I get the normal message when I change to regular english on the preferences).
Edit: Just to clarify, I don't know if this is an original software issue or something introduced by blockthespot.

**Comment by astrexxx** [comment]
are you still getting ads btw ? because i am

**Comment by sssajjad007** [comment]
> are you still getting ads btw ? because i am

same

**Comment by mrpond** [comment]
see https://github.com/mrpond/BlockTheSpot/issues/461
