### ISSUE TITLE
Ad banners reapeared, in betwin song ads seem to still be disabled, but banners with full content reapeared even after clear install

### ISSUE THREAD

**Issue by KamaronDX** [mrpond/BlockTheSpot#464]
### Important
- Issue related to AutoInstaller should be opened at [SpotX](https://github.com/amd64fox/SpotX)

---
### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Zip and attach the log file.

---

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [SpotX](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Basic.bat) and is still having issues.
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through [SpotX FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22The-remote-name-could-not-be-resolved%22-while-running-the-install)
 - [ ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by elendil7** [comment]
Yes, same issue here. Lets hope it gets fixed post-haste.

**Comment by elendil7** [comment]
****UPDATE****: All features work fine again (ads are blocked etc) after re-running the powershell script in the README file.

**Comment by PwccaCode** [comment]
Just did a new install tried several times, still having in mid song ads and banners

**Comment by samnum** [comment]
Temporary solution: install the offline version of Spotify here (https://download.scdn.co/SpotifyFullSetup.exe) and then open the executable file with a hex editor and modify a part of the update url otherwise the app will auto-update every time you launch spotify (credit to tooyoungtosimp: https://github.com/mrpond/BlockTheSpot/issues/461#issuecomment-1623939022)

This has been working for me so far and no banner/ad breaks have come up so far

**Comment by soraimperial** [comment]
I have a half issue - empty/grayed out ad banner comes up below songs, but no ads mid song. Also, weirdly, only happens in one computer (even though I have the same versions, same windows, on both).

**Comment by benny999x** [comment]
run this in powershell in admin:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify"

**Comment by TheArgentinian** [comment]
> run this in powershell in admin, it fixes it: elendil7 also found this.
> 
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify"

did anyone else get an error message in red at the end? still worked, though
