### ISSUE TITLE
"Lives through Spotify updates. No need to patch Spotify after every update anymore."

### ISSUE THREAD

**Issue by TheArgentinian** [mrpond/BlockTheSpot#465]
Not true. You still have to run BlockTheSpot.bat after every update.

**Comment by bryan-sto** [comment]
> Not true. You still have to run BlockTheSpot.bat after every update.

as for this Spotify version below it doesn't block ads or banner anymore I think because they migrated to 64 bit version
Spotify for Windows (64 bit)
1.2.15.828.g79f41970

**Comment by machines-github** [comment]
Spotify für Windows (64 Bit)
1.2.15.828.g79f41970

Same, doesn't block ads etc. anymore

**Comment by TheArgentinian** [comment]
Open windows powershell and copy this: https://github.com/mrpond/BlockTheSpot/issues/464#issuecomment-1635178629
