### ISSUE TITLE
Still having ads/banner after complete reinstall

### ISSUE THREAD

**Issue by BigBoss320** [mrpond/BlockTheSpot#472]
### Important
- Issue related to AutoInstaller should be opened at [SpotX](https://github.com/amd64fox/SpotX)

---
### Describe the bug
I am using the latest desktop version of spotify, re-run several times the .bat file. Completely re-install Spotify with the official website or by using the .bat file. Searched for an eventual issue that looks like mine, as apparently the fix was a complete re-install.
I also tried copying the chrome_elf.dll and dpapi.dll from the latest update manually.
Still having ads, banner and the "Discover Premium" button.

![image](https://github.com/mrpond/BlockTheSpot/assets/44122706/f5dd4712-1a94-407a-8524-3f77828062a0)
![image](https://github.com/mrpond/BlockTheSpot/assets/44122706/6fb8deb4-7e0b-42e7-adba-38464bd4d636)

Zip and attach the log file.

---

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [SpotX](https://raw.githack.com/amd64fox/SpotX/main/scripts/Install_Basic.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through [SpotX FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-get-the-error-%22The-remote-name-could-not-be-resolved%22-while-running-the-install)
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by mrpond** [comment]
Hi, start from newer version, please use 64bit Spotify instead of 32Bit.

**Comment by VoDSeth** [comment]
> Hi, start from newer version, please use 64bit Spotify instead of 32Bit.

Is there a 64bit for windows I cant find anything on it. I just fresh installed spotify as well straight from the website and its also 32bit

**Comment by mrpond** [comment]
I see, here it is https://github.com/mrpond/BlockTheSpot/releases/tag/2023.5.20.80

note: we're now stop support 32bit version, but it still continue to work for a while.

**Comment by BigBoss320** [comment]
Oh so the bat fil still downloads the 32 bit version?
Let's try it with the 64 bit one

**Comment by purplepew** [comment]
"You enabled logging by editing config.ini set log = 1."
 
there is no expression log. only Enable_log=0. should i replace it with 1?
