### ISSUE TITLE
new version x64 only?

### ISSUE THREAD

**Issue by zedd-0** [mrpond/BlockTheSpot#473]
do yo not make a x86/32bit version any more?

edit:
there is a ARM64 version also,
this could be interesting in future versions.
https://download.scdn.co/SpotifyFullSetupARM64.exe

does anyone use Windows on ARM?

**Comment by mrpond** [comment]
Yes, 32bit hook will continue working for a while.
Since pattern matching code still work.
But I choose to drop 32bit support because I will start using 64bit Spotify myself too.

ARM64 will take little time, ARM and Intel Assembly language is different.

**Comment by zedd-0** [comment]
It would be nice,
if you could use a consistent naming scheme

like:
 chrome_elf.x86.zip 
 chrome_elf.x64.zip 
 chrome_elf.arm64.zip

actual on the release page you cannot see
the differences between version 2023.5.20.80 & 2023.7.26.93.
it would be helpful, if you change it.

**Comment by mrpond** [comment]
>_< I still don't know how to config appveyor on this matter.
I'll look into it when I had time.

**Comment by VoDSeth** [comment]
Where do I find this 64bit spotify?

**Comment by Nuzair46** [comment]
@mrpond can you give me access to make changes to github actions?
We can user github actions to build and release which is easily configurable compared to appveyor

**Comment by zedd-0** [comment]
> Where do I find this 64bit spotify?
you cannot really find the links, they are undocumented.

i played around with the url-names + online research
here all the links i did discovered:

Web-Installer:
https://download.scdn.co/SpotifySetup.exe
https://download.scdn.co/SpotifySetupX64.exe
https://download.scdn.co/SpotifySetupARM64.exe

Full-Installer:
https://download.scdn.co/SpotifyFullSetup.exe
https://download.scdn.co/SpotifyFullSetupX64.exe
https://download.scdn.co/SpotifyFullSetupARM64.exe

Misc:
https://download.scdn.co/SpotifyFull7-8-8.1.exe (for Windows 7/8/8.1)
https://download.scdn.co/SpotifyBetaARM64.exe (old beta for Windows on ARM64)

**Comment by mrpond** [comment]
> 

Check MSDN document site. I use something like this, but I don't had time to play with github action at the moment.

`MsBuild /t:rebuild /p:DebugSymbols=true /p:DebugType=full /p:Configuration="Release" /p:platform=x86 xxxxx.sln`
