### ISSUE TITLE
Problems with Spotify desktop after running BlockTheSpot

### ISSUE THREAD

**Issue by sexual-orientation-disorder** [mrpond/BlockTheSpot#476]
Problems with Spotify desktop after running BlockTheSpot
![屏幕截图 2023-07-29 160652](https://github.com/mrpond/BlockTheSpot/assets/140881444/9c57fe8f-8609-4feb-a9f0-cbc63bbb78e5)
![屏幕截图 2023-07-29 161027](https://github.com/mrpond/BlockTheSpot/assets/140881444/50c3d376-99a1-4613-809a-70ecff29b4a6)

**Comment by Nuzair46** [comment]
This is not likely an issue with the patch rather likely your internet.

**Comment by xididri** [comment]
Same issue here, after installing patch 2023.8.14.95. Spotify slow to launch then unable to play any song. After reinstalling spotify (without the patch), everything works as expected. Running `BlockTheSpot.bat` then problem reappears. Unfortunately it is related to the patch.

**Comment by Chaython** [comment]
its from the windscribe vpn? it looks like that's running anyways....
