### ISSUE TITLE
Problems with the newest patch

### ISSUE THREAD

**Issue by Izayoiabafur** [mrpond/BlockTheSpot#477]
![image](https://github.com/mrpond/BlockTheSpot/assets/86138037/e4b995b5-3ca2-4d36-8e84-45c822844e73)
![image](https://github.com/mrpond/BlockTheSpot/assets/86138037/3d599dbe-23e8-4133-a59b-1d968694287e)
Cant sync with my account on other devices, cant play on other devices

**Comment by Nuzair46** [comment]
this is not caused by the patch. its something else. ask Spotify support
