### ISSUE TITLE
Explore premium button

### ISSUE THREAD

**Issue by iloveuFlyTek** [mrpond/BlockTheSpot#478]
I cannot remove this button
![Screenshot 2023-07-30 200610](https://github.com/mrpond/BlockTheSpot/assets/59393682/6b96030c-3c7f-48d6-ac9d-d10e44ee8d05)

**Comment by mrpond** [comment]
make sure you install 64bit spotify with the latest release of BTS

**Comment by ItxWeird** [comment]
> make sure you install 64bit spotify with the latest release of BTS

Did this with no success. Any advice?

**Comment by enterv0id** [comment]
Same problem. It worked until a day ago.

**Comment by ItxWeird** [comment]
Would like a follow up on this!
