### ISSUE TITLE
these banners started popping up today for me

### ISSUE THREAD

**Issue by ThonkPT** [mrpond/BlockTheSpot#48]
![Spotify_WEpQ2GpodE](https://user-images.githubusercontent.com/57663757/82968204-aa6e8e80-9fc4-11ea-9c6e-3a6bb1d5f5b3.png)

**Comment by rednek46** [comment]
I don't see any. whats your spotify version?

**Comment by mrpond** [comment]
make sure you read everything, e.g. reapply patch blah blah.
if it still not working, turn on the log in config & upload it here.

**Comment by pseudobacon** [comment]
It's broken in 1.1.33.569.gced9e0f5. Does anyone have a good way of blocking the updates to the Desktop app?

**Comment by rednek46** [comment]
> It's broken in 1.1.33.569.gced9e0f5. Does anyone have a good way of blocking the updates to the Desktop app?

using the same version and it still works fine. there is no good method to prevent updates for Spotify and this repo only supports **Latest** Spotify. check out the above comment.

**Comment by ThonkPT** [comment]
im on 1.1.4.197.g92d52c4f

**Comment by ThonkPT** [comment]
idk why its not showing up now but thanks for the help anyways

**Comment by rednek46** [comment]
> im on 1.1.4.197.g92d52c4f i used the batch script for installation

when did you get this update?
