### ISSUE TITLE
Bitrate selection "Unlocks all premium features except downloads."

### ISSUE THREAD

**Issue by Chaython** [mrpond/BlockTheSpot#480]
Can only set high quality in GUI, debug says 160 is the current bitrate.
Perhaps readme should be updated to say it only blocks ads? As all other premium features seem to be missing?
Thanks.

**Comment by Nuzair46** [comment]
Good catch. we are waiting to decide on #481 and will update it accordingly

**Comment by mrpond** [comment]
Hi, we focus on ads block only. 
song download will never implement into BTS.
