### ISSUE TITLE
the app doesn't work every time a major update happens on windows 11 beta

### ISSUE THREAD

**Issue by giuseppegg02** [mrpond/BlockTheSpot#485]
As mentioned in the title whenever a major update is launched in windows 11 on the beta channel the application even if in fact it still exists on the pc does not work 
the process in the task manager is closed automatically for after a few seconds, no anti virus error or anything else comes up

the application returns to work by installing it again

**Comment by Nuzair46** [comment]
sounds like issue caused with Windows 11 beta. this is not the place for a solution
