### ISSUE TITLE
how do i set it up?

### ISSUE THREAD

**Issue by TOOGOODFORYOAHH** [mrpond/BlockTheSpot#488]
i tried to install it in powershell and it wasnt working
![Screenshot 9_7_2023 12_15_38 PM](https://github.com/mrpond/BlockTheSpot/assets/144326526/d181b351-0075-4432-9c83-8fab2db13a36)
and when i press y it takes me to spotify but theres still ads

**Comment by Nuzair46** [comment]
This is not our repo.
please be careful of where you run the commands from. Please use the readme in this repo
