### ISSUE TITLE
error

### ISSUE THREAD

**Issue by phpladyy** [mrpond/BlockTheSpot#489]
this is my commandline after opening blockthespot.bat 
*****************
@revinewyd message:
Follow my socials!                                                                                                      https://myurls.co/revinewyd                                                                                             *****************                                                                                                       *****************                                                                                                       Author: @revinewyd                                                                                                      *****************                                                                                                       Stopping Spotify...

Downloading latest patch (chrome_elf.zip)...

Patching Spotify...
Copy-Item : Cannot find path 'C:\Users\PC\AppData\Local\Temp\BlockTheSpot-2023-09-26_19-18-16\chrome_elf.dll' because i
t does not exist.
At line:147 char:1
+ Copy-Item -LiteralPath $patchFiles -Destination "$SpotifyDirectory"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\PC\App...\chrome_elf.dll:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

![image](https://github.com/mrpond/BlockTheSpot/assets/134269199/3115bbfc-96e8-4fb0-acaf-ce8e94e290ce)

**Comment by phpladyy** [comment]
ofc i cant turn on spotify

**Comment by Nuzair46** [comment]
This is what happens when you blindly run a script. Make sure you downloaded it from this source and not somewhere else

**Comment by phpladyy** [comment]
i downloaded it from there
