### ISSUE TITLE
Facebook sidebar still not work

### ISSUE THREAD

**Issue by zakblacki** [mrpond/BlockTheSpot#49]
I uninstalled and reinstalled completely both Spotify and the patch 
but same issue I can't seem to make the friends sidebar appear although it seem to work on my laptop
any ideas ?
![image](https://user-images.githubusercontent.com/29728429/83288786-ddd73600-a1db-11ea-8736-c88bd9c8f8fd.png)

**Comment by mrpond** [comment]
you mean this ?
![image](https://user-images.githubusercontent.com/18654771/83340369-5257c500-a301-11ea-92b6-e8d264628773.png)

**Comment by zakblacki** [comment]
> you mean this ?
> ![image](https://user-images.githubusercontent.com/18654771/83340369-5257c500-a301-11ea-92b6-e8d264628773.png)

Yes !  It's really weird doesn't appear for me

**Comment by rednek46** [comment]
> > you mean this ?
> > ![image](https://user-images.githubusercontent.com/18654771/83340369-5257c500-a301-11ea-92b6-e8d264628773.png)
> 
> Yes ! It's really weird doesn't appear for me it's already enabled I don't have the right sidebar

It works for me. **Note That Facebook friends bar only works if your Friends listen to Spotify in PC**.
This bar doesn't show you friends if they listen on mobile.

**Comment by rednek46** [comment]
![Capture3](https://user-images.githubusercontent.com/38219313/83348584-ba32fd80-a34b-11ea-9378-d6d75f9a002e.PNG)
it works.

**Comment by zakblacki** [comment]
After some search it appear to be a bug from spotify 
like I said I have another computer which works fine doesn't matter if your friends using pc or phone it work both ways 
I'm closing this since it's not related to the patch 
Thanks.
