### ISSUE TITLE
account got banned

### ISSUE THREAD

**Issue by RelvinArsenio** [mrpond/BlockTheSpot#490]
![image](https://github.com/mrpond/BlockTheSpot/assets/88470966/07c6ce1d-34c2-4264-81ec-2984499093a7)

![image](https://github.com/mrpond/BlockTheSpot/assets/88470966/6100a4ce-61fd-42d8-9d89-70d1cca8d19f)

My account got banned :(

**Comment by Nuzair46** [comment]
You probably used other Spotify adblocker or tried to illegally download songs.
