### ISSUE TITLE
"Unable to connect to the remote server

### ISSUE THREAD

**Issue by CyberGhost1001** [mrpond/BlockTheSpot#495]
![Screenshot (46)](https://github.com/mrpond/BlockTheSpot/assets/55405723/0a3fbeea-80fc-408e-bab8-d3f5b71571d3)

This happens when I run the .bat file. I have used blockTheSpot before and it worked.
I reset my PC recently and when I used the file again, this is happening.
Any fixes?

**Comment by mrpond** [comment]
Hi, can you download the .zip file from github release section?
