### ISSUE TITLE
BTS not functioning

### ISSUE THREAD

**Issue by hharrisonn** [mrpond/BlockTheSpot#496]
for about a week and a half, every time I open BTS it opens to a blank window that cannot be dragged by the cursor. sometimes if I waited long enough spotify will show as normal but unable to play any music. If I try to close and reopen spotify, an error saying Spotify application not responding. I have ran the .bat multiple times and the same thing keeps happening. please help.

**Comment by Nuzair46** [comment]
Try without BTS.
