### ISSUE TITLE
Bug ig

### ISSUE THREAD

**Issue by PrakharBartwal** [mrpond/BlockTheSpot#497]
Hi @mrpond 
I am getting this error whenever I try to run BlockTheSpot + Spicetify.bat
Same with BlockTheSpot.bat
![Screenshot 2023-10-25 235029](https://github.com/mrpond/BlockTheSpot/assets/104559001/ee55272c-c49c-490e-b918-0f367421e150)

**Comment by Nuzair46** [comment]
Check the readme and install without spicetify
