### ISSUE TITLE
"Play from another device" Premium Feature Locked

### ISSUE THREAD

**Issue by coda101** [mrpond/BlockTheSpot#503]
I want to control and stream to another device via Spotify but the feature is locked as Premium. 

Is it possible to unlock?

![Screenshot 2023-12-02 185311](https://github.com/mrpond/BlockTheSpot/assets/126429288/614dd1e4-daeb-4647-8005-9fd1018c7518)

**Comment by mrpond** [comment]
Hi, I never use that feature. but it maybe working if you use some android Spotify (apk mod) with premium.

**Comment by coda101** [comment]
What I want to do is plug my phone into my stereo amp and use my laptop in bed. Then I would control what is being played on the phone app, from my desktop app. Essentially a cheap streamer. The apk mod does do the reverse of what I want.

**Comment by mrpond** [comment]
I’ll will have a look into it,

**Comment by ItxWeird** [comment]
> Hi, I never use that feature. but it maybe working if you use some android Spotify (apk mod) with premium.

Doesn't change a thing, SpotX has this feature, would be greatly appreciated if BTS has it as well
