### ISSUE TITLE
The automatic installation script did not detect platform architecture

### ISSUE THREAD

**Issue by Tiiiiiida** [mrpond/BlockTheSpot#504]
Spotify does support Win on ARM. While the script auto installation will always download and install Spotify X64. Meanwhile, the official online installation package of Spotify supports an automatic detection platform architecture. Maybe the installation can be changed to the official online installation package.

**Comment by Nuzair46** [comment]
This patch may not work with windows arm.
If you can, please install the Spotify from their website and apply the patch manually without the script. If it works, then let us know and we will update the script

**Comment by Tiiiiiida** [comment]
Unfortunately, it doesn't work on Win on arm.
Spotify for Windows (ARM64)
1.2.26.1187.g36b715a1
