### ISSUE TITLE
No Lyrics button..

### ISSUE THREAD

**Issue by Ejobat** [mrpond/BlockTheSpot#505]
Even though I enabled the `enableRightSidebarLyrics`, it's not showing up.

![Screenshot (10)](https://github.com/mrpond/BlockTheSpot/assets/56921073/c8f995ea-20e7-4547-8503-cdc28f9cfa93)

![Screenshot (9)](https://github.com/mrpond/BlockTheSpot/assets/56921073/074aab9b-8cc3-4860-a89b-bf80a2ca182e)

**Comment by Nuzair46** [comment]
Sadly lyrics was removed from free spotify. Please check into https://github.com/nuzair46/lyrixed
