### ISSUE TITLE
network issue 

### ISSUE THREAD

**Issue by kedar49** [mrpond/BlockTheSpot#506]
Invoke-WebRequest : Unable to connect to the remote server
At line:1 char:85
+ ... pe]::Tls12; Invoke-WebRequest -UseBasicParsing 'https://raw.githubuse ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
![Screenshot 2024-01-01 231915](https://github.com/mrpond/BlockTheSpot/assets/124454984/a3582c79-3f7f-46ac-9bb8-b30fa76d7d70)

**Comment by Nuzair46** [comment]
Do manual installation.
