### ISSUE TITLE
BlockTheSpot.bat fails to download chrome_elf.zip

### ISSUE THREAD

**Issue by shadopawn** [mrpond/BlockTheSpot#51]
Below is what shows up in the command prompt

*****************
Author: @rednek46
*****************
Stopping Spotify...

Downloading latest patch (chrome_elf.zip)...

Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At C:\Users\JARAINES\Downloads\BlockTheSpot-master\ps.ps1:51 char:3
+   $webClient.DownloadFile(
+   ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

cmdlet Start-Sleep at command pipeline position 1
Supply values for the following parameters:
Seconds:

**Comment by rednek46** [comment]
@shadopawn this issue was already registered and solved.
see [this](https://github.com/mrpond/BlockTheSpot/issues/42#issuecomment-615973812).

**Comment by shadopawn** [comment]
thank you adding
`[Net.ServicePointManager]::SecurityProtocol = "tls12"`
to the bat file worked for me

**Comment by ZapNapDev** [comment]
after downloading/installing block spot , i cant update my spotify windows app.

**Comment by rednek46** [comment]
> after downloading/installing block spot , i cant update my spotify windows app.

BlockTheSpot is not for Windows store Spotify.
And the .bat file clearly says it and ask if you wanna remove the Spotify Windows app.
You could only use anyone of the spotify at a time.

**Comment by rednek46** [comment]
> thank you adding
> `[Net.ServicePointManager]::SecurityProtocol = "tls12"`
> to the bat file worked for me

@shadopawn please close this issue. since its working for you now.

**Comment by ZapNapDev** [comment]
> > after downloading/installing block spot , i cant update my spotify windows app.
> 
> BlockTheSpot is not for Windows store Spotify.
> And the .bat file clearly says it and ask if you wanna remove the Spotify Windows app.
> You could only use anyone of the spotify at a time.

Ohh I'm realy sorry sir, i mean desktop app (download from Spotify website) not the windows app!!

So, when i go to about option on Spotify then it's shows  click here to download latest version, after it downloaded it ask me to restart Spotify app. After restart it again showing click here to download latest version , it doesn't update everytime I try this.

That's why I am asking , do i have to uninstall Spotify desktop app everytime whenever a new  update comes.

**Comment by rednek46** [comment]
> > > after downloading/installing block spot , i cant update my spotify windows app.
> > 
> > 
> > BlockTheSpot is not for Windows store Spotify.
> > And the .bat file clearly says it and ask if you wanna remove the Spotify Windows app.
> > You could only use anyone of the spotify at a time.
> 
> Ohh I'm realy sorry sir, i mean desktop app (download from Spotify website) not the windows app!!
> 
> So, when i go to about option on Spotify then it's shows click here to download latest version, after it downloaded it ask me to restart Spotify app. After restart it again showing click here to download latest version , it doesn't update everytime I try this.
> 
> That's why I am asking , do i have to uninstall Spotify desktop app everytime whenever a new update comes.

No you dont have to uninstall spotify. it looks like an issue at your end where spotify update is not working.
After updating, you have to run the bat file again to block ads.
about your issue, contact spotify support.

**Comment by mrpond** [comment]
meow, just update Spotify to latest version.
after that run blockthespot.bat.

this fork didn't block spotify update, we highly recommended to use latest version of software.
