### ISSUE TITLE
Seems a compatibility problem between MyDockFinder and BlockTheSpot

### ISSUE THREAD

**Issue by RosieDu21** [mrpond/BlockTheSpot#510]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

I'm using [MyDockFinder](https://www.mydockfinder.com/index_en.html), and I met a strange problem:

- When run spotify by double click spotify.exe in the explorer, it works
- When create a lnk to spotify.exe and double click the lnk, it works
- When run spotify through the Win+r, it works
- When drag the lnk to the dock (of mydockfinder) and click the icon on dock, it works
- When drag the spotify.exe to the dock and click the icon on dock, the spotify can be started, but BlockTheSpot **DOESN'T** work anymore

At beginning, I thought this might be resulted from that the MyDockFinder may add some extra args. However, when I wrote an exe file to print all parameters sent in, dragged it to dock and simply run it from dock, the result shows it doesn't add any args. So I suppose this is a compatibility problem. 

I also tried to find something from the log file, but I found when your mod doesn't work, there would even be no log file! Only in the first four cases above, there is a new log file created. (Of course, I renamed the log file after each test.)

I've also reported this issue to the official of MyDockFinder, but haven't got any reply yet. Because I'm not sure which app caused this issue, I also post this’issue here. Hope I'm in a right place.

Wish you can notice this and fix it. Thanks a lot!

Btw, I'm curious about if there is really any way to start BlockTheSpot purely (i.e. without this mod)?

**Comment by Nuzair46** [comment]
This is weird. Is it possible to drag the Ink to MyDockFinder?

**Comment by RosieDu21** [comment]
> This is weird. Is it possible to drag the Ink to MyDockFinder?

@Nuzair46 

Yes, it's possible, as I mentioned in case 4, it works, and this is also the way I currently use to avoid this problem. But it's, after all, an alternative.

**Comment by Nuzair46** [comment]
I'm not sure why this is an issue but seems out of scope for this patch.
