### ISSUE TITLE
Upgrade button not getting disabled

### ISSUE THREAD

**Issue by DIMIOURGIA13** [mrpond/BlockTheSpot#515]
I tried going to the debug window and disabled the "upgradeButtonCopyTest" but it still shows and works, tried reinstalling and setting different modes but the same issue.
![Screenshot 2024-02-12 225218](https://github.com/mrpond/BlockTheSpot/assets/94043064/8d14a2cc-ab0c-4f98-920f-4762e86c5f00)

**Comment by Nuzair46** [comment]
same as #516
