### ISSUE TITLE
Source destination incorrect?

### ISSUE THREAD

**Issue by matt-derrick** [mrpond/BlockTheSpot#519]
- [ x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [ x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ x] You uninstalled Spotify and just ran the patch
 - [ x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ x] You enabled logging by editing config.ini `set log = 1`.
 - [ x] Make sure whether an issue related yours is already open or not.
 - [ x] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

`Downloading the latest Spotify full setup, please wait...
Start-BitsTransfer : Object reference not set to an instance of an object.
At line:49 char:5
+     Start-BitsTransfer -Source $Uri -Destination "$($TargetFile.FullN ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.BackgroundIntelligentTransfer.Ma  
   nagement.NewBitsTransferCommand`

I get the above when running the bat file. Let me know if there's any other info I can provide.

**Comment by Nuzair46** [comment]
Try manual installation. Github raw links probably blocked by your provider
