### ISSUE TITLE
Switching device requires Premium

### ISSUE THREAD

**Issue by PolCeru** [mrpond/BlockTheSpot#521]
- [ ] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.

---

I'm not sure if this is a bug report or a feature request; I was able to switch devices without having premium in earlier versions.
I'm on the latest version of Spotify (which is not tested)

Spotify for Windows (64 bit)
1.2.32.997.g4c6498b6
xpui_2024-02-23_1708709925614_4c6498b
cef_121.3.15+g4d3b0b4+chromium-121.0.6167.184
Runtime: Chrome

![dev](https://github.com/mrpond/BlockTheSpot/assets/100514524/26a4ae3d-7e8d-47b3-9324-b8ba1dbe5739)

I don't think this can be useful, but here's the log
[blockthespot.log](https://github.com/mrpond/BlockTheSpot/files/14523020/blockthespot.log)

**Comment by ItxWeird** [comment]
> spotify made this a premium feature a while ago and have been rolling out slowly. I can't guarantee that if this repo will ever make it possible

SpotX does it, why can't this?
