### ISSUE TITLE
How to verify patched version?

### ISSUE THREAD

**Issue by zstdadi** [mrpond/BlockTheSpot#523]
After manual patcing two files, How to verify the patch is successfully?

**Comment by Nuzair46** [comment]
You can enable logging in config.ini and if everything done correctly, you can see the blockthespot.log file in the spotify directory. You can read it to know if everything is blocked.

**Comment by zstdadi** [comment]
According to https://open.spotify.com/premium, How do I verify these features in the PC client software?

**Comment by Nuzair46** [comment]
in short we only block ads. nothing else.
