### ISSUE TITLE
Spotify Connect

### ISSUE THREAD

**Issue by qeez3** [mrpond/BlockTheSpot#527]
Is the 'connect to a device in the network' feature not at all possible ?
![image](https://github.com/mrpond/BlockTheSpot/assets/126232285/f07fc2cb-9f46-4f74-88e3-02b2e1f867f7)
Aside from that, great software cheers.

**Comment by XdekHckr** [comment]
try using spotify on phone to control other devices playing music -_-

**Comment by Nuzair46** [comment]
This wont be done as of now as this might not be possible. closing for now
