### ISSUE TITLE
Features correction needed

### ISSUE THREAD

**Issue by Dantasstic** [mrpond/BlockTheSpot#528]
> Features:
> Unlocks all premium features except downloads.

This is incorrect, as it does not allow you to set the audio quality to "Very High", which is a Premium feature.

It should be amended to state: "Unlocks all premium features except downloads, and "Very High" audio quality."

**Comment by Nuzair46** [comment]
@Dantasstic good catch. you can open a PR if you want.

**Comment by Dantasstic** [comment]
> @Dantasstic good catch. you can open a PR if you want.

Done :)

**Comment by Nuzair46** [comment]
fixed with #529
