### ISSUE TITLE
solution for Mac Os X

### ISSUE THREAD

**Issue by pilot1981** [mrpond/BlockTheSpot#53]
Hi,
you have a solution also for Mac OS X?

**Comment by rednek46** [comment]
> Hi,
> you have a solution also for Mac OS X?

😄 No dude. This is only for Windows Desktop version. There is no Mac version available anywhere, Not even for linux.

**Comment by mrpond** [comment]
Hmm, Mac OS X.. I don't have hardware to devtest it. 
but it should work like linux version, https://github.com/abba23/spotify-adblock-linux
