### ISSUE TITLE
can't open lyrics (need premium account).

### ISSUE THREAD

**Issue by bayuzzs** [mrpond/BlockTheSpot#534]
- [✅ ] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [✅ ] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ ] You uninstalled Spotify and just ran the patch
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [ ] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by bayuzzs** [comment]
![image](https://github.com/mrpond/BlockTheSpot/assets/77946987/fd21cd5c-334b-4fda-b3cc-2f0ecda6869f)

**Comment by Timtaran** [comment]
server send only first 5 lines. ![изображение](https://github.com/mrpond/BlockTheSpot/assets/60805088/ae8626de-9ac6-4436-ba1d-755ed9d4553c)

**Comment by Nuzair46** [comment]
Spotify made it premium only. Please use Spicetify to add lyrics extensions
