### ISSUE TITLE
Lyric not available?

### ISSUE THREAD

**Issue by Axgis** [mrpond/BlockTheSpot#535]

**Comment by invinciblevenom** [comment]
Doesn't work after Spotify for Windows (64 bit) 1.2.37.701.ge66eb7bc update, which is also not a tested version for patch.

**Comment by Nuzair46** [comment]
Im working on [Lyrixed](https://github.com/Nuzair46/Lyrixed) for this issue.

Closing it here since it wont be fixed by BlockTheSpot
