### ISSUE TITLE
Change old/new theme

### ISSUE THREAD

**Issue by Skyroads7** [mrpond/BlockTheSpot#536]
Can you please tell me how to change the old/new theme in the developer options.
i couldn't find it.
And the lyrics page is also now behind the paywall,can u please look into it.

thank you.

**Comment by invinciblevenom** [comment]
There is no way to revert to old theme now. earlier there was a workaround. Though, you can try different themes through Spicetify.

**Comment by Nuzair46** [comment]
Its not worth it to provide in this repo. You can try Spicetify for that, they will have the option to do so or use a custom theme.
