### ISSUE TITLE
Lyrics not available anymore (Spotify Premium Feature)

### ISSUE THREAD

**Issue by natsuu0101** [mrpond/BlockTheSpot#538]
![spotify_lyrics](https://github.com/mrpond/BlockTheSpot/assets/157824730/88590d35-6ce0-4e04-bc7e-b3fbb14f17b8)
Lyrics is now block by this message (Enjoy Lyrics with Spotify Premium). 
Can someone do something about that?

**Comment by Pacolance** [comment]
> ![spotify_lyrics](https://private-user-images.githubusercontent.com/157824730/331746787-88590d35-6ce0-4e04-bc7e-b3fbb14f17b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTQzNTcsIm5iZiI6MTcxNjA5NDA1NywicGF0aCI6Ii8xNTc4MjQ3MzAvMzMxNzQ2Nzg3LTg4NTkwZDM1LTZjZTAtNGUwNC1iYzdlLWIzZmJiMTRmMTdiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwNDQ3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmYwYjE4YzcyZDY1ZjkyYWVlOWZkYjBkOGZlNzUxZjQxNTRlMTNmNTQ0NjhlMjIwNmY4NThlNmJiN2FjZDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpw0U_Wk1OOAcShLMzrCJ7ofe89c9JFdsmpzIg3nIFo) Lyrics is now block by this message (Enjoy Lyrics with Spotify Premium). Can someone do something about that?

Yeah, I hope they fix it.

**Comment by TheWolfCraft1** [comment]
Everyone is having this issue, since this was never a feature for blockthespot in the first place. It would be nice to have someone assigned to this

**Comment by Nuzair46** [comment]
This is something im looking into with [Lyrixed](https://github.com/Nuzair46/Lyrixed).
Closing this issue here as it wont be solved by block the spot
