### ISSUE TITLE
Streaming on OBS with Spotify Widget Help

### ISSUE THREAD

**Issue by Christopher-Robins** [mrpond/BlockTheSpot#540]
- [x ] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x ] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x ] You uninstalled Spotify and just ran the patch
 - [ x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x ] You enabled logging by editing config.ini `set log = 1`.
 - [x ] Make sure whether an issue related yours is already open or not.
 - [ x] Make sure you have completed everything in the above checklist.

I am using the 6klabs widget for spotify during virtual streaming with OBS and something somehwhere along the line is making ads pop up in playing of music.  I have an adless experience when I am not streaming.  Is there something I can do to enable adless experience while streaming?

**Comment by Nuzair46** [comment]
I think it might be 6klabs widget itself. I stream with Spotify audio directly and it doesnt cause ads to pop up.

**Comment by Christopher-Robins** [comment]
> I think it might be 6klabs widget itself. I stream with Spotify audio directly and it doesnt cause ads to pop up.

Without streaming anything I noticed something by accident the other day.

I get ads with my phone (separate ad block spotify app), but only when I directly connect to my soundbar via Wi-Fi.  If I connect it via bluetooth I do not get ads.

Testing with my laptop, if I listen to music (20+ songs) on my soundbar via bluetooth I do not get ads.  When I switch to Wi-Fi connection on the soundbar I get the ads after 5 songs.

Any idea what it might be?

**Comment by Velosofy** [comment]
> I get ads with my phone (separate ad block spotify app), but only when I directly connect to my soundbar via Wi-Fi. If I connect it via bluetooth I do not get ads.

Because your soundbar talks directly to Spotify, so no adblocking happening there. Your phone/laptop just act as a remote control for your spotify soundbar.
