### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by JosieHeartt** [mrpond/BlockTheSpot#541]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

 With the latest change to lyrics on spotify making lyric access premium only, it no longer works with BlockTheSpot. Please update with a fix so that I can access lyrics again! Thanks!

**Comment by Nuzair46** [comment]
We can't make lyrics available. This is something we are currently working on to enable lyrics with Spicetify https://github.com/Nuzair46/Lyrixed
