### ISSUE TITLE
BlockTheSpot doesn't work currently(at least on my PC)!

### ISSUE THREAD

**Issue by Pacha21-droid** [mrpond/BlockTheSpot#543]
Hey guys. I've been using BlockTheSpot for listening on Spotify for a months without any problem at all. But today suddenly Spotify wasn't opening for some reason. I've played with things and found out that actually BlockTheSpot causes the program to not run at all. Tried reinstalling the app, also tried reinstalling BlockTheSpot but no effects. I'm not using the MS version btw. If someone reads this, please fix this ASAP, because you really don't have an idea how AWESOME thing you've created and how much obsessed I'm with Spotify.

**Comment by ekaliclua** [comment]
Hey, I'm experiencing the same issue. Whenever I uninstall Spotify and reinstall it using BTS, it works fine. However, every time I close Spotify, I have to reinstall it with BTS again.

**Comment by roboticxr** [comment]
hey heyy.. same here +1

**Comment by Nuzair46** [comment]
known issue please wait for the fix

**Comment by Nuzair46** [comment]
Can you guys try auto install again with the script?

**Comment by ekaliclua** [comment]
Seems good

**Comment by Nuzair46** [comment]
closing
