### ISSUE TITLE
Songs don't play

### ISSUE THREAD

**Issue by xavier124** [mrpond/BlockTheSpot#55]
**Describe the bug**
Songs don't play. They start playing and the timer continues, but no sound comes from spotify. Before installing this, everything was working fine, so it isn't an issue with my audio setup.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Spotify Version: 1.1.35.458.g891674f3
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by rednek46** [comment]
> **Describe the bug**
> Songs don't play. They start playing and the timer continues, but no sound comes from spotify. Before installing this, everything was working fine, so it isn't an issue with my audio setup.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 1909
> * Spotify Version: 1.1.35.458.g891674f3
> * BlockTheSpot Product Version: 0.51.0.0

Spotify version 1.1.36.734.g8731c306 was released.
Uninstall your current Spotify and run BlockTheSpot.bat again. It will automatically install the latest Spotify and patch for you.

If that doesn't fix the issue, make sure you haven't muted Spotify in your Windows 10 Volume mixer. Refer the pic below.
![Capture](https://user-images.githubusercontent.com/38219313/86768622-7da1a280-c06b-11ea-8079-868af8431634.PNG)

**Comment by xavier124** [comment]
thanks for this, scoop was reporting spotify as the latest, but it was in fact not

**Comment by rudolphos** [comment]
I have a similar problem. Most songs only play 5-7 seconds and then stop, many songs don't play at all and stay at 0:00. Then the blue banner shows up 'Can't play the current song.'.
![image](https://user-images.githubusercontent.com/4366810/89062851-d7963f00-d36f-11ea-847f-5e000e85f9b4.png)

Version: 1.1.38.558.g4b100958

**Comment by rednek46** [comment]
> I have a similar problem. Most songs only play 5-7 seconds and then stop, many songs don't play at all and stay at 0:00. Then the blue banner shows up 'Can't play the current song.'.
> ![image](https://user-images.githubusercontent.com/4366810/89062851-d7963f00-d36f-11ea-847f-5e000e85f9b4.png)
> 
> Version: 1.1.38.558.g4b100958

Make sure you have a good internet connection or check if the music quality is not set to max.  
Im not sure this can cause the issue, but since Spotify uses p2p, make sure your isp isn't blocking it.  
 Another thing, if you are on a laptop and using bluetooth headsets, the bluetooth will take up the common antenna which will overall reduce the wifi speed.
