### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by light2k4** [mrpond/BlockTheSpot#553]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [ ] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ ] You uninstalled Spotify and just ran the patch
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [ ] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by Avestair** [comment]
spotify just got an update and u should wait for the updated version of patch aswell

**Comment by TheR0cketMan** [comment]
Sorry, I've just come across this as I'm looking for solutions to block the ads.

Reading this thread, I'm guessing the current patch doesn't support ```
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
```

Just wanted to double check before I proceed as this is the version number Spotify updated to today when I launched it.

**Comment by mrpond** [comment]
Hi, tested
```
Spotify for Windows (64 bit)
1.2.44.405.g81fd6352
xpui_2024-08-09_1723192885229_81fd635
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: Bazel
```

make sure you download latest dll, and/or update the signature.
you can manually update signature by copy dll and https://github.com/mrpond/BlockTheSpot/blob/master/blockthespot_settings.json
into spotify folder.
