### ISSUE TITLE
Can't read song lyrics

### ISSUE THREAD

**Issue by rizalihwan** [mrpond/BlockTheSpot#554]
Can't read song lyrics all music.

**Comment by SharkyDevBoi45** [comment]
Prolly cause its the most recent thing spotify has changed to be premium only. might take some time I was a little dissapointed

**Comment by VinceMack** [comment]
Pretty sure this works as a sophisticated ad blocker rather than an actual way to spoof premium. If Spotify gated that feature behind needing to verify you are premium, BlockTheSpot can't resolve that, unfortunately.

**Comment by SuperCuek** [comment]
AIMP can access Spotify's lyric feature with the custom aimp_weblyrics.ini from AIMP forum ([https://www.aimp.ru/forum/index.php?topic=57148.msg445282#msg445282](url))

![Capture](https://github.com/user-attachments/assets/a2632db2-c07a-4f2b-a731-e6b10df05e07)

why this mod can't get the lyric?

**Comment by SharkyDevBoi45** [comment]
> Pretty sure this works as a sophisticated ad blocker rather than an actual way to spoof premium. If Spotify gated that feature behind needing to verify you are premium, BlockTheSpot can't resolve that, unfortunately.

I thought that at first but it also gives me unlimeted skips so i wasnt too sure.

**Comment by SharkyDevBoi45** [comment]
> AIMP can access Spotify's lyric feature with the custom aimp_weblyrics.ini from AIMP forum ([https://www.aimp.ru/forum/index.php?topic=57148.msg445282#msg445282](url))
> 
> ![Capture](https://private-user-images.githubusercontent.com/104664907/352693569-a2632db2-c07a-4f2b-a731-e6b10df05e07.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTU5MzEsIm5iZiI6MTcyMjExNTYzMSwicGF0aCI6Ii8xMDQ2NjQ5MDcvMzUyNjkzNTY5LWEyNjMyZGIyLWMwN2EtNGYyYi1hNzMxLWU2YjEwZGYwNWUwNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMTI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzJkZmU1NWYwNWYxY2VkNzk1OGRjYmQ5ZGVjZTAxMmFjMzEwNTIyOTM1NjY1OTdjMWYwMmUyMjFmM2ZiYWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxUxKjjmBHUcO86UrJHJN7mtr62CXEi6CCBkJUNUR3s)
> 
> why this mod can't get the lyric?

I dont know, would the work together? I dont know what AIMP is so ill have to do some research

**Comment by SharkyDevBoi45** [comment]
> Can't read song lyrics all music.

I am using Lyrixed and I get the lyrics, but its in a new tab like the marketplace is. Install is one command in the powershel window but it does work with macos and linux

https://github.com/Nuzair46/Lyrixed

**Comment by ItxWeird** [comment]
They've now re-added lyrics for all users, and currently it isn't present using block the spot

**Comment by CipherVasat** [comment]
I can see the lyrics using this mod no problem at all

**Comment by rizalihwan** [comment]
already can guys now, thankyou :)
