### ISSUE TITLE
Powershell command facing issues

### ISSUE THREAD

**Issue by HeIp** [mrpond/BlockTheSpot#555]
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify"
**********************************
Authors: @Nuzair46, @KUTlime
**********************************
Stopping Spotify...

Downloading the latest Spotify full setup, please wait...
Start-BitsTransfer : Object reference not set to an instance of an object.
At line:49 char:5
+     Start-BitsTransfer -Source $Uri -Destination "$($TargetFile.FullN ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand

Press any key to exit...:

**Comment by Nuzair46** [comment]
Can you provide more info. its likely its an issue only in your system.

**Comment by DanielVolt** [comment]
Nah, same issue over here

**Comment by SimplisticGH** [comment]
Running as admin fixed it for me.
