### ISSUE TITLE
Despite Enable_Auto_Update=0 Spotify automatically updated

### ISSUE THREAD

**Issue by GrampaWildWilly** [mrpond/BlockTheSpot#558]
- [ x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [ x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ ] You uninstalled Spotify and just ran the patch
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.  **I don't see such a section.**
 - [x ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [ x] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.  **I can't.  I didn't do them all.  They don't seem to be relevant to my issue.**

I was running Spotify 1.2.47.364, which was the latest a couple of days ago.  I got that off the Spotify web site, not off any of the stores.  I am running Block the Spot 2024.7.22.109 which I got from GitHub.  That's about 3 months old now so I have to think it must be stable.  I have not run your install script but manually copied dpapi.dll and config.ini to my Spotify directory, per the Manual Installation instructions in the README.  I modified config.ini to include Enable_Auto_Update=0.  Spotify just automatically updated me to version 1.2.48.405.  I verified that the 2 Block the Spot files remain in the Spotify directory after the update.  I verified that the change to config.ini is still in place.

Now, I am pretty sure Block the Spot is working.  I've listened to Spotify in several sessions spanning several days, which is how long it's been since I discovered this lovely add-on.   I'm not what you can call an old-timer with Block the Spot.  I can't tell you how many tracks exactly I've listened to.  Has to be at least 100 tracks if not 200 or more.  I have not heard the slightest peep of an ad.  So that's great.

But I got auto-updated & I thought I had blocked that.  I'm not sure I should be leery of getting auto-updated, now that it's happened & things seem to continue to work fine, which is to say ad-free.  So, aside from reporting that blocking automatic updates doesn't seem to be working, I'd like to ask why I might want to block automatic updates to Spotify.  Is there code in Block the Spot that depends on something in a particular release of Spotify?  Is that code likely to quit functioning after an update to Spotify?  I would like to believe you would react to such a problem by releasing a new version of Block the Spot that corrects whatever went wrong.  Beyond that, I wouldn't have expected you to have any code that would rely on something unique in a particular release of Spotify.  But then, I'm not an expert on the inner workings of either the Spotify app nor of Block the Spot.  I'm just a user who is happy with your product.  Still, making an app like yours dependent on anything unique to a given release of Spotify would be . . . how can I say this . . . deprecated.  Not a good idea.  Surely you've tried to avoid such dependencies.  Do please elaborate.

**Comment by GrampaWildWilly** [comment]
Duh.  Forgot one minor detail.  I'm running Windows 11 Pro 64-bit version 24H2 build 26100.2033 on a desktop PC.

**Comment by Nuzair46** [comment]
that config is for the patch itself and not spotify. we recommend keeping Spotify upto date.

**Comment by GrampaWildWilly** [comment]
The patch.  Sorry.  I'm new to this product.  What patch?  Should I run something?  Where do I find this patch?

As for updating Spotify itself, OK.  I should let Spotify automatically update.  But I'm going to leave my Update directories in place to see whether that technique still works to block updates next time they push out an update.  Then I'll remove the 2 directories & accept all auto-updates from then on.

**Comment by GrampaWildWilly** [comment]
I'd still like someone to explain the terminology "the patch" to me.

Meanwhile, it appears that the old technique of creating a directory named Update with all privileges removed does still prevent Spotify from updating.  On the other hand, it took me downloading the new version about 3 times & executing it about 6 times before Spotify actually updated.  Maybe somebody else will see this as well.  Or maybe it's just a quirk of my system today & it will never happen again.  Only time will tell . . .
