### ISSUE TITLE
Ads showing up under the "On Repeat" playlist.

### ISSUE THREAD

**Issue by tylerfoggoa** [mrpond/BlockTheSpot#559]
![Screenshot 2024-10-10 174725](https://github.com/user-attachments/assets/d99b7ba5-fb96-472b-af2b-6bbd5c8268b3)
Issue with blocking ads under the "On Repeat" playlist.

Expected Outcome: There should be no ads on the Spotify app after running block the spot
Actual Outcome: Ads for Firefox appear on the "On Repeat" Playlist.
Steps to Recreate: Open Spotify desktop app, search for "On Repeat" playlist, click on the playlist ad will appear.

Info:
Spotify for Windows (64 bit)
1.2.47.364.gf06e5cee
xpui_2024-09-20_1726857715171_f06e5ce
cef_128.4.9+g9840ad9+chromium-128.0.6613.120
Runtime: Chrome
Build System: Bazel

**Comment by AzureBede** [comment]
I'm using Spotify for Windows, and I'm getting ads now, as well.

**Comment by mrpond** [comment]
<img width="580" alt="image" src="https://github.com/user-attachments/assets/9678f3ed-7c9e-4662-9091-f83358c1e57c">
Hi, I can't reproduce it.

@Nuzair46 can you test it on your env?

```Spotify for Windows (64 bit)
1.2.48.405.gf2c48e6f
xpui_2024-10-08_1728372466386_f2c48e6
cef_128.4.12+g1d7a1f9+chromium-128.0.6613.138
Runtime: Chrome
Build System: Bazel```
