### ISSUE TITLE
Add appveyor config to the repo or move to github actions

### ISSUE THREAD

**Issue by xPaw** [mrpond/BlockTheSpot#561]
Basically copy the configuration from the UI into appveyor.yml file

**Comment by Nuzair46** [comment]
@mrpond i think its a good idea. we could even use circleci. let me know.

**Comment by mrpond** [comment]
> Basically copy the configuration from the UI into appveyor.yml file

@Nuzair46  yes, good idea. honestly, I didn't know about appveyor 
until some guy open the issue and mention me to use it. 

I will copy these into appveyor.yml on weekend

**Comment by mrpond** [comment]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/9039815c-04e0-4fb3-be6c-b1d99d9f863d">
@xPaw how to deal with this token?

**Comment by xPaw** [comment]
There's an "encrypt yaml" somewhere in appveyor which would give you an encrypted token you can put in there, unless it's already encrypted.

**Comment by mrpond** [comment]
> There's an "encrypt yaml" somewhere in appveyor which would give you an encrypted token you can put in there, unless it's already encrypted.

done,  https://github.com/mrpond/BlockTheSpot/blob/master/appveyor.yml

please help me checking it.

**Comment by Nuzair46** [comment]
@mrpond i think we can use github actions instead? It will be easy to setup keys and all

**Comment by Nuzair46** [comment]
@mrpond you can set it as an ENV variable in github instead of hardcoding in the yaml file
