### ISSUE TITLE
BlockTheSpot update issued a warning from MS Defender

### ISSUE THREAD

**Issue by Skorn42** [mrpond/BlockTheSpot#562]
Today I got a prompt for an update for BTS and ran it, I got a prompt from microsoft defender immediately for a trojan, I have attached a screenshot of the occurrence for your reference.

![Screenshot 2024-10-14 114247](https://github.com/user-attachments/assets/0ac7e3e4-480f-4f15-ab06-077ca54831b6)

**Comment by luckyblackcat23** [comment]
was just about to do a similar report. wacatac is pretty common for being a false positive but i dont know the specifics. i'd wait for another reply just in case and stick to the last version this

**Comment by Alekceii** [comment]
Windows Defender blocking here too

**Comment by Arman-nsb** [comment]
already reported, was closed as a FP case. #560

**Comment by Mrfunreal** [comment]
well, 21 vendors flag dpapi.dll as virus.
![image](https://github.com/user-attachments/assets/ac63b07d-2c00-4cf7-860b-99c609b06e47)

How can i downgrade if i updated already?

**Comment by Vetrix68** [comment]
Code hasn't been updated in a while and suddenly there are 21 detections bruh

**Comment by Pixel-Count** [comment]
> How can i downgrade if i updated already?

You can download an older release and manually install it. The previous release (2024.7.22.109) is coming back clean on VirusTotal. Delete the DLL from your Spotify folder and put the one from the old release in.

**Comment by Mrfunreal** [comment]
Thank you very much.

**Comment by 0Anonym** [comment]
Bitdefender also blocks it instantly.

**Comment by RichardoJT** [comment]
![image](https://github.com/user-attachments/assets/8717c8bd-c5d4-4a2b-980a-19820e567c4c)
getting a similar problem here

**Comment by Windrogue78** [comment]
Same issue here. It's my understanding that block the sport is no longer being supported, so why are there updates that would flag defender?

**Comment by Arman-nsb** [comment]
guys the previous version works flawlessly, refrain from using the latest release. better be safe than sorry!

**Comment by Nuzair46** [comment]
Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue
