### ISSUE TITLE
Copy Item denied for dpapi.dll

### ISSUE THREAD

**Issue by AlphaRyz3** [mrpond/BlockTheSpot#564]
With the newest update of spotify installed today via the update of BTS it continues to give me the following error after even a clean reinstall, also as you can imagine empty spots appear in the spotify UI and it does not block spots anymore

```powershell
Copy-Item : Access to path 'C:\Users\Alpha\AppData\Roaming\Spotify\dpapi.dll' denied.
In line:266 char:1
+ Copy-Item -LiteralPath $patchFiles -Destination "$spotifyDirectory"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\Alpha...17-16\dpapi.dll:FileInfo) [Copy-Item], Unauthorized
   AccessException
    + FullyQualifiedErrorId : CopyFileInfoItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.CopyItemCommand
```
Tested on Windows 11

**Comment by AlphaRyz3** [comment]
![Uploading immagine_2024-10-14_222342602.png…](As an example see here)

**Comment by AlphaRyz3** [comment]
![immagine_2024-10-14_222408997](https://github.com/user-attachments/assets/aca034b4-f154-4876-b22c-10f8a4dc0be4)
As an example

**Comment by AlphaRyz3** [comment]
> Quote reply
> Reference in new iss

I am using BitDefender and aswell i disabled it temporarily for 10 minutes to do the update just as other times where everything went ok, but this time nop

**Comment by digby5** [comment]
the dppapi.dll  is  reported  as Trojan:Win32/Sabsik.FL.A!ml on defender - listed as severe. so 2 different ids from defender. if its the same malware id from the same program, i could understand it might be a false posiive, but 2 different ids??

**Comment by AlphaRyz3** [comment]
the thing is that i have antivirus disabled while doing all of this update just as other times that i did this so it wouldn't make sense that now it causes troubles

**Comment by AlphaRyz3** [comment]
tried again adding it to the ignore list, but still the same error appears and i can' even copy the file for the patch manually, the dpapi.dll one. The error message is still the original one

**Comment by single-spider** [comment]
Having the same issue. I disabled bitdefender as it was detecting the dpapi.dll as some Varient:Lazy sort of virus but the cmd panel is showing the same issue.

**Comment by strawbee07** [comment]
What's the solution, I'm also getting it saying its a severe threat but right after it says there's no threat. People are saying its a false positive but I just wanna be safe, should I still keep it installed + keep trying to fix the ads coming through?

**Comment by AlphaRyz3** [comment]
> What's the solution, I'm also getting it saying its a severe threat but right after it says there's no threat. People are saying its a false positive but I just wanna be safe, should I still keep it installed + keep trying to fix the ads coming through?

Yea it is safe but the problem is that the BTS patch doesn't work anymore since it cannot put in the Appdata/Roaming/Spotify the dpapi.dll file

**Comment by AlphaRyz3** [comment]
At the end i did a reinstall for the latest version, cleared the Temp folder, disabled temporarily the BitDefender protection completely and after a reboot the BTS script worked fine
