### ISSUE TITLE
Now don't block adds

### ISSUE THREAD

**Issue by PolBruG** [mrpond/BlockTheSpot#565]
I install all following the steps and Spotify still have adds, but before yesterday I don't have any problem with that. 

I don't know where is the problem.

**Comment by Enkatuya** [comment]
I am having the same issue. ever since i updated it this morning its been letting ads through

**Comment by luckyblackcat23** [comment]
a lot of people are getting virus warnings. the dev seemingly hasn't said anything from what I've seen. so i'd downgrade to an older version

**Comment by tommmoe** [comment]
> a lot of people are getting virus warnings. the dev seemingly hasn't said anything of value from what I've seen. so i'd downgrade to an older version
> 
> edit: thought i'd mention that this seems similar to another account hack where a virus was added to software, one where i got infected. dev was seemingly unresponsive for a while and avoided any questions about viruses. there was also a lot of new random users who were trying to ensure people that it wasn't a virus. for example: #563 this guy weirdly answering their own issue...
> 
> edit 2: checking the sourcecode and strangely enough, this line was removed... hm This .dll is virus free, false positive may appear. This can be reassured via the source code.

Sure the source looks okay, but the compile may have something in it right?

**Comment by luckyblackcat23** [comment]
according to virusTotal there's no issues. i dont know anything other than that. currently trying to look into it myself but i only have basic programming experience.

**Comment by digby5** [comment]
this is listed as severe in defender for me:
The Wacatac trojan virus is a malicious program that affects Windows devices. A Wacatac trojan can download and install other malware onto your computer, or record your keystrokes to steal personal information, such as login credentials or bank account details. Wacatac could also add your device to a [botnet](https://cybernews.com/malware/what-is-a-botnet/) by creating backdoors, which allow other devices to access and remotely control your device. A botnet is usually then used for executing DDoS attacks or crypto mining.

no reply from  github owner. i would not be surprise if the github has been commandeered.

**Comment by digby5** [comment]
and here is virustotal id of  the file. a third lists posiive [https://www.virustotal.com/gui/file/dd78d0175c58d842c6a897e6fa9eb238b19e650bac975154674d8e4a30064ae5](url)

**Comment by mrpond** [comment]
Hello, thanks for mention this. 
I want to clarify things,
1. the code is on Github, everyone can check it. 
2. BTS utilize Appveyor, https://www.appveyor.com/.
3. It is CI/CD any code change on Github, Appveyor will build it and make release on Github.
false positive can happen. but don't trust me on this, try verify by compile your own BTS and compare with the release.
