### ISSUE TITLE
The ads are still showing.

### ISSUE THREAD

**Issue by strawbee07** [mrpond/BlockTheSpot#567]
Heyy I updated my spotify just a bit ago, noticed another post that had the same issue and was closed. I reinstalled etc and tried to see if I could install a previous version but no luck. Any insight + help would be appreciated :)
I am skipping songs but when I play them through I get ads.

**Comment by mrpond** [comment]
![image](https://github.com/user-attachments/assets/4b7d7fb7-94de-494e-9f20-d5ff98ab058e)
make sure you using latest spotify, download this, and put it into spotify folder.

**Comment by strawbee07** [comment]
Hey! I'm kinda confused, where should I do that? When I click on the blockthespot_settings.json it doesn't let me download, just opens the code. Can you give me a more detailed rundown? So sorry for the trouble!

**Comment by McLOVINandCo** [comment]
I tried this and it still didnt work any other recommendations?

**Comment by titushm** [comment]
Yea im having the same issue

**Comment by Motaphe** [comment]
Same here! After the new update, I've started to get both banner ads and ads in-between songs.

**Comment by SapphireHue** [comment]
I also had ads start showing up today. I did not intentionally update Spotify, but I'm currently on version 1.2.48.405.gf2c48e6f

**Comment by definitelytheking** [comment]
> Same here! After the new update, I've started to get both banner ads and ads in-between songs.

Same, ive been using this since march, and now its not working because of the new update

**Comment by definitelytheking** [comment]
I had the same issue earlier, but I fixed it. I placed the file in the Spotify folder, then added both the BlockTheSpot file and the Spotify folder to Windows Defender exclusions. That's all. Just make sure the BlockTheSpot file is inside the Spotify folder.

**Comment by Asnowy1** [comment]
Need help here aswell, Doesn't seem to fix on a redownload or anything.

**Comment by McLOVINandCo** [comment]
> I had the same issue earlier, but I fixed it. I placed the file in the Spotify folder, then added both the BlockTheSpot file and the Spotify folder to Windows Defender exclusions. That's all. Just make sure the BlockTheSpot file is inside the Spotify folder.

i tried excluding both the blockthespot file, aswell as the spotify folder but it was still getting recognized as a trojan. can you specify what you excluded?

**Comment by SapphireHue** [comment]
> I had the same issue earlier, but I fixed it. I placed the file in the Spotify folder, then added both the BlockTheSpot file and the Spotify folder to Windows Defender exclusions. That's all. Just make sure the BlockTheSpot file is inside the Spotify folder.

Nothing of mine was ever flagged. I tried to exclude the Spotify folder, but couldn't figure out which file you meant by "the BlockTheSpot file".
