### ISSUE TITLE
Update shows dpapi.dll as Trojan (Wacatac.H!ml)

### ISSUE THREAD

**Issue by Nichait** [mrpond/BlockTheSpot#568]
Updated BlockTheSpot with the popup that showed up when I turned on my laptop, Defender immediately blocked it. 

Tried reinstalling, Defender blocked it again.

Is it a false positive or not?

**Comment by mrpond** [comment]
Hi, false positive. https://github.com/mrpond/BlockTheSpot/issues/565
kindly read me comment here.
