### ISSUE TITLE
Just a declaration

### ISSUE THREAD

**Issue by ayangg294** [mrpond/BlockTheSpot#569]
The chrome-elf.zip files (config.ini, dpapi.dll) are marked as a virus. I believe this is a false positive, so if yall start getting ads again make sure the antivirus has not quarintined/removed those files.

**Comment by princessMagenta** [comment]
just confirming the updated dpapi.dll got picked up by windows defender. thanks for the heads up

**Comment by potatobreadyum** [comment]
you know how to stop windows defender to delete them? its so annoying.

**Comment by Nuzair46** [comment]
Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue

**Comment by ayangg294** [comment]
> you know how to stop windows defender to delete them? its so annoying.

when u download the file, turn off defender
after u install, turn it on
and make sure u catch the notification saying that windows defender caught a threat
when u click it, itll give u option to allow the threat
when u allow, it won't attack it anymore
