### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml  

### ISSUE THREAD

**Issue by RaoHammas** [mrpond/BlockTheSpot#573]
Hi, 
Windows Defender is reporting Trojan. Why do we need DPAPI in the Spotify app with pretty much all the functionalities?

From the file [dpapi.def](https://github.com/mrpond/BlockTheSpot/blob/772b51dffeb9c9e41838d90c4f7cf60258baf85e/src/dpapi.def)
```
LIBRARY	"dpapi"

EXPORTS
CryptProtectData
CryptProtectMemory
CryptUnprotectData
CryptUnprotectMemory
CryptUpdateProtectedState

```

![image](https://github.com/user-attachments/assets/01dfe82d-ea4d-42a9-86a4-0c4a23480538)

**Comment by L0stThoughts** [comment]
Same problem here, not sure what's happening.

**Comment by docentYT** [comment]
I also received this warning just after unhibernating my computer, which had Spotify open all the time.

**Comment by Louisthexv** [comment]
I confirm today I got the notification from Windows Defender, some people says is false positive and others says is a trojan. On reddit https://www.reddit.com/r/computerviruses/comments/1g3oklq/should_i_be_concerned_with_this/

and fix or can we install a previous version?

**Comment by RaoHammas** [comment]
i think the dev need to answer why do we need DPAPI in the Spotify app?

**Comment by Nuzair46** [comment]
Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue
