### ISSUE TITLE
Keep getting asked if I wanna get the newest update

### ISSUE THREAD

**Issue by AgentKanashimi** [mrpond/BlockTheSpot#574]
I've clicked yes twice, and gave up on the third and just pressed no

It's gone now after I pressed no atleast, but why did it keep happening?

**Comment by wiz2596** [comment]
I'm having the same issue

**Comment by jmarmstrong1207** [comment]
Also the same issue.

**Comment by tonigvz** [comment]
Same here, it keeps happening on each boot up.

**Comment by AgentKanashimi** [comment]
From the other posts saying trojan and people claiming they got hacked.. maybe the coding really was edited, and the newest update thing is part of a bug from someone going into the coding, adding their stuff, and accidentally messing with other stuff? I'm unsure though.

**Comment by AgentKanashimi** [comment]
Either way, I'm gonna play it safe until someone with better knowledge comes out and tells us everything.

**Comment by jasonch35** [comment]
confirmed. same here

**Comment by Nuzair46** [comment]
Disable updates in config.ini to fix it.
regarding the virus warning Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue
