### ISSUE TITLE
Trojan detected by windows defender

### ISSUE THREAD

**Issue by wiz2596** [mrpond/BlockTheSpot#575]
![image](https://github.com/user-attachments/assets/c697cb61-9989-44a4-bb7d-82617b16d509)

**Comment by Edwinprb** [comment]
Yes, it has a virus, better uninstall it

**Comment by tonigvz** [comment]
Same issue here.

**Comment by Nuzair46** [comment]
Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue
