### ISSUE TITLE
DO NOT INSTALL - REPORT PROGRAM

### ISSUE THREAD

**Issue by esha0281** [mrpond/BlockTheSpot#576]
using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from GitHub.

**This is the first time running this program and its folder application with a virus protection notification (and I ignore most warnings from Microsoft Defender). Usually, this program is one of the main from GitHub that is normally nothing wrong, and no files attached to direct history or direct file measures. However, this most recent install has some severe interactions with the OS system folder (and a dll file) and is some form of a trojanVirus, thus I have reported this port/repo to GitHub Port, until this path is fixed in the most recent source code boot in the bat-red file. PLEASE DO NOT INSTALL AND REPORT UNTIL FIXED. **
![image](https://github.com/user-attachments/assets/9991d5a7-3720-428c-8968-97cea6b016d8)

**Comment by Nuzair46** [comment]
Its a false positive. Please read https://github.com/mrpond/BlockTheSpot?tab=readme-ov-file#virus-warning-on-windows-defender-issue
