### ISSUE TITLE
Spotify 1.2.49.439.gfae492c7 crash

### ISSUE THREAD

**Issue by Stefano-VLN** [mrpond/BlockTheSpot#578]
- [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran the patch
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.
 - [x] Make sure whether an issue related yours is already open or not.
 - [x] Make sure you have completed everything in the above checklist.

Hello,
I'm using the latest version of Spotify (see title) and the client immediately crashes on launch.

Here's the content of blockthespot.log
```
2024-10-24 14:19:27 | INFO  | BlockBanner - patch success!
2024-10-24 14:19:27 | INFO  | BlockAds - patch success!
2024-10-24 14:19:27 | INFO  | Developer - successfully patched!
2024-10-24 14:19:27 | INFO  | allow - https://apresolve.spotify.com/?time=1729772367&type=accesspoint
2024-10-24 14:19:27 | INFO  | hptocss - patch success!
2024-10-24 14:19:27 | INFO  | adsEnabled - patch success!
2024-10-24 14:19:27 | INFO  | ishptohidden - patch success!
2024-10-24 14:19:27 | ERROR | sponsorship - unable to find signature in memory!
2024-10-24 14:19:27 | INFO  | skipsentry - patch success!
2024-10-24 14:19:27 | INFO  | hptoEnabled - patch success!
2024-10-24 14:19:27 | INFO  | sp_localhost - patch success!
```

Can you help me out?

Thanks

**Comment by Arman-nsb** [comment]
use BTS version 109, it still works for me on the latest Spotify release.

**Comment by Chromos-Def** [comment]
> use BTS version 109, it still works for me on the latest Spotify release.

109 still crashes the Spotify client for me.

**Comment by Arman-nsb** [comment]
![image](https://github.com/user-attachments/assets/6c91428c-9399-460e-8789-017f3d3ac819)
I'm using this version(latest) with BTS 109. maybe reinstall yours? (don't use Microsoft Store)

**Comment by Chromos-Def** [comment]
Spotify for Windows (64 bit)
1.2.49.439.gfae492c7

So I got it working by

Removing dpapi.dll
Launching Spotify normally
Adding back dpapi.dll from BTS 109

**Comment by andrei0x309** [comment]
> Spotify for Windows (64 bit) 1.2.49.439.gfae492c7
> 
> So I got it working by
> 
> Removing dpapi.dll Launching Spotify normally Adding back dpapi.dll from BTS 109

Also after deleting the DLL, paste it after Spotify is launched, otherwise, it might not work if you paste it while the process is still closed. After the paste re-launch, it should work with 109.

**Comment by shuaiyetu** [comment]
Updating `Block_Banner` from `1` to `0` in `config.ini` worked for me.

**Comment by mrpond** [comment]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/2ee4707c-4583-4fb9-99ed-c4d61ac69dcc">
Fixed!
