### ISSUE TITLE
spotify crash

### ISSUE THREAD

**Issue by CrazyKidAswath** [mrpond/BlockTheSpot#579]
![image](https://github.com/user-attachments/assets/99fbfa25-692e-484f-9c30-593dcc2e2b88)
![Screenshot (5)]
(https://github.com/user-attachments/assets/f24c54f4-17d1-4cb2-b0bf-2165fe8d6239)

 - [ ] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [ ] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [ ] You uninstalled Spotify and just ran the patch
 - [ ] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [ ] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [ ] You enabled logging by editing config.ini `set log = 1`.
 - [ ] Make sure whether an issue related yours is already open or not.
 - [ ] Make sure you have completed everything in the above checklist.

## Note: 
- Antivirus detections are false positive. Please only open an issue if you find any vulnerability in the code. False reports will be closed without notice.
- If we find that you have opened an issue without following the troubleshooting above, the issue will be closed without notice.

**Comment by mrpond** [comment]
fixed, https://github.com/mrpond/BlockTheSpot/issues/578

try manually update blockthespot_settings.json if it still crash.
