### ISSUE TITLE
Environment path or Powershell command for BlockTheSpot + Spicetify on the mainpage

### ISSUE THREAD

**Issue by Mockii7** [mrpond/BlockTheSpot#580]
I couldn't ran the bat files and got the issue "Powershell' is not recognized as an internal or external command, operable program or batch file". 

Tried to find a copypasta powershell command for BlockTheSpot + Spicetify  instead and couldn't find one on the mainpage, would be cool if one can be added. 

Ended up editing the bat file and added a environment path "%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe" which made the bat file work perfectly. 

Thanks for the effort, much appreciated!

**Comment by Nuzair46** [comment]
auto installer works from windows 10 and above only
