### ISSUE TITLE
What is the last version of BlockTheSpot which is not detected as a trojan by MBAM or Windows Defender? 

### ISSUE THREAD

**Issue by OZJZERO** [mrpond/BlockTheSpot#585]
What is the last version of BlockTheSpot which is not detected as a trojan by MBAM or Windows Defender? Yes, I am aware it is considered a false positive but for peace of mind would prefer to have one which is not flagged by my AV.

**Comment by mrpond** [comment]
I will file false positive report to MS Defender next month.
