### ISSUE TITLE
dpapi.dll is marked as malicious

### ISSUE THREAD

**Issue by susbaconhairman** [mrpond/BlockTheSpot#586]
https://www.virustotal.com/gui/file/e3af73a03e35bac46045ec528496dc6009fedd6159e853ea761cda61837b044a

Location is ```C:\Users\username\AppData\Roaming\Spotify\dpapi.dll```

**Comment by mrpond** [comment]
Hi, if you download DLL from this official GitHub, you can ignore it. it is fault positive.
