### ISSUE TITLE
You should block Spotify from updating

### ISSUE THREAD

**Issue by jerkstorecaller** [mrpond/BlockTheSpot#588]
I don't understand why none of these tools think of disabling auto-updates. It seems really naive and a bad design.

Let's say today I have a working Spotify client and a working BlockTheSpot. This setup can work for years. The most likely thing this working setup will break is from a Spotify update, followed by server-side API changes (requiring a forced client update) a distant second. And you let them happen, and then people have to deal with update the whole thing, and perhaps by then you're not working on this tool anymore.

Please design your program better by preventing Spotify from updating in the first place. People who care more about new Spotify features (whatever they may be) are free to update and break their installation. 

Do you see developers of game cracks allow auto-updaters to run? Of course not. It's the smart design for these sort of tools.

(There is an autoupdate setting in the .ini but it only affects BlockTheSpot itself I think, not Spotify)

**Comment by Nuzair46** [comment]
Short answer, its a headache for us.
Spotify updates and breaks the patch and we update the script here which might not work with older spotify and users complain about that. Since generally most users want to keep Spotify upto date, and we too recommend it for security reasons, there is no strong reason to disable updates. Though it is possible other ways. But this wont be added to this script.

**Comment by jerkstorecaller** [comment]
>Since generally most users want to keep Spotify upto date, and we too recommend it for security reasons

Sorry but this is just flat out wrong.

Why would most users want to keep Spotify up to date? Can you name me a single thing that's different in Spotify in the past 2 years? It's a music player. Have Spotify recently come up with revolutionary new way to click the Play Song button recently, and I must absolutely update to get it?
And it's not like I'm telling you to disable auto-updates, but just to make it configurable, while keeping auto-updates enabled by default for people who think like you. It's a single config setting in the ini file, transferring responsability from you to the user.

And what security risks? It's a single-purpose desktop app that connects to a specific safe URL (spotify.com), not a web browser. That just makes no sense. I think you drank the "must always be updating" koolaid, at the expense of the robustness of your tool.

I think you'd have a heart attack if you saw my Android phone.
