### ISSUE TITLE
Last.fm scrobbling

### ISSUE THREAD

**Issue by FallenTF** [mrpond/BlockTheSpot#6]
Desktop
Win10 latest 1903
1.1.15.448.g00fba0e3

Does this break Last.fm scrobbling? It doesn't seem to be working (over a period of several days). Scrobbling is working fine on my mobile app.

Edit: Nevermind, stupid me didn't think to test with original dll. Yep, doesn't work :(

**Comment by mrpond** [comment]
fixed in v0.24 :)
