### ISSUE TITLE
Still getting audio ads

### ISSUE THREAD

**Issue by Rynerath** [mrpond/BlockTheSpot#60]
I am getting audio ads on the latest version of Spotify on Windows 10
Region: New Zealand
**Important**
 - Make sure you use [latest spotify](https://www.spotify.com) before report a bug.
 - Make sure you use [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before report a bug.
 - Make sure again... blockthespot dll got replace after spotify update, recheck this

**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Spotify Version: [e.g. 1.1.27.472.gf6574b97]
 - BlockTheSpot Product Version: [right click chrome_elf.dll -> Details]

**Additional context**
If ad blocking is not working, please include a debug Log by
 1. edit config.ini and set Log = 1 
 2. after ads song play close spotify
 3. zip the main_log.txt, utility_log.txt

**Comment by CHEF-KOCH** [comment]
No debug logs from you provided.

**Comment by Rynerath** [comment]
> No debug logs from you provided.

How do I do that?

**Comment by CHEF-KOCH** [comment]
```
If ad blocking is not working, please include a debug Log by

edit config.ini and set Log = 1
after ads song play close spotify
zip the main_log.txt, utility_log.txt
```

**Comment by Rynerath** [comment]
> ```
> If ad blocking is not working, please include a debug Log by
> 
> edit config.ini and set Log = 1
> after ads song play close spotify
> zip the main_log.txt, utility_log.txt
> ```

I don't know how to do any of that.

**Comment by rednek46** [comment]
@Rynerath you just change those in the config.ini  
Are you sure you installed the patch correctly?

**Comment by mrpond** [comment]
config.ini are place in Spotify installation folder.. (if you install blockthespot).

**Comment by dvcky** [comment]
I'm actually having an issue with ads still as well. I marked where the ads started loading (same type as above, audio ads) in the log below:

```
BlockTheSpot - Build date: Mon May 11 23:48:09 2020
Mhook_SetHook - getaddrinfo success!
allowed - login5.spotify.com
allowed - apresolve.spotify.com
allowed - spclient.wg.spotify.com
allowed - guc-spclient.spotify.com
allowed - dailymix-images.scdn.co
allowed - newjams-images.scdn.co
allowed - seeded-session-images.scdn.co
allowed - spclient.wg.spotify.com
blocked - adservice.google.com
allowed - platform-lookaside.fbsbx.com
blocked - securepubads.g.doubleclick.net
blocked - 23842d58b5e5ac404e07e9a98cf626b5.safeframe.googlesyndication.com
allowed - i.scdn.co
// I think this is where the ads started.
allowed - seeded-session-images.scdn.co
allowed - lineup-images.scdn.co
allowed - misc.scdn.co
// Song started playing here again.
allowed - i.scdn.co
```
For the record - there aren't ads for the first couple songs after launching, but then after those songs the ads come back.

**Comment by mrpond** [comment]
@dvcky 
Hi, this case need you information a little bit
1. Did you login with facebook account?
2. Did you cast the song from mobile phone?
if this true, spotify ads are playing from phone. 
blockthespot can't do anything about it.

**Comment by dvcky** [comment]
That would make sense, as I am logged in with a Facebook account. That makes me legitimately curious as to how that affects the functionality of ads though, does it fetch them based on something with my Facebook profile? Quite interesting!

**Comment by mrpond** [comment]
@dvcky 
Please test this, 
[chrome_elf_dvcky.zip](https://github.com/mrpond/BlockTheSpot/files/5076654/chrome_elf_dvcky.zip)
if it work I merge this into official.

**Comment by dvcky** [comment]
Hi! sorry for the late reply, but that did seem to work for me, at least for the time I tried it. Ironically enough, I was just given premium from a friend as well, so I almost forgot to report on it. Thanks for helping me out! :)
