### ISSUE TITLE
Any songs stopped near 0:06

### ISSUE THREAD

**Issue by Avtera** [mrpond/BlockTheSpot#62]
just play any song with newest spotify and newest chrome_elf, the song will always stop near 0:06 second.

OS: Windows 10
Spotify: 1.1.40.508.gd5bc2931
chrome_elf: 2020.8.17.16

**Comment by llacb47** [comment]
`https://www.theverge.com/2020/8/19/21375032/spotify-down-songs-loading-issues-outage`
