### ISSUE TITLE
[Info] Latest version supported by the project

### ISSUE THREAD

**Issue by dennyamarojr** [mrpond/BlockTheSpot#64]
Hi mrpond,

Just a information about the latest release of chrome_elf, still blocking the ads in Spotify version 1.1.41.634.gc2c73ca7 (stable)
Here's the pics to review 👍 
![01](https://user-images.githubusercontent.com/36896116/92137923-9f48ad00-edc2-11ea-9a1e-4ea03bbe5183.JPG)
![02](https://user-images.githubusercontent.com/36896116/92137927-a079da00-edc2-11ea-9d51-a6e739557ca0.JPG)
![Spotify ADS not present1](https://user-images.githubusercontent.com/36896116/92137932-a1127080-edc2-11ea-9544-6c650a5e1f08.jpg)

**Comment by mrpond** [comment]
hi thank you.
