### ISSUE TITLE
Improving language of readme

### ISSUE THREAD

**Issue by jayloofah** [mrpond/BlockTheSpot#66]
Hi,

I just wanted to update the readme with a few potential corrections in English for some of the wordings used. I think they will help clarify your project and make it look a little neater.

I will simply attach the markdown file in text format (as GitHub won't allow .md files to be uploaded) and let you decide if you would like to push these changes.

[README.txt](https://github.com/mrpond/BlockTheSpot/files/5177204/README.txt)

Thanks for all your work.

**Comment by rednek46** [comment]
@jayloofah , fork this repo and edit the readme.md in your fork and create a pull request.

**Comment by mrpond** [comment]
I'm gladly accept it. please fork and push into our repo.
