### ISSUE TITLE
Recently played songs do not update

### ISSUE THREAD

**Issue by Daksh777** [mrpond/BlockTheSpot#67]
**Important**
 - [x] Make sure you use [latest spotify](https://www.spotify.com) before report a bug.
 - [x] Make sure you use [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before report a bug.
 - [x] Make sure again... blockthespot dll got replace after spotify update, recheck this

**Describe the bug**
For some reason, the recently played songs do not seem to update. Spotify is also not able to check what I have been listening to and not giving any new "Made for you" playlists. Uninstalling BlockTheSpot seems to fix it. Here's what I've been stuck with when using BlockTheSpot: 
![image](https://user-images.githubusercontent.com/43648146/92684366-e995d500-f352-11ea-8c22-08e06fd7337a.png)
It's been like this for a long time and not changing at all.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 18363.418
 - Spotify Version: 1.1.41.634.gc2c73ca7
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by ronny941** [comment]
I have the same issue it doesn't show any songs I recent played
I hope it will be fixed

**Comment by ronny941** [comment]
> 
> 
> **Important**
> 
>     * [x]  Make sure you use [latest spotify](https://www.spotify.com) before report a bug.
> 
>     * [x]  Make sure you use [latest blockthespot](https://www.github.com/mrpond/BlockTheSpot/releases) before report a bug.
> 
>     * [x]  Make sure again... blockthespot dll got replace after spotify update, recheck this
> 
> 
> **Describe the bug**
> For some reason, the recently played songs do not seem to update. Spotify is also not able to check what I have been listening to and not giving any new "Made for you" playlists. Uninstalling BlockTheSpot seems to fix it. Here's what I've been stuck with when using BlockTheSpot:
> ![image](https://user-images.githubusercontent.com/43648146/92684366-e995d500-f352-11ea-8c22-08e06fd7337a.png)
> It's been like this for a long time and not changing at all.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10 1909 18363.418
> 
>     * Spotify Version: 1.1.41.634.gc2c73ca7
> 
>     * BlockTheSpot Product Version: 0.51.0.0

I have the same problem you have described on the latest version of spotify
I hope the releaser fix this issue 
the releaser has not released updated files for this new version
perhaps because he saw that all ads of spotify as blocked even with the 2 files for the old version
we hope it releases the new files created for this version

**Comment by mrpond** [comment]
Helllo, I look into it.

**Comment by ronny941** [comment]
> 
> 
> Helllo, I look into it.
> Please test this release,
> https://github.com/mrpond/BlockTheSpot/releases/tag/2020.9.14.17

I have tested but it doesn't showing any song I have already listening 
the bug it's remain

**Comment by Daksh777** [comment]
> Helllo, I look into it.
> Please test this release,
> https://github.com/mrpond/BlockTheSpot/releases/tag/2020.9.14.17

I too tested this and it didn't work. 
Also, a little worrying that chrome is marking it as a dangerous file,
![image](https://user-images.githubusercontent.com/43648146/93163813-b29a3780-f735-11ea-978e-0418308f187a.png)

**Comment by mrpond** [comment]
@Daksh777 
You can recompile it from source. file reputation are so low, not many ppl use this release.
@ronny941 ok, please wait for next release.

**Comment by Daksh777** [comment]
> @Daksh777
> You can recompile it from source. file reputation are so low, not many ppl use this release.

No, it's not that I don't trust your files. I was just saying that Chrome is giving that warning.

**Comment by mrpond** [comment]
@Daksh777 I know, I mean it's a chrome feature
https://www.darkreading.com/analytics/security-monitoring/google-uses-reputation-to-detect-malicious-downloads/d/d-id/1139482

**Comment by mrpond** [comment]
@ronny941 @Daksh777 
with current release 15/9/2020  after play some song did this section got updated?

![image](https://user-images.githubusercontent.com/18654771/93196458-a97c8b00-f774-11ea-854e-a0570e53476c.png)

**Comment by Daksh777** [comment]
> @ronny941 @Daksh777
> with current release 15/9/2020 after play some song did this section got updated?

![image](https://user-images.githubusercontent.com/43648146/93200129-0411e900-f76d-11ea-865d-837cd637064f.png)
Yes! It actually did update but the Home section isn't yet updated.

**Comment by ronny941** [comment]
> 
> 
> @ronny941 @Daksh777
> with current release 15/9/2020 after play some song did this section got updated?
> 
> ![image](https://user-images.githubusercontent.com/18654771/93196458-a97c8b00-f774-11ea-854e-a0570e53476c.png)

the section "recently played" of spotify it is empty for me and didn't updated
and the 'songs you like' 
items and recently listened songs have disappeared from the home page of spotify

**Comment by ronny941** [comment]
after the new update the recently played songs it never updates gives it to me empty

and in the home of spotify the "liked songs" and the songs played recently it never appears

**Comment by Daksh777** [comment]
> after the new update the recently played songs it never updates gives it to me empty
Are you talking about the version 1.1.42.622?
> and in the home of spotify the "liked songs" and the songs played recently it never appears
Yes, same for me. My recently played songs are only appearing in the "Recently played" tab.

**Comment by ronny941** [comment]
> 
> 
> > after the new update the recently played songs it never updates gives it to me empty
> 
> Are you talking about the version 1.1.42.622?
> 
> > and in the home of spotify the "liked songs" and the songs played recently it never appears
> 
> Yes, same for me. My recently played songs are only appearing in the "Recently played" tab.

no I have the v1.1.41.634 the latest version
and for me the recently played songs are empty as if I hadn't listened to anything
the 'recently listened' section does not appear in the home of spotify 
with the artists you have listened to and the 'liked songs' item

**Comment by ronny941** [comment]
this section are disappeared from the home of spotify
![Spotify Home](https://user-images.githubusercontent.com/32131958/93210128-5fd57580-f75f-11ea-81e8-d84afd8540c6.JPG)

and the recent played section is empty and it never updates

![Songs Listened Recently](https://user-images.githubusercontent.com/32131958/93210152-66fc8380-f75f-11ea-9d2c-519981ee8b71.JPG)
it does with the mod of blockthespot
and with the clean version of spotify but with the ads

**Comment by Daksh777** [comment]
> no I have the v1.1.41.634 the latest version
> and for me the "recently played" section of spotify
> are empty as if I hadn't listened to anything
> this problem gives it both with blockthespot applied
> and with the clean version of spotify without the script

I too am on the same version right now and it works for me. Tried reinstalling?

**Comment by ronny941** [comment]
i tried uninstalling and reinstalling but it doesn't work
gives it to me like this

**Comment by Daksh777** [comment]
> i tried uninstalling and reinstalling but it doesn't work
> gives it to me like this

Is your ISP or you trying to block any Spotify tracking links?

**Comment by ronny941** [comment]
> 
> 
> > i tried uninstalling and reinstalling but it doesn't work
> > gives it to me like this
> 
> Is your ISP or you trying to block any Spotify tracking links?

I have nothing in the hosts file that blocks spotify and on the firewall it is allowed

**Comment by ronny941** [comment]
my connection is working fine
for me it's a spotify bug
even if I uninstalled and reinstalled this version of spotify 
in the home that section it does not appear 
and the songs on recently played it is do not update
the program and mod it works great
the songs are played perfectly and do not crash during playback and the skip works
but for some reason the "recently played"  in the home section is gone
and the songs in that section doesn't updated the songs I have listened
before the bug there was only one song in that section but I had removed it
I don't know if it depends on that

**Comment by ronny941** [comment]
when i open spotify it appears that i was listening to a song but in that section it is not shown and the songs listened to no longer count

**Comment by Daksh777** [comment]
> when i open spotify it appears that i was listening to a song but in that section it is not shown and the songs listened to no longer count

Have you checked in the phone app?

**Comment by ronny941** [comment]
> 
> 
> > when i open spotify it appears that i was listening to a song but in that section it is not shown and the songs listened to no longer count
> 
> Have you checked in the phone app?

also in the spotify app it appears that I was listening to a song
and the section appears but does not update

**Comment by ronny941** [comment]
the app of spotify is the original and not modded

**Comment by ronny941** [comment]
> 
> 
> > when i open spotify it appears that i was listening to a song but in that section it is not shown and the songs listened to no longer count
> 
> Have you checked in the phone app?

the app of spotify is the original and not modded
on the phone app the "liked songs" it's on the playlist section 
and in the home of spotify  "recently played" is disappeared 
in the tablet app  "recently played" is in the home correctly 
but it doesn't update the songs or the artist I have listened
in the settings app I have enabled this option
![Spotify Settings](https://user-images.githubusercontent.com/32131958/93225888-024b2400-f773-11ea-9283-0973c9c11b21.JPG)
on the spotify profile page the artists I listened to are up to date and working

but the only problem in that section "recently played" it doesnt't update
and that section "recently played" does not appear in the home of spotify

**Comment by Daksh777** [comment]
If it's a problem in all your devices then your probably have enabled a setting which turns off Spotify tracking. It's an option in the advanced settings of the Windows app.

**Comment by mrpond** [comment]
@ronny941 
![image](https://user-images.githubusercontent.com/18654771/93237766-c469f200-f7aa-11ea-93e4-4399be7bd0f9.png)
Blockthespot working or applied correctly, this banner should not appear, can you try run blockthespot.bat again?

**Comment by ronny941** [comment]
![Blockthespot Recently Played](https://user-images.githubusercontent.com/32131958/93238495-ce2b2f80-f781-11ea-9a45-94ed6abf653d.JPG)
![blockthespot 2](https://user-images.githubusercontent.com/32131958/93238510-d4211080-f781-11ea-85c2-5e8e6ec8fd80.JPG)

**Comment by mrpond** [comment]
seem blockthespot applied now,
now turn on some log and paste it for me to debug.

**Comment by ronny941** [comment]
![Spotify Web Player](https://user-images.githubusercontent.com/32131958/93239178-b6a07680-f782-11ea-80a6-616e059e8526.JPG)

**Comment by ronny941** [comment]
![Spotify Settings](https://user-images.githubusercontent.com/32131958/93239299-e0599d80-f782-11ea-8f18-50ea7d6217aa.JPG)
I have disabled this option

**Comment by ronny941** [comment]
I'm sorry but I didn't understand this
now turn on log and paste it for me to debug.

**Comment by mrpond** [comment]
in spotify installation folder, there are config.ini 
![image](https://user-images.githubusercontent.com/18654771/93239845-8c17e300-f7ad-11ea-9893-022311db1615.png)

**Comment by ronny941** [comment]
in the config.ini I have this:
[Config]
;Log system
Log = 0
;skip proxy
Skip_wpad = 0

**Comment by ronny941** [comment]
![Folder Spotify](https://user-images.githubusercontent.com/32131958/93240465-6d512680-f784-11ea-89b4-0f1f7b3e7997.JPG)

**Comment by ronny941** [comment]
in the config.ini I have this

**Comment by ronny941** [comment]
you want the log file in this path ?
C:\Users\Ranaldo Marco\AppData\Local\Spotify

[LOG.zip](https://github.com/mrpond/BlockTheSpot/files/5228009/LOG.zip)

**Comment by mrpond** [comment]
> you want the log file in this path ?
> C:\Users\Ranaldo Marco\AppData\Local\Spotify
> 
> [LOG.zip](https://github.com/mrpond/BlockTheSpot/files/5228009/LOG.zip)
oh no, not that logs.

If ad blocking is not working, please include a debug log by
 1. edit config.ini and set Log = 1 
 2. after ads song play close spotify
 3. zip the main_log.txt, utility_log.txt

**Comment by ronny941** [comment]
[Log Spotify.zip](https://github.com/mrpond/BlockTheSpot/files/5228500/Log.Spotify.zip)
this is the script log
sorry for that  you have now written the procedure to send you the log file

**Comment by mrpond** [comment]
It in bug report template form.

I think this release will make somethings coming back. 
https://github.com/mrpond/BlockTheSpot/releases/tag/2020.9.15.19
As I'm lazy scrolling, I close this issue.
Please create new issue if you still had problem. 

I'm here to help you with it.

p.s. try use spotify without facebook login. I think it is facebook integrate problem in this spotify release.
p.s2. don't forget set log= 0 back
