### ISSUE TITLE
Spotify Connect and Lastfm scrobbling broke

### ISSUE THREAD

**Issue by HiagoPereira** [mrpond/BlockTheSpot#7]
BlockTheSpot's dll is blocking Spotify Connect and Lastfm scrobble for me. Only on desktop. Tested the original chrome_elf and it's working.

**Desktop:**
 - OS: Windows 10
 - Spotify Version: 1.1.15.448.g00fba0e3

**Comment by mrpond** [comment]
ok please test with latest version of dll v0.25
if it still not working please test with this atttachment...

and tell me how it goes.
[chrome_elf_test.zip](https://github.com/mrpond/BlockTheSpot/files/3664754/chrome_elf_test.zip)

**Comment by HiagoPereira** [comment]
> ok please test with latest version of dll v0.25
> if it still not working please test with this atttachment...
> 
> and tell me how it goes.
> [chrome_elf_test.zip](https://github.com/mrpond/BlockTheSpot/files/3664754/chrome_elf_test.zip)

Yeaaaaaah, now it's working with the test dll!!!!!!! Thank you for your amazing work!!!!!!! :)
