### ISSUE TITLE
Recently Played Never Updates and in the home it's disappeared

### ISSUE THREAD

**Issue by ronny941** [mrpond/BlockTheSpot#70]
I downloaded the new version of blockthespot but the problem remains nothing has changed
I changed the log file from 1 to 0
i copied the new version to spotify folder [obviously it's closed it's not open]
the recently played it's never updated anymore
 and in the home of spotify it doesn't appear that section
i didn't use a facebook account I have the free spotify account
I listen to the songs but that section doesn't update it doesn't count the songs you listen to
i think this is a spotify bug i don't think it's blockthespot

**Comment by ronny941** [comment]
if I play a playlist it counts
but if I play a song in my favorite songs it doesn't count

**Comment by ronny941** [comment]
if I play the song in the playlist it counts and it counts if visit a artist page and I play a song
but if I play a song in the "liked songs" it doesn't count

**Comment by ronny941** [comment]
![Spotify Recently Played Dissapeared](https://user-images.githubusercontent.com/32131958/93274317-60e7c080-f7ba-11ea-8fcc-0f508e65ab65.JPG)
![recently played songs](https://user-images.githubusercontent.com/32131958/93274322-63e2b100-f7ba-11ea-9af0-5315a20241b3.JPG)

**Comment by ronny941** [comment]
the same thing happens on the web player and on my smartphone
but that section only appears in the app on my tablet and works

![web player](https://user-images.githubusercontent.com/32131958/93274982-ee77e000-f7bb-11ea-911c-e3ed1ee341c5.JPG)

**Comment by Daksh777** [comment]
For me, in the Home tab nothing is updated due to blockthespot blocking some trackers but recently played songs do work.

**Comment by ronny941** [comment]
> 
> 
> For me, in the Home tab nothing is updated due to blockthespot blocking some trackers but recently played songs do work.

for me that section "recently played" in the home tab with the playlist called "liked songs" with the artist or album you played recently is disappeared as you can see
blockthespot has nothing to do with it because even when I did the test without applying it on the home screen that section was completely gone
that section "recently played" of spotify only updates if they play the songs from playlist or in the artist page of spotify
if you play it from the "liked songs" playlist it won't update it and it happens both in the home and in that section

**Comment by ronny941** [comment]
i did an update of the spotify app for android but that section is gone
while the 'created for you' one has been moved below
only in the tablet app is that section "recently played"

**Comment by ronny941** [comment]
spotify now looks like this
![Spotify Update](https://user-images.githubusercontent.com/32131958/93357360-7dc6d700-f840-11ea-877c-b9b91959e65a.JPG)

the recently played section in the home of the program is disappeared

**Comment by mrpond** [comment]
I think spotify team remove it.

mine also doesn't show.
![image](https://user-images.githubusercontent.com/18654771/93363295-3dcc1800-f871-11ea-9bac-c1727a0279e2.png)

**Comment by ronny941** [comment]
> 
> 
> I think spotify team remove it.
> 
> mine also doesn't show.
> 
> I remove the bypass, seem this is default spotify behaviour.
> I can't fix that.
> ![image](https://user-images.githubusercontent.com/18654771/93363295-3dcc1800-f871-11ea-9bac-c1727a0279e2.png)

thank you for your availability and for your work 
and congratulations for this script it works perfectly
