### ISSUE TITLE
recently played solved

### ISSUE THREAD

**Issue by ronny941** [mrpond/BlockTheSpot#71]
I found the solution to the problem
in the smartphone app there is an option called 'show only local devices'
when I enabled it that menu called "recently played" is reappeared on the home of spotify on the smartphone app
which practically updates the songs played and shows if you have listened to them from the playlist "liked songs" or from the artist
in the settings of the devices tab of spotify this option "local devices is missing"
all devices are detected but that section does not appear only from the pc app that option is missing

![Spotify Section Reappered](https://user-images.githubusercontent.com/32131958/93482524-183a1f80-f900-11ea-90f0-bf015a6845f9.JPG)

**Comment by ronny941** [comment]
I noticed that it disappears for no reason in the web player and in the pc version of spotify
and that the pc does not update if I listen to a song or a playlist

**Comment by ronny941** [comment]
![never updates](https://user-images.githubusercontent.com/32131958/93483449-1a50ae00-f901-11ea-8fa2-c26d0fde0d56.JPG)

**Comment by ronny941** [comment]
on the pc version it doesn't update

**Comment by ronny941** [comment]
the artists or playlists appear in the section "recently played"
but in the home of spotify does not follow the step and doesnt' updated the artist or the playlist you listened
that is, 
if I play a song from my "liked songs" playlist 
it should say 'liked songs' on the last I've listened
while from an artist it should say the name of the artist or playlist after what I've heard before
this thing does not happen does not update
it only updates from the smartphone app from the web player sometimes and from the pc it doesn't update at all


![doesn't appear the songs or the playlist you are listening](https://user-images.githubusercontent.com/32131958/93487143-43733d80-f905-11ea-943a-4c6c387963d2.JPG)

**Comment by ronny941** [comment]
blockthespot still works with version v1.1.42.622

**Comment by mrpond** [comment]
aha thanks for this valuable information, I will take more time and look into it.
for now I will left this issue open. who knows?, maybe I can fix it someday xD.

**Comment by ronny941** [comment]
this time without blockthespot I have not tried sorry for that
the script works though with the v1.1.42.622

**Comment by Bec-de-Xorbin** [comment]
It's clear that Recently played in Home section does not update properly. Is it somehow possible to remove those from Home?

**Comment by Daksh777** [comment]
> It's clear that "Recently played" in "Home" does not update properly. Is it somehow possible to remove "Recently played" from "Home" altogether?

That's exactly my problem. My Home tab is just stuck with the recently played songs I used to listen to before blockthespot.

**Comment by ronny941** [comment]
> 
> 
> > It's clear that "Recently played" in "Home" does not update properly. Is it somehow possible to remove "Recently played" from "Home" altogether?
> 
> That's exactly my problem. My Home tab is just stuck with the recently played songs I used to listen to before blockthespot.

it was the exact same problem it gave me too
in the spotify home that section does not update at all, and no longer follows the order based on what you have listening
that section in my case had completely disappeared from the home, then when I enabled that option on the smartphone app it reappeared there too.
for example if you play a song from the playlist "liked songs", the name it should appear in the home 
while if you listen to the song from an artist's page, the name of the artist it should appear after the playlist you were listening to but this not happens,

**Comment by rednek46** [comment]
fixed by Spotify
