### ISSUE TITLE
Is it possible to add the discord integration premium features like join listening party?

### ISSUE THREAD

**Issue by rednek46** [mrpond/BlockTheSpot#74]
![image](https://user-images.githubusercontent.com/38219313/94449791-19a1fc80-01ca-11eb-971d-334cb5a0dbdf.png)
A way to join that party. Usually it need spotify premium.

**Comment by Davoleo** [comment]
wow, that would be awesome, although I don't think that's anywhere near easy or maybe even impossible to do

**Comment by Daksh777** [comment]
As far as I know, it is not possible because Discord checks your Spotify account if it has premium subscription, blockthespot can possibly not do anything to bypass it.

**Comment by mrpond** [comment]
I'll look into it,

**Comment by rednek46** [comment]
@Daksh777  you maybe right. But I don't think Discord directly checks the premium status from linked account.
The link is used to provide discord rich presence for Spotify and the join feature only works on PC. If it worked on mobiles too, we could say that it is verifying the premium status from linked account. So it may be possible somehow by tweaking Spotify to fake the premium for discord rich presence.

**Comment by gabe56f** [comment]
Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.

**Comment by Daksh777** [comment]
> Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.

And isn't that against Discord's terms of service?

**Comment by gabe56f** [comment]
> > Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.
> 
> And isn't that against Discord's terms of service?

Yup, it is.

**Comment by BobMcclaw** [comment]
> Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.

Do you have a link to this monkey patch? Or theoretical

**Comment by rednek46** [comment]
> > Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.
> 
> Do you have a link to this monkey patch? Or theoretical

Can't provide the direct link here. but its a patch that comes with Better Discord. So you should check there.

**Comment by redsauce117** [comment]
> > > Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.
> > 
> > 
> > Do you have a link to this monkey patch? Or theoretical
> 
> Can't provide the direct link here. but its a patch that comes with Better Discord. So you should check there.

Spent several hours searching for this patch. Couldn't find it anywhere.

**Comment by BobMcclaw** [comment]
> > > Discord itself checks if the user is premium or not. You'd need to mod your discord itself to allow the usage of this feature. A simple monkey patch works as far as I know.
> > 
> > 
> > Do you have a link to this monkey patch? Or theoretical
> 
> Can't provide the direct link here. but its a patch that comes with Better Discord. So you should check there.

Yeah, I also can't find anything about this...

**Comment by Mspy1** [comment]
Can anyone shine a light on this matter? I found some information in this repo https://github.com/Juby210/EnhancedDiscord-plugins, might be useful.

**Comment by rednek46** [comment]
@Mspy1 its the better discord plugin. You can use it but it is against discord’s ToS. As for that repo, it is based on a discord modification. It doesn’t have anything to do with BlockTheSpot.

**Comment by Mspy1** [comment]
> 
> 
> @Mspy1 its the better discord plugin. You can use it but it is against discord’s ToS. As for that repo, it is based on a discord modification. It doesn’t have anything to do with BlockTheSpot.

Yes, I realized that, for this repo's safety, I will be deleting that repo from my post.

**Comment by rednek46** [comment]
Closing this since This is related to Discord itself. And it will break Discord ToS.
