### ISSUE TITLE
Spotify 1.1.43.700 won't launch after applying BTS 2020.9.16.21 patch

### ISSUE THREAD

**Issue by freespotify** [mrpond/BlockTheSpot#75]
**Describe the bug**
Spotify released an update on 27-28/Sep (1.1.43.700) when apply the newest patch of BlockTheSpot (2020.9.16.21) can't launch Spotify anymore (error message). 

**Desktop (please complete the following information):**
 - OS: Windows 10 (2004)
 - Spotify Version: 1.1.43.700
 - BlockTheSpot Product Version: 2020.9.16.21

**Additional context**
https://i.imgur.com/ooWnYZl.png

**Comment by mrpond** [comment]
Hello, My region still 1.1.42.622.gbd112320,

Please wait few days, until spotify push update here. I do quick fix asap

**Comment by Nigh7Stalk3r** [comment]
It's because they update CEF to 85

**Comment by urmikesmuted** [comment]
What's CEF?

**Comment by mrpond** [comment]
@Nigh7Stalk3r thankyou for this information.
Fixed!, please check the release.
