### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by infunsionist** [mrpond/BlockTheSpot#78]
I tried reinstalling spotify and install the patch, but when i tried to play something, it doesn't work at all.
I'am on Spotify ver 1.1.44.538.g8057de92

**Comment by rednek46** [comment]
> I tried reinstalling spotify and install the patch, but when i tried to play something, it doesn't work at all.
> I'am on Spotify ver 1.1.44.538.g8057de92
  
Make sure you are not using windows store Spotify.  
Also, use the BlockTheSpot.bat to install the patch.  
or you can uninstall Spotify and make BlockTheSpot.bat install the latest version by itslef.

**Comment by infunsionist** [comment]
> > I tried reinstalling spotify and install the patch, but when i tried to play something, it doesn't work at all.
> > I'am on Spotify ver 1.1.44.538.g8057de92
> 
> Make sure you are not using windows store Spotify.
> Also, use the BlockTheSpot.bat to install the patch.
> or you can uninstall Spotify and make BlockTheSpot.bat install the latest version by itslef.

Still, can't play anything, i tried reinstalling and install with the bat file, and no result.

**Comment by mrpond** [comment]
Likely that you had been modified windows hosts file to block ads.
revert all other first.

**Comment by infunsionist** [comment]
> Likely that you had been modified windows hosts file to block ads.
> revert all other first.
> check this pinned issue #4

Thank you so much, it's working now
