### ISSUE TITLE
"Spotify can't play this right now" error

### ISSUE THREAD

**Issue by wtf911** [mrpond/BlockTheSpot#8]
windows 10
v.26 dll moved over
1.1.16.522.g55a4b852

not sure if it's an issue with spotify or blockthespot. a few weeks ago (haven't used spotify in a while) i had this working no problem with your dll.

**Comment by mrpond** [comment]
Hi, I can't reproduce this problem,
some ppl had problem 'cause modified host file.

**Comment by dhinakg** [comment]
@wtf911, Spotify seems to have caught on and the DLL seems to be being replaced with the original frequently. Recopy the DLL and try again.

@mrpond, is there anything you could do to fix this?

**Comment by mrpond** [comment]
@dhinakg thank for clarify.
It is spotify (update)installer.
to work around this issue, a loader/injector is needed.  
process hacker or extreme injector does the job.
https://github.com/master131/BlockTheSpot/issues/19

I'm personally prefer replace dll.
