### ISSUE TITLE
Is it possible to disable auto-update of spotify?

### ISSUE THREAD

**Issue by ToTheMoon1234** [mrpond/BlockTheSpot#80]
Hey there,
I wanted to request if you could also make a code/script/file to disable the auto updates(if the user wants to) of Spotify or intruct how to do so manually so or provide a already written code/file/script .It would be of great help to most of us.
Thanks a lot!

**Comment by rednek46** [comment]
@ToTheMoon1234 This is an unwanted code as BlockTheSpot works with all the latest Spotify version. And Also, this repo is only focused on latest Spotify Releases. Check the issue #46 .  
There is no reason to keep Spotify from updating as each update fixes things and improves up on the last.  
Usually BlockTheSpot only works with latest Spotify only. check #19 .
So this just an unwanted feature that could open up more issues.

As long as the current client can support be made ad free by BlockTheSpot, There is no need for preventing an update.

**Comment by mrpond** [comment]
Hi, BTS will only work & tested with latest Spotify only.
as today Spotify version are 1.1.44.538.g8057de92.

If some people tell me that Spotify 1.1.2x.xxx.xxxx.  + bts not working
in order to help them I need downgrade my Spotify and reproduce these bug then fix it.
very much time consuming.

**Comment by ToTheMoon1234** [comment]
Sure, I understand.
Thanks for the reply and for the wonderful client :-)
