### ISSUE TITLE
"FINDSTR: cannot open blockthespot.bat"

### ISSUE THREAD

**Issue by djhifi** [mrpond/BlockTheSpot#81]
Im having a "FINDSTR: cannot open blockthespot.bat presse any key to continue".

What can I do to fix?

EDIT: I realized that I need to place the actual .bat on the appdata folder.

PS: This doesn't unlock high quality audio does it? I still cant select it.

**Comment by rednek46** [comment]
@djhifi you just have to double click the bat file for the patch to install.
And No. this doesn't unlock the high quality, it only removes ads.

**Comment by mrpond** [comment]
@djhifi the bat file should smart enough to find the Spotify installation folder.
me and rednek would be glad to know on how to reproduce these bug.
you still need to re-run the bat file each time after spotify got updated.

**Comment by djhifi** [comment]
Thanks for the answers guys. Got it working !

**Comment by rednek46** [comment]
@djhifi 
I just checked running the script inside %Appdata%/spotify/ and the script works fine.
BlockTheSpot.bat doesn't matter where the script is being run. Only issue can occur if the the bat file is in an archive or in a ReadOnly directory. Just copying the Bat to the desktop or literally any folder which does not have permission issue and running the script can patch Spotify.

The bat file should be executed after every spotify update. And make sure the script is not inside any archive eg: "BlockTheSpot.zip".

Currently BlockTheSpot only works for the Desktop version. Windows Store Spotify is not supported.

**Comment by mrpond** [comment]
> I can use the .bat or the compressed file each time spotify upgrades, correct?

correct, it will fetch latest build of blockthespot.

I close this for now. happy listening
