### ISSUE TITLE
Spotify Thailand on Mac OSX

### ISSUE THREAD

**Issue by musosoft** [mrpond/BlockTheSpot#82]
Hello Mr. Pond,

I also live in Thailand and would like to block the ads on Spotify. However, my system is OSX and I'm unable to use BlockTheSpot. Would you please share domains to block in my hosts file? I guess that thai ads are hosted somewhere else and that's why this hosts won't stop them: https://github.com/x0uid/SpotifyAdBlock/blob/master/hosts 

Thank you

**Comment by paperclip-dayo** [comment]
It's not possible to fully block Spotify ads with hosts file.

**Comment by musosoft** [comment]
Got it. Any full block solution for OSX? Thanks

**Comment by rednek46** [comment]
@musosoft there isn't anything like BLockTheSpot for OSX.
The only best thing you could do is edit the host files. Try [this](https://privatebin.net/?7cb5ae890f088478#FGzDaimpwL1hNvQieEFWXwmpf2UWq20hkx4iLaHPUvI=) host. It was maintained by CHEF-KOCH, but his github account seems to be suspended right now.

**Comment by mrpond** [comment]
@musosoft latest macOS is very much secure, they won't allow these kind of operation by default.

off-topic: Welcome to Thailand. hope you enjoy living here.

**Comment by aspenluxxxy** [comment]
`sudo nano /etc/hosts` works on macOS Big Sur 11.0.1 for me?

**Comment by mimecry** [comment]
@rednek46 on CHEF-KOCH: https://github.com/arkenfox/user.js/issues/323

**Comment by aspenluxxxy** [comment]
Also, Spotify for macOS also uses CEF. Would a similar patch to the one on Windows not be possible?

**Comment by akash-258** [comment]
A mac version would be very appreciated
