### ISSUE TITLE
Local Files not showing up

### ISSUE THREAD

**Issue by danieldodi** [mrpond/BlockTheSpot#88]
Updated Spotify to latest version and noticed that the covers for local files disappeared, so I decided to delete local-files.bnk to reload them. Then I reopened Spotify and enabled Local Files selecting the respective folder they're located in, but they don't show up. Downgrading to an older Spotify version fixes this issue.

 - OS: Windows 10
 - Spotify Version: 1.1.46.916.g416cacf1
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by rednek46** [comment]
@danieldodi BlockTheSpot Version 0.51 is old.
Use BlockTheSpot.bat to use the latest patch or manually patch with the latest [Release](https://github.com/mrpond/BlockTheSpot/releases/latest/download/chrome_elf.zip).

I don't have issues with the latest patch and Spotify.
See below.

![image](https://user-images.githubusercontent.com/38219313/99886363-e5930700-2c61-11eb-8d13-eb797dccca48.png)

**Comment by danieldodi** [comment]
Not working either, I had already installed the latest release of BlockTheSpot and using BlockTheSpot.bat installs the same version, see screenshot below of the file properties.

**Comment by rednek46** [comment]
@danieldodi can you let me know if it works fine while not using the adblock. That is a clean spotify installation.

**Comment by danieldodi** [comment]
@rednek46 just reinstalled Spotify cleanly and it's still not working. It must be something wrong with my computer :/

**Comment by rednek46** [comment]
So its an issue at your end. You have to contact Spotify support for that.

**Comment by mrpond** [comment]
check your host file, maybe it block album image access.
