### ISSUE TITLE
the new spotify have ads

### ISSUE THREAD

**Issue by Victor9578** [mrpond/BlockTheSpot#89]
use the new .bat to install ,however have ads
![image](https://user-images.githubusercontent.com/45564367/100986006-97e29c80-3587-11eb-875d-9a4e3d8b1da3.png)

**Comment by rednek46** [comment]
@Victor9578 Which version is that?
It doesn't look like normal spotify.

This is the current latest version 1.1.47.684.g136419d9
And it works fine.

**Comment by Victor9578** [comment]
> @Victor9578 Which version is that?
> It doesn't look like normal spotify.
> 
> This is the current latest version 1.1.47.684.g136419d9
> And it works fine.

i use the spicetify ==a theme, is it reason? ii  try to delect  thanks!

**Comment by rednek46** [comment]
@Victor9578 It might be the reason.
Try using the patch without the theme.

**Comment by Daksh777** [comment]
> > @Victor9578 Which version is that?
> > It doesn't look like normal spotify.
> > This is the current latest version 1.1.47.684.g136419d9
> > And it works fine.
> 
> i use the spicetify ==a theme, is it reason? ii try to delect thanks!

I use spicetify too, you have to run the bat file again after applying a new theme, it works well here.

**Comment by rednek46** [comment]
@Victor9578 the above reply by @Daksh777 is the solution for you.
