### ISSUE TITLE
Spotify premium sponsored banner

### ISSUE THREAD

**Issue by BlitW0** [mrpond/BlockTheSpot#9]
**Describe the bug**
All ads are blocked, except the spotify premium banner on the home tab.
Instead of 'Home' as heading, the banner is displayed(possibly covering the heading).

**Desktop:**
 - OS: Windows 10 Version 1903
 - Spotify Version: 1.1.17.543.geb9254e9

**Additional context**
I started using BlockTheSpot only recently, so I don't know if it is even possible to block the premium banner. I am using v0.26.

**Comment by mrpond** [comment]
Wow, seem you region had other domain in host.h(https://github.com/mrpond/BlockTheSpot/blob/master/src/hosts.h) block list
Help me update it,
1. replace chrome_elf.dll from this 
[chrome_elf_log.zip](https://github.com/mrpond/BlockTheSpot/files/3747388/chrome_elf_log.zip)

2. after open spotify wait for the banner to be loaded, 
3. browse to spotify installation folder and paste the content in "hostlog.txt"

here are the code I add into DLL in the case you don't trust the dll above so you can recompile it.
host.cpp
```
int WINAPI getaddrinfohook (DWORD RetAddr,
	pfngetaddrinfo fngetaddrinfo,
	const char* nodename,
	const char* servname,
	const struct addrinfo* hints,
	struct addrinfo** res)
{
	for (size_t i = 0; i < sizeof (whitelist) / sizeof (whitelist[0]); i++)
	{
		if (strstr (nodename, whitelist[i]) != NULL)
			return fngetaddrinfo (nodename, servname, hints, res);
	}
	for (size_t i = 0; i < sizeof (blockhost) / sizeof (blockhost[0]); i++)
	{
		if (strstr (nodename, blockhost[i]) != NULL)
			return WSANO_RECOVERY;
	}
	// log the missing
	std::ofstream logfile;
	logfile.open ("hostlog.txt", std::ios::out | std::ios::app);
	logfile << nodename << '\n';
	logfile.close ();
	return fngetaddrinfo (nodename, servname, hints, res);
}
```

stdafx.h
add #include <fstream> after #include <winhttp.h>

```
// TODO: reference additional headers your program requires here
#include <winsock2.h>
#include <winhttp.h>
#include <fstream>
#include "HookApi.h"
#include "hosts.h"
```

**Comment by BlitW0** [comment]
It seems that the domain you are talking about is the proxy server used by my college. Following are the complete contents of "hostlog.txt":
```
proxy.iiit.ac.in
proxy.iiit.ac.in
proxy.iiit.ac.in
proxy.iiit.ac.in
```

**Comment by mrpond** [comment]
it is proxy (your network) issue.
you can change spotify proxy settings -> none. maybe it work.

**Comment by mrpond** [comment]
v0.31 release,
I add built-in AdGuard DNS blocking.
https://github.com/mrpond/BlockTheSpot/blob/master/chrome_elf.zip

help me test it.

**Comment by BlitW0** [comment]
The premium banner is visible again with v0.31. I'm using no proxy option in Spotify this time.

- OS: Windows 10 Version 1903
- Spotify Version: 1.1.19.480.g7d17e3ce

**Comment by mrpond** [comment]
[chrome_elf_log.zip](https://github.com/mrpond/BlockTheSpot/files/3843286/chrome_elf_log.zip)
test with this debug module, zip the log_*.txt and post here

**Comment by BlitW0** [comment]
Spotify does not launch with the debug module and for some reason, the banner does not appear with windscribe VPN.

**Comment by mrpond** [comment]
ok try this instead
[chrome_elf_log.zip](https://github.com/mrpond/BlockTheSpot/files/3843542/chrome_elf_log.zip)

**Comment by BlitW0** [comment]
This one is also not working.

**Comment by mrpond** [comment]
try run spotify as admin, if it not working, this is special made for you :) 
[chrome_elf_bypasswpad.zip](https://github.com/mrpond/BlockTheSpot/files/3843601/chrome_elf_bypasswpad.zip)

**Comment by eneseliagir** [comment]
It's working (v0.31 release). It doesn't have premium banner on spotify (version 1.1.19.480.g7d17e3ce). Thank you.

**Comment by lostman3** [comment]
It is working properly (v0.31 release) on Windows 10 1909 x64. Also, there is no premium banner on homepage of spotify (1.1.19.480.g7d17e3ce). Thank you so much. 
![Başlıksız-1](https://user-images.githubusercontent.com/57743575/68832196-60c1f480-06c1-11ea-94a7-1e4fae0d0e62.jpg)

**Comment by jayloofah** [comment]
I still can still find the banner on the front page. However, I am currently on a different VPN service.

- OS: Windows 10 Version 1903
- Spotify Version: 1.1.19.480.g7d17e3ce

**Comment by BlitW0** [comment]
> try run spotify as admin, if it not working, this is special made for you :)
> [chrome_elf_bypasswpad.zip](https://github.com/mrpond/BlockTheSpot/files/3843601/chrome_elf_bypasswpad.zip)

This one does not show the banner. Although sometimes thumbnails load slower or song gets paused for a few seconds, but it does not happen very often.

**Comment by jayloofah** [comment]
I see. I think the integration of the DNS filter might have resulted in a pretty heavy slowdown on startup. It might be worthwhile looking into.

**Comment by mrpond** [comment]
@BlitW0 v0.34 is now out!
in your network set Skip_wpad in config.ini to 1 will bypass local proxy
```
[Config]
AdGuardDNS = 1
Log = 0
Skip_wpad = 1
```
