### ISSUE TITLE
30s ads are back

### ISSUE THREAD

**Issue by SmartManoj** [mrpond/BlockTheSpot#90]
**Desktop**
 - OS: Windows 10
 - Spotify Version: 1.1.47.684.g136419d9
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by Daksh777** [comment]
I have no ads here, using Spotify version 1.1.48.625.g1c87c7f7 and BlockTheSpot Product version 0.51.0.0

**Comment by SmartManoj** [comment]
How should one do in-app update?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/101727946-792a5b80-3adb-11eb-8f85-87e5abe84567.png)
Added file version

**Comment by Daksh777** [comment]
> How should one do in-app update?

You can download the latest binary from here and update: https://www.spotify.com/us/download/windows/

**Comment by SmartManoj** [comment]
Still, I have 1.1.47.684.g136419d9

**Comment by Daksh777** [comment]
Okay, can you try applying BlockTheSpot again using [BlockTheSpot.bat](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mrpond/BlockTheSpot/blob/master/BlockTheSpot.bat)

**Comment by SmartManoj** [comment]
Applied. Since the version is not changed, will add the logs if I get ads again.

**Comment by Daksh777** [comment]
If the ads are not there anymore, you may close the issue.

**Comment by SmartManoj** [comment]
I got it randomly. I will reopen if I get it again.

**Comment by SmartManoj** [comment]
> I have no ads here, using Spotify version 1.1.48.625.g1c87c7f7 and BlockTheSpot Product version 0.51.0.0
> Please try updating your Spotify app.

![image](https://user-images.githubusercontent.com/7231077/101762442-77748e00-3b03-11eb-96fe-afd1b204ff95.png)
Beta version?

**Comment by Daksh777** [comment]
Oh yes, it's a dev tools enabled version

**Comment by SmartManoj** [comment]
How should I get that?

**Comment by SmartManoj** [comment]
Got ad
![image](https://user-images.githubusercontent.com/7231077/101773382-b3631f80-3b12-11eb-9ffc-997d137b7ad1.png)

**Comment by SmartManoj** [comment]
> Okay, can you try applying BlockTheSpot again using [BlockTheSpot.bat](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/mrpond/BlockTheSpot/blob/master/BlockTheSpot.bat)?

no logs files as config.ini was reset.

**Comment by rednek46** [comment]
@SmartManoj please provide the logs.

**Comment by SmartManoj** [comment]
Sure if I get

**Comment by rednek46** [comment]
Considering this as a false positive.
