### ISSUE TITLE
Don't download dll file all time

### ISSUE THREAD

**Issue by SmartManoj** [mrpond/BlockTheSpot#92]
Useful when repatch
[Sample file](https://github.com/SmartManoj/CST3/blob/master/Data/Packages/Custom_Plugins/Update.py)

**Comment by Velosofy** [comment]
You can use the old chrome_elf.dll...
Atleast that is what I do

**Comment by SmartManoj** [comment]
with a little tweak to the bat file and [Github Releases Notify Bot](t.me/@github_releases_notify_bot) will help

**Comment by rednek46** [comment]
@SmartManoj please provide more detail on this Issue.

**Comment by SmartManoj** [comment]
https://t.me/PuppuTheTechie/3538

**Comment by rednek46** [comment]
> https://t.me/PuppuTheTechie/3538

Please try to keep the links on github. I can't access this file without getting into that channel which I prefer not to.

**Comment by SmartManoj** [comment]
It's a public channel.

**Comment by rednek46** [comment]
> It's a public channel.

Im not a telegram user. thats why ;).
nvm I got it downloaded on my pc and the edit doesn't do anything more than the BlockTheSpot.bat currently already do. Moreover it seems to have removed some codes to keep provide unique folder names and also to clean up after the patching is done.
