### ISSUE TITLE
What does `;;;===,,,` mean?

### ISSUE THREAD

**Issue by SmartManoj** [mrpond/BlockTheSpot#94]
Clearly seems, it is not a comment.

**Comment by rednek46** [comment]
Its is a commenting for the powershell to avoid the batch script.
Please use [this](https://github.com/rednek46/BlockTheSpot) Repo to talk about the Auto installer.

**Comment by SmartManoj** [comment]
@rednek46 it doesn't have discussions

**Comment by rednek46** [comment]
> @rednek46 it doesn't have issues & discussions tab

oh. sorry. I've added that now.
