### ISSUE TITLE
[Question] Previous release was removed

### ISSUE THREAD

**Issue by HeIp** [mrpond/BlockTheSpot#97]
Hello just wanted to address why the previous release was removed ?
Speaking in reference to release 28.

**Comment by ronny941** [comment]
> 
> 
> Hello just wanted to address why the previous release was removed ?
> Speaking in reference to release 28.

I noticed it too I don't know why he removed it
I use the last version and I did not notice any problems on spotify

**Comment by mrpond** [comment]
technically it the same as 26FIX release,
each new commit into github trigger CI to do a release.
please check here https://github.com/mrpond/BlockTheSpot/issues/96
