### ISSUE TITLE
adblock doesnt work

### ISSUE THREAD

**Issue by spartaque12** [mrpond/BlockTheSpot#98]
ads blocking doesnt work

**Desktop:**
 - OS: Windows 10 19041.508
 - Spotify Version: 1.1.48.625
 - BlockTheSpot Product Version:  0.51.0.0
[Spotify.zip](https://github.com/mrpond/BlockTheSpot/files/5713174/Spotify.zip)

**Comment by Daksh777** [comment]
Ad block does work for me, I am on the same version. Could you tell me what type of ads are you getting?

**Comment by spartaque12** [comment]
> Ad block does work for me, I am on the same version. Could you tell me what type of ads are you getting?

i fixed it by applying this patch
https://www.reddit.com/r/Spotifyhosts/comments/kdnk0u/spotify_1148625g1c87c7f7_patch/
